In [3]:
import numpy as np
import pandas as pd
import warnings
import matplotlib.pyplot as plt
import requests
import io

warnings.filterwarnings("ignore")

In [4]:
a=pd.read_csv("jan_to_march.csv")
b=pd.read_csv("apr_to_june.csv")
c=pd.read_csv("july_to_sep.csv")
d=pd.read_csv("oct_to_dec.csv")
MSC_noon_2023= pd.concat([a,b,c,d])

In [5]:
pd.set_option('display.max_columns', None)  
MSC_noon_2023

,id,imo,vessel,id_vessel,gid,voyage,corrected_date,report_date_time,report_date_time_offset,report_type,status,lat,long,latitude,longitude,me_foc,cargo_total,total_steaming_time,me_fuel_only_steaming_time,miles_by_gps,oil_cyl,rpm,slip,wind_direction,wind_speed,draft_aft,draft_fwd,displacement,course_at_sea,wave_height,sea_direction,cargo_total_teu,ambient_temp,sw_temp,miles_by_speed_log,eta_port_code,eta_date_time,eta_date_time_offset,eta_port,time_change,time_sea,temp_min,temp_max,requested_speed,rem_dist_to_pilot,rem_time_to_pilot,total_unplnd_stpge_tech,total_unplnd_stpge_ope_wx,reefers_positive_plugged,reefers_negative_plugged,me_total_revs_counter,port_code,port,aux_blowers_on,hold_ventilation_on,since_date_time,since_date_time_offset,time_hrs_anchor,time_hrs_drift,reason,type_of_delay,etb_date_time,etb_date_time_offset,pilot_date_time,pilot_date_time_offset,time_manoeuvring,tug_arr,tug_shift,etd_date_time,etd_date_time_offset,shift_berth_hours,cargo_load,cargo_disch,teu_full,teu_empty,bilge_removed,garbage_removed,garbage_remvl_reqstd,garbage_remvl_cmplsry,fw_supply,cy_crew_signed_on,cy_crew_signed_off,cy_doctors_visit,cy_mail_received_ref_no,cy_lub_oil_sample_landed,cy_checkd_for_stowaways,cy_stowaways_on_board,cy_dep_gm_mtr,cy_requisitions_received,distance_to_next_pilot,tug_sailing_transit,steaming_time_me_rsdl_vls,steaming_time_me_rsdl_hs,steaming_time_me_rsdl_uls,steaming_time_me_dstlt_vls,steaming_time_me_dstlt_uls,steaming_time_me_tnktnr_dstlt_vls,steaming_time_me_mdo,steaming_time_aux_1,steaming_time_aux_2,steaming_time_aux_3,steaming_time_aux_4,steaming_time_aux_5,steaming_time_sh_gen,steaming_time_tg,fuel_me_rsdl_vls,fuel_me_rsdl_hs,fuel_me_rsdl_uls,fuel_me_dstlt_vls,fuel_me_dstlt_uls,fuel_me_mdo,fuel_me_tnktnr_dstlt_vls,fuel_aux_rsdl_vls,fuel_aux_rsdl_hs,fuel_aux_rsdl_uls,fuel_aux_dstlt_vls,fuel_aux_dstlt_uls,fuel_aux_tnktnr_dstlt_vls,fuel_aux_mdo,fuel_boiler_rsdl_vls,fuel_boiler_rsdl_hs,fuel_boiler_rsdl_uls,fuel_boiler_dstlt_vls,fuel_boiler_dstlt_uls,fuel_boiler_tnktnr_dstlt_vls,fuel_boiler_mdo,power_kw,steaming_load_kw_aux_1,steaming_load_kw_aux_2,steaming_load_kw_aux_3,steaming_load_kw_aux_4,steaming_load_kw_aux_5,steaming_load_kw_sh_gen,steaming_load_kw_tg,deck_last_change_user,engine_last_change_user,deck_part_is_complete,engine_part_is_complete,scavenge_pressure,seca_entry_time,seca_entry_lat,seca_entry_long,seca_exit_time,seca_exit_lat,seca_exit_long,rob_fresh_water,manvrng_miles_by_gps,manvrng_miles_by_speed_log,tanktainer_transfd_quantity,pilot_taken,date_time_start_transit,date_time_start_transit_offset,date_time_end_transit,date_time_end_transit_offset,ballast,tanktainer_number,steaming_kwhr_total,cy_others,rob_fo_sludge,rob_lo_sludge,rob_bilge,sludge_removed_fo,sludge_removed_lo,sea_state,cy_lub_added_to_system_me_cc,cy_lub_added_to_system_ae_cc,cy_lub_added_to_thrusters,cy_me_lo_purifier_in_use,cy_ballast,cy_bending_moment,cy_shearing_force,cy_tortion_moment,cy_supdt_auditor_signed_on,cy_supdt_auditor_signed_off,cy_cash_received,cy_lub_oil_received_me_cyl,cy_lub_oil_received_me_cc,cy_lub_oil_received_ae_cc,cy_me_under_piston_temp,cy_mail_received,wind_direction_port_stbd,sea_direction_port_stbd,time_pilot_onboard,grades_rob,so_2_co_2_ratio,bunker_order,remarks,bdn_number,fuel_type,carbon_factor,sulphur_content_pc,quantity,port_delivery,product_quality,tanktainer_number_1,supplier,delivery,volume_lt,density,viscosity,rob_dstlt_uls,rob_dstlt_vls,rob_rsdl_mdo,rob_tnktnr_dstlt_vls,rob_rsdl_vls,rob_rsdl_hs,rob_rsdl_uls,has_cargo,steaming_time_me_hs,steaming_time_me_ls,steaming_time_me_mgo,steaming_time_me_mgo_ls,fuel_me_hs,fuel_me_ls,fuel_me_mgo,fuel_me_mgo_ls,fuel_aux_hs,fuel_aux_ls,fuel_aux_mgo,fuel_aux_mgo_ls,fuel_boiler_hs,fuel_boiler_ls,fuel_boiler_mgo,fuel_boiler_mgo_ls,rob_fuel_hs_fo,rob_fuel_ls_fo,rob_fuel_mdo,rob_fuel_mgo,rob_fuel_mgo_ls,rob_fuel_tanktainer_mgo,eca_miles,eca_time,egcs_dry_waste_removed,egcs_running_time,egcs_wet_slurry_removed,egcs_open_loop_running_time,egcs_closed_loop_running_time,voyage_order,voyage_code,eca,eu,sea_time,eta_country_code,port_country_code,check_eta_code,check_port_code,status_temp_eu,fuel_hs,fuel_ls,fuel_mdo,fuel_mgo,fuel_mgo_ls,cargo_transport_work,teu_transport_work,eeoi_voyage_no,cargo_total_old,draft,fo_per_24_hrs,sfoc,cy_oil_gm_hr,scoc,voyage_name,total_fo,total_co_2,eeoi,voy_condition,same_date,time_since_last_report,wind_direction_360,true_wind_speed,true_wind_dir,ref_power,ref_fuel,fuel_loss,relative_wind_speed,relative_wind_direction,caa,rw,corrected_power,draft_pow,draft_sp_pow,fo_nor,fo_model,sfoc_model,sfoc_deviation,ref_power_corrected,ref_fo_corrected,propulsive_eff,speed_performance,ref_speed,pi,me_con,ae_con,bl_con,t_con,hs,ls,mdo,mgo,mgo_ls,t_co_2,ae_t_steaming,ae_power,trim,distance_covered,updated_date,hyd_slip_sog,hyd_slip_stw,fuel_rsdl_hs,fuel_rsdl_vls,fuel_rsdl_uls,fuel_dstlt_vls,fuel_dstlt_uls,fuel_tnktnr_dstlt_vls,rsdl_hs,rsdl_vls,rsdl_uls,dstlt_vls,dstlt_uls,tnktnr_dstlt_vls,created_at,updated_at,created_by_id,updated_by_id,speed_by_log,speed_by_gps,fuel_m_e_lng,fuel_aux_lng,fuel_boiler_lng,rob_rsdl_lng,sulphur_content_pc_main,quantity_main,port_delivery_main,product_quality_main,delivery_main,bdn_number_main
0,3847401,9180968,MSC SHEILA,SHEI,0000a039-ae42-4c60-a2e4-7ef4ad214741,AV303A,2023-02-02 00:00:00,2023-02-02 12:00:00,UTC +02:00,NOON,AT SEA,3542N,03522E,35.700000,35.366667,3.75,6106.00,9.0,9.0,74.0,26.0,161.0,1.9,30.0,10.0,7.10,6.90,15932.8,182.0,0.14,85.00,621.0,12.0,11.0,74.0,ILHFA,2023-02-03 12:00:00,UTC +02:00,HAIFA,NaN,9.0,329.0,349.0,9.0,189.0,24.0,0.0,0.0,5.0,0.0,258463000.0,TRISK,ISKENDERUN,True,False,NaN,NaN,NaN,NaN,Congestion,NaN,2023-02-01 20:00:00,UTC +02:00,NaN,NaN,NaN,NaN,NaN,2023-02-02 01:00:00,UTC +03:00,NaN,NaN,NaN,480.0,141.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,0.0,3.750,0.0,0.0,0,0.0,0,0.0,0.0,0.0,0.0,0,0.000,0.0,0,0.0,0.0,0.0,0,0.00,0.0,0,1773,0.0,0.0,0.0,0.0,0.0,210.0,0.0,MASTER,CE,True,True,1.0,NaN,NaN,NaN,NaN,NaN,NaN,122.0,0.0,NaN,NaN,False,NaN,NaN,NaN,NaN,3350.0,0,210.0,NaN,NaN,NaN,3.0,NaN,NaN,2.0,300.0,0.0,0.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,S,S,NaN,NaN,0.0,NaN,NaN,NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0.0,0.0,149.62,0.0,0.0,True,0.0,9.0,0.0,0.0,0.0,3.750,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.00,0.0,149.62,0.0,0.0,0.00,0.0,0.0,0.0,NaN,0.0,NaN,0.0,0.0,830.0,TRISK-ILHFA,N,N,9.0,IL,TR,NaN,NaN,0,0.0,3.750,0,0.0,0.000,451844.0,45954.0,830.0,0,7.00,10.00000,235.007,2600.00,1.46644,0,3.750,11.67750,0,Laden,0,NaN,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.75,0.00,0.00,3.75,0.0,3.75,0.0,0.0,0.00,11.68,0.0,0.0,0.2,74.0,2023-02-17 09:09:09,NaN,NaN,0.0,3.750,0.0,0.0,0.000,0.0,0.0,3.75,0.0,0.0,0.00,0.0,NaN,NaN,NaN,NaN,8.22222,8.22222,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3847407,9502908,MSC TOPAZ,TOPA,00024c2d-14ef-4a30-b71d-b0ec2bceacb2,NaN,2023-03-25 00:00:00,2023-03-25 05:59:59,UTC +03:00,SND,NaN,NaN,NaN,NaN,NaN,NaN,129666.00,NaN,NaN,0.0,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6968.0,1619.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000,0.0,0.0,0,0.0,0,0.0,0.0,0.0,0.0,0,0.000,0.0,0,0.0,0.0,0.0,0,0.00,0.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,0.0,0.0,NaN,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.00,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,529.0,DJJIB-SAKAC,N,N,0.0,SA,DJ,NaN,NaN,0,0.0,0.000,0,0.0,0.000,0.0,0.0,529.0,0,0.00,0.00000,0.000,0.00,0.00000,0,0.000,0.00000,0,Laden,0,NaN,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.00,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,2023-04-12 19:27:40,NaN,NaN,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.00,0.0,0.0,0.00,0.0,NaN,NaN,NaN,NaN,0.00000,0.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3847408,9150080,WEC BOUMEESTER,BMSR,0002e6d0-34b6-4d25-ba8e-74ffdc1c154f,NaN,2023-02-25 00:00:00,2023-02-24 21:12:00,UTC +00:00,SND,NaN,NaN,NaN,NaN,NaN,NaN,1855.57,NaN,NaN,0.0,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38.0,240.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000,0.0,0.0,0,0.0,0,0.0,0.0,0.0,0.0,0,0.000,0.0,0,0.0,0.0,0.0,0,0.00,0.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,0.0,0.0,NaN,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.00,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,142.0,MACAS-PTFDF,N,Y,0.0,PT,MA,NaN,NaN,0,0.0,0.000,0,0.0,0.000,0.0,0.0,142.0,0,0.00,0.00000,0.000,0.00,0.00000,0,0.000,0.00000,0,Laden,0,NaN,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.00,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,2023-03-31 11:36:03,NaN,NaN,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.00,0.0,0.0,0.00,0.0,NaN,NaN,NaN,NaN,0.00000,0.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3847409,9315006,WEC VAN RIJN,WVRN,0003204b-6229-4e3b-82a3-6a0cbf6fdefc,EC309A,2023-03-18 00:00:00,2023-03-18 06:30:00,UTC +01:00,EOSP,AT SEA,3824N,00904W,38.400000,-9.066667,1.69,1931.00,2.5,2.5,29.6,0.0,130.0,0.7,110.0,13.0,7.04,4.94,11573.0,67.0,1.00,130.00,101.0,11.0,10.0,29.5,PTSET,2023-03-18 07:00:00,UTC +01:00,NaN,NaN,2.5,386.0,400.0,10.0,NaN,NaN,0.0,0.0,0.0,3.0,75000.0,PTSET,SETUBAL,False,False,NaN,NaN,NaN,NaN,BERTH OCCUPIED,NaN,2023-03-18 08:12:00,UTC +01:00,NaN,NaN,NaN,NaN,NaN,2023-03-18 02:00:00,UTC +01:00,NaN,NaN,NaN,82.0,19.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.5,0.0,0.0,0.0,0.0,0.0,0.0,0.3,0.3,0.0,0.0,0.0,2.5,0.0,1.688,0.0,0.0,0,0.0,0,0.0,0.0,0.0,0.0,0,0.019,0.0,0,0.0,0.0,0.0,0,0.00,0.0,0,3304,155.0,155.0,0.0,0.0,0.0,250.0,0.0,2ND OFF,CH.ENG,True,True,0.7,NaN,NaN,NaN,NaN,NaN,NaN,87.0,0.0,NaN,NaN,False,NaN,NaN,NaN,NaN,4289.0,0,0.0,NaN,NaN,NaN,1.5,NaN,NaN,3.0,0.0,0.0,0.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,P,P,NaN,NaN,0.0,NaN,NaN,NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,129.47,0.0,0.0,0.0,87.82,0.0,0.0,True,0.0,2.5,0.0,0.0,0.0,1.688,0.0,0.0,0.0,0.0,0.0,0.019,0.0,0.0,0.0,0.00,0.0,87.82,0.0,0.0,129.47,0.0,0.0,0.0,NaN,0.0,NaN,0.0,0.0,313.0,PTLIS-PTSET,N,Y,2.5,PT,PT,NaN,NaN,0,0.0,1.688,0,0.0,0.019,57157.6,2989.6,313.0,0,5.99,16.20480,204.358,0.00,0.00000,0,1.707,5.31735,0,Laden,0,NaN,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.69,0.02,0.00,1.71,0.0,1.69,0.0,0.0,0.02,5.33,0.6,310.0,2.1,29.6,2023-03-31 16:15:25,NaN,NaN,0.0,1.688,0.0,0.0,0.019,0.0,0.0,1.69,0.0,0.0,0.02,0.0,NaN,NaN,NaN,NaN,11.80000,11.84000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3847411,9248928,MSC TIGER F,TGRF,0003b151-4b19-4c4e-8a5c-a97a74cdb6ba,NaN,2023-01-29 00:00:00,2023-01-28 15:53:59,UTC +03:00,SND,NaN,NaN,NaN,NaN,NaN,NaN,14220.70,NaN,NaN,0.0,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34.0,976.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000,0.0,0.0,0,0.0,0,0.0,0.0,0.0,0.0,0,0.000,0.0,0,0.0,0.0,0.0,0,0.00,0.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,0.0,0.0,NaN,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.00,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,174.0,SAKAC-SDPZU,N,N,0.0,SD,SA,NaN,NaN,0,0.0,0.000,0,0.0,0.000,0.0,0.0,174.0,0,0.00,0.00000,0.000,0.00,0.00000,0,0.000,0.00000,0,Laden,0,NaN,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.00,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,2023-02-14 11:37:44,NaN,NaN,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.00,0.0,0.0,0.00,0.0,NaN,NaN,NaN,NaN,0.00000,0.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194552,4689247,9337676,MSC ROSHNEY V,ROSH,ff2a4513-e132-4db8-9baf-a87af4eb66cf,NaN,2023-12-31 00:00:00,2023-12-30 21:11:59,UTC +02:00,SND,NaN,NaN,NaN,NaN,NaN,NaN,32066.30,NaN,NaN,0.0,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2908.0,33.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000,0.0,0.0,0,0.0,0,0.0,0.0,0.0,0.0,0,0.000,0.0,0,0.0,0.0,0.0,0,0.00,0.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,0.0,0.0,NaN,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.00,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,167.0,TRTEK-GRPIR,N,Y,0.0,GR,TR,NaN,NaN,0,0.0,0.000,0,0.0,0.000,0.0,0.0,167.0,0,0.00,0.00000,0.000,0.00,0.00000,0,0.000,0.00000,0,Laden,0,NaN,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.00,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,2024-01-17 09:04:49,NaN,NaN,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.00,0.0,0.0,0.00,0.0,NaN,NaN,NaN,NaN,0.00000,0.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
194553,4689248,9180968,MSC SHEILA,SHEI,ff428bca-5a8b-40b4-a4ff-9e5b02016d30,AO352A,2023-12-31 00:00:00,2023-12-31 12:00:00,UTC +03:00,COSP,DRIFTING,4025N,02854E,40.416667,28.900000,0.21,1524.00,1.3,1.3,9.8,2.0,0.0,0.0,15.0,7.0,5.60,5.30,12130.4,271.0,0.28,15.00,179.0,20.0,19.0,NaN,TRTEK,2023-12-31 20:00:00,UTC +03:00,TEKIRDAG _ASYAPORT_,NaN,1.3,180.0,190.0,9.5,NaN,NaN,0.0,0.0,0.0,0.0,304180400.0,TRGEM,GEMLIK,True,False,NaN,NaN,NaN,NaN,TRANSIT,NaN,2023-12-31 07:00:00,UTC +03:00,NaN,NaN,1.3,NaN,NaN,2023-12-31 12:00:00,UTC +03:00,NaN,NaN,NaN,0.0,0.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,76.6,2.0,1.3,0.0,0.0,0.0,0.0,0.0,0.0,1.3,0.0,1.3,0.0,0.0,0.0,0.0,0.210,0.0,0.0,0,0.0,0,0.0,0.0,0.0,0.0,0,0.050,0.0,0,0.0,0.0,0.0,0,0.02,0.0,0,955,150.0,0.0,150.0,0.0,0.0,0.0,0.0,MASTER,CE,True,True,1.0,NaN,NaN,NaN,NaN,NaN,NaN,42.0,9.8,9.5,NaN,True,NaN,NaN,NaN,NaN,4106.0,0,0.0,NaN,NaN,NaN,4.0,NaN,NaN,2.0,0.0,0.0,0.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,P,P,0.4,NaN,0.0,NaN,NaN,NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49.36,0.0,0.0,0.0,162.88,0.0,0.0,True,0.0,1.3,0.0,0.0,0.0,0.210,0.0,0.0,0.0,0.0,0.0,0.050,0.0,0.0,0.0,0.02,0.0,162.88,0.0,0.0,49.36,0.0,NaN,NaN,NaN,0.0,NaN,0.0,0.0,NaN,NaN,N,N,1.3,NaN,NaN,NaN,NaN,0,0.0,0.210,0,0.0,0.070,14935.2,0.0,NaN,0,5.45,3.87692,169.150,1384.62,1.44986,0,0.280,0.87836,0,Laden,0,NaN,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.21,0.05,0.02,0.28,0.0,0.21,0.0,0.0,0.07,0.88,2.6,300.0,0.3,9.8,2024-01-17 09:04:49,NaN,NaN,0.0,0.210,0.0,0.0,0.070,0.0,0.0,0.21,0.0,0.0,0.07,0.0,NaN,NaN,NaN,NaN,0.00000,0.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
194554,4689249,9139086,MSC POLO II,POLO,ff53dccd-5076-4257-89a9-26ef9548dcad,SG352R,2023-12-31 00:00:00,2023-12-30 16:12:00,UTC +06:00,COSP,DRIFTING,2208N,09145E,22.133333,91.750000,1.30,9951.00,1.5,1.5,14.0,10.0,0.0,0.0,150.0,16.0,8.90,7.30,24651.0,196.0,1.45,150.00,1245.0,24.0,25.0,NaN,LKCMB,2024-01-03 06:00:00,UTC +05:30,COLOMBO,NaN,5.7,334.0,375.0,15.5,NaN,NaN,0.0,0.0,1.0,4.0,491431530.0,BDCGP,CHATTOGRAM,True,False,NaN,NaN,NaN,NaN,Waiting for berth,NaN,2023-12-28 12:00:00,UTC +06:00,NaN,NaN,1.5,NaN,NaN,2023-12-30 11:00:00,UTC +06:00,NaN,NaN,NaN,1245.0,0.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1345.0,1.0,1.5,0.0,0.0,0.0,0.0,0.0,0.0,5.7,5.7,1.5,0.0,0.0,0.0,0.0,1.300,0.0,0.0,0,0.0,0,0.0,0.8,0.0,0.0,0,0.000,0.0,0,0.3,0.0,0.0,0,0.00,0.0,0,4420,300.0,300.0,300.0,0.0,0.0,0.0,0.0,CAPT. KYAW ZAY LATT,C_E NYUNT MYINT,True,True,0.2,NaN,NaN,NaN,NaN,NaN,NaN,105.0,14.0,14.0,NaN,True,NaN,NaN,NaN,NaN,5241.0,0,900.0,NaN,NaN,NaN,4.0,NaN,NaN,4.0,0.0,0.0,0.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,S,S,1.2,NaN,0.0,NaN,NaN,NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0.0,0.0,655.98,0.0,0.0,True,0.0,1.5,0.0,0.0,0.0,1.300,0.0,0.0,0.0,0.8,0.0,0.000,0.0,0.3,0.0,0.00,0.0,655.98,0.0,0.0,0.00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,N,1.5,NaN,NaN,NaN,NaN,0,0.0,2.400,0,0.0,0.000,139314.0,17430.0,NaN,0,8.10,20.80000,196.078,6000.00,1.35747,0,2.400,7.47360,0,Laden,0,NaN,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.30,0.80,0.30,2.40,0.0,2.40,0.0,0.0,0.00,7.47,12.9,900.0,1.6,14.0,2024-01-17 09:04:49,NaN,NaN,0.0,2.400,0.0,0.0,0.000,0.0,0.0,2.40,0.0,0.0,0.00,0.0,NaN,NaN,NaN,NaN,0.00000,0.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
MSC_noon_2023['Date'] = pd.to_datetime(MSC_noon_2023['corrected_date']).apply(lambda x: x.strftime("%d") if not pd.isnull(x) else 'NaT')
MSC_noon_2023['Month'] = pd.to_datetime(MSC_noon_2023['corrected_date']).apply(lambda x: x.strftime("%m") if not pd.isnull(x) else 'NaT')
MSC_noon_2023['Year'] = pd.to_datetime(MSC_noon_2023['corrected_date']).apply(lambda x: x.strftime("%Y") if not pd.isnull(x) else 'NaT')
MSC_noon_2023['Month_name'] = pd.to_datetime(MSC_noon_2023['corrected_date']).apply(lambda x: x.strftime("%B") if not pd.isnull(x) else 'NaT')
MSC_noon_2023['date'] = pd.to_datetime(MSC_noon_2023["corrected_date"]).dt.date
MSC_noon_2023.dropna(subset=['imo'])
MSC_noon_2023_sort=MSC_noon_2023.sort_values(by="corrected_date")
#Total HS,LS,MGO and Total Fuel
MSC_noon_2023_sort['Total_Calculated_HS']= MSC_noon_2023_sort[['fuel_me_rsdl_hs' , 'fuel_aux_rsdl_hs' , 'fuel_boiler_rsdl_hs']].sum(axis=1)
MSC_noon_2023_sort['Total_Calculated_LS'] = MSC_noon_2023_sort[['fuel_me_rsdl_vls' , 'fuel_me_dstlt_vls' , 'fuel_me_tnktnr_dstlt_vls' ,'fuel_aux_rsdl_vls' ,  'fuel_aux_dstlt_vls' , 'fuel_aux_tnktnr_dstlt_vls','fuel_boiler_rsdl_vls','fuel_boiler_dstlt_vls','fuel_boiler_tnktnr_dstlt_vls']].fillna(0).sum(axis=1)
MSC_noon_2023_sort['Total_Calculated_ULS'] = MSC_noon_2023_sort[['fuel_me_rsdl_uls' , 'fuel_aux_rsdl_uls' , 'fuel_boiler_rsdl_uls' ,'fuel_me_dstlt_uls' ,'fuel_aux_dstlt_uls' , 'fuel_boiler_dstlt_uls']].fillna(0).sum(axis=1)
MSC_noon_2023_sort['Total_Calculated_Fuel'] = MSC_noon_2023_sort[['Total_Calculated_HS' ,'Total_Calculated_LS' , 'Total_Calculated_ULS']].fillna(0).sum(axis=1)
MSC_noon_2023_sort['Total_Calculated_LNG'] = MSC_noon_2023_sort[['fuel_m_e_lng' ,'fuel_boiler_lng' , 'fuel_aux_lng']].fillna(0).sum(axis=1)

#HS_CO2,LSCO2,MGO_CO2 and Total CO2
MSC_noon_2023_sort['HS_CO2'] = 3.114 * MSC_noon_2023_sort["Total_Calculated_HS"]
MSC_noon_2023_sort['LS_CO2'] = 3.151 * MSC_noon_2023_sort["Total_Calculated_LS"]
MSC_noon_2023_sort['ULS_CO2'] = 3.206 * MSC_noon_2023_sort["Total_Calculated_ULS"]
MSC_noon_2023_sort['Total_CO2'] = MSC_noon_2023_sort[['HS_CO2' ,'LS_CO2' ,'ULS_CO2']].fillna(0).sum(axis=1)

MSC_noon_2023_sort["fuel_m_e_calculated"]=MSC_noon_2023_sort[["fuel_me_rsdl_hs","fuel_me_rsdl_vls","fuel_me_dstlt_vls",'fuel_me_rsdl_uls','fuel_me_rsdl_uls','fuel_me_tnktnr_dstlt_vls']].fillna(0).sum(axis=1)
MSC_noon_2023_sort["fuel_aux_calculated"]=MSC_noon_2023_sort[["fuel_aux_rsdl_vls","fuel_aux_rsdl_hs","fuel_aux_dstlt_vls",'fuel_aux_rsdl_uls','fuel_aux_dstlt_uls','fuel_aux_tnktnr_dstlt_vls']].fillna(0).sum(axis=1)
MSC_noon_2023_sort["fuel_boiler_calculated"]=MSC_noon_2023_sort[["fuel_boiler_rsdl_hs","fuel_boiler_rsdl_vls","fuel_boiler_dstlt_vls",'fuel_boiler_rsdl_uls','fuel_boiler_tnktnr_dstlt_vls','fuel_boiler_dstlt_uls']].fillna(0).sum(axis=1)
MSC_noon_2023_sort["Total_fuel_calculated"]=MSC_noon_2023_sort[["fuel_m_e_calculated","fuel_aux_calculated","fuel_boiler_calculated"]].fillna(0).sum(axis=1)

In [7]:
MSC_noon_2023_sort["voyage"].isna().sum()

407963

# Yearly Total of each Parameters

# 1. CARGO TOTAL

In [8]:
MSC_noon_2023_sort["voyage"].unique()

array([nan, 'M250A', 'XA251A', ..., 'BB352A', 'EC351A', '9E52'],
      dtype=object)

In [9]:

MSC_noon_2023_str = MSC_noon_2023_sort[MSC_noon_2023_sort['voyage'].apply(lambda x: isinstance(x, str))]
MSC_noon_2023_str['voyage'] = MSC_noon_2023_str['voyage'].str.lstrip('0').str.rstrip('.0')

# Filter by Float Type and Convert to String
MSC_noon_2023_float = MSC_noon_2023_sort[MSC_noon_2023_sort['voyage'].apply(lambda x: isinstance(x, float))]
MSC_noon_2023_float['voyage'] = pd.to_numeric(MSC_noon_2023_float['voyage'], errors='coerce').fillna(0).astype(int).astype(str)

# Filter by Integer Type and Convert to String
MSC_noon_2023_int = MSC_noon_2023_sort[MSC_noon_2023_sort['voyage'].apply(lambda x: isinstance(x, int))]
MSC_noon_2023_int['voyage'] = MSC_noon_2023_int['voyage'].astype(int).astype(str)

# Concatenate DataFrames and Sort
MSC_noon_2023_sort_new = pd.concat([MSC_noon_2023_str, MSC_noon_2023_float, MSC_noon_2023_int])
MSC_noon_2023_sort_new = MSC_noon_2023_sort_new.sort_values(by=["corrected_date"])

In [10]:
MSC_noon_2023_sort_new["voyage"].isna().sum()

0

In [11]:
MSC_noon_2023_sort_new["cargo_total"].isna().sum()

0

In [12]:
cargo_vessel_mean_2023 = MSC_noon_2023_sort_new.groupby(["imo", "voyage"])[["cargo_total"]].mean().reset_index()
Total_cargo_2023 = cargo_vessel_mean_2023[["cargo_total"]].sum().reset_index()
Total_cargo_2023 = round(Total_cargo_2023[0] / (10 ** 6), 2)
Total_cargo_2023.reset_index()

   index       0
0      0  283.12

# 2.  MILES BY GPS

In [13]:
MSC_noon_2023_sort_new.columns.values

array(['id', 'imo', 'vessel', 'id_vessel', 'gid', 'voyage',
       'corrected_date', 'report_date_time', 'report_date_time_offset',
       'report_type', 'status', 'lat', 'long', 'latitude', 'longitude',
       'me_foc', 'cargo_total', 'total_steaming_time',
       'me_fuel_only_steaming_time', 'miles_by_gps', 'oil_cyl', 'rpm',
       'slip', 'wind_direction', 'wind_speed', 'draft_aft', 'draft_fwd',
       'displacement', 'course_at_sea', 'wave_height', 'sea_direction',
       'cargo_total_teu', 'ambient_temp', 'sw_temp', 'miles_by_speed_log',
       'eta_port_code', 'eta_date_time', 'eta_date_time_offset',
       'eta_port', 'time_change', 'time_sea', 'temp_min', 'temp_max',
       'requested_speed', 'rem_dist_to_pilot', 'rem_time_to_pilot',
       'total_unplnd_stpge_tech', 'total_unplnd_stpge_ope_wx',
       'reefers_positive_plugged', 'reefers_negative_plugged',
       'me_total_revs_counter', 'port_code', 'port', 'aux_blowers_on',
       'hold_ventilation_on', 'since_date_time', 'since_date_time_offset',
       'time_hrs_anchor', 'time_hrs_drift', 'reason', 'type_of_delay',
       'etb_date_time', 'etb_date_time_offset', 'pilot_date_time',
       'pilot_date_time_offset', 'time_manoeuvring', 'tug_arr',
       'tug_shift', 'etd_date_time', 'etd_date_time_offset',
       'shift_berth_hours', 'cargo_load', 'cargo_disch', 'teu_full',
       'teu_empty', 'bilge_removed', 'garbage_removed',
       'garbage_remvl_reqstd', 'garbage_remvl_cmplsry', 'fw_supply',
       'cy_crew_signed_on', 'cy_crew_signed_off', 'cy_doctors_visit',
       'cy_mail_received_ref_no', 'cy_lub_oil_sample_landed',
       'cy_checkd_for_stowaways', 'cy_stowaways_on_board',
       'cy_dep_gm_mtr', 'cy_requisitions_received',
       'distance_to_next_pilot', 'tug_sailing_transit',
       'steaming_time_me_rsdl_vls', 'steaming_time_me_rsdl_hs',
       'steaming_time_me_rsdl_uls', 'steaming_time_me_dstlt_vls',
       'steaming_time_me_dstlt_uls', 'steaming_time_me_tnktnr_dstlt_vls',
       'steaming_time_me_mdo', 'steaming_time_aux_1',
       'steaming_time_aux_2', 'steaming_time_aux_3',
       'steaming_time_aux_4', 'steaming_time_aux_5',
       'steaming_time_sh_gen', 'steaming_time_tg', 'fuel_me_rsdl_vls',
       'fuel_me_rsdl_hs', 'fuel_me_rsdl_uls', 'fuel_me_dstlt_vls',
       'fuel_me_dstlt_uls', 'fuel_me_mdo', 'fuel_me_tnktnr_dstlt_vls',
       'fuel_aux_rsdl_vls', 'fuel_aux_rsdl_hs', 'fuel_aux_rsdl_uls',
       'fuel_aux_dstlt_vls', 'fuel_aux_dstlt_uls',
       'fuel_aux_tnktnr_dstlt_vls', 'fuel_aux_mdo',
       'fuel_boiler_rsdl_vls', 'fuel_boiler_rsdl_hs',
       'fuel_boiler_rsdl_uls', 'fuel_boiler_dstlt_vls',
       'fuel_boiler_dstlt_uls', 'fuel_boiler_tnktnr_dstlt_vls',
       'fuel_boiler_mdo', 'power_kw', 'steaming_load_kw_aux_1',
       'steaming_load_kw_aux_2', 'steaming_load_kw_aux_3',
       'steaming_load_kw_aux_4', 'steaming_load_kw_aux_5',
       'steaming_load_kw_sh_gen', 'steaming_load_kw_tg',
       'deck_last_change_user', 'engine_last_change_user',
       'deck_part_is_complete', 'engine_part_is_complete',
       'scavenge_pressure', 'seca_entry_time', 'seca_entry_lat',
       'seca_entry_long', 'seca_exit_time', 'seca_exit_lat',
       'seca_exit_long', 'rob_fresh_water', 'manvrng_miles_by_gps',
       'manvrng_miles_by_speed_log', 'tanktainer_transfd_quantity',
       'pilot_taken', 'date_time_start_transit',
       'date_time_start_transit_offset', 'date_time_end_transit',
       'date_time_end_transit_offset', 'ballast', 'tanktainer_number',
       'steaming_kwhr_total', 'cy_others', 'rob_fo_sludge',
       'rob_lo_sludge', 'rob_bilge', 'sludge_removed_fo',
       'sludge_removed_lo', 'sea_state', 'cy_lub_added_to_system_me_cc',
       'cy_lub_added_to_system_ae_cc', 'cy_lub_added_to_thrusters',
       'cy_me_lo_purifier_in_use', 'cy_ballast', 'cy_bending_moment',
       'cy_shearing_force', 'cy_tortion_moment',
       'cy_supdt_auditor_signed_on', 'cy_supdt_auditor_signed_off',
       'cy_cash_received', 'cy_lub_oil_received_me_cyl',
       'cy_lub_oil_received_me_cc', 'cy_lub_oil_received_ae_cc',
       'cy_me_under_piston_temp', 'cy_mail_received',
       'wind_direction_port_stbd', 'sea_direction_port_stbd',
       'time_pilot_onboard', 'grades_rob', 'so_2_co_2_ratio',
       'bunker_order', 'remarks', 'bdn_number', 'fuel_type',
       'carbon_factor', 'sulphur_content_pc', 'quantity', 'port_delivery',
       'product_quality', 'tanktainer_number_1', 'supplier', 'delivery',
       'volume_lt', 'density', 'viscosity', 'rob_dstlt_uls',
       'rob_dstlt_vls', 'rob_rsdl_mdo', 'rob_tnktnr_dstlt_vls',
       'rob_rsdl_vls', 'rob_rsdl_hs', 'rob_rsdl_uls', 'has_cargo',
       'steaming_time_me_hs', 'steaming_time_me_ls',
       'steaming_time_me_mgo', 'steaming_time_me_mgo_ls', 'fuel_me_hs',
       'fuel_me_ls', 'fuel_me_mgo', 'fuel_me_mgo_ls', 'fuel_aux_hs',
       'fuel_aux_ls', 'fuel_aux_mgo', 'fuel_aux_mgo_ls', 'fuel_boiler_hs',
       'fuel_boiler_ls', 'fuel_boiler_mgo', 'fuel_boiler_mgo_ls',
       'rob_fuel_hs_fo', 'rob_fuel_ls_fo', 'rob_fuel_mdo', 'rob_fuel_mgo',
       'rob_fuel_mgo_ls', 'rob_fuel_tanktainer_mgo', 'eca_miles',
       'eca_time', 'egcs_dry_waste_removed', 'egcs_running_time',
       'egcs_wet_slurry_removed', 'egcs_open_loop_running_time',
       'egcs_closed_loop_running_time', 'voyage_order', 'voyage_code',
       'eca', 'eu', 'sea_time', 'eta_country_code', 'port_country_code',
       'check_eta_code', 'check_port_code', 'status_temp_eu', 'fuel_hs',
       'fuel_ls', 'fuel_mdo', 'fuel_mgo', 'fuel_mgo_ls',
       'cargo_transport_work', 'teu_transport_work', 'eeoi_voyage_no',
       'cargo_total_old', 'draft', 'fo_per_24_hrs', 'sfoc',
       'cy_oil_gm_hr', 'scoc', 'voyage_name', 'total_fo', 'total_co_2',
       'eeoi', 'voy_condition', 'same_date', 'time_since_last_report',
       'wind_direction_360', 'true_wind_speed', 'true_wind_dir',
       'ref_power', 'ref_fuel', 'fuel_loss', 'relative_wind_speed',
       'relative_wind_direction', 'caa', 'rw', 'corrected_power',
       'draft_pow', 'draft_sp_pow', 'fo_nor', 'fo_model', 'sfoc_model',
       'sfoc_deviation', 'ref_power_corrected', 'ref_fo_corrected',
       'propulsive_eff', 'speed_performance', 'ref_speed', 'pi', 'me_con',
       'ae_con', 'bl_con', 't_con', 'hs', 'ls', 'mdo', 'mgo', 'mgo_ls',
       't_co_2', 'ae_t_steaming', 'ae_power', 'trim', 'distance_covered',
       'updated_date', 'hyd_slip_sog', 'hyd_slip_stw', 'fuel_rsdl_hs',
       'fuel_rsdl_vls', 'fuel_rsdl_uls', 'fuel_dstlt_vls',
       'fuel_dstlt_uls', 'fuel_tnktnr_dstlt_vls', 'rsdl_hs', 'rsdl_vls',
       'rsdl_uls', 'dstlt_vls', 'dstlt_uls', 'tnktnr_dstlt_vls',
       'created_at', 'updated_at', 'created_by_id', 'updated_by_id',
       'speed_by_log', 'speed_by_gps', 'fuel_m_e_lng', 'fuel_aux_lng',
       'fuel_boiler_lng', 'rob_rsdl_lng', 'sulphur_content_pc_main',
       'quantity_main', 'port_delivery_main', 'product_quality_main',
       'delivery_main', 'bdn_number_main', 'Date', 'Month', 'Year',
       'Month_name', 'date', 'Total_Calculated_HS', 'Total_Calculated_LS',
       'Total_Calculated_ULS', 'Total_Calculated_Fuel',
       'Total_Calculated_LNG', 'HS_CO2', 'LS_CO2', 'ULS_CO2', 'Total_CO2',
       'fuel_m_e_calculated', 'fuel_aux_calculated',
       'fuel_boiler_calculated', 'Total_fuel_calculated'], dtype=object)

In [14]:
MSC_noon_2023_sort_new["miles_by_gps"].isna().sum()

0

In [15]:
#for getting sum of distance in million nautical miles 

distance_2023 = MSC_noon_2023_sort_new.groupby(["imo"])[["miles_by_gps"]].sum().reset_index()
Total_distance_2023 = distance_2023[["miles_by_gps"]].sum().reset_index()
Total_distance_2023 =round( Total_distance_2023[0] / (10 ** 6), 2)
Total_distance_2023.reset_index()

   index      0
0      0  32.85

# 3.  Voyages Laden and Ballast

MSC_noon_2023_sort_new["voy_condition"].isna().sum()

# 4.  Changing unit of Fuel

In [16]:

# Fuel calculations
fuel_hs_2023 = MSC_noon_2023_sort.groupby(["imo"])[["Total_Calculated_HS"]].sum().reset_index()
Total_fuel_hs_2023 = fuel_hs_2023[["Total_Calculated_HS"]].sum().reset_index()
Total_fuel_hs_2023 = Total_fuel_hs_2023[0] / (10 ** 6)
Total_fuel_hs_2023.reset_index()

fuel_ls_2023 = MSC_noon_2023_sort.groupby(["imo"])[["Total_Calculated_LS"]].sum().reset_index()
Total_fuel_ls_2023 = fuel_ls_2023[["Total_Calculated_LS"]].sum().reset_index()
Total_fuel_ls_2023 = Total_fuel_ls_2023[0] / (10 ** 6)
Total_fuel_ls_2023.reset_index()

fuel_uls_2023 = MSC_noon_2023_sort.groupby(["imo"])[["Total_Calculated_ULS"]].sum().reset_index()
Total_fuel_uls_2023 = fuel_uls_2023[["Total_Calculated_ULS"]].sum().reset_index()
Total_fuel_uls_2023 = Total_fuel_uls_2023[0] / (10 ** 6)
Total_fuel_uls_2023.reset_index()

fuel_lng_2023 = MSC_noon_2023_sort.groupby(["imo"])[["Total_Calculated_LNG"]].sum().reset_index()
Total_fuel_lng_2023 = fuel_lng_2023[["Total_Calculated_LNG"]].sum().reset_index()
Total_fuel_lng_2023 = Total_fuel_lng_2023[0] / (10 ** 6)
Total_fuel_lng_2023.reset_index()

fuel_me_2023 = MSC_noon_2023_sort.groupby(["imo"])[["fuel_m_e_calculated"]].sum().reset_index()
Total_fuel_me_2023 = fuel_me_2023[["fuel_m_e_calculated"]].sum().reset_index()
Total_fuel_me_2023 = round(Total_fuel_me_2023[0] / (10 ** 6),2)
Total_fuel_me_2023.reset_index()

fuel_aux_2023 = MSC_noon_2023_sort.groupby(["imo"])[["fuel_aux_calculated"]].sum().reset_index()
Total_fuel_aux_2023 = fuel_aux_2023[["fuel_aux_calculated"]].sum().reset_index()
Total_fuel_aux_2023 = Total_fuel_aux_2023[0] / (10 ** 6)
Total_fuel_aux_2023.reset_index()

fuel_boiler_2023 = MSC_noon_2023_sort.groupby(["imo"])[["fuel_boiler_calculated"]].sum().reset_index()
Total_fuel_boiler_2023 = fuel_boiler_2023[["fuel_boiler_calculated"]].sum().reset_index()
Total_fuel_boiler_2023 = Total_fuel_boiler_2023[0] / (10 ** 6)
Total_fuel_boiler_2023.reset_index()

fuel_2023 = MSC_noon_2023_sort.groupby(["imo"])[["Total_fuel_calculated"]].sum().reset_index()
Total_fuel_2023 = fuel_2023[["Total_fuel_calculated"]].sum().reset_index()
Total_fuel_2023 = Total_fuel_2023[0] / (10 ** 6)
Total_fuel_2023.reset_index()

# CO2 calculations
fuel_CO2_2023 = MSC_noon_2023_sort.groupby(["imo"])[["Total_CO2"]].sum().reset_index()
Total_CO2_2023 = fuel_CO2_2023[["Total_CO2"]].sum().reset_index()
Total_CO2_2023 =Total_CO2_2023[0] / (10 ** 6)
Total_CO2_2023.reset_index()

   index          0
0      0  18.755911

In [22]:

Steam_2023=MSC_noon_2023_sort_new.groupby(["imo"])[["total_steaming_time"]].sum().reset_index()
Total_Steam_2023=Steam_2023[["total_steaming_time"]].sum().reset_index()
Total_Steam_2023=Total_Steam_2023[0]/(24)
Total_Steam_2023.reset_index(drop=True, inplace=True)
Total_Steam_2023

0    135409.75911
Name: 0, dtype: float64

In [18]:

Total_fuel_HS= {'Parameter':['Total HS Fuel'], '2023':Total_fuel_hs_2023[0].sum()}
Total_fuel_HS= pd.DataFrame(Total_fuel_HS)

Total_fuel_LS= {'Parameter':['Total LS Fuel'], '2023':Total_fuel_ls_2023[0].sum()}
Total_fuel_LS= pd.DataFrame(Total_fuel_LS)

Total_fuel_ULS= {'Parameter':['Total ULS Fuel'], '2023':Total_fuel_uls_2023[0].sum()}
Total_fuel_ULS= pd.DataFrame(Total_fuel_ULS)


Total_fuel_LNG= {'Parameter':['Total LNG Fuel'], '2023':Total_fuel_lng_2023[0].sum()}
Total_fuel_LNG= pd.DataFrame(Total_fuel_LNG)


Total_fuel= {'Parameter':['Total Fuel'], '2023':Total_fuel_2023[0].sum()}
Total_fuel= pd.DataFrame(Total_fuel)

Total_ME_fuel= {'Parameter':['Total ME Fuel'], '2023':Total_fuel_me_2023[0].sum()}
Total_ME_fuel= pd.DataFrame(Total_ME_fuel)

Total_AUX_fuel= {'Parameter':['Total AUX Fuel'], '2023':Total_fuel_aux_2023[0].sum()}
Total_AUX_fuel= pd.DataFrame(Total_AUX_fuel)

Total_BOI_fuel= {'Parameter':['Total BOILER Fuel'], '2023':Total_fuel_boiler_2023[0].sum()}
Total_BOI_fuel= pd.DataFrame(Total_BOI_fuel)

Total_CO2= {'Parameter':['Total CO2'], '2023':Total_CO2_2023[0].sum()}
Total_CO2= pd.DataFrame(Total_CO2)

In [23]:

#distance is calculating using above cell procedure(sum of vessel,total sum,divide it with 10^6 - Million nautical miles)
Total_Distance= {'Parameter':['Total Distance'], '2023':Total_distance_2023[0].sum()}
Total_Distance= pd.DataFrame(Total_Distance)

#cargo is calculating using above cell procedure(mean of vessel that is in voyage wise,total sum,multiple it with 10^6 - Million tonnes)
Total_Cargo= {'Parameter':['Total Cargo'],'2023':Total_cargo_2023[0].sum()}
Total_Cargo= pd.DataFrame(Total_Cargo)


Total_vsl= {'Parameter':['Number of Vessel'], '2023':MSC_noon_2023["imo"].nunique()}
Total_vsl= pd.DataFrame(Total_vsl)
Total_vsl['2023'] = Total_vsl['2023'].fillna(0).astype(int)

Total_voy= {'Parameter':['Total Voyages'], '2023':MSC_noon_2023["voyage"].nunique()}
Total_voy= pd.DataFrame(Total_voy)

Total_steaming_time= {'Parameter':['Total Steaming Days'], '2023':Total_Steam_2023[0].sum()}
Total_steaming_time= pd.DataFrame(Total_steaming_time)

In [24]:
#Total_Parameters=pd.concat([Total_vsl,Total_fuel_LS,Total_fuel_MGO,Total_fuel,Total_ME_fuel,Total_AUX_fuel,Total_CO2,Total_Cargo,Total_Distance,Total_fresh_pro,Total_fresh_con,Total_voy,Total_steaming_time,Total_ballast_voy_time,Total_Laden_voy_time,Avg_ballast_voy_time,Avg_Laden_voy_time])
Total_Parameters=pd.concat([Total_vsl,Total_fuel_HS,Total_fuel_LS,Total_fuel_ULS,Total_fuel_LNG,Total_fuel,Total_ME_fuel,Total_AUX_fuel,Total_BOI_fuel,Total_CO2,Total_voy,Total_Cargo,Total_Distance,Total_steaming_time])

Total_Parameters=Total_Parameters.reset_index()
Total_Parameters=Total_Parameters.drop(['index'], axis=1)

In [25]:

unit_parameters = ["", 'Kilotonne', 'Kilotonne', 'Kilotonne', 'Kilotonne','Kilotonne', 'Kilotonne', 'Kilotonne', 'Kilotonne', 'Kilotonne', '', 'Kilotonne', 'Nautical Miles', 'Day']
parameter_unit = pd.DataFrame(unit_parameters, columns=['Unit'])
Total_Parameter_1 = pd.concat([Total_Parameters, parameter_unit], axis=1)
Total_Parameter_1

              Parameter           2023            Unit
0      Number of Vessel     557.000000
1         Total HS Fuel       2.709065       Kilotonne
2         Total LS Fuel       2.447774       Kilotonne
3        Total ULS Fuel       0.813146       Kilotonne
4        Total LNG Fuel       0.003790       Kilotonne
5            Total Fuel       5.736895       Kilotonne
6         Total ME Fuel       4.190000       Kilotonne
7        Total AUX Fuel       1.318509       Kilotonne
8     Total BOILER Fuel       0.230052       Kilotonne
9             Total CO2      18.755911       Kilotonne
10        Total Voyages   11151.000000
11          Total Cargo     283.120000       Kilotonne
12       Total Distance      32.850000  Nautical Miles
13  Total Steaming Days  135409.759110             Day

Total_Parameter_1["%change(2021-2022)"]=(Total_Parameter_1["2022"]-Total_Parameter_1["2021"])*(100)/(Total_Parameter_1["2021"])
#Total_Parameter_1["Projected 2022"]=(Total_Parameter_1["2022"]*12)/(7)
#Total_Parameter_1["%change projected22"]=(Total_Parameter_1["Projected 2022"]-Total_Parameter_1["2021"])*(100)/(Total_Parameter_1["2021"])
Total_Parameter_1=Total_Parameter_1[['Parameter', "Unit", '2021',"2022",'%change(2021-2022)' ]]
Total_Parameter_1=Total_Parameter_1.round(decimals = 2)
Total_Parameter_1

In [ ]:
Total_Parameter_1.to_excel("MSC_2023_Total_Parameter_final.xlsx",index=False)