In [1]:
import numpy as np
import pandas as pd
import warnings
import matplotlib.pyplot as plt
import requests
import io

warnings.filterwarnings("ignore")

In [2]:
MSC_noon_2024=pd.read_csv("msc_2024.csv")

In [3]:
pd.set_option('display.max_columns', None)  
MSC_noon_2024

,id,imo,vessel,id_vessel,gid,voyage,corrected_date,report_date_time,report_date_time_offset,report_type,status,lat,long,latitude,longitude,me_foc,cargo_total,total_steaming_time,me_fuel_only_steaming_time,miles_by_gps,oil_cyl,rpm,slip,wind_direction,wind_speed,draft_aft,draft_fwd,displacement,course_at_sea,wave_height,sea_direction,cargo_total_teu,ambient_temp,sw_temp,miles_by_speed_log,eta_port_code,eta_date_time,eta_date_time_offset,eta_port,time_change,time_sea,temp_min,temp_max,requested_speed,rem_dist_to_pilot,rem_time_to_pilot,total_unplnd_stpge_tech,total_unplnd_stpge_ope_wx,reefers_positive_plugged,reefers_negative_plugged,me_total_revs_counter,port_code,port,aux_blowers_on,hold_ventilation_on,since_date_time,since_date_time_offset,time_hrs_anchor,time_hrs_drift,reason,type_of_delay,etb_date_time,etb_date_time_offset,pilot_date_time,pilot_date_time_offset,time_manoeuvring,tug_arr,tug_shift,etd_date_time,etd_date_time_offset,shift_berth_hours,cargo_load,cargo_disch,teu_full,teu_empty,bilge_removed,garbage_removed,garbage_remvl_reqstd,garbage_remvl_cmplsry,fw_supply,cy_crew_signed_on,cy_crew_signed_off,cy_doctors_visit,cy_mail_received_ref_no,cy_lub_oil_sample_landed,cy_checkd_for_stowaways,cy_stowaways_on_board,cy_dep_gm_mtr,cy_requisitions_received,distance_to_next_pilot,tug_sailing_transit,steaming_time_me_rsdl_vls,steaming_time_me_rsdl_hs,steaming_time_me_rsdl_uls,steaming_time_me_dstlt_vls,steaming_time_me_dstlt_uls,steaming_time_me_tnktnr_dstlt_vls,steaming_time_me_mdo,steaming_time_aux_1,steaming_time_aux_2,steaming_time_aux_3,steaming_time_aux_4,steaming_time_aux_5,steaming_time_sh_gen,steaming_time_tg,fuel_me_rsdl_vls,fuel_me_rsdl_hs,fuel_me_rsdl_uls,fuel_me_dstlt_vls,fuel_me_dstlt_uls,fuel_me_mdo,fuel_me_tnktnr_dstlt_vls,fuel_aux_rsdl_vls,fuel_aux_rsdl_hs,fuel_aux_rsdl_uls,fuel_aux_dstlt_vls,fuel_aux_dstlt_uls,fuel_aux_tnktnr_dstlt_vls,fuel_aux_mdo,fuel_boiler_rsdl_vls,fuel_boiler_rsdl_hs,fuel_boiler_rsdl_uls,fuel_boiler_dstlt_vls,fuel_boiler_dstlt_uls,fuel_boiler_tnktnr_dstlt_vls,fuel_boiler_mdo,power_kw,steaming_load_kw_aux_1,steaming_load_kw_aux_2,steaming_load_kw_aux_3,steaming_load_kw_aux_4,steaming_load_kw_aux_5,steaming_load_kw_sh_gen,steaming_load_kw_tg,deck_last_change_user,engine_last_change_user,deck_part_is_complete,engine_part_is_complete,scavenge_pressure,seca_entry_time,seca_entry_lat,seca_entry_long,seca_exit_time,seca_exit_lat,seca_exit_long,rob_fresh_water,manvrng_miles_by_gps,manvrng_miles_by_speed_log,tanktainer_transfd_quantity,pilot_taken,date_time_start_transit,date_time_start_transit_offset,date_time_end_transit,date_time_end_transit_offset,ballast,tanktainer_number,steaming_kwhr_total,cy_others,rob_fo_sludge,rob_lo_sludge,rob_bilge,sludge_removed_fo,sludge_removed_lo,sea_state,cy_lub_added_to_system_me_cc,cy_lub_added_to_system_ae_cc,cy_lub_added_to_thrusters,cy_me_lo_purifier_in_use,cy_ballast,cy_bending_moment,cy_shearing_force,cy_tortion_moment,cy_supdt_auditor_signed_on,cy_supdt_auditor_signed_off,cy_cash_received,cy_lub_oil_received_me_cyl,cy_lub_oil_received_me_cc,cy_lub_oil_received_ae_cc,cy_me_under_piston_temp,cy_mail_received,wind_direction_port_stbd,sea_direction_port_stbd,time_pilot_onboard,grades_rob,so_2_co_2_ratio,bunker_order,remarks,bdn_number,fuel_type,carbon_factor,sulphur_content_pc,quantity,port_delivery,product_quality,tanktainer_number_1,supplier,delivery,volume_lt,density,viscosity,rob_dstlt_uls,rob_dstlt_vls,rob_rsdl_mdo,rob_tnktnr_dstlt_vls,rob_rsdl_vls,rob_rsdl_hs,rob_rsdl_uls,has_cargo,steaming_time_me_hs,steaming_time_me_ls,steaming_time_me_mgo,steaming_time_me_mgo_ls,fuel_me_hs,fuel_me_ls,fuel_me_mgo,fuel_me_mgo_ls,fuel_aux_hs,fuel_aux_ls,fuel_aux_mgo,fuel_aux_mgo_ls,fuel_boiler_hs,fuel_boiler_ls,fuel_boiler_mgo,fuel_boiler_mgo_ls,rob_fuel_hs_fo,rob_fuel_ls_fo,rob_fuel_mdo,rob_fuel_mgo,rob_fuel_mgo_ls,rob_fuel_tanktainer_mgo,eca_miles,eca_time,egcs_dry_waste_removed,egcs_running_time,egcs_wet_slurry_removed,egcs_open_loop_running_time,egcs_closed_loop_running_time,voyage_order,voyage_code,eca,eu,sea_time,eta_country_code,port_country_code,check_eta_code,check_port_code,status_temp_eu,fuel_hs,fuel_ls,fuel_mdo,fuel_mgo,fuel_mgo_ls,cargo_transport_work,teu_transport_work,eeoi_voyage_no,cargo_total_old,draft,fo_per_24_hrs,sfoc,cy_oil_gm_hr,scoc,voyage_name,total_fo,total_co_2,eeoi,voy_condition,same_date,time_since_last_report,wind_direction_360,true_wind_speed,true_wind_dir,ref_power,ref_fuel,fuel_loss,relative_wind_speed,relative_wind_direction,caa,rw,corrected_power,draft_pow,draft_sp_pow,fo_nor,fo_model,sfoc_model,sfoc_deviation,ref_power_corrected,ref_fo_corrected,propulsive_eff,speed_performance,ref_speed,pi,me_con,ae_con,bl_con,t_con,hs,ls,mdo,mgo,mgo_ls,t_co_2,ae_t_steaming,ae_power,trim,distance_covered,updated_date,hyd_slip_sog,hyd_slip_stw,fuel_rsdl_hs,fuel_rsdl_vls,fuel_rsdl_uls,fuel_dstlt_vls,fuel_dstlt_uls,fuel_tnktnr_dstlt_vls,rsdl_hs,rsdl_vls,rsdl_uls,dstlt_vls,dstlt_uls,tnktnr_dstlt_vls,created_at,updated_at,created_by_id,updated_by_id,speed_by_log,speed_by_gps,fuel_m_e_lng,fuel_aux_lng,fuel_boiler_lng,rob_rsdl_lng,sulphur_content_pc_main,quantity_main,port_delivery_main,product_quality_main,delivery_main,bdn_number_main
0,4689252,9146479,MSC VILDA X,VILD,00057cb8-20c6-4209-be62-28c236acf763,XA343A,2024-01-01,2024-01-01 12:00:00,UTC +02:00,NOON,AT SEA,3220S,03100E,-32.333333,31.000000,68.59,9778.77,24.0,24.0,312.0,599.0,60.8,24.90,42.0,34.0,10.00,6.5,68821.0,48.0,3.77,61.67,764.0,28.0,23.7,330.0,INMUN,2024-01-14 10:30:00,UTC +05:30,MUNDRA,NaN,24.0,291.0,346.0,13.0,4006.0,307.0,0.0,0.0,0.0,0.0,731281810.0,GHTEM,TEMA,True,False,NaN,NaN,NaN,NaN,PORT CONGESTION,NaN,2023-12-21 23:00:00,UTC +00:00,NaN,NaN,NaN,NaN,NaN,2023-12-22 18:30:00,UTC +00:00,NaN,NaN,NaN,388,376,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,24.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,68.59,0.0,0,0.0,0,0,0.0,7.09,0.0,0,0.0,0.0,0,0.0,0.0,0.0,0,0.0,0,0,16300,1439.0,0.0,0.0,0.0,0.0,0.0,0.0,2O,CE,True,True,0.25,NaN,NaN,NaN,NaN,NaN,NaN,157.0,0.0,NaN,NaN,False,NaN,NaN,NaN,NaN,13803.0,0,34527.3,NaN,NaN,NaN,52.94,NaN,NaN,5.0,0.0,0.0,0.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,S,S,NaN,NaN,0.00,NaN,NaN,NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0.0,0.0,0.00,3206.29,0.0,True,24.0,0.0,0.0,0.0,68.59,0.0,0,0.0,7.09,0.0,0.0,0.0,0.0,0.0,0,0.0,3206.29,0.00,0.0,0.0,0.00,0.0,0.0,0.0,NaN,24.0,NaN,24.0,0.0,NaN,NaN,N,N,24.0,NaN,NaN,NaN,NaN,0,75.68,0.0,0,0.0,0.0,3050980.0,238368.0,NaN,0,8.250,68.5900,175.3320,22462.50,1.378070,0,75.68,235.6670,0,Laden,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,68.59,7.09,0.0,75.68,75.68,0.0,0,0.0,0.0,235.67,24.0,1439.0,3.50,312.0,2024-01-19 17:32:03,NaN,NaN,75.68,0.0,0.0,0,0.0,0.0,75.68,0.0,0.0,0,0.0,0.0,NaN,NaN,NaN,NaN,13.7500,13.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4689253,9908047,MSC WASHINGTON,WASH,0005f36e-3d07-4931-a455-15283d489b32,XA348A,2024-01-01,2024-01-01 12:00:00,UTC +08:00,NOON,AT SEA,3129N,12358E,31.483333,123.966667,50.50,19463.80,24.0,24.0,312.0,300.0,51.8,14.17,20.0,26.0,10.50,7.8,89911.0,2.0,1.18,37.88,9351.0,11.0,15.0,292.0,CNTXG,2024-01-03 06:00:00,UTC +08:00,TIANJINXINGANG,NaN,24.0,233.0,265.0,13.0,632.0,42.0,0.0,0.0,0.0,0.0,34315650.0,QAHMD,HAMAD,True,False,NaN,NaN,NaN,NaN,PILOTAGE SUSPENDED DUE TO DENSE FOG,NaN,2023-12-11 14:00:00,UTC +03:00,NaN,NaN,NaN,NaN,NaN,2023-12-12 21:30:00,UTC +03:00,NaN,NaN,NaN,0,9351,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.0,0.0,0.0,0.0,24.0,0.0,0.0,0.0,24.0,0.0,0.0,0.0,0.0,0.0,49.9,0.00,0.0,0,0.6,0,0,9.5,0.00,0.0,0,0.4,0.0,0,0.4,0.0,0.0,0,0.0,0,0,11285,0.0,1862.0,0.0,0.0,0.0,0.0,0.0,2OFF,ce,True,True,0.80,NaN,NaN,NaN,NaN,NaN,NaN,320.0,0.0,NaN,NaN,False,NaN,NaN,NaN,NaN,24056.0,0,44685.0,NaN,NaN,NaN,34.50,NaN,NaN,3.0,0.0,0.0,0.0,Both,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,P,P,NaN,NaN,0.00,NaN,NaN,NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,280.40,0.0,0.0,0.0,1368.00,0.00,0.0,True,0.0,24.0,0.0,24.0,0.00,49.9,0,0.6,0.00,9.5,0.0,0.4,0.0,0.4,0,0.0,0.00,1368.00,0.0,0.0,280.40,0.0,0.0,0.0,NaN,0.0,NaN,0.0,0.0,196.0,QAHMD-CNTXG,N,N,48.0,CN,QA,NaN,NaN,0,0.00,59.8,0,0.0,1.0,6072710.0,2917510.0,196.0,0,9.150,25.2500,93.2285,5625.00,0.498449,0,60.80,189.4230,0,Laden,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,50.50,9.90,0.4,60.80,0.00,59.8,0,0.0,1.0,189.42,24.0,1862.0,2.70,312.0,2024-01-19 17:32:03,NaN,NaN,0.00,59.8,0.0,0,1.0,0.0,0.00,59.8,0.0,0,1.0,0.0,NaN,NaN,NaN,NaN,12.1667,13.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4689254,9927275,MSC SOFIA,SOFI,005f1864-6317-413c-adaf-d8a73f69e116,FY349A,2024-01-01,2023-12-31 23:00:00,UTC +08:00,EOSP,AT SEA,0121N,10422E,1.350000,104.366667,36.30,129113.00,11.0,11.0,186.0,280.0,58.5,2.50,90.0,5.0,15.60,14.2,180939.6,231.0,1.76,163.53,8185.0,27.0,29.0,183.0,SGSIN,2024-01-01 03:00:00,UTC +08:00,NaN,NaN,11.0,285.0,301.0,19.4,NaN,NaN,0.0,0.0,0.0,61.0,15322442.0,SGSIN,SINGAPORE,False,False,NaN,NaN,NaN,NaN,BERTH CONGESTION,NaN,2024-01-01 05:00:00,UTC +08:00,NaN,NaN,NaN,NaN,NaN,2023-12-28 16:30:00,UTC +08:00,NaN,NaN,NaN,8183,2,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.7,9.3,0.0,0.0,0.0,0.0,36.3,0.00,0.0,0,0.0,0,0,6.1,0.00,0.0,0,0.2,0.0,0,0.0,0.0,0.0,0,0.0,0,0,19450,0.0,2036.0,2144.0,0.0,0.0,0.0,0.0,MASTER,CE,True,True,1.20,NaN,NaN,NaN,NaN,NaN,NaN,438.0,0.0,NaN,NaN,False,NaN,NaN,NaN,NaN,3868.0,0,23404.0,NaN,NaN,NaN,50.00,NaN,NaN,4.0,0.0,0.0,0.0,Both,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,S,S,NaN,NaN,0.00,NaN,NaN,NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,226.26,0.0,0.0,0.0,1862.85,0.00,0.0,True,0.0,11.0,0.0,0.0,0.00,36.3,0,0.0,0.00,6.1,0.0,0.2,0.0,0.0,0,0.0,0.00,1862.85,0.0,0.0,226.26,0.0,0.0,0.0,NaN,0.0,NaN,0.0,0.0,159.0,CNSHK-SGSIN,N,N,11.0,SG,CN,NaN,NaN,0,0.00,42.4,0,0.0,0.2,24015000.0,1522410.0,159.0,0,14.900,79.2000,169.6660,22909.10,1.177850,0,42.60,132.6750,0,Laden,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,36.30,6.30,0.0,42.60,0.00,42.4,0,0.0,0.2,132.67,11.0,4180.0,1.40,186.0,2024-01-19 17:32:03,NaN,NaN,0.00,42.4,0.0,0,0.2,0.0,0.00,42.4,0.0,0,0.2,0.0,NaN,NaN,NaN,NaN,16.6364,16.9091,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4689336,9227302,MSC KATYA R.,KATA,0f138389-393d-4c2e-b09f-429dd5019609,NQ348A,2024-01-01,2023-12-31 22:24:00,UTC -05:00,COSP,DRIFTING,0244S,08025W,-2.733333,-80.416667,5.12,11385.70,4.4,4.4,51.0,19.0,0.0,0.00,5.0,5.0,11.10,10.9,43514.0,257.0,0.14,5.00,807.0,32.0,7.0,NaN,PEPAI,2024-01-01 13:00:00,UTC -05:00,PAITA,NaN,4.4,178.0,214.0,11.8,NaN,NaN,0.0,0.0,347.0,0.0,94010584.0,ECGYE,GUAYAQUIL,True,True,NaN,NaN,NaN,NaN,BERTH CONGESTION,NaN,2023-12-30 20:00:00,UTC -05:00,NaN,NaN,4.4,NaN,NaN,2023-12-31 18:00:00,UTC -05:00,NaN,NaN,NaN,752,55,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,166.0,2.0,0.0,4.4,0.0,0.0,0.0,0.0,0.0,4.4,4.4,4.4,0.0,0.0,0.0,0.0,0.0,5.12,0.0,0,0.0,0,0,0.0,2.36,0.0,0,1.3,0.0,0,0.0,0.0,0.0,0,0.2,0,0,4560,1350.0,1350.0,1000.0,0.0,0.0,0.0,0.0,20,CE,True,True,0.10,NaN,NaN,NaN,NaN,NaN,NaN,330.0,51.0,49.0,NaN,True,NaN,NaN,NaN,NaN,7495.0,0,136051.0,NaN,NaN,NaN,12.30,NaN,NaN,2.0,0.0,0.0,0.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,P,P,4.8,NaN,0.37,NaN,NaN,NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,336.64,0.0,0.0,0.0,0.00,2421.19,0.0,True,4.4,0.0,0.0,0.0,5.12,0.0,0,0.0,2.36,0.0,0.0,1.3,0.0,0.0,0,0.2,2421.19,0.00,0.0,0.0,336.64,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,779.0,ECGYE-PEPAI,N,N,4.4,PE,EC,NaN,NaN,0,7.48,0.0,0,0.0,1.5,580671.0,41157.0,779.0,0,11.000,27.9273,255.1830,3886.36,0.852273,0,8.98,28.1017,0,Laden,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5.12,3.66,0.2,8.98,7.48,0.0,0,0.0,1.5,28.10,13.2,3700.0,0.20,51.0,2024-01-19 17:32:03,NaN,NaN,7.48,0.0,0.0,0,1.5,0.0,7.48,0.0,0.0,0,1.5,0.0,NaN,NaN,NaN,NaN,0.0000,0.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4689337,9793947,MSC SIYA B,SIYA,0f5803bf-fcdd-42a3-a9e6-d3fe172037d9,NaN,2024-01-01,2023-12-31 12:23:59,UTC +03:00,SND,NaN,NaN,NaN,NaN,NaN,NaN,117295.00,NaN,NaN,0.0,NaN,0.0,0.00,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5471,1572,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.00,0.0,0,0.0,0,0,0.0,0.00,0.0,0,0.0,0.0,0,0.0,0.0,0.0,0,0.0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,0.0,0.0,NaN,0.00,0.0,0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0,0.0,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,265.0,SAKAC-DJJIB,N,N,0.0,DJ,SA,NaN,NaN,0,0.00,0.0,0,0.0,0.0,0.0,0.0,265.0,0,0.000,0.0000,0.0000,0.00,0.000000,0,0.00,0.0000,0,Laden,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.0,0.00,0.00,0.0,0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,2024-01-19 17:32:03,NaN,NaN,0.00,0.0,0.0,0,0.0,0.0,0.00,0.0,0.0,0,0.0,0.0,NaN,NaN,NaN,NaN,0.0000,0.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35159,4727120,9957347,MSC THAIS,THAI,f36fe7b3-55dd-4e92-b582-8ded207bd57c,FY350A,2024-01-07,2024-01-07 12:00:00,UTC +08:00,NOON,AT SEA,1618N,11315E,16.300000,113.250000,95.10,135739.00,17.0,17.0,340.0,757.0,70.1,5.60,100.0,21.0,15.50,15.5,192520.0,209.0,1.00,138.83,8830.0,25.0,23.0,334.0,SGSIN,2024-01-09 21:00:00,UTC +08:00,SINGAPORE,NaN,17.0,318.0,351.0,19.9,1088.0,57.0,0.0,0.0,3.0,28.0,1354045.0,CNSHK,SHEKOU,False,True,NaN,NaN,NaN,NaN,AWAITING BERTHING,NaN,2024-01-06 04:30:00,UTC +08:00,NaN,NaN,NaN,NaN,NaN,2024-01-06 15:30:00,UTC +08:00,NaN,NaN,NaN,8830,0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,17.0,0.0,0.0,95.1,0.00,0.0,0,0.0,0,0,0.0,0.00,0.0,0,11.0,0.0,0,0.0,0.0,0.0,0,0.0,0,0,30242,1182.0,0.0,0.0,0.0,3040.0,0.0,0.0,2OFF,CE,True,True,2.40,NaN,NaN,NaN,NaN,NaN,NaN,302.0,0.0,NaN,NaN,False,NaN,NaN,NaN,NaN,11204.0,0,4222.0,NaN,NaN,NaN,12.40,NaN,NaN,3.0,0.0,0.0,0.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,P,P,NaN,NaN,0.00,NaN,NaN,NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,295.01,0.0,0.0,0.0,793.39,0.00,0.0,True,0.0,17.0,0.0,0.0,0.00,95.1,0,0.0,0.00,0.0,0.0,11.0,0.0,0.0,0,0.0,0.00,793.39,0.0,0.0,295.01,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,107.0,CNSHK-SGSIN,N,N,17.0,SG,CN,NaN,NaN,0,0.00,95.1,0,0.0,11.0,46151300.0,3002200.0,107.0,0,15.500,134.2590,184.9780,40076.50,1.325190,0,106.10,331.4070,0,Laden,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,95.10,11.00,0.0,106.10,0.00,95.1,0,0.0,11.0,331.41,19.0,4222.0,0.00,340.0,2024-02-11 13:07:34,NaN,NaN,0.00,95.1,0.0,0,11.0,0.0,0.00,95.1,0.0,0,11.0,0.0,NaN,NaN,NaN,NaN,19.6471,20.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35160,4727126,9244946,MSC KALAMATA VII,KALA,f4701792-8c60-4a27-9814-0a3bccf29fda,KQ350A,2024-01-07,2024-01-06 14:30:00,UTC +08:00,COSP,DRIFTING,2213N,11409E,22.216667,114.150000,1.50,52409.00,1.0,1.0,8.9,12.0,0.0,0.00,90.0,8.0,12.85,12.6,93669.0,130.0,0.36,90.00,4675.0,24.0,19.0,NaN,CNYTN,2024-01-06 18:00:00,UTC +08:00,YANTIAN,NaN,1.6,148.0,170.0,10.0,NaN,NaN,0.0,0.0,1.0,7.0,16582026.0,HKHKG,HONG KONG,True,False,NaN,NaN,NaN,NaN,Congestion,NaN,2024-01-05 23:30:00,UTC +08:00,NaN,NaN,1.3,NaN,NaN,2024-01-06 13:00:00,UTC +08:00,NaN,NaN,NaN,4675,0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.6,0.0,1.6,1.6,0.0,0.0,0.0,1.5,0.00,0.0,0,0.0,0,0,0.8,0.00,0.0,0,0.0,0.0,0,0.2,0.0,0.0,0,0.0,0,0,7395,710.0,0.0,700.0,710.0,0.0,0.0,0.0,O.Dvorchuk,I. Akulibaba,True,True,0.20,NaN,NaN,NaN,NaN,NaN,NaN,202.0,8.9,8.8,NaN,True,NaN,NaN,NaN,NaN,9345.0,NaN,3392.0,NaN,NaN,NaN,2.70,NaN,NaN,2.0,0.0,0.0,0.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,P,P,1.5,NaN,0.00,NaN,NaN,NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0.0,0.0,685.90,0.00,0.0,True,0.0,1.0,0.0,0.0,0.00,1.5,0,0.0,0.00,0.8,0.0,0.0,0.0,0.2,0,0.0,0.00,685.90,0.0,0.0,0.00,0.0,NaN,NaN,NaN,0.0,NaN,0.0,0.0,140.0,HKHKG-CNYTN,N,N,1.0,CN,HK,NaN,NaN,0,0.00,2.5,0,0.0,0.0,466440.0,41607.5,140.0,0,12.725,36.0000,202.8400,10800.00,1.460450,0,2.50,7.7850,0,Laden,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.50,0.80,0.2,2.50,0.00,2.5,0,0.0,0.0,7.78,4.8,2120.0,0.25,8.9,2024-02-11 13:07:34,NaN,NaN,0.00,2.5,0.0,0,0.0,0.0,0.00,2.5,0.0,0,0.0,0.0,NaN,NaN,NaN,NaN,0.0000,0.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35161,4727166,9403437,MSC AZURIT F,AZRT,fa51ce08-3ca5-4132-b0b0-dc8b7327a60c,YN341A,2024-01-07,2024-01-07 12:00:00,UTC +01:00,DLY D,DRIFTING,4518N,01428E,45.300000,14.466667,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,5.60,3.7,10655.0,0.0,0.00,0.00,0.0,11.0,12.0,NaN,HRRJK,2023-12-23 12:00:00,UTC +01:00,RIJEKA,NaN,24.0,374.0,400.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,75644.0,HRRJK,RIJEKA,False,False,NaN,NaN,0.0,0.0,REPAIRS,LAYBAY,2024-01-15 12:00:00,UTC +01:00,NaN,NaN,0.0,NaN,NaN,2024-01-15 12:00:00,UTC +01:00,NaN,NaN,NaN,0,0,NaN,NaN,False,False,NaN,0,0,No,0,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.00,0.0,0,0.0,0,0,0.0,0.00,0.0,0,0.0,0.0,0,0.0,0.0,0.0,0,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,128.0,0.0,0.0,NaN,False,NaN,NaN,NaN,NaN,2743.0,0,0.0,NaN,NaN,NaN,0.00,NaN,NaN,NaN,0.0,0.0,0.0,0,NaN,NaN,NaN,NaN,0,0,0.0,0.0,0.0,0.0,NaN,False,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,0.0,0.0,NaN,0.00,0.0,0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0,0.0,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,N,0.0,NaN,NaN,NaN,NaN,0,0.00,0.0,0,0.0,0.0,0.0,0.0,NaN,0,4.650,0.0000,0.0000,0.00,0.000000,0,0.00,0.0000,0,Ballast,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.0,0.00,0.00,0.0,0,0.0,0.0,0.00,0.0,0.0,1.90,0.0,2024-02-11 13:07:34,NaN,NaN,0.00,0.0,0.0,0,0.0,0.0,0.00,0.0,0.0,0,0.0,0.0,NaN,NaN,NaN,NaN,0.0000,0.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
MSC_noon_2024['Date'] = pd.to_datetime(MSC_noon_2024['corrected_date']).apply(lambda x:x.strftime("%d"))
MSC_noon_2024['Month'] = pd.to_datetime(MSC_noon_2024['corrected_date']).apply(lambda x:x.strftime("%m"))
MSC_noon_2024['Year'] = pd.to_datetime(MSC_noon_2024['corrected_date']).apply(lambda x:x.strftime("%Y"))
MSC_noon_2024['Month_name'] = pd.to_datetime(MSC_noon_2024['corrected_date']).apply(lambda x:x.strftime("%B"))
MSC_noon_2024['date'] = pd.to_datetime(MSC_noon_2024["corrected_date"]).dt.date
MSC_noon_2024.dropna(subset=['imo'])
MSC_noon_2024_sort=MSC_noon_2024.sort_values(by="corrected_date")
#Total HS,LS,MGO and Total Fuel
MSC_noon_2024_sort['Total_Calculated_HS']= MSC_noon_2024_sort[['fuel_me_rsdl_hs' , 'fuel_aux_rsdl_hs' , 'fuel_boiler_rsdl_hs']].sum(axis=1)
MSC_noon_2024_sort['Total_Calculated_LS'] = MSC_noon_2024_sort[['fuel_me_rsdl_vls' , 'fuel_me_dstlt_vls' , 'fuel_me_tnktnr_dstlt_vls' ,'fuel_aux_rsdl_vls' ,  'fuel_aux_dstlt_vls' , 'fuel_aux_tnktnr_dstlt_vls','fuel_boiler_rsdl_vls','fuel_boiler_dstlt_vls','fuel_boiler_tnktnr_dstlt_vls']].fillna(0).sum(axis=1)
MSC_noon_2024_sort['Total_Calculated_ULS'] = MSC_noon_2024_sort[['fuel_me_rsdl_uls' , 'fuel_aux_rsdl_uls' , 'fuel_boiler_rsdl_uls' ,'fuel_me_dstlt_uls' ,'fuel_aux_dstlt_uls' , 'fuel_boiler_dstlt_uls']].fillna(0).sum(axis=1)
MSC_noon_2024_sort['Total_Calculated_Fuel'] = MSC_noon_2024_sort[['Total_Calculated_HS' ,'Total_Calculated_LS' , 'Total_Calculated_ULS']].fillna(0).sum(axis=1)
MSC_noon_2024_sort['Total_Calculated_LNG'] = MSC_noon_2024_sort[['fuel_m_e_lng' ,'fuel_boiler_lng' , 'fuel_aux_lng']].fillna(0).sum(axis=1)

#HS_CO2,LSCO2,MGO_CO2 and Total CO2
MSC_noon_2024_sort['HS_CO2'] = 3.114 * MSC_noon_2024_sort["Total_Calculated_HS"]
MSC_noon_2024_sort['LS_CO2'] = 3.151 * MSC_noon_2024_sort["Total_Calculated_LS"]
MSC_noon_2024_sort['ULS_CO2'] = 3.206 * MSC_noon_2024_sort["Total_Calculated_ULS"]
MSC_noon_2024_sort['Total_CO2'] = MSC_noon_2024_sort[['HS_CO2' ,'LS_CO2' ,'ULS_CO2']].fillna(0).sum(axis=1)

MSC_noon_2024_sort["fuel_m_e_calculated"]=MSC_noon_2024_sort[["fuel_me_rsdl_hs","fuel_me_rsdl_vls","fuel_me_dstlt_vls",'fuel_me_rsdl_uls','fuel_me_rsdl_uls','fuel_me_tnktnr_dstlt_vls']].fillna(0).sum(axis=1)
MSC_noon_2024_sort["fuel_aux_calculated"]=MSC_noon_2024_sort[["fuel_aux_rsdl_vls","fuel_aux_rsdl_hs","fuel_aux_dstlt_vls",'fuel_aux_rsdl_uls','fuel_aux_dstlt_uls','fuel_aux_tnktnr_dstlt_vls']].fillna(0).sum(axis=1)
MSC_noon_2024_sort["fuel_boiler_calculated"]=MSC_noon_2024_sort[["fuel_boiler_rsdl_hs","fuel_boiler_rsdl_vls","fuel_boiler_dstlt_vls",'fuel_boiler_rsdl_uls','fuel_boiler_tnktnr_dstlt_vls','fuel_boiler_dstlt_uls']].fillna(0).sum(axis=1)
MSC_noon_2024_sort["Total_fuel_calculated"]=MSC_noon_2024_sort[["fuel_m_e_calculated","fuel_aux_calculated","fuel_boiler_calculated"]].fillna(0).sum(axis=1)

# Yearly Total of each Parameters

# 1. CARGO TOTAL

In [7]:
MSC_noon_2024_sort["voyage"].isna().sum()

7457

In [8]:
MSC_noon_2024_sort["voyage"].unique()

array(['XA343A', 'WP351R', nan, ..., 'WF403R', 'AN403R', 'CX402A'],
      dtype=object)

In [11]:

MSC_noon_2024_str = MSC_noon_2024_sort[MSC_noon_2024_sort['voyage'].apply(lambda x: isinstance(x, str))]
MSC_noon_2024_str['voyage'] = MSC_noon_2024_str['voyage'].str.lstrip('0').str.rstrip('.0')

# Filter by Float Type and Convert to String
MSC_noon_2024_float = MSC_noon_2024_sort[MSC_noon_2024_sort['voyage'].apply(lambda x: isinstance(x, float))]
MSC_noon_2024_float['voyage'] = pd.to_numeric(MSC_noon_2024_float['voyage'], errors='coerce').fillna(0).astype(int).astype(str)

# Filter by Integer Type and Convert to String
MSC_noon_2024_int = MSC_noon_2024_sort[MSC_noon_2024_sort['voyage'].apply(lambda x: isinstance(x, int))]
MSC_noon_2024_int['voyage'] = MSC_noon_2024_int['voyage'].astype(int).astype(str)

# Concatenate DataFrames and Sort
MSC_noon_2024_sort_new = pd.concat([MSC_noon_2024_str, MSC_noon_2024_float, MSC_noon_2024_int])
MSC_noon_2024_sort_new = MSC_noon_2024_sort_new.sort_values(by=["corrected_date"])

In [12]:
MSC_noon_2024_sort_new["voyage"].isna().sum()

0

In [13]:
MSC_noon_2024_sort_new["cargo_total"].isna().sum()

0

In [14]:
cargo_vessel_mean_2024 = MSC_noon_2024_sort_new.groupby(["imo", "voyage"])[["cargo_total"]].mean().reset_index()
Total_cargo_2024 = cargo_vessel_mean_2024[["cargo_total"]].sum().reset_index()
Total_cargo_2024 = round(Total_cargo_2024[0] / (10 ** 6), 2)
Total_cargo_2024.reset_index()

   index      0
0      0  46.79

# 2.  MILES BY GPS

In [15]:
MSC_noon_2024_sort_new.columns.values

array(['id', 'imo', 'vessel', 'id_vessel', 'gid', 'voyage',
       'corrected_date', 'report_date_time', 'report_date_time_offset',
       'report_type', 'status', 'lat', 'long', 'latitude', 'longitude',
       'me_foc', 'cargo_total', 'total_steaming_time',
       'me_fuel_only_steaming_time', 'miles_by_gps', 'oil_cyl', 'rpm',
       'slip', 'wind_direction', 'wind_speed', 'draft_aft', 'draft_fwd',
       'displacement', 'course_at_sea', 'wave_height', 'sea_direction',
       'cargo_total_teu', 'ambient_temp', 'sw_temp', 'miles_by_speed_log',
       'eta_port_code', 'eta_date_time', 'eta_date_time_offset',
       'eta_port', 'time_change', 'time_sea', 'temp_min', 'temp_max',
       'requested_speed', 'rem_dist_to_pilot', 'rem_time_to_pilot',
       'total_unplnd_stpge_tech', 'total_unplnd_stpge_ope_wx',
       'reefers_positive_plugged', 'reefers_negative_plugged',
       'me_total_revs_counter', 'port_code', 'port', 'aux_blowers_on',
       'hold_ventilation_on', 'since_date_time', 'since_date_time_offset',
       'time_hrs_anchor', 'time_hrs_drift', 'reason', 'type_of_delay',
       'etb_date_time', 'etb_date_time_offset', 'pilot_date_time',
       'pilot_date_time_offset', 'time_manoeuvring', 'tug_arr',
       'tug_shift', 'etd_date_time', 'etd_date_time_offset',
       'shift_berth_hours', 'cargo_load', 'cargo_disch', 'teu_full',
       'teu_empty', 'bilge_removed', 'garbage_removed',
       'garbage_remvl_reqstd', 'garbage_remvl_cmplsry', 'fw_supply',
       'cy_crew_signed_on', 'cy_crew_signed_off', 'cy_doctors_visit',
       'cy_mail_received_ref_no', 'cy_lub_oil_sample_landed',
       'cy_checkd_for_stowaways', 'cy_stowaways_on_board',
       'cy_dep_gm_mtr', 'cy_requisitions_received',
       'distance_to_next_pilot', 'tug_sailing_transit',
       'steaming_time_me_rsdl_vls', 'steaming_time_me_rsdl_hs',
       'steaming_time_me_rsdl_uls', 'steaming_time_me_dstlt_vls',
       'steaming_time_me_dstlt_uls', 'steaming_time_me_tnktnr_dstlt_vls',
       'steaming_time_me_mdo', 'steaming_time_aux_1',
       'steaming_time_aux_2', 'steaming_time_aux_3',
       'steaming_time_aux_4', 'steaming_time_aux_5',
       'steaming_time_sh_gen', 'steaming_time_tg', 'fuel_me_rsdl_vls',
       'fuel_me_rsdl_hs', 'fuel_me_rsdl_uls', 'fuel_me_dstlt_vls',
       'fuel_me_dstlt_uls', 'fuel_me_mdo', 'fuel_me_tnktnr_dstlt_vls',
       'fuel_aux_rsdl_vls', 'fuel_aux_rsdl_hs', 'fuel_aux_rsdl_uls',
       'fuel_aux_dstlt_vls', 'fuel_aux_dstlt_uls',
       'fuel_aux_tnktnr_dstlt_vls', 'fuel_aux_mdo',
       'fuel_boiler_rsdl_vls', 'fuel_boiler_rsdl_hs',
       'fuel_boiler_rsdl_uls', 'fuel_boiler_dstlt_vls',
       'fuel_boiler_dstlt_uls', 'fuel_boiler_tnktnr_dstlt_vls',
       'fuel_boiler_mdo', 'power_kw', 'steaming_load_kw_aux_1',
       'steaming_load_kw_aux_2', 'steaming_load_kw_aux_3',
       'steaming_load_kw_aux_4', 'steaming_load_kw_aux_5',
       'steaming_load_kw_sh_gen', 'steaming_load_kw_tg',
       'deck_last_change_user', 'engine_last_change_user',
       'deck_part_is_complete', 'engine_part_is_complete',
       'scavenge_pressure', 'seca_entry_time', 'seca_entry_lat',
       'seca_entry_long', 'seca_exit_time', 'seca_exit_lat',
       'seca_exit_long', 'rob_fresh_water', 'manvrng_miles_by_gps',
       'manvrng_miles_by_speed_log', 'tanktainer_transfd_quantity',
       'pilot_taken', 'date_time_start_transit',
       'date_time_start_transit_offset', 'date_time_end_transit',
       'date_time_end_transit_offset', 'ballast', 'tanktainer_number',
       'steaming_kwhr_total', 'cy_others', 'rob_fo_sludge',
       'rob_lo_sludge', 'rob_bilge', 'sludge_removed_fo',
       'sludge_removed_lo', 'sea_state', 'cy_lub_added_to_system_me_cc',
       'cy_lub_added_to_system_ae_cc', 'cy_lub_added_to_thrusters',
       'cy_me_lo_purifier_in_use', 'cy_ballast', 'cy_bending_moment',
       'cy_shearing_force', 'cy_tortion_moment',
       'cy_supdt_auditor_signed_on', 'cy_supdt_auditor_signed_off',
       'cy_cash_received', 'cy_lub_oil_received_me_cyl',
       'cy_lub_oil_received_me_cc', 'cy_lub_oil_received_ae_cc',
       'cy_me_under_piston_temp', 'cy_mail_received',
       'wind_direction_port_stbd', 'sea_direction_port_stbd',
       'time_pilot_onboard', 'grades_rob', 'so_2_co_2_ratio',
       'bunker_order', 'remarks', 'bdn_number', 'fuel_type',
       'carbon_factor', 'sulphur_content_pc', 'quantity', 'port_delivery',
       'product_quality', 'tanktainer_number_1', 'supplier', 'delivery',
       'volume_lt', 'density', 'viscosity', 'rob_dstlt_uls',
       'rob_dstlt_vls', 'rob_rsdl_mdo', 'rob_tnktnr_dstlt_vls',
       'rob_rsdl_vls', 'rob_rsdl_hs', 'rob_rsdl_uls', 'has_cargo',
       'steaming_time_me_hs', 'steaming_time_me_ls',
       'steaming_time_me_mgo', 'steaming_time_me_mgo_ls', 'fuel_me_hs',
       'fuel_me_ls', 'fuel_me_mgo', 'fuel_me_mgo_ls', 'fuel_aux_hs',
       'fuel_aux_ls', 'fuel_aux_mgo', 'fuel_aux_mgo_ls', 'fuel_boiler_hs',
       'fuel_boiler_ls', 'fuel_boiler_mgo', 'fuel_boiler_mgo_ls',
       'rob_fuel_hs_fo', 'rob_fuel_ls_fo', 'rob_fuel_mdo', 'rob_fuel_mgo',
       'rob_fuel_mgo_ls', 'rob_fuel_tanktainer_mgo', 'eca_miles',
       'eca_time', 'egcs_dry_waste_removed', 'egcs_running_time',
       'egcs_wet_slurry_removed', 'egcs_open_loop_running_time',
       'egcs_closed_loop_running_time', 'voyage_order', 'voyage_code',
       'eca', 'eu', 'sea_time', 'eta_country_code', 'port_country_code',
       'check_eta_code', 'check_port_code', 'status_temp_eu', 'fuel_hs',
       'fuel_ls', 'fuel_mdo', 'fuel_mgo', 'fuel_mgo_ls',
       'cargo_transport_work', 'teu_transport_work', 'eeoi_voyage_no',
       'cargo_total_old', 'draft', 'fo_per_24_hrs', 'sfoc',
       'cy_oil_gm_hr', 'scoc', 'voyage_name', 'total_fo', 'total_co_2',
       'eeoi', 'voy_condition', 'same_date', 'time_since_last_report',
       'wind_direction_360', 'true_wind_speed', 'true_wind_dir',
       'ref_power', 'ref_fuel', 'fuel_loss', 'relative_wind_speed',
       'relative_wind_direction', 'caa', 'rw', 'corrected_power',
       'draft_pow', 'draft_sp_pow', 'fo_nor', 'fo_model', 'sfoc_model',
       'sfoc_deviation', 'ref_power_corrected', 'ref_fo_corrected',
       'propulsive_eff', 'speed_performance', 'ref_speed', 'pi', 'me_con',
       'ae_con', 'bl_con', 't_con', 'hs', 'ls', 'mdo', 'mgo', 'mgo_ls',
       't_co_2', 'ae_t_steaming', 'ae_power', 'trim', 'distance_covered',
       'updated_date', 'hyd_slip_sog', 'hyd_slip_stw', 'fuel_rsdl_hs',
       'fuel_rsdl_vls', 'fuel_rsdl_uls', 'fuel_dstlt_vls',
       'fuel_dstlt_uls', 'fuel_tnktnr_dstlt_vls', 'rsdl_hs', 'rsdl_vls',
       'rsdl_uls', 'dstlt_vls', 'dstlt_uls', 'tnktnr_dstlt_vls',
       'created_at', 'updated_at', 'created_by_id', 'updated_by_id',
       'speed_by_log', 'speed_by_gps', 'fuel_m_e_lng', 'fuel_aux_lng',
       'fuel_boiler_lng', 'rob_rsdl_lng', 'sulphur_content_pc_main',
       'quantity_main', 'port_delivery_main', 'product_quality_main',
       'delivery_main', 'bdn_number_main', 'Date', 'Month', 'Year',
       'Month_name', 'date', 'Total_Calculated_HS', 'Total_Calculated_LS',
       'Total_Calculated_ULS', 'Total_Calculated_Fuel',
       'Total_Calculated_LNG', 'HS_CO2', 'LS_CO2', 'ULS_CO2', 'Total_CO2',
       'fuel_m_e_calculated', 'fuel_aux_calculated',
       'fuel_boiler_calculated', 'Total_fuel_calculated'], dtype=object)

In [16]:
MSC_noon_2024_sort_new["miles_by_gps"].isna().sum()

0

In [19]:
#for getting sum of distance in million nautical miles 

distance_2024 = MSC_noon_2024_sort_new.groupby(["imo"])[["miles_by_gps"]].sum().reset_index()
Total_distance_2024 = distance_2024[["miles_by_gps"]].sum().reset_index()
Total_distance_2024 =round( Total_distance_2024[0] / (10 ** 6), 2)
Total_distance_2024.reset_index()

   index     0
0      0  2.78

# 3.  Changing unit of Fuel

In [21]:

# Fuel calculations
fuel_hs_2024 = MSC_noon_2024_sort.groupby(["imo"])[["Total_Calculated_HS"]].sum().reset_index()
Total_fuel_hs_2024 = fuel_hs_2024[["Total_Calculated_HS"]].sum().reset_index()
Total_fuel_hs_2024 = Total_fuel_hs_2024[0] / (10 ** 6)
Total_fuel_hs_2024.reset_index()

fuel_ls_2024 = MSC_noon_2024_sort.groupby(["imo"])[["Total_Calculated_LS"]].sum().reset_index()
Total_fuel_ls_2024 = fuel_ls_2024[["Total_Calculated_LS"]].sum().reset_index()
Total_fuel_ls_2024 = Total_fuel_ls_2024[0] / (10 ** 6)
Total_fuel_ls_2024.reset_index()

fuel_uls_2024 = MSC_noon_2024_sort.groupby(["imo"])[["Total_Calculated_ULS"]].sum().reset_index()
Total_fuel_uls_2024 = fuel_uls_2024[["Total_Calculated_ULS"]].sum().reset_index()
Total_fuel_uls_2024 = Total_fuel_uls_2024[0] / (10 ** 6)
Total_fuel_uls_2024.reset_index()

fuel_lng_2024 = MSC_noon_2024_sort.groupby(["imo"])[["Total_Calculated_LNG"]].sum().reset_index()
Total_fuel_lng_2024 = fuel_lng_2024[["Total_Calculated_LNG"]].sum().reset_index()
Total_fuel_lng_2024 = Total_fuel_lng_2024[0] / (10 ** 6)
Total_fuel_lng_2024.reset_index()

fuel_me_2024 = MSC_noon_2024_sort.groupby(["imo"])[["fuel_m_e_calculated"]].sum().reset_index()
Total_fuel_me_2024 = fuel_me_2024[["fuel_m_e_calculated"]].sum().reset_index()
Total_fuel_me_2024 = Total_fuel_me_2024[0] / (10 ** 6)
Total_fuel_me_2024.reset_index()

fuel_aux_2024 = MSC_noon_2024_sort.groupby(["imo"])[["fuel_aux_calculated"]].sum().reset_index()
Total_fuel_aux_2024 = fuel_aux_2024[["fuel_aux_calculated"]].sum().reset_index()
Total_fuel_aux_2024 = Total_fuel_aux_2024[0] / (10 ** 6)
Total_fuel_aux_2024.reset_index()

fuel_boiler_2024 = MSC_noon_2024_sort.groupby(["imo"])[["fuel_boiler_calculated"]].sum().reset_index()
Total_fuel_boiler_2024 = fuel_boiler_2024[["fuel_boiler_calculated"]].sum().reset_index()
Total_fuel_boiler_2024 = Total_fuel_boiler_2024[0] / (10 ** 6)
Total_fuel_boiler_2024.reset_index()

fuel_2024 = MSC_noon_2024_sort.groupby(["imo"])[["Total_fuel_calculated"]].sum().reset_index()
Total_fuel_2024 = fuel_2024[["Total_fuel_calculated"]].sum().reset_index()
Total_fuel_2024 = Total_fuel_2024[0] / (10 ** 6)
Total_fuel_2024.reset_index()

# CO2 calculations
fuel_CO2_2024 = MSC_noon_2024_sort.groupby(["imo"])[["Total_CO2"]].sum().reset_index()
Total_CO2_2024 = fuel_CO2_2024[["Total_CO2"]].sum().reset_index()
Total_CO2_2024 =Total_CO2_2024[0] / (10 ** 6)
Total_CO2_2024.reset_index()

   index         0
0      0  1.682713

In [22]:
#Steaming Time


Steam_2024=MSC_noon_2024_sort.groupby(["imo"])[["total_steaming_time"]].sum().reset_index()
Total_Steam_2024=Steam_2024[["total_steaming_time"]].sum().reset_index()
Total_Steam_2024=Total_Steam_2024[0]/(24)
Total_Steam_2024.reset_index(drop=True, inplace=True)

In [23]:

Total_fuel_HS= {'Parameter':['Total HS Fuel'], '2024':Total_fuel_hs_2024[0].sum()}
Total_fuel_HS= pd.DataFrame(Total_fuel_HS)

Total_fuel_LS= {'Parameter':['Total LS Fuel'], '2024':Total_fuel_ls_2024[0].sum()}
Total_fuel_LS= pd.DataFrame(Total_fuel_LS)

Total_fuel_ULS= {'Parameter':['Total ULS Fuel'], '2024':Total_fuel_uls_2024[0].sum()}
Total_fuel_ULS= pd.DataFrame(Total_fuel_ULS)

Total_fuel_LNG= {'Parameter':['Total LNG Fuel'], '2024':Total_fuel_lng_2024[0].sum()}
Total_fuel_LNG= pd.DataFrame(Total_fuel_LNG)


Total_fuel= {'Parameter':['Total Fuel'], '2024':Total_fuel_2024[0].sum()}
Total_fuel= pd.DataFrame(Total_fuel)

Total_ME_fuel= {'Parameter':['Total ME Fuel'], '2024':Total_fuel_me_2024[0].sum()}
Total_ME_fuel= pd.DataFrame(Total_ME_fuel)

Total_AUX_fuel= {'Parameter':['Total AUX Fuel'], '2024':Total_fuel_aux_2024[0].sum()}
Total_AUX_fuel= pd.DataFrame(Total_AUX_fuel)

Total_BOI_fuel= {'Parameter':['Total BOILER Fuel'], '2024':Total_fuel_boiler_2024[0].sum()}
Total_BOI_fuel= pd.DataFrame(Total_BOI_fuel)

Total_CO2= {'Parameter':['Total CO2'], '2024':Total_CO2_2024[0].sum()}
Total_CO2= pd.DataFrame(Total_CO2)

In [25]:

#distance is calculating using above cell procedure(sum of vessel,total sum,divide it with 10^6 - Million nautical miles)
Total_Distance= {'Parameter':['Total Distance'], '2024':Total_distance_2024[0].sum()}
Total_Distance= pd.DataFrame(Total_Distance)

#cargo is calculating using above cell procedure(mean of vessel that is in voyage wise,total sum,multiple it with 10^6 - Million tonnes)
Total_Cargo= {'Parameter':['Total Cargo'],'2024':Total_cargo_2024[0].sum()}
Total_Cargo= pd.DataFrame(Total_Cargo)


Total_vsl= {'Parameter':['Number of Vessel'], '2024':MSC_noon_2024["imo"].nunique()}
Total_vsl= pd.DataFrame(Total_vsl)
Total_vsl['2024'] = Total_vsl['2024'].fillna(0).astype(int)

Total_voy= {'Parameter':['Total Voyages'], '2024':MSC_noon_2024["voyage"].nunique()}
Total_voy= pd.DataFrame(Total_voy)

Total_steaming_time= {'Parameter':['Total Steaming Days'], '2024':Total_Steam_2024[0].sum()}
Total_steaming_time= pd.DataFrame(Total_steaming_time)

In [26]:
#Total_Parameters=pd.concat([Total_vsl,Total_fuel_LS,Total_fuel_MGO,Total_fuel,Total_ME_fuel,Total_AUX_fuel,Total_CO2,Total_Cargo,Total_Distance,Total_fresh_pro,Total_fresh_con,Total_voy,Total_steaming_time,Total_ballast_voy_time,Total_Laden_voy_time,Avg_ballast_voy_time,Avg_Laden_voy_time])
Total_Parameters=pd.concat([Total_vsl,Total_fuel_HS,Total_fuel_LS,Total_fuel_ULS,Total_fuel_LNG,Total_fuel,Total_ME_fuel,Total_AUX_fuel,Total_BOI_fuel,Total_CO2,Total_voy,Total_Cargo,Total_Distance,Total_steaming_time])

Total_Parameters=Total_Parameters.reset_index()
Total_Parameters=Total_Parameters.drop(['index'], axis=1)

In [27]:

unit_parameters = ["", 'Kilotonne', 'Kilotonne', 'Kilotonne', 'Kilotonne','Kilotonne', 'Kilotonne', 'Kilotonne', 'Kilotonne', 'Kilotonne', '', 'Kilotonne', 'Nautical Miles', 'Day']
parameter_unit = pd.DataFrame(unit_parameters, columns=['Unit'])
Total_Parameter_1 = pd.concat([Total_Parameters, parameter_unit], axis=1)
Total_Parameter_1

              Parameter          2024            Unit
0      Number of Vessel    542.000000
1         Total HS Fuel      0.295226       Kilotonne
2         Total LS Fuel      0.169372       Kilotonne
3        Total ULS Fuel      0.071643       Kilotonne
4        Total LNG Fuel      0.000172       Kilotonne
5            Total Fuel      0.515973       Kilotonne
6         Total ME Fuel      0.383729       Kilotonne
7        Total AUX Fuel      0.111866       Kilotonne
8     Total BOILER Fuel      0.020379       Kilotonne
9             Total CO2      1.682713       Kilotonne
10        Total Voyages   1305.000000
11          Total Cargo     46.790000       Kilotonne
12       Total Distance      2.780000  Nautical Miles
13  Total Steaming Days  11113.704569             Day