In [2]:
import numpy as np
import pandas as pd
import warnings
import matplotlib.pyplot as plt
import requests
import io

warnings.filterwarnings("ignore")

In [3]:
MSC_noon_2022=pd.read_csv("NOONDATA (2) 1.csv")

In [4]:
pd.set_option('display.max_columns', None)  
MSC_noon_2022

,idvessel,GID,VSL,IMO_No,VOY,Corrected_Date,REPORT_DATE_TIME,REPORT_DATE_TIME_Offset,Report_Type,Status,LAT,LONG_,LATITUDE,LONGITUDE,M_E_FOC,CARGO_TOTAL,Has_Cargo,TOTAL_STEAMING_TIME,M_E_Fuel_Only_Steaming_Time,MILES_BY_GPS,OIL_CYL,SOW,SOG,RPM,SLIP,WIND_DIRECTION,WIND_SPEED,DRAFT_AFT,DRAFT_FWD,DISPLACEMENT,COURSE_AT_SEA,WAVE_HEIGHT,SEA_DIRECTION,CARGO_TOTAL_TEU,AMBIENT_TEMP,SW_TEMP,MILES_BY_SPEED_LOG,ETA_PORT_CODE,ETA_DATE_TIME,ETA_DATE_TIME_Offset,ETA_PORT,TIME_CHANGE,TIME_SEA,TEMP_MIN,TEMP_MAX,REQUESTED_SPEED,REM_DIST_TO_PILOT,REM_TIME_TO_PILOT,TOTAL_UNPLND_STPGE_TECH,TOTAL_UNPLND_STPGE_OPE_WX,REEFERS_POSITIVE_PLUGGED,REEFERS_NEGATIVE_PLUGGED,ME_TOTAL_REVS_COUNTER,PORT_CODE,PORT,AUX_BLOWERS_ON,HOLD_VENTILATION_ON,SINCE_DATE_TIME,SINCE_DATE_TIME_Offset,TIME_HRS_ANCHOR,TIME_HRS_DRIFT,REASON,TYPE_OF_DELAY,ETB_DATE_TIME,ETB_DATE_TIME_Offset,PILOT_DATE_TIME,PILOT_DATE_TIME_Offset,TIME_MANOEUVRING,TUG_ARR,TUG_SHIFT,ETD_DATE_TIME,ETD_DATE_TIME_Offset,SHIFT_BERTH_HOURS,CARGO_LOAD,CARGO_DISCH,TEU_FULL,TEU_EMPTY,BILGE_REMOVED,GARBAGE_REMOVED,GARBAGE_REMVL_REQSTD,GARBAGE_REMVL_CMPLSRY,FW_SUPPLY,CY_CREW_SIGNED_ON,CY_CREW_SIGNED_OFF,CY_DOCTORS_VISIT,CY_MAIL_RECEIVED_Ref_NO,CY_LUB_OIL_SAMPLE_LANDED,CY_CHECKD_FOR_STOWAWAYS,CY_STOWAWAYS_ON_BOARD,CY_DEP_GM_Mtr,CY_REQUISITIONS_RECEIVED,DISTANCE_TO_NEXT_PILOT,TUG_SAILING_TRANSIT,STEAMING_TIME_M_E_Rsdl_VLS,STEAMING_TIME_M_E_Rsdl_HS,STEAMING_TIME_M_E_Rsdl_ULS,STEAMING_TIME_M_E_Dstlt_VLS,STEAMING_TIME_M_E_Dstlt_ULS,STEAMING_TIME_M_E_Tnktnr_Dstlt_VLS,STEAMING_TIME_M_E_HS,STEAMING_TIME_M_E_LS,STEAMING_TIME_M_E_MDO,STEAMING_TIME_M_E_MGO,STEAMING_TIME_M_E_MGO_LS,STEAMING_TIME_AUX_1,STEAMING_TIME_AUX_2,STEAMING_TIME_AUX_3,STEAMING_TIME_AUX_4,STEAMING_TIME_AUX_5,STEAMING_TIME_SH_GEN,STEAMING_TIME_TG,POWER_kW,STEAMING_LOAD_KW_AUX_1,STEAMING_LOAD_KW_AUX_2,STEAMING_LOAD_KW_AUX_3,STEAMING_LOAD_KW_AUX_4,STEAMING_LOAD_KW_AUX_5,STEAMING_LOAD_KW_SH_GEN,STEAMING_LOAD_KW_TG,FUEL_M_E_Rsdl_VLS,FUEL_M_E_Rsdl_HS,FUEL_M_E_Rsdl_ULS,FUEL_M_E_Dstlt_VLS,FUEL_M_E_Dstlt_ULS,FUEL_M_E_Tnktnr_Dstlt_VLS,FUEL_M_E_HS,FUEL_M_E_LS,FUEL_M_E_MDO,FUEL_M_E_MGO,FUEL_M_E_MGO_LS,FUEL_Aux_Rsdl_VLS,FUEL_Aux_Rsdl_HS,FUEL_Aux_Rsdl_ULS,FUEL_Aux_Dstlt_VLS,FUEL_Aux_Dstlt_ULS,FUEL_Aux_Tnktnr_Dstlt_VLS,FUEL_AUX_HS,FUEL_AUX_LS,FUEL_AUX_MDO,FUEL_AUX_MGO,FUEL_AUX_MGO_LS,FUEL_Boiler_Rsdl_VLS,FUEL_Boiler_Rsdl_HS,FUEL_Boiler_Rsdl_ULS,FUEL_Boiler_Dstlt_VLS,FUEL_Boiler_Dstlt_ULS,FUEL_Boiler_Tnktnr_Dstlt_VLS,FUEL_BOILER_HS,FUEL_BOILER_LS,FUEL_BOILER_MDO,FUEL_BOILER_MGO,FUEL_BOILER_MGO_LS,DECK_LAST_CHANGE_USER,ENGINE_LAST_CHANGE_USER,DECK_PART_IS_COMPLETE,ENGINE_PART_IS_COMPLETE,SCAVENGE_PRESSURE,SECA_ENTRY_TIME,SECA_ENTRY_LAT,SECA_ENTRY_LONG,SECA_EXIT_TIME,SECA_EXIT_LAT,SECA_EXIT_LONG,ROB_FRESH_WATER,MANVRNG_MILES_BY_GPS,MANVRNG_MILES_BY_SPEED_LOG,TANKTAINER_TRANSFD_QUANTITY,PILOT_TAKEN,DATE_TIME_START_TRANSIT,DATE_TIME_START_TRANSIT_Offset,DATE_TIME_END_TRANSIT,DATE_TIME_END_TRANSIT_Offset,BALLAST,TANKTAINER_NUMBER,STEAMING_KWHR_TOTAL,CY_OTHERS,ROB_FO_SLUDGE,ROB_LO_SLUDGE,ROB_BILGE,SLUDGE_REMOVED_FO,SLUDGE_REMOVED_LO,SEA_STATE,CY_LUB_ADDED_TO_SYSTEM_MECC,CY_LUB_ADDED_TO_SYSTEM_AECC,CY_LUB_ADDED_TO_THRUSTERS,CY_ME_LO_PURIFIER_IN_USE,CY_BALLAST,CY_BENDING_MOMENT,CY_SHEARING_FORCE,CY_TORTION_MOMENT,CY_SUPDT_AUDITOR_SIGNED_ON,CY_SUPDT_AUDITOR_SIGNED_OFF,CY_CASH_RECEIVED,CY_LUB_OIL_RECEIVED_MECYL,CY_LUB_OIL_RECEIVED_MECC,CY_LUB_OIL_RECEIVED_AECC,CY_M_E_UNDER_PISTON_TEMP,CY_MAIL_RECEIVED,WIND_DIRECTION_PORT_STBD,SEA_DIRECTION_PORT_STBD,TIME_PILOT_ONBOARD,GRADES_ROB,SO2_CO2_RATIO,Bunker_Order,Remarks,Fuel_Type,Carbon_Factor,Sulphur_Content_PC,Quantity,Port_Delivery,Product_Quality,Tanktainer_Number_1,Supplier,Delivery,Vol_Lt,Den,Vis,ROB_Dstlt_ULS,ROB_Dstlt_VLS,ROB_Rsdl_MDO,ROB_Tnktnr_Dstlt_VLS,ROB_Rsdl_VLS,ROB_Rsdl_HS,ROB_Rsdl_ULS,ROB_Fuel_HSFO,ROB_Fuel_LSFO,ROB_Fuel_MDO,ROB_Fuel_MGO,ROB_Fuel_MGO_LS,ROB_Fuel_Tanktainer_MGO,ECA_MILES,ECA_TIME,EGCS_DRY_WASTE_REMOVED,EGCS_RUNNING_TIME,EGCS_WET_SLURRY_REMOVED,EGCS_OPEN_LOOP_RUNNING_TIME,EGCS_CLOSED_LOOP_RUNNING_TIME,Voyage_Order,Voyage_Code,ECA,EU,Sea_Time,ETA_Country_Code,Port_Country_Code,check_ETA_code,check_Port_code,Status_TEMP_EU,FUEL_HS,FUEL_LS,FUEL_MDO,FUEL_MGO,FUEL_MGO_LS,Cargo_Transport_Work,TEU_Transport_Work,EEOI_Voyage_no,CARGO_TOTAL_Old,DRAFT,FO_per_24Hrs,SFOC,CY_OIL_gm_hr,SCOC,Voyage_Name,TOTAL_FO,TOTAL_CO2,EEOI,voyCondition,samedate,timesincelastreport,BDN,Wind_direction_360,True_wind_speed,True_wind_dir,ref_power,ref_fuel,fuel_loss,Relative_wind_speed,Relative_wind_direction,CAA,RW,Corrected_Power,draft_pow,draft_sp_pow,fo_nor,fo_model,sfoc_model,sfoc_deviation,ref_power_corrected,ref_FO_corrected,Propulsive_eff,speed_performance,Ref_speed,P_I,MEcon,AEcon,BLcon,Tcon,HS,LS,MDO,MGO,MGOLS,TCO2,AETsteaming,AEPOWER,TRIM,DISTANCECOVERED,updated_date,hyd_slip_sog,hyd_slip_stw,FUEL_Rsdl_HS,FUEL_Rsdl_VLS,FUEL_Rsdl_ULS,FUEL_Dstlt_VLS,FUEL_Dstlt_ULS,FUEL_Tnktnr_Dstlt_VLS,Rsdl_HS,Rsdl_VLS,Rsdl_ULS,Dstlt_VLS,Dstlt_ULS,Tnktnr_Dstlt_VLS
0,JOLL,000009ba-bd9c-4628-8233-b2ea761fec40,JOLLY EXPRESS,9180190,NaN,2022-01-24 00:00:00,2022-01-23 18:17:00,UTC +01:00,SND,NaN,NaN,NaN,NaN,NaN,NaN,3419.7,False,NaN,NaN,0.0,NaN,0.0000,0.0000,0.0,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSE,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,228.0,122.0,NaN,NaN,FALSE,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.00,0,0.0,0.00,0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0,0.0,0.0,0,0.0,0.00,NaN,NaN,FALSE,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,391.0,TNTUN-ITGIT,N,Y,0.0,IT,TN,NaN,NaN,0,0.0,0.00,0,0.0,0.00,0.0,0.0,391.0,0,0.00,0.0000,0.000,0.0,0.00000,0,0.00,0.0000,0,Laden,0,NaN,NO,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.0,0.00,0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,2022-05-12 09:53:25,NaN,NaN,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00,0.0
1,ROBE,00000a5b-7334-43a8-a022-51fd00f74518,MSC ROBERTA,9038907,XA230A,2022-10-23 00:00:00,2022-10-23 12:00:00,UTC +08:00,PORT,IN PORT,2209N,11410E,22.150000,114.166667,0.00,0.0,False,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0,0.0,0.0,0.0,6.0,5.5,30700.0,0.0,0.00,0.00,0.0,18.0,15.0,NaN,CNZOS,2022-08-31 11:00:00,UTC +08:00,NaN,NaN,24.0,70.0,70.0,17.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,CNZOS,ZHOUSHAN,False,False,NaN,NaN,NaN,NaN,AWAITING FOR DRYDOCK,NaN,2022-09-17 20:00:00,UTC +08:00,NaN,NaN,NaN,NaN,NaN,2022-12-15 12:00:00,UTC +08:00,0.0,NaN,NaN,0.0,0.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.00,0,0.0,0.00,0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0,0.0,0.0,0,0.0,0.00,MASTER,CH.ENG,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.0,0.0,NaN,NaN,False,NaN,NaN,NaN,NaN,0.0,0,0.0,NaN,NaN,NaN,0.00,NaN,NaN,NaN,0.0,0.0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,0.0,672.0,HKHKG-CNZOS,N,N,0.0,CN,HK,NaN,NaN,0,0.0,0.00,0,0.0,0.00,0.0,0.0,672.0,0,5.75,0.0000,0.000,0.0,0.00000,0,0.00,0.0000,0,Ballast,0,NaN,NO,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.0,0.00,0,0.0,0.00,0.00,0.0,0.0,0.5,0.0,2023-01-11 13:02:50,NaN,NaN,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00,0.0
2,NDRL,00003e1f-bd7b-4629-8307-8b9d9c58fbce,MSC NADRIELY,9149328,NaN,2022-12-10 00:00:00,2022-12-09 13:10:00,UTC -05:00,REFL,NaN,NaN,NaN,NaN,NaN,NaN,33161.0,False,NaN,NaN,0.0,NaN,0.0000,0.0000,0.0,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.0,1582.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0.0,0.0,0.00,0,0.0,0.00,0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0,0.0,0.0,0,0.0,0.00,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0.0,NaN,NaN,RESIDUAL VLS,NaN,0.47,329.400,CAMTR,RESIDUAL VLS,NaN,SHELL TRADING,874007,358710.0,918.5000,48.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,749.0,DOCAU-ITNAP,N,Y,0.0,IT,DO,NaN,NaN,0,0.0,0.00,0,0.0,0.00,0.0,0.0,749.0,0,0.00,0.0000,0.000,0.0,0.00000,0,0.00,0.0000,0,Laden,0,NaN,NO,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.0,0.00,0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,2023-02-14 12:04:12,NaN,NaN,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00,0.0
3,SHNV,00005c99-42d2-41bf-ac79-9030930438fd,MSC SHANVI,9392561,HU206R,2022-02-12 00:00:00,2022-02-12 05:36:00,UTC +08:00,EOSP,AT SEA,0114N,10327E,1.233333,103.450000,0.91,8506.0,True,0.9,0.9,12.0,3.0,11.1111,13.3333,55.0,-6.7,45.0,4.0,9.4,7.4,36175.0,345.0,0.67,164.93,1175.0,27.0,26.0,10.0,NaN,44604.27083,UTC +08:00,NaN,NaN,0.9,175.0,231.0,10.0,NaN,NaN,0.0,0.0,0.0,0.0,2970.0,MYTPP,TANJUNG PELEPAS,TRUE,FALSE,NaN,NaN,NaN,NaN,Port Congestion,NaN,44605.45833,UTC +08:00,NaN,NaN,NaN,NaN,NaN,44604.35417,UTC +08:00,NaN,NaN,NaN,1175.0,0.0,NaN,NaN,FALSE,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.9,0.0,0.0,0.0,0.0,0.0,0.0,0.9,0.0,0.0,0.0,0.9,0.0,0.9,0.9,0.0,0.0,0.0,5774,333.0,0.0,497.0,503.0,0.0,0.0,0.0,0.91,0.0,0.0,0.0,0.00,0,0.0,0.91,0,0.0,0.00,0.50,0.0,0.0,0.0,0.0,0.0,0.0,0.50,0,0.0,0.0,0.0,0.0,0.0,0.0,0.16,0,0.0,0.0,0,0.0,0.16,2O MARK LESTER ENCARNACION,4E RANDY BORBOR,TRUE,TRUE,0.05,NaN,NaN,NaN,NaN,NaN,NaN,186.0,0.0,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,9615.0,0,0.0,NaN,NaN,NaN,38.27,NaN,NaN,3.0,0.0,0.0,0.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSE,S,S,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,81.23,0.0,0.0,0.0,60.91,0.0,0.0,0.0,60.91,0.0,0.0,81.23,0.0,0.0,0.0,NaN,0.0,NaN,0.0,0.0,249.0,SGSIN-MYTPP,N,N,0.9,MY,SG,NaN,NaN,0,0.0,1.41,0,0.0,0.16,102072.0,14100.0,249.0,0,8.40,24.2667,175.115,3000.0,0.51957,0,1.57,4.9037,0,Laden,0,NaN,NO,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.91,0.50,0.16,1.57,0.0,1.41,0,0.0,0.16,4.90,2.7,1333.0,2.0,12.0,2022-05-12 09:53:25,NaN,NaN,0.0,1.41,0.0,0.0,0.16,0.0,0.0,1.41,0.0,0.0,0.16,0.0
4,UNIT,000067b9-a4d1-4835-a687-02d5fec73245,MSC UNITED VIII,9302619,NaN,2022-09-18 00:00:00,2022-09-17 18:59:59,UTC +07:00,SND,NaN,NaN,NaN,NaN,NaN,NaN,0.0,False,NaN,NaN,0.0,NaN,0.0000,0.0000,0.0,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0.0,0.0,0.00,0,0.0,0.00,0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0,0.0,0.0,0,0.0,0.00,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,N,0.0,NaN,NaN,NaN,NaN,0,0.0,0.00,0,0.0,0.00,0.0,0.0,NaN,0,0.00,0.0000,0.000,0.0,0.00000,0,0.00,0.0000,0,Ballast,0,NaN,NO,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.0,0.00,0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,2023-02-14 14:27:47,NaN,NaN,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
648477,MILA,ffff7672-b97a-44c4-84dc-ead8a7ad33c8,MSC MILA 3,9062996,NaN,2022-01-14 00:00:00,2022-01-14 09:45:00,UTC +02:00,REFL,NaN,NaN,NaN,NaN,NaN,NaN,0.0,False,NaN,NaN,0.0,NaN,0.0000,0.0000,0.0,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSE,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,FALSE,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.00,0,0.0,0.00,0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0,0.0,0.0,0,0.0,0.00,NaN,NaN,FALSE,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,0.0,11274137,NaN,DISTILLATE ULS,NaN,0.03,120.029,ZADUR,DISTILLATE ULS,0,SHELL,RAI 527,142654.0,0.8447,3.4,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,N,0.0,NaN,NaN,NaN,NaN,0,0.0,0.00,0,0.0,0.00,0.0,0.0,NaN,0,0.00,0.0000,0.000,0.0,0.00000,0,0.00,0.0000,0,Ballast,0,NaN,NO,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.0,0.00,0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,2022-05-12 09:53:25,NaN,NaN,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00,0.0
648478,LARA,ffff7a6e-866a-43f6-a4f3-081e91769b0b,MSC LARA,9064748,AC241R,2022-11-24 00:00:00,2022-11-24 12:00:00,UTC +03:00,PORT,IN PORT,4050N,02913E,40.833333,29.216667,0.00,0.0,False,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0,0.0,0.0,0.0,7.0,3.0,17606.2,0.0,0.00,0.00,0.0,20.0,14.0,NaN,TRTUZ,2022-10-10 10:00:00,UTC +03:00,NaN,NaN,24.0,70.0,70.0,13.5,NaN,NaN,0.0,0.0,0.0,0.0,0.0,TRTUZ,TUZLA,False,False,NaN,NaN,NaN,NaN,AWAITING FOR PILOT,NaN,2022-10-17 15:00:00,UTC +03:00,NaN,NaN,NaN,NaN,NaN,2022-12-15 12:00:00,UTC +03:00,0.0,NaN,NaN,0.0,0.0,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.00,0,0.0,0.00,0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0,0.0,0.0,0,0.0,0.00,MASTER,CHENG,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,62.0,0.0,NaN,NaN,False,NaN,NaN,NaN,NaN,0.0,0,0.0,SHORE CONNECTION AT NOON R 2630.5 S 3161.7 T 3...,NaN,NaN,4.00,NaN,NaN,NaN,0.0,0.0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,0.0,828.0,TRTEK-TRTUZ,N,N,0.0,TR,TR,NaN,NaN,0,0.0,0.00,0,0.0,0.00,0.0,0.0,828.0,0,5.00,0.0000,0.000,0.0,0.00000,0,0.00,0.0000,0,Ballast,0,NaN,NO,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.0,0.00,0,0.0,0.00,0.00,0.0,0.0,4.0,0.0,2023-03-15 16:47:03,NaN,NaN,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00,0.0
648479,ABY,ffffb067-939d-4695-9f0f-6c0ef5d857c2,MSC ABY,9166778,NaN,2022-04-03 00:00:00,2022-04-02 14:11:00,UTC +02:00,SND,NaN,NaN,NaN,NaN,NaN,NaN,69380.0,False,NaN,NaN,0.0,NaN,0.0000,0.0000,0.0,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSE,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5463.0,0.0,NaN,NaN,FALSE,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.00,0,0.0,0.00,0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0,0.0,0.0,0,0.0,0.00,NaN,NaN,FALSE,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FALSE,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,149.0,ITSPE-ITGIT,N,Y,0.0,IT,IT,NaN,NaN,0,0.0,0.00,0,0.0,0.00,0.0,0.0,149.0,0,0.00,0.0000,0.000,0.0,0.00000,0,0.00,0.0000,0,Laden,0,NaN,NO,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.0,0.00,0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,2022-05-20 09:26:58,NaN,NaN,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00,0.0
648480,ZLAT,ffffd9de-8941-40b3-80ba-7a0285098f5a,MSC ZLATA R.,9227314,XA236A,2022-09-19 00:00:00,2022-09-19 12:00:00,UTC +03:00,DLY A,DRIFTING,4045N,02906E,40.750000,29.100000,0.65,0.0,False,1.0,1.0,5.0,10.0,0.0000,0.0000,0.0,0.0,0.0,0.0,9.3,4.2,33380.0,0.0,0.00,0.00,0.0,28.0,24.0,NaN,TRTUZ,2022-09-19 02:00:00,UTC +03:00,NaN,NaN,10.5,80.0,92.0,12.0,NaN,NaN,0.0,0.0,0.0,0.0,76046109.0,TRTUZ,TUZLA,True,False,NaN,NaN,0.0,9.5,Awaiting permission for Anchoring in Tuzla,Drifting,2022-09-22 08:00:00,UTC +03:00,NaN,NaN,1.0,NaN,NaN,2022-09-26 08:00:00,UTC +03:00,NaN,NaN,NaN,0.0,0.0,NaN,NaN,False,False,NaN,0,0,No,0,0,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,10.5,0.0,0.0,0.0,1852,0.0,0.0,0.0,1250.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.65,0,0.0,0.00,0,0.0,0.65,3.68,0.0,0.0,0.0,0.0,0.0,0.0,3.68,0,0.0,0.0,1.5,0.0,0.0,0.0,0.00,0,0.0,1.5,0,0.0,0.00,Master,CE,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,147.0,5.0,5.0,NaN,False,NaN,NaN,NaN,NaN,7079.0,0,12500.0,NaN,NaN,NaN,30.40,NaN,NaN,0.0,0.0,0.0,0.0,1,NaN,NaN,NaN,NaN,0,0,0.0,0.0,0.0,0.0,NaN,False,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,208.19,0.0,0.0,0.0,3067.16,0.0,0.0,0.0,3067.16,0.0,0.0,208.19,0.0,NaN,NaN,NaN,0.0,NaN,0.0,0.0,678.0,TRTEK-TRYAL,N,N,1.0,TR,TR,NaN,NaN,0,0.0,5.18,0,0.0,0.65,0.0,0.0,678.0,0,6.75,15.6000,350.972,9000.0,4.85961,0,5.83,18.2144,0,Ballast,0,NaN,NO,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.65,3.68,1.50,5.83,0.0,5.18,0,0.0,0.65,18.21,10.5,1250.0,5.1,5.0,2023-02-14 14:27:47,NaN,NaN,0.0,5.18,0.0,0.0,0.65,0.0,0.0,5.18,0.0,0.0,0.65,0.0

In [33]:
MSC_noon_2022['Date'] = pd.to_datetime(MSC_noon_2022['Corrected_Date']).apply(lambda x:x.strftime("%d"))
MSC_noon_2022['Month'] = pd.to_datetime(MSC_noon_2022['Corrected_Date']).apply(lambda x:x.strftime("%m"))
MSC_noon_2022['Year'] = pd.to_datetime(MSC_noon_2022['Corrected_Date']).apply(lambda x:x.strftime("%Y"))
MSC_noon_2022['Month_name'] = pd.to_datetime(MSC_noon_2022['Corrected_Date']).apply(lambda x:x.strftime("%B"))
MSC_noon_2022['date'] = pd.to_datetime(MSC_noon_2022["Corrected_Date"]).dt.date
MSC_noon_2022.dropna(subset=['IMO_No'])
MSC_noon_2022_sort=MSC_noon_2022.sort_values(by="Corrected_Date")
#Total HS,LS,MGO and Total Fuel
MSC_noon_2022_sort['Total_Calculated_HS']= MSC_noon_2022_sort[['FUEL_M_E_Rsdl_HS' , 'FUEL_Aux_Rsdl_HS' , 'FUEL_Boiler_Rsdl_HS']].sum(axis=1)
MSC_noon_2022_sort['Total_Calculated_LS'] = MSC_noon_2022_sort[['FUEL_M_E_Rsdl_VLS' , 'FUEL_M_E_Dstlt_VLS' , 'FUEL_M_E_Tnktnr_Dstlt_VLS' ,'FUEL_Aux_Rsdl_VLS' ,  'FUEL_Aux_Dstlt_VLS' , 'FUEL_Aux_Tnktnr_Dstlt_VLS','FUEL_Boiler_Rsdl_VLS','FUEL_Boiler_Dstlt_VLS','FUEL_Boiler_Tnktnr_Dstlt_VLS']].fillna(0).sum(axis=1)
MSC_noon_2022_sort['Total_Calculated_ULS'] = MSC_noon_2022_sort[['FUEL_M_E_Rsdl_ULS' , 'FUEL_Aux_Rsdl_ULS' , 'FUEL_Boiler_Rsdl_ULS' ,'FUEL_M_E_Dstlt_ULS' ,'FUEL_Aux_Dstlt_ULS' , 'FUEL_Boiler_Dstlt_ULS']].fillna(0).sum(axis=1)
MSC_noon_2022_sort['Total_Calculated_Fuel'] = MSC_noon_2022_sort[['Total_Calculated_HS' ,'Total_Calculated_LS' , 'Total_Calculated_ULS']].fillna(0).sum(axis=1)

#HS_CO2,LSCO2,MGO_CO2 and Total CO2
MSC_noon_2022_sort['HS_CO2'] = 3.114 * MSC_noon_2022_sort["Total_Calculated_HS"]
MSC_noon_2022_sort['LS_CO2'] = 3.151 * MSC_noon_2022_sort["Total_Calculated_LS"]
MSC_noon_2022_sort['ULS_CO2'] = 3.206 * MSC_noon_2022_sort["Total_Calculated_ULS"]
MSC_noon_2022_sort['Total_CO2'] = MSC_noon_2022_sort[['HS_CO2' ,'LS_CO2' ,'ULS_CO2']].fillna(0).sum(axis=1)

MSC_noon_2022_sort["fuel_m_e_calculated"]=MSC_noon_2022_sort[["FUEL_M_E_Rsdl_HS","FUEL_M_E_Rsdl_VLS","FUEL_M_E_Dstlt_VLS",'FUEL_M_E_Rsdl_ULS','FUEL_M_E_Tnktnr_Dstlt_VLS']].fillna(0).sum(axis=1)
MSC_noon_2022_sort["fuel_aux_calculated"]=MSC_noon_2022_sort[["FUEL_Aux_Rsdl_VLS","FUEL_Aux_Rsdl_HS","FUEL_Aux_Dstlt_VLS",'FUEL_Aux_Rsdl_ULS','FUEL_Aux_Tnktnr_Dstlt_VLS']].fillna(0).sum(axis=1)
MSC_noon_2022_sort["fuel_boiler_calculated"]=MSC_noon_2022_sort[["FUEL_Boiler_Rsdl_HS","FUEL_Boiler_Dstlt_VLS","FUEL_Boiler_Rsdl_VLS",'FUEL_Boiler_Rsdl_ULS','FUEL_Boiler_Tnktnr_Dstlt_VLS']].fillna(0).sum(axis=1)
MSC_noon_2022_sort["Total_fuel_calculated"]=MSC_noon_2022_sort[["fuel_m_e_calculated","fuel_aux_calculated","fuel_boiler_calculated"]].fillna(0).sum(axis=1)

# Yearly Total of each Parameters

# 1. CARGO TOTAL

In [34]:
MSC_noon_2022_sort["VOY"].isna().sum()

365353

In [35]:
MSC_noon_2022_sort["VOY"].unique()

array(['UZ148N', 'HX141R', nan, ..., 'AC251R', 'HN252A', 'SB252R'],
      dtype=object)

In [36]:

MSC_noon_2022_str = MSC_noon_2022_sort[MSC_noon_2022_sort['VOY'].apply(lambda x: isinstance(x, str))]
MSC_noon_2022_str['VOY'] = MSC_noon_2022_str['VOY'].str.lstrip('0').str.rstrip('.0')

# Filter by Float Type and Convert to String
MSC_noon_2022_float = MSC_noon_2022_sort[MSC_noon_2022_sort['VOY'].apply(lambda x: isinstance(x, float))]
MSC_noon_2022_float['VOY'] = pd.to_numeric(MSC_noon_2022_float['VOY'], errors='coerce').fillna(0).astype(int).astype(str)

# Filter by Integer Type and Convert to String
MSC_noon_2022_int = MSC_noon_2022_sort[MSC_noon_2022_sort['VOY'].apply(lambda x: isinstance(x, int))]
MSC_noon_2022_int['VOY'] = MSC_noon_2022_int['VOY'].astype(int).astype(str)

# Concatenate DataFrames and Sort
MSC_noon_2022_sort_new = pd.concat([MSC_noon_2022_str, MSC_noon_2022_float, MSC_noon_2022_int])
MSC_noon_2022_sort_new = MSC_noon_2022_sort_new.sort_values(by=["Corrected_Date"])

In [37]:
MSC_noon_2022_sort_new["VOY"].isna().sum()

0

In [38]:
MSC_noon_2022_sort_new["CARGO_TOTAL"].isna().sum()

0

In [39]:
cargo_vessel_mean_2022 = MSC_noon_2022_sort_new.groupby(["IMO_No", "VOY"])[["CARGO_TOTAL"]].mean().reset_index()
Total_cargo_2022 = cargo_vessel_mean_2022[["CARGO_TOTAL"]].sum().reset_index()
Total_cargo_2022 = round(Total_cargo_2022[0] / (10 ** 6), 2)
Total_cargo_2022.reset_index()

   index      0
0      0  281.3

# 2.  MILES BY GPS

In [40]:
MSC_noon_2022_sort_new.columns.values

array(['idvessel', 'GID', 'VSL', 'IMO_No', 'VOY', 'Corrected_Date',
       'REPORT_DATE_TIME', 'REPORT_DATE_TIME_Offset', 'Report_Type',
       'Status', 'LAT', 'LONG_', 'LATITUDE', 'LONGITUDE', 'M_E_FOC',
       'CARGO_TOTAL', 'Has_Cargo', 'TOTAL_STEAMING_TIME',
       'M_E_Fuel_Only_Steaming_Time', 'MILES_BY_GPS', 'OIL_CYL', 'SOW',
       'SOG', 'RPM', 'SLIP', 'WIND_DIRECTION', 'WIND_SPEED', 'DRAFT_AFT',
       'DRAFT_FWD', 'DISPLACEMENT', 'COURSE_AT_SEA', 'WAVE_HEIGHT',
       'SEA_DIRECTION', 'CARGO_TOTAL_TEU', 'AMBIENT_TEMP', 'SW_TEMP',
       'MILES_BY_SPEED_LOG', 'ETA_PORT_CODE', 'ETA_DATE_TIME',
       'ETA_DATE_TIME_Offset', 'ETA_PORT', 'TIME_CHANGE', 'TIME_SEA',
       'TEMP_MIN', 'TEMP_MAX', 'REQUESTED_SPEED', 'REM_DIST_TO_PILOT',
       'REM_TIME_TO_PILOT', 'TOTAL_UNPLND_STPGE_TECH',
       'TOTAL_UNPLND_STPGE_OPE_WX', 'REEFERS_POSITIVE_PLUGGED',
       'REEFERS_NEGATIVE_PLUGGED', 'ME_TOTAL_REVS_COUNTER', 'PORT_CODE',
       'PORT', 'AUX_BLOWERS_ON', 'HOLD_VENTILATION_ON', 'SINCE_DATE_TIME',
       'SINCE_DATE_TIME_Offset', 'TIME_HRS_ANCHOR', 'TIME_HRS_DRIFT',
       'REASON', 'TYPE_OF_DELAY', 'ETB_DATE_TIME', 'ETB_DATE_TIME_Offset',
       'PILOT_DATE_TIME', 'PILOT_DATE_TIME_Offset', 'TIME_MANOEUVRING',
       'TUG_ARR', 'TUG_SHIFT', 'ETD_DATE_TIME', 'ETD_DATE_TIME_Offset',
       'SHIFT_BERTH_HOURS', 'CARGO_LOAD', 'CARGO_DISCH', 'TEU_FULL',
       'TEU_EMPTY', 'BILGE_REMOVED', 'GARBAGE_REMOVED',
       'GARBAGE_REMVL_REQSTD', 'GARBAGE_REMVL_CMPLSRY', 'FW_SUPPLY',
       'CY_CREW_SIGNED_ON', 'CY_CREW_SIGNED_OFF', 'CY_DOCTORS_VISIT',
       'CY_MAIL_RECEIVED_Ref_NO', 'CY_LUB_OIL_SAMPLE_LANDED',
       'CY_CHECKD_FOR_STOWAWAYS', 'CY_STOWAWAYS_ON_BOARD',
       'CY_DEP_GM_Mtr', 'CY_REQUISITIONS_RECEIVED',
       'DISTANCE_TO_NEXT_PILOT', 'TUG_SAILING_TRANSIT',
       'STEAMING_TIME_M_E_Rsdl_VLS', 'STEAMING_TIME_M_E_Rsdl_HS',
       'STEAMING_TIME_M_E_Rsdl_ULS', 'STEAMING_TIME_M_E_Dstlt_VLS',
       'STEAMING_TIME_M_E_Dstlt_ULS',
       'STEAMING_TIME_M_E_Tnktnr_Dstlt_VLS', 'STEAMING_TIME_M_E_HS',
       'STEAMING_TIME_M_E_LS', 'STEAMING_TIME_M_E_MDO',
       'STEAMING_TIME_M_E_MGO', 'STEAMING_TIME_M_E_MGO_LS',
       'STEAMING_TIME_AUX_1', 'STEAMING_TIME_AUX_2',
       'STEAMING_TIME_AUX_3', 'STEAMING_TIME_AUX_4',
       'STEAMING_TIME_AUX_5', 'STEAMING_TIME_SH_GEN', 'STEAMING_TIME_TG',
       'POWER_kW', 'STEAMING_LOAD_KW_AUX_1', 'STEAMING_LOAD_KW_AUX_2',
       'STEAMING_LOAD_KW_AUX_3', 'STEAMING_LOAD_KW_AUX_4',
       'STEAMING_LOAD_KW_AUX_5', 'STEAMING_LOAD_KW_SH_GEN',
       'STEAMING_LOAD_KW_TG', 'FUEL_M_E_Rsdl_VLS', 'FUEL_M_E_Rsdl_HS',
       'FUEL_M_E_Rsdl_ULS', 'FUEL_M_E_Dstlt_VLS', 'FUEL_M_E_Dstlt_ULS',
       'FUEL_M_E_Tnktnr_Dstlt_VLS', 'FUEL_M_E_HS', 'FUEL_M_E_LS',
       'FUEL_M_E_MDO', 'FUEL_M_E_MGO', 'FUEL_M_E_MGO_LS',
       'FUEL_Aux_Rsdl_VLS', 'FUEL_Aux_Rsdl_HS', 'FUEL_Aux_Rsdl_ULS',
       'FUEL_Aux_Dstlt_VLS', 'FUEL_Aux_Dstlt_ULS',
       'FUEL_Aux_Tnktnr_Dstlt_VLS', 'FUEL_AUX_HS', 'FUEL_AUX_LS',
       'FUEL_AUX_MDO', 'FUEL_AUX_MGO', 'FUEL_AUX_MGO_LS',
       'FUEL_Boiler_Rsdl_VLS', 'FUEL_Boiler_Rsdl_HS',
       'FUEL_Boiler_Rsdl_ULS', 'FUEL_Boiler_Dstlt_VLS',
       'FUEL_Boiler_Dstlt_ULS', 'FUEL_Boiler_Tnktnr_Dstlt_VLS',
       'FUEL_BOILER_HS', 'FUEL_BOILER_LS', 'FUEL_BOILER_MDO',
       'FUEL_BOILER_MGO', 'FUEL_BOILER_MGO_LS', 'DECK_LAST_CHANGE_USER',
       'ENGINE_LAST_CHANGE_USER', 'DECK_PART_IS_COMPLETE',
       'ENGINE_PART_IS_COMPLETE', 'SCAVENGE_PRESSURE', 'SECA_ENTRY_TIME',
       'SECA_ENTRY_LAT', 'SECA_ENTRY_LONG', 'SECA_EXIT_TIME',
       'SECA_EXIT_LAT', 'SECA_EXIT_LONG', 'ROB_FRESH_WATER',
       'MANVRNG_MILES_BY_GPS', 'MANVRNG_MILES_BY_SPEED_LOG',
       'TANKTAINER_TRANSFD_QUANTITY', 'PILOT_TAKEN',
       'DATE_TIME_START_TRANSIT', 'DATE_TIME_START_TRANSIT_Offset',
       'DATE_TIME_END_TRANSIT', 'DATE_TIME_END_TRANSIT_Offset', 'BALLAST',
       'TANKTAINER_NUMBER', 'STEAMING_KWHR_TOTAL', 'CY_OTHERS',
       'ROB_FO_SLUDGE', 'ROB_LO_SLUDGE', 'ROB_BILGE', 'SLUDGE_REMOVED_FO',
       'SLUDGE_REMOVED_LO', 'SEA_STATE', 'CY_LUB_ADDED_TO_SYSTEM_MECC',
       'CY_LUB_ADDED_TO_SYSTEM_AECC', 'CY_LUB_ADDED_TO_THRUSTERS',
       'CY_ME_LO_PURIFIER_IN_USE', 'CY_BALLAST', 'CY_BENDING_MOMENT',
       'CY_SHEARING_FORCE', 'CY_TORTION_MOMENT',
       'CY_SUPDT_AUDITOR_SIGNED_ON', 'CY_SUPDT_AUDITOR_SIGNED_OFF',
       'CY_CASH_RECEIVED', 'CY_LUB_OIL_RECEIVED_MECYL',
       'CY_LUB_OIL_RECEIVED_MECC', 'CY_LUB_OIL_RECEIVED_AECC',
       'CY_M_E_UNDER_PISTON_TEMP', 'CY_MAIL_RECEIVED',
       'WIND_DIRECTION_PORT_STBD', 'SEA_DIRECTION_PORT_STBD',
       'TIME_PILOT_ONBOARD', 'GRADES_ROB', 'SO2_CO2_RATIO',
       'Bunker_Order', 'Remarks', 'Fuel_Type', 'Carbon_Factor',
       'Sulphur_Content_PC', 'Quantity', 'Port_Delivery',
       'Product_Quality', 'Tanktainer_Number_1', 'Supplier', 'Delivery',
       'Vol_Lt', 'Den', 'Vis', 'ROB_Dstlt_ULS', 'ROB_Dstlt_VLS',
       'ROB_Rsdl_MDO', 'ROB_Tnktnr_Dstlt_VLS', 'ROB_Rsdl_VLS',
       'ROB_Rsdl_HS', 'ROB_Rsdl_ULS', 'ROB_Fuel_HSFO', 'ROB_Fuel_LSFO',
       'ROB_Fuel_MDO', 'ROB_Fuel_MGO', 'ROB_Fuel_MGO_LS',
       'ROB_Fuel_Tanktainer_MGO', 'ECA_MILES', 'ECA_TIME',
       'EGCS_DRY_WASTE_REMOVED', 'EGCS_RUNNING_TIME',
       'EGCS_WET_SLURRY_REMOVED', 'EGCS_OPEN_LOOP_RUNNING_TIME',
       'EGCS_CLOSED_LOOP_RUNNING_TIME', 'Voyage_Order', 'Voyage_Code',
       'ECA', 'EU', 'Sea_Time', 'ETA_Country_Code', 'Port_Country_Code',
       'check_ETA_code', 'check_Port_code', 'Status_TEMP_EU', 'FUEL_HS',
       'FUEL_LS', 'FUEL_MDO', 'FUEL_MGO', 'FUEL_MGO_LS',
       'Cargo_Transport_Work', 'TEU_Transport_Work', 'EEOI_Voyage_no',
       'CARGO_TOTAL_Old', 'DRAFT', 'FO_per_24Hrs', 'SFOC', 'CY_OIL_gm_hr',
       'SCOC', 'Voyage_Name', 'TOTAL_FO', 'TOTAL_CO2', 'EEOI',
       'voyCondition', 'samedate', 'timesincelastreport', 'BDN',
       'Wind_direction_360', 'True_wind_speed', 'True_wind_dir',
       'ref_power', 'ref_fuel', 'fuel_loss', 'Relative_wind_speed',
       'Relative_wind_direction', 'CAA', 'RW', 'Corrected_Power',
       'draft_pow', 'draft_sp_pow', 'fo_nor', 'fo_model', 'sfoc_model',
       'sfoc_deviation', 'ref_power_corrected', 'ref_FO_corrected',
       'Propulsive_eff', 'speed_performance', 'Ref_speed', 'P_I', 'MEcon',
       'AEcon', 'BLcon', 'Tcon', 'HS', 'LS', 'MDO', 'MGO', 'MGOLS',
       'TCO2', 'AETsteaming', 'AEPOWER', 'TRIM', 'DISTANCECOVERED',
       'updated_date', 'hyd_slip_sog', 'hyd_slip_stw', 'FUEL_Rsdl_HS',
       'FUEL_Rsdl_VLS', 'FUEL_Rsdl_ULS', 'FUEL_Dstlt_VLS',
       'FUEL_Dstlt_ULS', 'FUEL_Tnktnr_Dstlt_VLS', 'Rsdl_HS', 'Rsdl_VLS',
       'Rsdl_ULS', 'Dstlt_VLS', 'Dstlt_ULS', 'Tnktnr_Dstlt_VLS', 'Date',
       'Month', 'Year', 'Month_name', 'date', 'Total_Calculated_HS',
       'Total_Calculated_LS', 'Total_Calculated_ULS',
       'Total_Calculated_Fuel', 'HS_CO2', 'LS_CO2', 'ULS_CO2',
       'Total_CO2', 'fuel_m_e_calculated', 'fuel_aux_calculated',
       'fuel_boiler_calculated', 'Total_fuel_calculated'], dtype=object)

In [41]:
MSC_noon_2022_sort_new["MILES_BY_GPS"].isna().sum()

0

In [42]:
#for getting sum of distance in million nautical miles 

distance_2022 = MSC_noon_2022_sort_new.groupby(["IMO_No"])[["MILES_BY_GPS"]].sum().reset_index()
Total_distance_2022 = distance_2022[["MILES_BY_GPS"]].sum().reset_index()
Total_distance_2022 =round( Total_distance_2022[0] / (10 ** 6), 2)
Total_distance_2022.reset_index()

   index      0
0      0  28.39

# 3.  Changing unit of Fuel

In [43]:

# Fuel calculations
fuel_hs_2022 = MSC_noon_2022_sort.groupby(["IMO_No"])[["Total_Calculated_HS"]].sum().reset_index()
Total_fuel_hs_2022 = fuel_hs_2022[["Total_Calculated_HS"]].sum().reset_index()
Total_fuel_hs_2022 = Total_fuel_hs_2022[0] / (10 ** 6)
Total_fuel_hs_2022.reset_index()

fuel_ls_2022 = MSC_noon_2022_sort.groupby(["IMO_No"])[["Total_Calculated_LS"]].sum().reset_index()
Total_fuel_ls_2022 = fuel_ls_2022[["Total_Calculated_LS"]].sum().reset_index()
Total_fuel_ls_2022 = Total_fuel_ls_2022[0] / (10 ** 6)
Total_fuel_ls_2022.reset_index()

fuel_uls_2022 = MSC_noon_2022_sort.groupby(["IMO_No"])[["Total_Calculated_ULS"]].sum().reset_index()
Total_fuel_uls_2022 = fuel_uls_2022[["Total_Calculated_ULS"]].sum().reset_index()
Total_fuel_uls_2022 = Total_fuel_uls_2022[0] / (10 ** 6)
Total_fuel_uls_2022.reset_index()


fuel_me_2022 = MSC_noon_2022_sort.groupby(["IMO_No"])[["fuel_m_e_calculated"]].sum().reset_index()
Total_fuel_me_2022 = fuel_me_2022[["fuel_m_e_calculated"]].sum().reset_index()
Total_fuel_me_2022 = Total_fuel_me_2022[0] / (10 ** 6)
Total_fuel_me_2022.reset_index()

fuel_aux_2022 = MSC_noon_2022_sort.groupby(["IMO_No"])[["fuel_aux_calculated"]].sum().reset_index()
Total_fuel_aux_2022 = fuel_aux_2022[["fuel_aux_calculated"]].sum().reset_index()
Total_fuel_aux_2022 = Total_fuel_aux_2022[0] / (10 ** 6)
Total_fuel_aux_2022.reset_index()

fuel_boiler_2022 = MSC_noon_2022_sort.groupby(["IMO_No"])[["fuel_boiler_calculated"]].sum().reset_index()
Total_fuel_boiler_2022 = fuel_boiler_2022[["fuel_boiler_calculated"]].sum().reset_index()
Total_fuel_boiler_2022 = Total_fuel_boiler_2022[0] / (10 ** 6)
Total_fuel_boiler_2022.reset_index()

fuel_2022 = MSC_noon_2022_sort.groupby(["IMO_No"])[["Total_fuel_calculated"]].sum().reset_index()
Total_fuel_2022 = fuel_2022[["Total_fuel_calculated"]].sum().reset_index()
Total_fuel_2022 = Total_fuel_2022[0] / (10 ** 6)
Total_fuel_2022.reset_index()

# CO2 calculations
fuel_CO2_2022 = MSC_noon_2022_sort.groupby(["IMO_No"])[["Total_CO2"]].sum().reset_index()
Total_CO2_2022 = fuel_CO2_2022[["Total_CO2"]].sum().reset_index()
Total_CO2_2022 =Total_CO2_2022[0] / (10 ** 6)
Total_CO2_2022.reset_index()

   index          0
0      0  17.800642

In [44]:
#Steaming Time


Steam_2022=MSC_noon_2022_sort.groupby(["IMO_No"])[["TOTAL_STEAMING_TIME"]].sum().reset_index()
Total_Steam_2022=Steam_2022[["TOTAL_STEAMING_TIME"]].sum().reset_index()
Total_Steam_2022=Total_Steam_2022[0]/(24)
Total_Steam_2022.reset_index(drop=True, inplace=True)

In [45]:

Total_fuel_HS= {'Parameter':['Total HS Fuel'], '2022':Total_fuel_hs_2022[0].sum()}
Total_fuel_HS= pd.DataFrame(Total_fuel_HS)

Total_fuel_LS= {'Parameter':['Total LS Fuel'], '2022':Total_fuel_ls_2022[0].sum()}
Total_fuel_LS= pd.DataFrame(Total_fuel_LS)

Total_fuel_ULS= {'Parameter':['Total ULS Fuel'], '2022':Total_fuel_uls_2022[0].sum()}
Total_fuel_ULS= pd.DataFrame(Total_fuel_ULS)


Total_fuel= {'Parameter':['Total Fuel'], '2022':Total_fuel_2022[0].sum()}
Total_fuel= pd.DataFrame(Total_fuel)

Total_ME_fuel= {'Parameter':['Total ME Fuel'], '2022':Total_fuel_me_2022[0].sum()}
Total_ME_fuel= pd.DataFrame(Total_ME_fuel)

Total_AUX_fuel= {'Parameter':['Total AUX Fuel'], '2022':Total_fuel_aux_2022[0].sum()}
Total_AUX_fuel= pd.DataFrame(Total_AUX_fuel)

Total_BOI_fuel= {'Parameter':['Total BOILER Fuel'], '2022':Total_fuel_boiler_2022[0].sum()}
Total_BOI_fuel= pd.DataFrame(Total_BOI_fuel)

Total_CO2= {'Parameter':['Total CO2'], '2022':Total_CO2_2022[0].sum()}
Total_CO2= pd.DataFrame(Total_CO2)

In [46]:

#distance is calculating using above cell procedure(sum of vessel,total sum,divide it with 10^6 - Million nautical miles)
Total_Distance= {'Parameter':['Total Distance'], '2022':Total_distance_2022[0].sum()}
Total_Distance= pd.DataFrame(Total_Distance)

#cargo is calculating using above cell procedure(mean of vessel that is in voyage wise,total sum,multiple it with 10^6 - Million tonnes)
Total_Cargo= {'Parameter':['Total Cargo'],'2022':Total_cargo_2022[0].sum()}
Total_Cargo= pd.DataFrame(Total_Cargo)


Total_vsl= {'Parameter':['Number of Vessel'], '2022':MSC_noon_2022["IMO_No"].nunique()}
Total_vsl= pd.DataFrame(Total_vsl)
Total_vsl['2022'] = Total_vsl['2022'].fillna(0).astype(int)

Total_voy= {'Parameter':['Total Voyages'], '2022':MSC_noon_2022["VOY"].nunique()}
Total_voy= pd.DataFrame(Total_voy)

Total_steaming_time= {'Parameter':['Total Steaming Days'], '2022':Total_Steam_2022[0].sum()}
Total_steaming_time= pd.DataFrame(Total_steaming_time)

In [47]:
#Total_Parameters=pd.concat([Total_vsl,Total_fuel_LS,Total_fuel_MGO,Total_fuel,Total_ME_fuel,Total_AUX_fuel,Total_CO2,Total_Cargo,Total_Distance,Total_fresh_pro,Total_fresh_con,Total_voy,Total_steaming_time,Total_ballast_voy_time,Total_Laden_voy_time,Avg_ballast_voy_time,Avg_Laden_voy_time])
Total_Parameters=pd.concat([Total_vsl,Total_fuel_HS,Total_fuel_LS,Total_fuel_ULS,Total_fuel,Total_ME_fuel,Total_AUX_fuel,Total_BOI_fuel,Total_CO2,Total_voy,Total_Cargo,Total_Distance,Total_steaming_time])

Total_Parameters=Total_Parameters.reset_index()
Total_Parameters=Total_Parameters.drop(['index'], axis=1)

In [48]:

unit_parameters = ["", 'Kilotonne', 'Kilotonne', 'Kilotonne','Kilotonne', 'Kilotonne', 'Kilotonne', 'Kilotonne', 'Kilotonne', '', 'Kilotonne', 'Nautical Miles', 'Day']
parameter_unit = pd.DataFrame(unit_parameters, columns=['Unit'])
Total_Parameter_1 = pd.concat([Total_Parameters, parameter_unit], axis=1)
Total_Parameter_1

              Parameter           2022            Unit
0      Number of Vessel     473.000000
1         Total HS Fuel       2.120093       Kilotonne
2         Total LS Fuel       2.845349       Kilotonne
3        Total ULS Fuel       0.696500       Kilotonne
4            Total Fuel       5.100297       Kilotonne
5         Total ME Fuel       4.143465       Kilotonne
6        Total AUX Fuel       0.866333       Kilotonne
7     Total BOILER Fuel       0.090498       Kilotonne
8             Total CO2      17.800642       Kilotonne
9         Total Voyages    9735.000000
10          Total Cargo     281.300000       Kilotonne
11       Total Distance      28.390000  Nautical Miles
12  Total Steaming Days  109211.469211             Day