In [1]:
#importing the necessary packages
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
#Get the excel data
data=pd.read_csv("MSC_Agrigento_Data (1).csv")

In [3]:
data.head()

,VSL,IMO_No,VOY,REPORT_DATE_TIME,Report_Type,Status,LAT,LONG_,LATITUDE,LONGITUDE,...,FUEL_Boiler_Rsdl_ULS,FUEL_Boiler_Dstlt_VLS,FUEL_Boiler_Dstlt_ULS,FUEL_Boiler_Tnktnr_Dstlt_VLS,MANVRNG_MILES_BY_GPS,MANVRNG_MILES_BY_SPEED_LOG,Fuel_Type,Sulphur_Content_PC,Quantity,Port_Delivery
0,MSC AGRIGENTO,9618276.0,NL829R,2018-07-27 05:30:00,SAIL,IN PORT,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
1,MSC AGRIGENTO,9618276.0,NL839R,2018-10-06 12:00:00,PORT,IN PORT,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
2,MSC AGRIGENTO,9618276.0,NX708R,2017-03-03 12:00:00,NOON,AT SEA,0342S,08140W,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
3,MSC AGRIGENTO,9618276.0,FI124A,2021-08-18 09:48:00,COSP,DRIFTING,2655S,04834W,-26.916667,-48.566667,...,0.0,0.0,0.0,0.0,5.7,5.7,NaN,NaN,NaN,NaN
4,MSC AGRIGENTO,9618276.0,NX746R,2017-12-02 12:00:00,NOON,AT SEA,2328N,06323W,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN

In [4]:
df=data.copy()

In [5]:
df.dtypes #checking the variable types

VSL                              object
IMO_No                          float64
VOY                              object
REPORT_DATE_TIME                 object
Report_Type                      object
Status                           object
LAT                              object
LONG_                            object
LATITUDE                        float64
LONGITUDE                       float64
TOTAL_STEAMING_TIME             float64
M_E_Fuel_Only_Steaming_Time     float64
MILES_BY_GPS                    float64
SOW                             float64
SOG                             float64
PORT_CODE                        object
PORT                             object
POWER_kW                          int64
FUEL_M_E_Rsdl_VLS               float64
FUEL_M_E_Rsdl_HS                float64
FUEL_M_E_Rsdl_ULS               float64
FUEL_M_E_Dstlt_VLS              float64
FUEL_M_E_Dstlt_ULS              float64
FUEL_M_E_Tnktnr_Dstlt_VLS       float64
FUEL_Aux_Rsdl_VLS               float64
FUEL_Aux_Rsdl_HS                float64
FUEL_Aux_Rsdl_ULS               float64
FUEL_Aux_Dstlt_VLS              float64
FUEL_Aux_Dstlt_ULS              float64
FUEL_Aux_Tnktnr_Dstlt_VLS       float64
FUEL_Boiler_Rsdl_VLS            float64
FUEL_Boiler_Rsdl_HS             float64
FUEL_Boiler_Rsdl_ULS            float64
FUEL_Boiler_Dstlt_VLS           float64
FUEL_Boiler_Dstlt_ULS           float64
FUEL_Boiler_Tnktnr_Dstlt_VLS    float64
MANVRNG_MILES_BY_GPS            float64
MANVRNG_MILES_BY_SPEED_LOG      float64
Fuel_Type                        object
Sulphur_Content_PC              float64
Quantity                        float64
Port_Delivery                    object
dtype: object

In [6]:
df['REPORT_DATE_TIME'] = pd.to_datetime(df['REPORT_DATE_TIME'], format='%Y-%m-%d %H:%M:%S', errors='coerce') #changing the type

In [7]:
#splitting data into date and time
df['Date']= df['REPORT_DATE_TIME'].dt.date
df['Time'] = df['REPORT_DATE_TIME'].dt.time

In [8]:
df['Date'] = pd.to_datetime(df['Date'])

In [9]:
df.drop(columns=['REPORT_DATE_TIME'], inplace=True)

In [10]:
df.head()

,VSL,IMO_No,VOY,Report_Type,Status,LAT,LONG_,LATITUDE,LONGITUDE,TOTAL_STEAMING_TIME,...,FUEL_Boiler_Dstlt_ULS,FUEL_Boiler_Tnktnr_Dstlt_VLS,MANVRNG_MILES_BY_GPS,MANVRNG_MILES_BY_SPEED_LOG,Fuel_Type,Sulphur_Content_PC,Quantity,Port_Delivery,Date,Time
0,MSC AGRIGENTO,9618276.0,NL829R,SAIL,IN PORT,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,2018-07-27,05:30:00
1,MSC AGRIGENTO,9618276.0,NL839R,PORT,IN PORT,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,2018-10-06,12:00:00
2,MSC AGRIGENTO,9618276.0,NX708R,NOON,AT SEA,0342S,08140W,NaN,NaN,24.0,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,2017-03-03,12:00:00
3,MSC AGRIGENTO,9618276.0,FI124A,COSP,DRIFTING,2655S,04834W,-26.916667,-48.566667,0.8,...,0.0,0.0,5.7,5.7,NaN,NaN,NaN,NaN,2021-08-18,09:48:00
4,MSC AGRIGENTO,9618276.0,NX746R,NOON,AT SEA,2328N,06323W,NaN,NaN,23.0,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,2017-12-02,12:00:00

In [11]:
#Entering the required year
cii_year = int(input("Enter a year (2014-2022): "))
Res_df = df[df['Date'].dt.year == cii_year]
Res_df.set_index('Date', inplace=True)

Enter a year (2014-2022): 2022

In [12]:
Res_df.head()

,VSL,IMO_No,VOY,Report_Type,Status,LAT,LONG_,LATITUDE,LONGITUDE,TOTAL_STEAMING_TIME,...,FUEL_Boiler_Dstlt_VLS,FUEL_Boiler_Dstlt_ULS,FUEL_Boiler_Tnktnr_Dstlt_VLS,MANVRNG_MILES_BY_GPS,MANVRNG_MILES_BY_SPEED_LOG,Fuel_Type,Sulphur_Content_PC,Quantity,Port_Delivery,Time
Date,,,,,,,,,,,,,,,,,,,,,
2022-12-09,MSC AGRIGENTO,9618276.0,FI246R,NOON,AT SEA,3540S,00405W,-35.666667,-4.083333,24.0,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,12:00:00
2022-06-23,MSC AGRIGENTO,9618276.0,FI219R,NOON,AT SEA,1704N,11335E,17.066667,113.583333,24.0,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,12:00:00
2022-09-12,MSC AGRIGENTO,9618276.0,FI233R,NOON,AT SEA,3358S,01236E,-33.966667,12.600000,24.0,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,12:00:00
2022-02-15,MSC AGRIGENTO,9618276.0,FI151A,BRTH,DRIFTING,3443S,05751W,-34.716667,-57.850000,2.5,...,0.0,0.0,0.0,133.0,136.2,NaN,NaN,NaN,NaN,22:00:00
2022-11-13,MSC AGRIGENTO,9618276.0,FI239A,DLY A,DRIFTING,2656S,04832W,-26.933333,-48.533333,0.9,...,0.0,0.0,0.0,5.7,5.5,NaN,NaN,NaN,NaN,17:06:00

# ATTAINED CII

In [13]:
'''

ATTAINED CII= MACSS OF CO2(M)/ TRANSPORT WORK(W)
CII= [ANNUAL FUEL CONSUMPTION]*[CO2 EMISSION FACTOR]/ TRANSPORT WORK
REQUIRED CII= CII(REF)*[(100-Z)/100]

'''

'\n\nATTAINED CII= MACSS OF CO2(M)/ TRANSPORT WORK(W)\nCII= [ANNUAL FUEL CONSUMPTION]*[CO2 EMISSION FACTOR]/ TRANSPORT WORK\nREQUIRED CII= CII(REF)*[(100-Z)/100]\n\n'

In [14]:
#Total HS
Res_df['Total_Calculated_HS'] =  Res_df[['FUEL_M_E_Rsdl_HS' , 'FUEL_Aux_Rsdl_HS' , 'FUEL_Boiler_Rsdl_HS']].sum(axis=1)

#Total LS
Res_df['Total_Calculated_LS'] =  Res_df[['FUEL_M_E_Rsdl_VLS' , 'FUEL_Aux_Rsdl_VLS' , 'FUEL_Boiler_Rsdl_VLS' ,'FUEL_M_E_Rsdl_ULS' ,  'FUEL_Aux_Rsdl_ULS' , 'FUEL_Boiler_Rsdl_ULS']].sum(axis=1)

#Total ULS
Res_df['Total_Calculated_ULS'] =  Res_df[['FUEL_M_E_Dstlt_VLS' , 'FUEL_Aux_Dstlt_VLS' , 'FUEL_Boiler_Dstlt_VLS' ,'FUEL_M_E_Dstlt_ULS' ,'FUEL_Aux_Dstlt_ULS' , 'FUEL_Boiler_Dstlt_ULS' ,'FUEL_M_E_Tnktnr_Dstlt_VLS' , 'FUEL_Aux_Tnktnr_Dstlt_VLS' ,'FUEL_Boiler_Tnktnr_Dstlt_VLS']].sum(axis=1)

In [15]:
"""
EMISSION FACTOR:

FUEL OIL TYPE                CF
DIESEL/ GAS OIL             3.206
LIGHT FUEL OIL              3.151
HEAVY FUEL OIL              3.114
LPG (PROPANE)               3.000
LPG (BUTANE)                3.030
LNG                         2.750
METHANOL                    1.375
ETHANOL                     1.913
OTHER

"""

'\nEMISSION FACTOR:\n\nFUEL OIL TYPE                CF\nDIESEL/ GAS OIL             3.206\nLIGHT FUEL OIL              3.151\nHEAVY FUEL OIL              3.114\nLPG (PROPANE)               3.000\nLPG (BUTANE)                3.030\nLNG                         2.750\nMETHANOL                    1.375\nETHANOL                     1.913\nOTHER\n\n'

In [16]:
#carbon emission factor
Res_df['CO2_HFC']=Res_df['Total_Calculated_HS']*3.114
Res_df['CO2_LFC']=Res_df['Total_Calculated_LS']*3.151
Res_df['CO2_UFC']=Res_df['Total_Calculated_ULS']*3.206

In [17]:
Res_df['Mass_FC']=Res_df[['CO2_HFC','CO2_LFC','CO2_UFC']].sum(axis=1)

In [19]:
# Transport of work :Distance
dist = Res_df['MILES_BY_GPS'].sum()
print(dist)

105003.07999999999

In [20]:
#Deadweight
dwt= 127951.80
Res_df = Res_df.assign(DWT=dwt)
#Res_df.head()

In [20]:
#Total annual fuel consumption
TAFC= Res_df['Mass_FC'].sum() * 10**6
print(TAFC)

107916802189.99998

In [21]:
#Attained CII
ATT_CII = TAFC / (dist * dwt)
ATT_CII

8.032313114583012

# REFERENCE CII

In [ ]:
'''

CII(REF)= A.CAPACITY^-C

PARAMETER FOR A AND C ARE

SHIP TYPE                           A            C         CAPACITY
TANKER                             5247         0.610       DWT
CONTAIER SHIP                      1984         0.489       DWT
BULK CARRIER: DWT >= 2,79,000      4745         0.622       2,79,00     
BULK CARRIER: DWT <= 2,79,00       4745         0.622       DWT
COMBINATION CARRIER                40853        0.812       DWT

'''

In [ ]:
#Parameters for reference cii
a = int(input("A:"))
c = float(input("C:"))
dwt= 110652.40

In [ ]:
CII_REF = a * (dwt ** (-c))
print(CII_REF)

# REQUIRED CII

In [ ]:
'''
Required CII= CII(REF) * [(100-Z)/100]

REDUCATION FACTOR(Z%)
YEAR           REDUCTION FACTOR RELATIVE TO 2019
2019                   
2020                  1%
2021                  2%
2022                  3%
2023                  5%
2024                  7%
2025                  9%
2026                  11%

'''

In [ ]:
#Z-Reduction value
years = {
    2019: 0,
    2020: 1,
    2021: 2,
    2022: 3 ,
    2023: 5 ,
    2024: 7 ,
    2025: 9 ,
    2026: 11
}

a = int(input("Enter a year: "))    #ENTER THE CII YEAR
if a in years:
    Z = years[a]
    print(Z)
else:
    print("No Z value")

In [ ]:
#Required CII 
CII_REQ = CII_REF * ((100 - Z) / 100)
print(CII_REQ)

# CII RATING

In [ ]:
'''

CII RATIO= ATTAINED CII/ REQUIRED CII
                                                DD VECTORS
SHIP TYPE                          CAPACITY     D1     D2    D3    D4  
BULK CARRIER                         DWT       0.86   0.94  1.06  1.18
TANKER                               DWT       0.82   0.93  1.08  1.28
CONTAINER                            DWT       0.83   0.94  1.07  1.19
COMBINATION                          DWT       0.87   0.96  1.06  1.14
GENERAL CARGO SHIP                   DWT       0.83   0.94  1.06  1.19


CII RATIO <= D1 ---------- A RATING
D1<CII RATIO <= D2 ------- B RATING
D2<CII RATIO <= D3 ------- C RATING
D3<CII RATIO <= D4 ------- D RATING
CII RATIO  > D4 ---------- E RATING

A – Major superior performance level
B – Minor superior performance level
C – Moderate performance level
D – Minor Inferior performance level
E – Inferior performance level

All vessels must aspire to be at least C-rated.Any vessel that is rated D or E for three years in a row will have to 
submit a corrective action plan that explains the efforts that will be taken to achieve an acceptable rating (C or above). 
 
'''

In [ ]:
#CII Ratio
CII_RATIO= ATT_CII/ CII_REQ
print(CII_RATIO)

# RESULT

In [ ]:
ships = {
    'BULK': {'D1': 0.86, 'D2': 0.94, 'D3': 1.06, 'D4': 1.18},
    'TANKER': {'D1': 0.82, 'D2': 0.93, 'D3': 1.08, 'D4': 1.28},
    'CONTAINER': {'D1': 0.83, 'D2': 0.94, 'D3': 1.07, 'D4': 1.19},
    'COMBINATION': {'D1': 0.87, 'D2': 0.96, 'D3': 1.06, 'D4': 1.14},
    'GENERAL CARGO SHIP': {'D1': 0.83, 'D2': 0.94, 'D3': 1.06, 'D4': 1.19},
}

def ratings(ship, cii_ratio):
    a = ships.get(ship)
    if a:
        if cii_ratio <= a['D1']:
            return 'A RATING'
        elif a['D1'] < cii_ratio <= a['D2']:
            return 'B RATING'
        elif a['D2'] < cii_ratio <= a['D3']:
            return 'C RATING'
        elif a['D3'] < cii_ratio <= a['D4']:
            return 'D RATING'
        else:
            return 'E RATING'
    else:
        return 'Data not founded'

ship = input("Enter the ship: ").strip().upper()  
CII_RATIO = CII_RATIO
rating = ratings(ship, CII_RATIO)
print(f'The rating for MSC AGREGENTO is: {rating}')

In [ ]:
#110652.40