In [1]:
import pandas as pd

In [2]:
data= pd.read_csv(r'D:\Navalt\Files\EEOI_ANASTAISA_CLASS.csv')
data

C:\Users\akshaya\AppData\Local\Temp\ipykernel_50360\3541340306.py:1: DtypeWarning: Columns (87,99,150,152,153,155,156,162,164,170,181,182,183,186,187,188,189,190,194,353,354) have mixed types. Specify dtype option on import or set low_memory=False.
  data= pd.read_csv(r'D:\Navalt\Files\EEOI_ANASTAISA_CLASS.csv')

,id,pi_sog,pi_stw,true_wind_dir,true_wind_speed,relative_wind_speed,relative_wind_direction,caa,corrected_power,rw,...,rob_garbage_cat_a_plastic,rob_garbage_cat_b_organic,rob_garbage_cat_c_domestic,rob_garbage_cat_e_ashes,qty_sludge_disposed,steaming_time_m_e_lng,reefer_power_consumption,wind_direction_side,sea_direction_side,tot_sludge_removed
0,4543691,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4678622,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.84729,0.00000,0.00000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4687824,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4688026,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4688718,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.84729,0.00000,0.00000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11687,4896207,-6.90238,-5.19641,291.81769,2.16766,4.57687,14.59227,0.88203,4673.86612,-7939.34746,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,10P,38P,NaN
11688,4896208,-5.16549,-7.50609,330.00000,9.38853,2.03446,0.00000,0.84729,4787.52102,-19862.90638,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0P,0P,NaN
11689,4896210,-10.10029,-9.43926,71.76539,11.62210,12.41691,-52.04809,0.41452,4389.80761,27038.01580,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,55P,78P,NaN
11690,4896211,-17.18976,-14.16511,53.13062,13.51360,12.16108,-71.69057,0.21208,4566.99217,6045.63567,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,75P,97P,NaN
11691,4896212,-21.08193,-16.63584,63.53317,14.53008,13.49261,-67.54795,0.25737,3232.57794,20669.59849,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,70P,86P,NaN

In [3]:
data.columns.to_list()

['id',
 'pi_sog',
 'pi_stw',
 'true_wind_dir',
 'true_wind_speed',
 'relative_wind_speed',
 'relative_wind_direction',
 'caa',
 'corrected_power',
 'rw',
 'ref_speed',
 'imo',
 'vessel',
 'id_vessel',
 'gid',
 'voyage',
 'corrected_date',
 'report_date_time',
 'report_date_time_offset',
 'report_type',
 'status',
 'lat',
 'long',
 'latitude',
 'longitude',
 'me_foc',
 'cargo_total',
 'total_steaming_time',
 'me_fuel_only_steaming_time',
 'miles_by_gps',
 'oil_cyl',
 'speed_by_log',
 'speed_by_gps',
 'rpm',
 'slip',
 'wind_direction',
 'wind_speed',
 'draft_aft',
 'draft_fwd',
 'displacement',
 'course_at_sea',
 'wave_height',
 'sea_direction',
 'cargo_total_teu',
 'ambient_temp',
 'sw_temp',
 'miles_by_speed_log',
 'eta_port_code',
 'eta_date_time',
 'eta_date_time_offset',
 'eta_port',
 'time_change',
 'time_sea',
 'temp_min',
 'temp_max',
 'requested_speed',
 'rem_dist_to_pilot',
 'rem_time_to_pilot',
 'total_unplnd_stpge_tech',
 'total_unplnd_stpge_ope_wx',
 'reefers_positive_plugged',
 'reefers_negative_plugged',
 'me_total_revs_counter',
 'port_code',
 'port',
 'aux_blowers_on',
 'hold_ventilation_on',
 'since_date_time',
 'since_date_time_offset',
 'time_hrs_anchor',
 'time_hrs_drift',
 'reason',
 'type_of_delay',
 'etb_date_time',
 'etb_date_time_offset',
 'pilot_date_time',
 'pilot_date_time_offset',
 'time_manoeuvring',
 'tug_arr',
 'tug_shift',
 'etd_date_time',
 'etd_date_time_offset',
 'shift_berth_hours',
 'cargo_load',
 'cargo_disch',
 'teu_full',
 'teu_empty',
 'bilge_removed',
 'garbage_removed',
 'garbage_remvl_reqstd',
 'garbage_remvl_cmplsry',
 'fw_supply',
 'cy_crew_signed_on',
 'cy_crew_signed_off',
 'cy_doctors_visit',
 'cy_mail_received_ref_no',
 'cy_lub_oil_sample_landed',
 'cy_checkd_for_stowaways',
 'cy_stowaways_on_board',
 'cy_dep_gm_mtr',
 'cy_requisitions_received',
 'distance_to_next_pilot',
 'tug_sailing_transit',
 'steaming_time_me_rsdl_vls',
 'steaming_time_me_rsdl_hs',
 'steaming_time_me_rsdl_uls',
 'steaming_time_me_dstlt_vls',
 'steaming_time_me_dstlt_uls',
 'steaming_time_me_tnktnr_dstlt_vls',
 'steaming_time_me_mdo',
 'steaming_time_aux_1',
 'steaming_time_aux_2',
 'steaming_time_aux_3',
 'steaming_time_aux_4',
 'steaming_time_aux_5',
 'steaming_time_sh_gen',
 'steaming_time_tg',
 'fuel_me_rsdl_vls',
 'fuel_me_rsdl_hs',
 'fuel_me_rsdl_uls',
 'fuel_me_dstlt_vls',
 'fuel_me_dstlt_uls',
 'fuel_me_mdo',
 'fuel_me_tnktnr_dstlt_vls',
 'fuel_aux_rsdl_vls',
 'fuel_aux_rsdl_hs',
 'fuel_aux_rsdl_uls',
 'fuel_aux_dstlt_vls',
 'fuel_aux_dstlt_uls',
 'fuel_aux_tnktnr_dstlt_vls',
 'fuel_aux_mdo',
 'fuel_boiler_rsdl_vls',
 'fuel_boiler_rsdl_hs',
 'fuel_boiler_rsdl_uls',
 'fuel_boiler_dstlt_vls',
 'fuel_boiler_dstlt_uls',
 'fuel_boiler_tnktnr_dstlt_vls',
 'fuel_boiler_mdo',
 'power_kw',
 'steaming_load_kw_aux_1',
 'steaming_load_kw_aux_2',
 'steaming_load_kw_aux_3',
 'steaming_load_kw_aux_4',
 'steaming_load_kw_aux_5',
 'steaming_load_kw_sh_gen',
 'steaming_load_kw_tg',
 'deck_last_change_user',
 'engine_last_change_user',
 'deck_part_is_complete',
 'engine_part_is_complete',
 'scavenge_pressure',
 'seca_entry_time',
 'seca_entry_lat',
 'seca_entry_long',
 'seca_exit_time',
 'seca_exit_lat',
 'seca_exit_long',
 'rob_fresh_water',
 'manvrng_miles_by_gps',
 'manvrng_miles_by_speed_log',
 'tanktainer_transfd_quantity',
 'pilot_taken',
 'date_time_start_transit',
 'date_time_start_transit_offset',
 'date_time_end_transit',
 'date_time_end_transit_offset',
 'ballast',
 'tanktainer_number',
 'steaming_kwhr_total',
 'cy_others',
 'rob_fo_sludge',
 'rob_lo_sludge',
 'rob_bilge',
 'sludge_removed_fo',
 'sludge_removed_lo',
 'sea_state',
 'cy_lub_added_to_system_me_cc',
 'cy_lub_added_to_system_ae_cc',
 'cy_lub_added_to_thrusters',
 'cy_me_lo_purifier_in_use',
 'cy_ballast',
 'cy_bending_moment',
 'cy_shearing_force',
 'cy_tortion_moment',
 'cy_supdt_auditor_signed_on',
 'cy_supdt_auditor_signed_off',
 'cy_cash_received',
 'cy_lub_oil_received_me_cyl',
 'cy_lub_oil_received_me_cc',
 'cy_lub_oil_received_ae_cc',
 'cy_me_under_piston_temp',
 'cy_mail_received',
 'wind_direction_port_stbd',
 'sea_direction_port_stbd',
 'time_pilot_onboard',
 'grades_rob',
 'so_2_co_2_ratio',
 'bunker_order',
 'remarks',
 'bdn_number',
 'fuel_type',
 'carbon_factor',
 'sulphur_content_pc',
 'quantity',
 'port_delivery',
 'product_quality',
 'tanktainer_number_1',
 'supplier',
 'delivery',
 'volume_lt',
 'density',
 'viscosity',
 'rob_dstlt_uls',
 'rob_dstlt_vls',
 'rob_rsdl_mdo',
 'rob_tnktnr_dstlt_vls',
 'rob_rsdl_vls',
 'rob_rsdl_hs',
 'rob_rsdl_uls',
 'has_cargo',
 'steaming_time_me_hs',
 'steaming_time_me_ls',
 'steaming_time_me_mgo',
 'steaming_time_me_mgo_ls',
 'fuel_me_hs',
 'fuel_me_ls',
 'fuel_me_mgo',
 'fuel_me_mgo_ls',
 'fuel_aux_hs',
 'fuel_aux_ls',
 'fuel_aux_mgo',
 'fuel_aux_mgo_ls',
 'fuel_boiler_hs',
 'fuel_boiler_ls',
 'fuel_boiler_mgo',
 'fuel_boiler_mgo_ls',
 'rob_fuel_hs_fo',
 'rob_fuel_ls_fo',
 'rob_fuel_mdo',
 'rob_fuel_mgo',
 'rob_fuel_mgo_ls',
 'rob_fuel_tanktainer_mgo',
 'eca_miles',
 'eca_time',
 'egcs_dry_waste_removed',
 'egcs_running_time',
 'egcs_wet_slurry_removed',
 'egcs_open_loop_running_time',
 'egcs_closed_loop_running_time',
 'voyage_order',
 'voyage_code',
 'eca',
 'eu',
 'sea_time',
 'eta_country_code',
 'port_country_code',
 'check_eta_code',
 'check_port_code',
 'status_temp_eu',
 'fuel_hs',
 'fuel_ls',
 'fuel_mdo',
 'fuel_mgo',
 'fuel_mgo_ls',
 'cargo_transport_work',
 'teu_transport_work',
 'eeoi_voyage_no',
 'cargo_total_old',
 'draft',
 'fo_per_24_hrs',
 'sfoc',
 'cy_oil_gm_hr',
 'scoc',
 'voyage_name',
 'total_fo',
 'total_co_2',
 'eeoi',
 'voy_condition',
 'same_date',
 'time_since_last_report',
 'wind_direction_360',
 'ref_power',
 'ref_fuel',
 'fuel_loss',
 'draft_pow',
 'draft_sp_pow',
 'fo_nor',
 'fo_model',
 'sfoc_model',
 'sfoc_deviation',
 'ref_power_corrected',
 'ref_fo_corrected',
 'propulsive_eff',
 'speed_performance',
 'pi',
 'me_con',
 'ae_con',
 'bl_con',
 't_con',
 'hs',
 'ls',
 'mdo',
 'mgo',
 'mgo_ls',
 't_co_2',
 'ae_t_steaming',
 'ae_power',
 'trim',
 'distance_covered',
 'updated_date',
 'hyd_slip_sog',
 'hyd_slip_stw',
 'fuel_rsdl_hs',
 'fuel_rsdl_vls',
 'fuel_rsdl_uls',
 'fuel_dstlt_vls',
 'fuel_dstlt_uls',
 'fuel_tnktnr_dstlt_vls',
 'rsdl_hs',
 'rsdl_vls',
 'rsdl_uls',
 'dstlt_vls',
 'dstlt_uls',
 'tnktnr_dstlt_vls',
 'fuel_m_e_lng',
 'fuel_aux_lng',
 'fuel_boiler_lng',
 'rob_rsdl_lng',
 'sulphur_content_pc_main',
 'quantity_main',
 'port_delivery_main',
 'product_quality_main',
 'delivery_main',
 'bdn_number_main',
 'fo_nor_sog',
 'fo_nor_stw',
 'created_at',
 'updated_at',
 'created_by_id',
 'updated_by_id',
 'rob_lng',
 'sludge_rob',
 'garbage_cat_a_plastic_removed',
 'garbage_cat_b_organic_removed',
 'garbage_cat_c_domestic_removed',
 'garbage_cat_e_ashes_removed',
 'rob_garbage_cat_a_plastic',
 'rob_garbage_cat_b_organic',
 'rob_garbage_cat_c_domestic',
 'rob_garbage_cat_e_ashes',
 'qty_sludge_disposed',
 'steaming_time_m_e_lng',
 'reefer_power_consumption',
 'wind_direction_side',
 'sea_direction_side',
 'tot_sludge_removed']

In [4]:
df=pd.DataFrame()

In [5]:
df['imo']=pd.to_numeric(data['imo'])

In [ ]:
df

In [6]:
finaldata=pd.DataFrame()

In [7]:
finaldata['imo']=df['imo']

In [11]:
finaldata['voyages']=finaldata['imo'].nunique()
print(finaldata)

           imo  voyages
0      9625932        3
1      9625944        3
2      9625944        3
3      9625944        3
4      9625944        3
...        ...      ...
11687  9625932        3
11688  9625932        3
11689  9625932        3
11690  9625932        3
11691  9625932        3

[11692 rows x 2 columns]

In [12]:
df1=data.copy()

In [15]:
df1.columns.to_list()

['id',
 'pi_sog',
 'pi_stw',
 'true_wind_dir',
 'true_wind_speed',
 'relative_wind_speed',
 'relative_wind_direction',
 'caa',
 'corrected_power',
 'rw',
 'ref_speed',
 'imo',
 'vessel',
 'id_vessel',
 'gid',
 'voyage',
 'corrected_date',
 'report_date_time',
 'report_date_time_offset',
 'report_type',
 'status',
 'lat',
 'long',
 'latitude',
 'longitude',
 'me_foc',
 'cargo_total',
 'total_steaming_time',
 'me_fuel_only_steaming_time',
 'miles_by_gps',
 'oil_cyl',
 'speed_by_log',
 'speed_by_gps',
 'rpm',
 'slip',
 'wind_direction',
 'wind_speed',
 'draft_aft',
 'draft_fwd',
 'displacement',
 'course_at_sea',
 'wave_height',
 'sea_direction',
 'cargo_total_teu',
 'ambient_temp',
 'sw_temp',
 'miles_by_speed_log',
 'eta_port_code',
 'eta_date_time',
 'eta_date_time_offset',
 'eta_port',
 'time_change',
 'time_sea',
 'temp_min',
 'temp_max',
 'requested_speed',
 'rem_dist_to_pilot',
 'rem_time_to_pilot',
 'total_unplnd_stpge_tech',
 'total_unplnd_stpge_ope_wx',
 'reefers_positive_plugged',
 'reefers_negative_plugged',
 'me_total_revs_counter',
 'port_code',
 'port',
 'aux_blowers_on',
 'hold_ventilation_on',
 'since_date_time',
 'since_date_time_offset',
 'time_hrs_anchor',
 'time_hrs_drift',
 'reason',
 'type_of_delay',
 'etb_date_time',
 'etb_date_time_offset',
 'pilot_date_time',
 'pilot_date_time_offset',
 'time_manoeuvring',
 'tug_arr',
 'tug_shift',
 'etd_date_time',
 'etd_date_time_offset',
 'shift_berth_hours',
 'cargo_load',
 'cargo_disch',
 'teu_full',
 'teu_empty',
 'bilge_removed',
 'garbage_removed',
 'garbage_remvl_reqstd',
 'garbage_remvl_cmplsry',
 'fw_supply',
 'cy_crew_signed_on',
 'cy_crew_signed_off',
 'cy_doctors_visit',
 'cy_mail_received_ref_no',
 'cy_lub_oil_sample_landed',
 'cy_checkd_for_stowaways',
 'cy_stowaways_on_board',
 'cy_dep_gm_mtr',
 'cy_requisitions_received',
 'distance_to_next_pilot',
 'tug_sailing_transit',
 'steaming_time_me_rsdl_vls',
 'steaming_time_me_rsdl_hs',
 'steaming_time_me_rsdl_uls',
 'steaming_time_me_dstlt_vls',
 'steaming_time_me_dstlt_uls',
 'steaming_time_me_tnktnr_dstlt_vls',
 'steaming_time_me_mdo',
 'steaming_time_aux_1',
 'steaming_time_aux_2',
 'steaming_time_aux_3',
 'steaming_time_aux_4',
 'steaming_time_aux_5',
 'steaming_time_sh_gen',
 'steaming_time_tg',
 'fuel_me_rsdl_vls',
 'fuel_me_rsdl_hs',
 'fuel_me_rsdl_uls',
 'fuel_me_dstlt_vls',
 'fuel_me_dstlt_uls',
 'fuel_me_mdo',
 'fuel_me_tnktnr_dstlt_vls',
 'fuel_aux_rsdl_vls',
 'fuel_aux_rsdl_hs',
 'fuel_aux_rsdl_uls',
 'fuel_aux_dstlt_vls',
 'fuel_aux_dstlt_uls',
 'fuel_aux_tnktnr_dstlt_vls',
 'fuel_aux_mdo',
 'fuel_boiler_rsdl_vls',
 'fuel_boiler_rsdl_hs',
 'fuel_boiler_rsdl_uls',
 'fuel_boiler_dstlt_vls',
 'fuel_boiler_dstlt_uls',
 'fuel_boiler_tnktnr_dstlt_vls',
 'fuel_boiler_mdo',
 'power_kw',
 'steaming_load_kw_aux_1',
 'steaming_load_kw_aux_2',
 'steaming_load_kw_aux_3',
 'steaming_load_kw_aux_4',
 'steaming_load_kw_aux_5',
 'steaming_load_kw_sh_gen',
 'steaming_load_kw_tg',
 'deck_last_change_user',
 'engine_last_change_user',
 'deck_part_is_complete',
 'engine_part_is_complete',
 'scavenge_pressure',
 'seca_entry_time',
 'seca_entry_lat',
 'seca_entry_long',
 'seca_exit_time',
 'seca_exit_lat',
 'seca_exit_long',
 'rob_fresh_water',
 'manvrng_miles_by_gps',
 'manvrng_miles_by_speed_log',
 'tanktainer_transfd_quantity',
 'pilot_taken',
 'date_time_start_transit',
 'date_time_start_transit_offset',
 'date_time_end_transit',
 'date_time_end_transit_offset',
 'ballast',
 'tanktainer_number',
 'steaming_kwhr_total',
 'cy_others',
 'rob_fo_sludge',
 'rob_lo_sludge',
 'rob_bilge',
 'sludge_removed_fo',
 'sludge_removed_lo',
 'sea_state',
 'cy_lub_added_to_system_me_cc',
 'cy_lub_added_to_system_ae_cc',
 'cy_lub_added_to_thrusters',
 'cy_me_lo_purifier_in_use',
 'cy_ballast',
 'cy_bending_moment',
 'cy_shearing_force',
 'cy_tortion_moment',
 'cy_supdt_auditor_signed_on',
 'cy_supdt_auditor_signed_off',
 'cy_cash_received',
 'cy_lub_oil_received_me_cyl',
 'cy_lub_oil_received_me_cc',
 'cy_lub_oil_received_ae_cc',
 'cy_me_under_piston_temp',
 'cy_mail_received',
 'wind_direction_port_stbd',
 'sea_direction_port_stbd',
 'time_pilot_onboard',
 'grades_rob',
 'so_2_co_2_ratio',
 'bunker_order',
 'remarks',
 'bdn_number',
 'fuel_type',
 'carbon_factor',
 'sulphur_content_pc',
 'quantity',
 'port_delivery',
 'product_quality',
 'tanktainer_number_1',
 'supplier',
 'delivery',
 'volume_lt',
 'density',
 'viscosity',
 'rob_dstlt_uls',
 'rob_dstlt_vls',
 'rob_rsdl_mdo',
 'rob_tnktnr_dstlt_vls',
 'rob_rsdl_vls',
 'rob_rsdl_hs',
 'rob_rsdl_uls',
 'has_cargo',
 'steaming_time_me_hs',
 'steaming_time_me_ls',
 'steaming_time_me_mgo',
 'steaming_time_me_mgo_ls',
 'fuel_me_hs',
 'fuel_me_ls',
 'fuel_me_mgo',
 'fuel_me_mgo_ls',
 'fuel_aux_hs',
 'fuel_aux_ls',
 'fuel_aux_mgo',
 'fuel_aux_mgo_ls',
 'fuel_boiler_hs',
 'fuel_boiler_ls',
 'fuel_boiler_mgo',
 'fuel_boiler_mgo_ls',
 'rob_fuel_hs_fo',
 'rob_fuel_ls_fo',
 'rob_fuel_mdo',
 'rob_fuel_mgo',
 'rob_fuel_mgo_ls',
 'rob_fuel_tanktainer_mgo',
 'eca_miles',
 'eca_time',
 'egcs_dry_waste_removed',
 'egcs_running_time',
 'egcs_wet_slurry_removed',
 'egcs_open_loop_running_time',
 'egcs_closed_loop_running_time',
 'voyage_order',
 'voyage_code',
 'eca',
 'eu',
 'sea_time',
 'eta_country_code',
 'port_country_code',
 'check_eta_code',
 'check_port_code',
 'status_temp_eu',
 'fuel_hs',
 'fuel_ls',
 'fuel_mdo',
 'fuel_mgo',
 'fuel_mgo_ls',
 'cargo_transport_work',
 'teu_transport_work',
 'eeoi_voyage_no',
 'cargo_total_old',
 'draft',
 'fo_per_24_hrs',
 'sfoc',
 'cy_oil_gm_hr',
 'scoc',
 'voyage_name',
 'total_fo',
 'total_co_2',
 'eeoi',
 'voy_condition',
 'same_date',
 'time_since_last_report',
 'wind_direction_360',
 'ref_power',
 'ref_fuel',
 'fuel_loss',
 'draft_pow',
 'draft_sp_pow',
 'fo_nor',
 'fo_model',
 'sfoc_model',
 'sfoc_deviation',
 'ref_power_corrected',
 'ref_fo_corrected',
 'propulsive_eff',
 'speed_performance',
 'pi',
 'me_con',
 'ae_con',
 'bl_con',
 't_con',
 'hs',
 'ls',
 'mdo',
 'mgo',
 'mgo_ls',
 't_co_2',
 'ae_t_steaming',
 'ae_power',
 'trim',
 'distance_covered',
 'updated_date',
 'hyd_slip_sog',
 'hyd_slip_stw',
 'fuel_rsdl_hs',
 'fuel_rsdl_vls',
 'fuel_rsdl_uls',
 'fuel_dstlt_vls',
 'fuel_dstlt_uls',
 'fuel_tnktnr_dstlt_vls',
 'rsdl_hs',
 'rsdl_vls',
 'rsdl_uls',
 'dstlt_vls',
 'dstlt_uls',
 'tnktnr_dstlt_vls',
 'fuel_m_e_lng',
 'fuel_aux_lng',
 'fuel_boiler_lng',
 'rob_rsdl_lng',
 'sulphur_content_pc_main',
 'quantity_main',
 'port_delivery_main',
 'product_quality_main',
 'delivery_main',
 'bdn_number_main',
 'fo_nor_sog',
 'fo_nor_stw',
 'created_at',
 'updated_at',
 'created_by_id',
 'updated_by_id',
 'rob_lng',
 'sludge_rob',
 'garbage_cat_a_plastic_removed',
 'garbage_cat_b_organic_removed',
 'garbage_cat_c_domestic_removed',
 'garbage_cat_e_ashes_removed',
 'rob_garbage_cat_a_plastic',
 'rob_garbage_cat_b_organic',
 'rob_garbage_cat_c_domestic',
 'rob_garbage_cat_e_ashes',
 'qty_sludge_disposed',
 'steaming_time_m_e_lng',
 'reefer_power_consumption',
 'wind_direction_side',
 'sea_direction_side',
 'tot_sludge_removed']

In [16]:
df1['transportation_mt']=df1['cargo_transport_work']

In [17]:
df1[['distance_covered','teu_full', 'teu_empty', 'manvrng_miles_by_gps','miles_by_gps','cargo_transport_work','fuel_hs','fuel_ls','fuel_mdo','fuel_mgo','fuel_mgo_ls','teu_transport_work','fuel_me_rsdl_hs','fuel_aux_rsdl_hs','fuel_boiler_rsdl_hs','fuel_me_rsdl_vls','fuel_aux_rsdl_vls','fuel_boiler_rsdl_vls','fuel_me_rsdl_uls','fuel_boiler_rsdl_uls','fuel_aux_rsdl_uls','fuel_me_dstlt_vls','fuel_aux_dstlt_uls','fuel_boiler_dstlt_uls','fuel_me_tnktnr_dstlt_vls','fuel_aux_tnktnr_dstlt_vls','fuel_boiler_tnktnr_dstlt_vls','fuel_aux_dstlt_vls','fuel_boiler_dstlt_vls','fuel_me_dstlt_uls','cargo_total','transportation_mt']] = df1[['distance_covered','teu_full', 'teu_empty', 'manvrng_miles_by_gps','miles_by_gps','cargo_transport_work','fuel_hs','fuel_ls','fuel_mdo','fuel_mgo','fuel_mgo_ls','teu_transport_work','fuel_me_rsdl_hs','fuel_aux_rsdl_hs','fuel_boiler_rsdl_hs','fuel_me_rsdl_vls','fuel_aux_rsdl_vls','fuel_boiler_rsdl_vls','fuel_me_rsdl_uls','fuel_boiler_rsdl_uls','fuel_aux_rsdl_uls','fuel_me_dstlt_vls','fuel_aux_dstlt_uls','fuel_boiler_dstlt_uls','fuel_me_tnktnr_dstlt_vls','fuel_aux_tnktnr_dstlt_vls','fuel_boiler_tnktnr_dstlt_vls','fuel_aux_dstlt_vls','fuel_boiler_dstlt_vls','fuel_me_dstlt_uls','cargo_total','transportation_mt']].apply(pd.to_numeric)

In [20]:
finaldata['totalco2']=round(((pd.to_numeric(df1['fuel_me_rsdl_hs'])+pd.to_numeric(df1['fuel_aux_rsdl_hs'])+pd.to_numeric(df1['fuel_boiler_rsdl_hs']))*3.114)+((pd.to_numeric(df1['fuel_me_rsdl_vls'])+pd.to_numeric(df1['fuel_aux_rsdl_vls'])+pd.to_numeric(df1['fuel_boiler_rsdl_vls'])+pd.to_numeric(df1['fuel_me_rsdl_uls'])+pd.to_numeric(df1['fuel_aux_rsdl_uls'])+pd.to_numeric(df1['fuel_boiler_rsdl_uls']))*3.151)   +((pd.to_numeric(df1['fuel_me_dstlt_vls'])+pd.to_numeric(df1['fuel_aux_dstlt_vls'])+pd.to_numeric(df1['fuel_boiler_dstlt_vls'])+pd.to_numeric(df1['fuel_me_dstlt_uls'])+pd.to_numeric(df1['fuel_aux_dstlt_uls'])+pd.to_numeric(df1['fuel_boiler_dstlt_uls'])+pd.to_numeric(df1['fuel_me_tnktnr_dstlt_vls'])+pd.to_numeric(df1['fuel_aux_tnktnr_dstlt_vls'])+pd.to_numeric(df1['fuel_boiler_tnktnr_dstlt_vls']))*3.206),2)
#fuel_ls  = df1[['fuel_hs','fuel_ls','fuel_mdo','fuel_mgo','fuel_mgo_ls','cargo_transport_work','teu_transport_work','miles_by_gps','manvrng_miles_by_gps','distance_covered','fuel_me_rsdl_hs','fuel_aux_rsdl_hs','fuel_boiler_rsdl_hs']].sum().reset_index()

In [23]:
EEOIData=pd.DataFrame()

In [24]:
EEOIData['HFO']=df1['fuel_me_rsdl_hs']+df1['fuel_aux_rsdl_hs']+df1['fuel_boiler_rsdl_hs']
EEOIData['LFO']=df1['fuel_me_rsdl_vls'] + df1['fuel_aux_rsdl_vls'] +df1['fuel_boiler_rsdl_vls'] +df1['fuel_me_rsdl_uls'] +df1['fuel_aux_rsdl_uls'] +df1['fuel_boiler_rsdl_uls']
EEOIData['MDO_MGO']=df1['fuel_me_dstlt_vls'] + df1['fuel_aux_dstlt_vls'] + df1['fuel_boiler_dstlt_vls'] + df1['fuel_me_dstlt_uls'] + df1['fuel_aux_dstlt_uls'] + df1['fuel_boiler_dstlt_uls']+df1['fuel_me_tnktnr_dstlt_vls'] + df1['fuel_aux_tnktnr_dstlt_vls'] + df1['fuel_boiler_tnktnr_dstlt_vls']

In [26]:

finaldata['totalco2_mt'] = finaldata['totalco2'].sum()
finaldata['hfo_total']=EEOIData['HFO'].sum()
finaldata['lfo_total']=EEOIData['LFO'].sum()
finaldata['MDO_MGO_total']=EEOIData['MDO_MGO'].sum()

In [ ]:

# mt  = df1.groupby(['imo','voyage_order'])['cargo_transport_work'].sum().reset_index()
# mt  = df1.groupby(['imo','voyage_order'])['cargo_transport_work'].sum().reset_index()
# EEOIData['mt']=fuel_ls['cargo_transport_work']
# EEOIData['tue']=fuel_ls['teu_transport_work']

In [29]:
finaldata['equivalent_hfo'] = round((finaldata['hfo_total'] + (finaldata['lfo_total'] + finaldata['MDO_MGO_total'])* 1.05 ), 2)
finaldata['distance_x'] = round(df1['miles_by_gps'], 2).sum()
finaldata['fuelkg/nm'] = round(((finaldata['equivalent_hfo'] * 1000) / finaldata['distance_x']), 2)
finaldata['totalco2_kgnm'] =round((finaldata['totalco2_mt'] ) / finaldata['distance_x'], 2)
finaldata['equivalent_hfo'] = round((finaldata['hfo_total'] + (finaldata['lfo_total'] + finaldata['MDO_MGO_total'])* 1.05 ), 2)

In [33]:
finaldata['mt_x'] = df1.groupby(['imo', 'voyage_order'])['cargo_transport_work'].sum().reset_index()['cargo_transport_work']
finaldata['teu'] = df1.groupby(['imo', 'voyage_order'])['teu_transport_work'].sum().reset_index()['teu_transport_work']

In [34]:
finaldata['eeoi_mt'] = round((round(finaldata['totalco2_mt'],2) * 10 ** 6) / round(finaldata['mt_x'],2), 2)
finaldata['eeoi_teu'] = round((round(finaldata['totalco2_mt'],2) * 10 ** 6 )/ round(finaldata['teu'],2), 2)
finaldata['eeoi_mt'] =pd.to_numeric(finaldata['eeoi_mt'])
finaldata['eeoi_teu']=pd.to_numeric(finaldata['eeoi_teu'])

In [42]:
# finaldata=pd.merge(finaldata, eeoigoal,how='left', left_on=['imo'], right_on = ['vesselname'])
finaldata['voyages']=finaldata['imo'].count()

finaldata['average_perteu'] = round(df1['cargo_total_teu'] / pd.to_numeric(finaldata['voyages']),2)
finaldata['average_permt'] = round(df1['cargo_total'] / pd.to_numeric(finaldata['voyages']),2)
finaldata['average_distance'] = round(finaldata['distance_x'] / pd.to_numeric(finaldata['voyages']),2)
finaldata['average_fuelcons'] =round( finaldata['equivalent_hfo'] / pd.to_numeric(finaldata['voyages']),2)

In [ ]:


EEOIData['EEOI_TEU'] = np.where(fuel_ls['eeoitype'] == "1", round(EEOIData['TotalCo2_mt']  * 1000000 / sum(fuel_ls['teu_transport_work']), 2),np.NaN)
# EEOIData['TotalCo2_mt']=df1_new['TotalCo2_mt']
EEOIData['eeoi_voyage_no']=df1_new['eeoi_voyage_no']
# EEOIData['eeoi_voyage_no']=df1_new['eeoi_voyage_no']
EEOIData['EEOIGOALMT']=np.NaN
EEOIData['EEOIGOALTEU']=np.NaN
# EEOIData['vessel_name']=df1_new['name']

In [ ]:
    dropnan
    finaldata['voyages']=finaldata['imo'].unique().count()
    #print(finaldata)
    finaldata['totalco2_mt'] = finaldata['totalco2'].sum().re
    finaldata['hfo_total']=finaldata['HFO'].sum()
    finaldata['lfo_total']=finaldata['LFO'].sum()
    finaldata['MDO_MGO_total']=finaldata['MDO_MGO'].sum()
    mt  = df1.groupby(['imo','voyage_order'])['cargo_transport_work'].sum().reset_index()
    mt  = df1.groupby(['imo','voyage_order'])['cargo_transport_work'].sum().reset_index()
#     EEOIData['mt']=fuel_ls['cargo_transport_work']
#     EEOIData['tue']=fuel_ls['teu_transport_work']

    
    finaldata['fuelkg/nm'] = round(((finaldata['equivalent_hfo'] * 1000) / finaldata['distance_x']), 2)
    finaldata['totalco2_kgnm'] =round((finaldata['totalco2_mt'] ) / finaldata['distance_x'], 2)miles by gps sum
    finaldata['equivalent_hfo'] = round((finaldata['hfo_total'] + (finaldata['lfo_total'] + finaldata['MDO_MGO_total'])* 1.05 ), 2)
    finaldata['eeoi_mt'] = round((round(finaldata['totalco2_mt'],2) * 10 ** 6) / round(finaldata['mt_x'],2), 2)
    finaldata['eeoi_teu'] = round((round(finaldata['totalco2_mt'],2) * 10 ** 6 )/ round(finaldata['teu'],2), 2)
    finaldata['eeoi_mt'] =pd.to_numeric(finaldata['eeoi_mt'])
    finaldata['eeoi_teu']=pd.to_numeric(finaldata['eeoi_teu'])

In [ ]:
    # finaldata=pd.merge(finaldata, eeoigoal,how='left', left_on=['imo'], right_on = ['vesselname'])
    finaldata['voyages']=finaldata['imo'].count()
    
    finaldata['average_perteu'] = round(finaldata['cargoteu'] / pd.to_numeric(finaldata['voyages']),2)
    finaldata['average_permt'] = round(finaldata['cargomt'] / pd.to_numeric(finaldata['voyages']),2)
    finaldata['average_distance'] = round(finaldata['distance_x'] / pd.to_numeric(finaldata['voyages']),2)
    finaldata['average_fuelcons'] =round( finaldata['equivalent_hfo'] / pd.to_numeric(finaldata['voyages']),2)

In [45]:
finaldata

,imo,voyages,totalco2,totalco2_mt,hfo_total,lfo_total,MDO_MGO_total,equivalent_hfo,distance_x,fuelkg/nm,totalco2_kgnm,mt_x,teu,eeoi_mt,eeoi_teu,average_perteu,average_permt,average_distance,average_fuelcons
0,9625932,11692,0.00,273576.76,3873.191,75666.198,7203.169,90886.03,1368918.87,66.39,0.2,0.0,0.0,inf,inf,NaN,8.59,117.08,7.77
1,9625944,11692,14.18,273576.76,3873.191,75666.198,7203.169,90886.03,1368918.87,66.39,0.2,39116840.0,0.0,6993.84,inf,NaN,0.00,117.08,7.77
2,9625944,11692,0.00,273576.76,3873.191,75666.198,7203.169,90886.03,1368918.87,66.39,0.2,0.0,0.0,inf,inf,NaN,0.00,117.08,7.77
3,9625944,11692,0.00,273576.76,3873.191,75666.198,7203.169,90886.03,1368918.87,66.39,0.2,38763700.0,0.0,7057.55,inf,NaN,0.00,117.08,7.77
4,9625944,11692,1.89,273576.76,3873.191,75666.198,7203.169,90886.03,1368918.87,66.39,0.2,0.0,0.0,inf,inf,NaN,0.00,117.08,7.77
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11687,9625932,11692,NaN,273576.76,3873.191,75666.198,7203.169,90886.03,1368918.87,66.39,0.2,NaN,NaN,NaN,NaN,0.0,0.00,117.08,7.77
11688,9625932,11692,NaN,273576.76,3873.191,75666.198,7203.169,90886.03,1368918.87,66.39,0.2,NaN,NaN,NaN,NaN,0.0,0.00,117.08,7.77
11689,9625932,11692,NaN,273576.76,3873.191,75666.198,7203.169,90886.03,1368918.87,66.39,0.2,NaN,NaN,NaN,NaN,0.0,0.00,117.08,7.77
11690,9625932,11692,NaN,273576.76,3873.191,75666.198,7203.169,90886.03,1368918.87,66.39,0.2,NaN,NaN,NaN,NaN,0.0,0.00,117.08,7.77
11691,9625932,11692,NaN,273576.76,3873.191,75666.198,7203.169,90886.03,1368918.87,66.39,0.2,NaN,NaN,NaN,NaN,0.0,0.00,117.08,7.77

In [46]:
finaldata.to_excel('EEOIF9.xlsx')