In [1]:
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
import numpy as np

"/Users/Ann Mary Thomas/Downloads/MSC/VESSEL DETAILS/ALL_VESSELS_IMO-IDVESSEL.xlsx"

In [2]:
all_imo = pd.read_excel("/Users/Ann Mary Thomas/Downloads/2. MSC/VESSEL DETAILS/ALL_VESSELS_IMO-IDVESSEL.xlsx",sheet_name = 'Sheet1')
all_imo

    Vessel_Name (NEW) ID VESSEL      IMO  Fleet          CLASS
0           ANASTASIA      ANAS  9625970    9.0      ANASTASIA
1         MSC AURELIA      AURE  7602120    4.0        AURELIA
2           GNV ATLAS      GATL  8712520    4.0          ATLAS
3         GNV AZZURRA      GAZZ  7826790    2.0     GNV AZZURA
4          JOLLY BLUE      JBLU  9180205   11.0  JOLLY EXPRESS
..                ...       ...      ...    ...            ...
551      MSC BEIRA IV      MBRA  9477309    8.0          BEIRA
552       MSC CANDIDA      CADD  9946714   16.0    MSC CANDIDA
553   MSC POLONIA III      MPOL  9219379   17.0        POLONIA
554         MSC FREYA      FRYA  9932062   22.0          FREYA
555         MSC RONIT      RONI  8905878    NaN            NaN

[556 rows x 5 columns]

In [3]:
#unique.to_excel("/Users/Ann Mary Thomas/Downloads/unique.xlsx")

In [6]:
ada_file = pd.read_csv("ELECTRICALREPORTS.csv")
ada_file

,idvessel,YEAR,MODEL,AE_TG_SG_PPACK,RATED_CAPACITY_Kw,LAST_TESTED_LOAD_Kw,LOAD_LAST_TESTED_Perc,MAX_CONT_LOADING_POSSIBLE_UPTO,REMARKS,updated_date
0,ERMI,2017-01-01,Shinko _,Turbo Generator,1200,360.0,30.0,0.30,can safely take 30_ load,2020-02-18 11:11:13
1,MESS,2017-01-01,Nishishiba _,Shaft Generator,900,400.0,44.0,0.50,can safety take 50_,2020-02-18 11:11:13
2,MESS,2017-01-01,Shinko _,Turbo Generator,870,400.0,46.0,0.50,can safety take 50_,2020-02-18 11:11:13
3,GRAC,2017-01-01,SKL _ 8VD 26_20,Auxillary Engine 1,720,400.0,56.0,0.57,Maker_s restrictions set at 57 _.,2020-02-18 11:11:13
4,GRAC,2017-01-01,SKL _ 6VD 26_20,Auxillary Engine 3,530,300.0,57.0,0.57,Maker_s restrictions set at 57 _.,2020-02-18 11:11:13
...,...,...,...,...,...,...,...,...,...,...
65565,ANCO,2023-11-01,Warstila - 9l20,Auxillary Engine 3,1530,700.0,45.0,0.80,NaN,2023-12-28 16:00:58
65566,JUSC,2023-11-01,DOOSAN-MAN - 7 L32/40,Auxillary Engine 1,3000,2370.0,79.0,0.80,NaN,2023-12-29 16:01:09
65567,JUSC,2023-11-01,DOOSAN-MAN - 7 L32/40,Auxillary Engine 2,3000,2500.0,83.0,0.80,NaN,2023-12-29 16:01:09
65568,JUSC,2023-11-01,DOOSAN-MAN - 7 L32/40,Auxillary Engine 3,3000,2047.0,68.0,0.80,NaN,2023-12-29 16:01:09
65569,JUSC,2023-11-01,DOOSAN-MAN - 7 L32/40,Auxillary Engine 4,3000,1900.0,63.0,0.80,NaN,2023-12-29 16:01:09

In [7]:
dict_imo = pd.Series(all_imo['IMO'].values,index=all_imo['ID VESSEL']).to_dict()
ada_file['imo'] = np.nan
ada_file['imo'] = ada_file['imo'].fillna(ada_file['idvessel'].apply(lambda x: dict_imo.get(x)))
ada_file

,idvessel,YEAR,MODEL,AE_TG_SG_PPACK,RATED_CAPACITY_Kw,LAST_TESTED_LOAD_Kw,LOAD_LAST_TESTED_Perc,MAX_CONT_LOADING_POSSIBLE_UPTO,REMARKS,updated_date,imo
0,ERMI,2017-01-01,Shinko _,Turbo Generator,1200,360.0,30.0,0.30,can safely take 30_ load,2020-02-18 11:11:13,9043756.0
1,MESS,2017-01-01,Nishishiba _,Shaft Generator,900,400.0,44.0,0.50,can safety take 50_,2020-02-18 11:11:13,9074042.0
2,MESS,2017-01-01,Shinko _,Turbo Generator,870,400.0,46.0,0.50,can safety take 50_,2020-02-18 11:11:13,9074042.0
3,GRAC,2017-01-01,SKL _ 8VD 26_20,Auxillary Engine 1,720,400.0,56.0,0.57,Maker_s restrictions set at 57 _.,2020-02-18 11:11:13,8918057.0
4,GRAC,2017-01-01,SKL _ 6VD 26_20,Auxillary Engine 3,530,300.0,57.0,0.57,Maker_s restrictions set at 57 _.,2020-02-18 11:11:13,8918057.0
...,...,...,...,...,...,...,...,...,...,...,...
65565,ANCO,2023-11-01,Warstila - 9l20,Auxillary Engine 3,1530,700.0,45.0,0.80,NaN,2023-12-28 16:00:58,9259379.0
65566,JUSC,2023-11-01,DOOSAN-MAN - 7 L32/40,Auxillary Engine 1,3000,2370.0,79.0,0.80,NaN,2023-12-29 16:01:09,9450351.0
65567,JUSC,2023-11-01,DOOSAN-MAN - 7 L32/40,Auxillary Engine 2,3000,2500.0,83.0,0.80,NaN,2023-12-29 16:01:09,9450351.0
65568,JUSC,2023-11-01,DOOSAN-MAN - 7 L32/40,Auxillary Engine 3,3000,2047.0,68.0,0.80,NaN,2023-12-29 16:01:09,9450351.0
65569,JUSC,2023-11-01,DOOSAN-MAN - 7 L32/40,Auxillary Engine 4,3000,1900.0,63.0,0.80,NaN,2023-12-29 16:01:09,9450351.0

In [8]:
ada_file['imo'].isna().sum()

46

In [9]:
ada_file[ada_file['imo'].isnull()]

,idvessel,YEAR,MODEL,AE_TG_SG_PPACK,RATED_CAPACITY_Kw,LAST_TESTED_LOAD_Kw,LOAD_LAST_TESTED_Perc,MAX_CONT_LOADING_POSSIBLE_UPTO,REMARKS,updated_date,imo
34691,JAMI,2021-05-01,Yanmar - 8N21AL-GL,Auxillary Engine 1,1300,NaN,NaN,NaN,NaN,2021-06-11 16:00:50,NaN
34692,JAMI,2021-05-01,Yanmar - 8N21AL-GL,Auxillary Engine 2,1300,NaN,NaN,NaN,NaN,2021-06-11 16:00:50,NaN
34693,JAMI,2021-05-01,Yanmar - 8N21AL-GL,Auxillary Engine 3,1300,NaN,NaN,NaN,NaN,2021-06-11 16:00:50,NaN
34694,JAMI,2021-05-01,Yanmar - 8N21AL-GL,Auxillary Engine 4,1300,NaN,NaN,NaN,NaN,2021-06-11 16:00:50,NaN
35776,JAMI,2021-06-01,Yanmar - 8N21AL-GL,Auxillary Engine 1,1300,NaN,NaN,NaN,NaN,2021-06-23 16:00:31,NaN
35777,JAMI,2021-06-01,Yanmar - 8N21AL-GL,Auxillary Engine 2,1300,NaN,NaN,NaN,NaN,2021-06-23 16:00:31,NaN
35778,JAMI,2021-06-01,Yanmar - 8N21AL-GL,Auxillary Engine 3,1300,NaN,NaN,NaN,NaN,2021-06-23 16:00:31,NaN
35779,JAMI,2021-06-01,Yanmar - 8N21AL-GL,Auxillary Engine 4,1300,NaN,NaN,NaN,NaN,2021-06-23 16:00:31,NaN
36901,JAMI,2021-07-01,Yanmar - 8N21AL-GL,Auxillary Engine 1,1300,NaN,NaN,NaN,NaN,2021-07-15 12:00:33,NaN
36902,JAMI,2021-07-01,Yanmar - 8N21AL-GL,Auxillary Engine 2,1300,NaN,NaN,NaN,NaN,2021-07-15 12:00:33,NaN
36903,JAMI,2021-07-01,Yanmar - 8N21AL-GL,Auxillary Engine 3,1300,NaN,NaN,NaN,NaN,2021-07-15 12:00:33,NaN
36904,JAMI,2021-07-01,Yanmar - 8N21AL-GL,Auxillary Engine 4,1300,NaN,NaN,NaN,NaN,2021-07-15 12:00:33,NaN
38078,JAMI,2021-08-01,Yanmar - 8N21AL-GL,Auxillary Engine 1,1300,NaN,NaN,NaN,NaN,2021-08-16 12:00:31,NaN
38079,JAMI,2021-08-01,Yanmar - 8N21AL-GL,Auxillary Engine 2,1300,NaN,NaN,NaN,NaN,2021-08-16 12:00:31,NaN
38080,JAMI,2021-08-01,Yanmar - 8N21AL-GL,Auxillary Engine 3,1300,NaN,NaN,NaN,NaN,2021-08-16 12:00:31,NaN
38081,JAMI,2021-08-01,Yanmar - 8N21AL-GL,Auxillary Engine 4,1300,NaN,NaN,NaN,NaN,2021-08-16 12:00:31,NaN
39311,JAMI,2021-09-01,Yanmar - 8N21AL-GL,Auxillary Engine 1,1300,NaN,NaN,NaN,NaN,2021-10-15 16:00:33,NaN
39312,JAMI,2021-09-01,Yanmar - 8N21AL-GL,Auxillary Engine 2,1300,NaN,NaN,NaN,NaN,2021-10-15 16:00:33,NaN
39313,JAMI,2021-09-01,Yanmar - 8N21AL-GL,Auxillary Engine 3,1300,NaN,NaN,NaN,NaN,2021-10-15 16:00:33,NaN
39314,JAMI,2021-09-01,Yanmar - 8N21AL-GL,Auxillary Engine 4,1300,NaN,NaN,NaN,NaN,2021-10-15 16:00:33,NaN
40512,JAMI,2021-10-01,Yanmar - 8N21AL-GL,Auxillary Engine 1,1300,NaN,NaN,NaN,NaN,2021-11-12 16:01:01,NaN
40513,JAMI,2021-10-01,Yanmar - 8N21AL-GL,Auxillary Engine 2,1300,NaN,NaN,NaN,NaN,2021-11-12 16:01:01,NaN
40514,JAMI,2021-10-01,Yanmar - 8N21AL-GL,Auxillary Engine 3,1300,NaN,NaN,NaN,NaN,2021-11-12 16:01:01,NaN
40515,JAMI,2021-10-01,Yanmar - 8N21AL-GL,Auxillary Engine 4,1300,NaN,NaN,NaN,NaN,2021-11-12 16:01:01,NaN
41770,JAMI,2021-11-01,Yanmar - 8N21AL-GL,Auxillary Engine 1,1300,NaN,NaN,NaN,Not under Fleet 14,2021-12-17 20:00:41,NaN
41771,JAMI,2021-11-01,Yanmar - 8N21AL-GL,Auxillary Engine 2,1300,NaN,NaN,NaN,Not under Fleet 14,2021-12-17 20:00:41,NaN
41772,JAMI,2021-11-01,Yanmar - 8N21AL-GL,Auxillary Engine 3,1300,NaN,NaN,NaN,Not under Fleet 14,2021-12-17 20:00:41,NaN
41773,JAMI,2021-11-01,Yanmar - 8N21AL-GL,Auxillary Engine 4,1300,NaN,NaN,NaN,Not under Fleet 14,2021-12-17 20:00:41,NaN
62279,e01015,2023-09-01,Daihatsu - 8DC-32e,Auxillary Engine 1,3320,NaN,NaN,NaN,NaN,2023-10-09 16:01:12,NaN
62280,e01015,2023-09-01,Daihatsu - 8DC-32e,Auxillary Engine 2,3320,NaN,NaN,NaN,NaN,2023-10-09 16:01:12,NaN
62281,e01015,2023-09-01,Daihatsu - 8DC-32e,Auxillary Engine 3,3320,NaN,NaN,NaN,NaN,2023-10-09 16:01:12,NaN
62282,e01015,2023-09-01,Daihatsu - 8DC-32e,Auxillary Engine 4,3320,NaN,NaN,NaN,NaN,2023-10-09 16:01:12,NaN
62830,e01015,2023-10-01,Daihatsu - 8DC-32e,Auxillary Engine 1,3320,NaN,NaN,NaN,NaN,2023-11-06 16:01:07,NaN
62831,e01015,2023-10-01,Daihatsu - 8DC-32e,Auxillary Engine 2,3320,NaN,NaN,NaN,NaN,2023-11-06 16:01:07,NaN
62832,e01015,2023-10-01,Daihatsu - 8DC-32e,Auxillary Engine 3,3320,NaN,NaN,NaN,NaN,2023-11-06 16:01:07,NaN
62833,e01015,2023-10-01,Daihatsu - 8DC-32e,Auxillary Engine 4,3320,NaN,NaN,NaN,NaN,2023-11-06 16:01:07,NaN
64437,e01015,2023-11-01,Daihatsu - 8DC-32e,Auxillary Engine 1,3320,2040.0,61.0,NaN,NaN,2023-12-08 16:01:30,NaN
64438,e01015,2023-11-01,Daihatsu - 8DC-32e,Auxillary Engine 2,3320,2040.0,61.0,NaN,NaN,2023-12-08 16:01:30,NaN
64439,e01015,2023-11-01,Daihatsu - 8DC-32e,Auxillary Engine 3,3320,1966.0,59.0,NaN,NaN,2023-12-08 16:01:30,NaN
64440,e01015,2023-11-01,Daihatsu - 8DC-32e,Auxillary Engine 4,3320,2104.0,63.0,NaN,NaN,2023-12-08 16:01:30,NaN
65306,ALLE,2023-09-01,STX Engine Co Ltd - 6L32/40,Auxillary Engine 1,2800,NaN,NaN,NaN,NaN,2023-12-22 16:01:07,NaN
65307,ALLE,2023-09-01,STX Engine Co Ltd - 9L32/40,Auxillary Engine 2,4300,NaN,NaN,NaN,NaN,2023-12-22 16:01:07,NaN
65451,CHARTE,2023-09-01,HYUNDAI MAN B&W - 8L28/32H,Auxillary Engine 1,1600,NaN,NaN,NaN,NaN,2023-12-22 16:01:08,NaN
65452,CHARTE,2023-09-01,HYUNDAI MAN B&W - 8L28/32H,Auxillary Engine 2,1600,NaN,NaN,NaN,NaN,2023-12-22 16:01:08,NaN
65475,fd15b6,2023-09-01,test - test,Auxillary Engine 1,620,NaN,NaN,NaN,NaN,2023-12-22 16:01:08,NaN
65476,fd15b6,2023-09-01,test1 - test,Auxillary Engine 2,506,NaN,NaN,NaN,NaN,2023-12-22 16:01:08,NaN

In [10]:
ada_file.to_csv("ELECTRICALREPORTS_05-01-2024.csv",index = False)

In [17]:
all_2021 = pd.read_csv("ME_file_01_11_2023.csv")
all_2021

,id,insert_datetime,VESSEL,Date,Filename,Location,imo
0,34836,2023-11-01 13:31:20,MSC VIDISHA R,25-10-23,WARTSILA_MSC_VIDISHA_R_(10_25_2023).html,msc_vessels_new/MSC VIDISHA R/WARTSILA_MSC_VID...,9227326.0
1,34837,2023-11-01 13:31:20,MSC MADHU B,28-10-23,MSC_ME_Performance_MSC_MADHU_B_(10_28_2023).html,msc_vessels_new/MSC MADHU B/MSC_ME_Performance...,9778088.0
2,34838,2023-11-01 13:31:20,MSC DON GIOVANNI,27-10-23,MSC_ME_Performance_MSC_DON_GIOVANNI_(10_27_202...,msc_vessels_new/MSC DON GIOVANNI/MSC_ME_Perfor...,9102746.0
3,34839,2023-11-01 13:31:21,MSC FATMA,12-10-23,MSC_ME_Performance_MSC_FATMA_(10_12_2023)_(2)....,msc_vessels_new/MSC FATMA/MSC_ME_Performance_M...,9927251.0
4,34840,2023-11-01 13:31:21,MSC TEXAS,24-10-23,MSC_ME_Performance_MSC_TEXAS_(10_24_2023).html,msc_vessels_new/MSC TEXAS/MSC_ME_Performance_M...,9318058.0
...,...,...,...,...,...,...,...
97,34933,2023-11-01 14:44:09,MSC ULSAN III,16-10-23,MSC_ME_Performance_MSC_ULSAN_III_(16_10_2023)....,msc_vessels_new/MSC ULSAN III/MSC_ME_Performan...,9305001.0
98,34934,2023-11-01 14:44:09,MSC MALENA,22-10-23,WARTSILA_MSC_MALENA_(22_10_2023).html,msc_vessels_new/MSC MALENA/WARTSILA_MSC_MALENA...,9203538.0
99,34935,2023-11-01 14:44:09,MSC MAGALI,25-10-23,MSC_ME_Performance_MSC_MAGALI_(25_10_23).html,msc_vessels_new/MSC MAGALI/MSC_ME_Performance_...,9625932.0
100,34936,2023-11-01 14:44:10,MSC ADRIANA II,25-10-23,MSC_ME_Performance_MSC_ADRIANA_II_(10_25_2023)...,msc_vessels_new/MSC ADRIANA II/MSC_ME_Performa...,9169055.0
101,34937,2023-11-01 14:44:10,MSC CORNELIA,22-10-23,MSC_ME_Performance_MSC_CORNELIA__(22_10_2023)....,msc_vessels_new/MSC CORNELIA/MSC_ME_Performanc...,9426817.0

In [20]:
all_2022 = pd.read_csv("ME_file.csv")
all_2022

,id,insert_datetime,VESSEL,Date,Filename,Location
0,34999,2023-11-15 09:38:37,MSC REN V,25-10-23,WARTSILA_MSC_REN_V_(10_25_2023).html,msc_vessels_new/MSC REN V/WARTSILA_MSC_REN_V_(...
1,35000,2023-11-15 09:38:38,MSC SHAHAR,05-11-23,MSC_ME_Performance_MSC_SHAHAR_(11_05_2023).html,msc_vessels_new/MSC SHAHAR/MSC_ME_Performance_...
2,35001,2023-11-15 09:38:38,MSC JUSTICE VIII,30-10-23,MSC_ME_Performance_MSC_JUSTICE_VIII_(10_30_202...,msc_vessels_new/MSC JUSTICE VIII/MSC_ME_Perfor...
3,35002,2023-11-15 09:38:38,MSC PAMIRA III,28-10-23,WARTSILA_MSC_Pamira_III_(10_28_2023).html,msc_vessels_new/MSC PAMIRA III/WARTSILA_MSC_Pa...
4,35003,2023-11-15 09:38:39,MSC TUXPAN,11-11-23,MSC_ME_Performance_MSC_TUXPAN_(11_11_2023).html,msc_vessels_new/MSC TUXPAN/MSC_ME_Performance_...
...,...,...,...,...,...,...
155,35154,2023-11-15 11:57:15,MSC AAYA,08-11-23,MSC_ME_Performance_MSC_AAYA_(11_08_2023).html,msc_vessels_new/MSC AAYA/MSC_ME_Performance_MS...
156,35155,2023-11-15 11:57:15,MSC MARGRIT,26-10-23,MSC_ME_Performance_MSC_MARGRIT_(26.10.2023).html,msc_vessels_new/MSC MARGRIT/MSC_ME_Performance...
157,35156,2023-11-15 11:57:15,MSC MANYA,25-10-23,MSC_ME_Performance_MANYA_(25_10_2023).html,msc_vessels_new/MSC MANYA/MSC_ME_Performance_M...
158,35157,2023-11-15 11:57:16,MSC AMERICA III,26-10-23,WARTSILA_MSC_AMERICA_(10_26_2023).html,msc_vessels_new/MSC AMERICA III/WARTSILA_MSC_A...
159,35158,2023-11-15 14:29:10,MSC EDITH,10-11-23,MSC_ME2_Performance_MSC_EDITH_(10_11_2023).html,msc_vessels_new/MSC EDITH/MSC_ME2_Performance_...

In [21]:
dict_imo = pd.Series(all_2021['imo'].values,index=all_2021['VESSEL']).to_dict()
all_2022['imo'] = np.nan
all_2022['imo'] = all_2022['imo'].fillna(all_2022['VESSEL'].apply(lambda x: dict_imo.get(x)))
all_2022

,id,insert_datetime,VESSEL,Date,Filename,Location,imo
0,34999,2023-11-15 09:38:37,MSC REN V,25-10-23,WARTSILA_MSC_REN_V_(10_25_2023).html,msc_vessels_new/MSC REN V/WARTSILA_MSC_REN_V_(...,NaN
1,35000,2023-11-15 09:38:38,MSC SHAHAR,05-11-23,MSC_ME_Performance_MSC_SHAHAR_(11_05_2023).html,msc_vessels_new/MSC SHAHAR/MSC_ME_Performance_...,NaN
2,35001,2023-11-15 09:38:38,MSC JUSTICE VIII,30-10-23,MSC_ME_Performance_MSC_JUSTICE_VIII_(10_30_202...,msc_vessels_new/MSC JUSTICE VIII/MSC_ME_Perfor...,NaN
3,35002,2023-11-15 09:38:38,MSC PAMIRA III,28-10-23,WARTSILA_MSC_Pamira_III_(10_28_2023).html,msc_vessels_new/MSC PAMIRA III/WARTSILA_MSC_Pa...,NaN
4,35003,2023-11-15 09:38:39,MSC TUXPAN,11-11-23,MSC_ME_Performance_MSC_TUXPAN_(11_11_2023).html,msc_vessels_new/MSC TUXPAN/MSC_ME_Performance_...,9289972.0
...,...,...,...,...,...,...,...
155,35154,2023-11-15 11:57:15,MSC AAYA,08-11-23,MSC_ME_Performance_MSC_AAYA_(11_08_2023).html,msc_vessels_new/MSC AAYA/MSC_ME_Performance_MS...,9927263.0
156,35155,2023-11-15 11:57:15,MSC MARGRIT,26-10-23,MSC_ME_Performance_MSC_MARGRIT_(26.10.2023).html,msc_vessels_new/MSC MARGRIT/MSC_ME_Performance...,NaN
157,35156,2023-11-15 11:57:15,MSC MANYA,25-10-23,MSC_ME_Performance_MANYA_(25_10_2023).html,msc_vessels_new/MSC MANYA/MSC_ME_Performance_M...,NaN
158,35157,2023-11-15 11:57:16,MSC AMERICA III,26-10-23,WARTSILA_MSC_AMERICA_(10_26_2023).html,msc_vessels_new/MSC AMERICA III/WARTSILA_MSC_A...,NaN
159,35158,2023-11-15 14:29:10,MSC EDITH,10-11-23,MSC_ME2_Performance_MSC_EDITH_(10_11_2023).html,msc_vessels_new/MSC EDITH/MSC_ME2_Performance_...,9169029.0

In [22]:
all_2022['imo'].isna().sum()

135

In [16]:
all_2022.to_csv("ME_file_17_11_2023.csv", index = False)

In [18]:
all_2022

,id,insert_datetime,VESSEL,Date,Filename,Location,imo
0,34836,2023-11-01 13:31:20,MSC VIDISHA R,25-10-23,WARTSILA_MSC_VIDISHA_R_(10_25_2023).html,msc_vessels_new/MSC VIDISHA R/WARTSILA_MSC_VID...,9227326.0
1,34837,2023-11-01 13:31:20,MSC MADHU B,28-10-23,MSC_ME_Performance_MSC_MADHU_B_(10_28_2023).html,msc_vessels_new/MSC MADHU B/MSC_ME_Performance...,9778088.0
2,34838,2023-11-01 13:31:20,MSC DON GIOVANNI,27-10-23,MSC_ME_Performance_MSC_DON_GIOVANNI_(10_27_202...,msc_vessels_new/MSC DON GIOVANNI/MSC_ME_Perfor...,9102746.0
3,34839,2023-11-01 13:31:21,MSC FATMA,12-10-23,MSC_ME_Performance_MSC_FATMA_(10_12_2023)_(2)....,msc_vessels_new/MSC FATMA/MSC_ME_Performance_M...,9927251.0
4,34840,2023-11-01 13:31:21,MSC TEXAS,24-10-23,MSC_ME_Performance_MSC_TEXAS_(10_24_2023).html,msc_vessels_new/MSC TEXAS/MSC_ME_Performance_M...,9318058.0
...,...,...,...,...,...,...,...
97,34933,2023-11-01 14:44:09,MSC ULSAN III,16-10-23,MSC_ME_Performance_MSC_ULSAN_III_(16_10_2023)....,msc_vessels_new/MSC ULSAN III/MSC_ME_Performan...,9305001.0
98,34934,2023-11-01 14:44:09,MSC MALENA,22-10-23,WARTSILA_MSC_MALENA_(22_10_2023).html,msc_vessels_new/MSC MALENA/WARTSILA_MSC_MALENA...,9203538.0
99,34935,2023-11-01 14:44:09,MSC MAGALI,25-10-23,MSC_ME_Performance_MSC_MAGALI_(25_10_23).html,msc_vessels_new/MSC MAGALI/MSC_ME_Performance_...,9625932.0
100,34936,2023-11-01 14:44:10,MSC ADRIANA II,25-10-23,MSC_ME_Performance_MSC_ADRIANA_II_(10_25_2023)...,msc_vessels_new/MSC ADRIANA II/MSC_ME_Performa...,9169055.0
101,34937,2023-11-01 14:44:10,MSC CORNELIA,22-10-23,MSC_ME_Performance_MSC_CORNELIA__(22_10_2023)....,msc_vessels_new/MSC CORNELIA/MSC_ME_Performanc...,9426817.0

In [ ]:
sep = all_2022