In [1]:
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
import numpy as np

In [2]:
data = pd.read_excel(r"D:\Navalt\MSC\2024\Weekly Data\CLIENT\Month Client data\Lim_Dec.xlsx")

In [4]:
# data = data[data['DateTimeUtc'] >= '2024-04-01 00:00:00']
# data

In [7]:
def find_outliers(data, column, lower_bound, upper_bound):
    outliers = data[(data[column] > upper_bound) | (data[column] < lower_bound)][['ImoNumber', 'vName', 'DateTimeUtc', column]].copy()
    outliers['outlier'] = column
    outliers.rename(columns={column: 'value'}, inplace=True)
    return outliers

# List of columns with their bounds and labels
outlier_conditions = [
    ('CargoMT', 0, 300000),
    ('CargoTEU', 0, 25000),
    ('DraftAft', 0, 30),
    ('DraftFwd', 0, 30),
    ('Speed by gps', 0, 50),
    ('Speed by log', 0, 50),
    ('Power_AE_1', 0, 7000),
    ('Power_AE_2', 0, 7000),
    ('Power_AE_3', 0, 7000),
    ('Power_AE_4', 0, 7000),
    ('Power_AE_5', 0, 7000),
    ('Power_ME', 0, 100000),
    ('RPM', 0, 750),
    ('Miles by gps', 0, 1000),
    ('Slip', -100, 100),
    ('Sea state', 0, 10),
    ('Hours_AE_1', 0, 26),
    ('Hours_AE_2', 0, 26),
    ('Hours_AE_3', 0, 26),
    ('Hours_AE_4', 0, 26),
    ('Hours_AE_5', 0, 26),
    ('Hours_ME', 0, 26),
    ('Hours_SG', 0, 26),
    ('Hours_TG', 0, 26)
]

outliers_list = [find_outliers(data, col, lb, ub) for col, lb, ub in outlier_conditions]

all_outliers = pd.concat(outliers_list, ignore_index=True)

outliers = all_outliers[['ImoNumber', 'vName', 'DateTimeUtc', 'outlier', 'value']]


outliers

   ImoNumber       vName         DateTimeUtc outlier  value
0    9181651  MSC INGRID 2024-12-06 02:00:00    Slip  180.1

# Update the DraftAft column in the original data where the value is too high (e.g., >30)
data.loc[data['DraftAft'] > 70, 'DraftAft'] = data.loc[data['DraftAft'] > 70, 'DraftAft'] / 100

In [10]:
#Rename the client file column to our old db columns name
data= data.rename(columns = {"MessagesId":"GID",
"DateTimeLt":"REPORT DATE TIME",
"vName":"VSL",
"ImoNumber":"IMO No",
"DateTimeUtc":"Corrected Date",
"MessageType":"Report Type",
"Latitude":"LAT",
"Longitude":"LONG",
"CargoMT":"CARGO TOTAL",
"Hours_ME":'M_E_Fuel_Only_Steaming_Time',
"Miles by gps":"MILES BY GPS",
"Oil Cylinder":"OIL CYL",
"Speed by log":"SPEED BY LOG",
"Speed by gps":"SPEED BY GPS",
"RPM":"RPM",
"Slip":"SLIP",
"Wind direction":"WIND DIRECTION",
"Wind speed":"WIND SPEED",
"DraftAft":"DRAFT AFT",
"DraftFwd":"DRAFT FWD",
"Displacement":"DISPLACEMENT",
"Course at Sea":"COURSE AT SEA",
"Wave height":"WAVE HEIGHT",
"SEA DIRECTION":"SEA DIRECTION",
"CargoTEU":"CARGO TOTAL TEU",
"Ambient temp":"AMBIENT TEMP",
"Sw temp":"SW TEMP",
"Miles speed log":"MILES BY SPEED LOG",
"ETA Port Code":"ETA PORT CODE",
"ETA Date/Time":"ETA DATE TIME",
"ETA Port Name":"ETA PORT",
"Time change":"TIME CHANGE",
"Time sea":"TIME SEA",
"Requested speed":"REQUESTED SPEED",
"Reefers positive plugged":"REEFERS POSITIVE PLUGGED",
"Reefers negative plugged":"REEFERS NEGATIVE PLUGGED",
"Me total revs counter":"ME TOTAL REVS COUNTER",
"Port Code":"PORT CODE",
"Port Name":"PORT",
"Time hrs. anchor":"TIME HRS ANCHOR",
"Time hrs. drift":"TIME HRS DRIFT",
"Reason":"REASON",
"Type of delay":"TYPE OF DELAY",
"ETB Date/Time":"ETB DATE TIME",
"Time manoeuvring":"TIME MANOEUVRING",
"Estimated departure date/time":"ETD DATE TIME",
"Shift berth hours":"SHIFT BERTH HOURS",
"TEU Full":"TEU FULL",
"TEU Empty":"TEU EMPTY",
"Bilge removed":"BILGE REMOVED",
"Fresh water supply":"FW SUPPLY",
"Steaming time m/e residual vls":"STEAMING TIME M E Rsdl VLS",
"Steaming time m/e residual hs":"STEAMING TIME M E Rsdl HS",
"Steaming time m/e residual uls":"STEAMING TIME M E Rsdl ULS",
"Steaming time m/e distillate vls":"STEAMING TIME M E Dstlt VLS",
"Steaming time m/e distillate uls":"STEAMING TIME M E Dstlt ULS",
"Hours_AE_1":"STEAMING TIME AUX 1",
"Hours_AE_2":"STEAMING TIME AUX 2",
"Hours_AE_3":"STEAMING TIME AUX 3",
"Hours_AE_4":"STEAMING TIME AUX 4",
"Hours_AE_5":"STEAMING TIME AUX 5",
"Hours_SG":"STEAMING TIME SH GEN",
"Hours_TG":"STEAMING TIME TG",
"FOC_ME_RES_VLS":"FUEL M E Rsdl VLS",
"FOC_ME_RES_HS":"FUEL M E Rsdl HS",
"FOC_ME_RES_ULS":"FUEL M E Rsdl ULS",
"FOC_ME_DIS_VLS":"FUEL M E Dstlt VLS",
"FOC_ME_DIS_ULS":"FUEL M E Dstlt ULS",
"FOC_ME_LNG":"FUEL M E LNG",
"FOC_ME_DIS":"FUEL M E Tnktnr Dstlt VLS",
"FOC_AE_RES_VLS":"FUEL Aux Rsdl VLS",
"FOC_AE_RES_HS":"FUEL Aux Rsdl HS",
"FOC_AE_RES_ULS":"FUEL Aux Rsdl ULS",
"FOC_AE_DIS_VLS":"FUEL Aux Dstlt VLS",
"FOC_AE_DIS_ULS":"FUEL Aux Dstlt ULS",
"FOC_AE_DIS":"FUEL Aux Tnktnr Dstlt VLS",
"FOC_AE_LNG":"FUEL Aux LNG",
"FOC_BLR_RES_VLS":"FUEL Boiler Rsdl VLS",
"FOC_BLR_RES_HS":"FUEL Boiler Rsdl HS",
"FOC_BLR_RES_ULS":"FUEL Boiler Rsdl ULS",
"FOC_BLR_DIS_VLS":"FUEL Boiler Dstlt VLS",
"FOC_BLR_DIS_ULS":"FUEL Boiler Dstlt ULS",
"FOC_BLR_DIS":"FUEL Boiler Tnktnr Dstlt VLS",
"FOC_BLR_LNG":"FUEL Boiler LNG",
"Power_ME":"POWER KW",
"Power_AE_1":"STEAMING LOAD KW AUX 1",
"Power_AE_2":"STEAMING LOAD KW AUX 2",
"Power_AE_3":"STEAMING LOAD KW AUX 3",
"Power_AE_4":"STEAMING LOAD KW AUX 4",
"Power_AE_5":"STEAMING LOAD KW AUX 5",
"Power_SG":"STEAMING LOAD KW SH GEN",
"Power_TG":"STEAMING LOAD KW TG",
"Scavenge pressure":"SCAVENGE PRESSURE",
"Rob fresh water":"ROB FRESH WATER",
"Manoeuvring miles by gps":"MANVRNG MILES BY GPS",
"Manoeuvring miles by speed log":"MANVRNG MILES BY SPEED LOG",
"Ballast":"BALLAST",
"Number of Tanktainer":"TANKTAINER NUMBER",
"Rob actual bilge":"ROB BILGE",
"Sea state":"SEA STATE",
"So2/co2 ratio":"SO2 CO2 RATIO",
"Bunker Order":"Bunker Order",
"Bdn number":"BDN Number",
"Product Name":"Fuel Type",
"Sulfur content":"Sulphur Content PC",
"Quantity":"Quantity",
"Port bunkering":"Port Delivery",
"Tanktainer number":"Tanktainer Number_1",
"Physical supplier name":"Supplier",
"Volume":"Vol Lt",
"Density at 15Â°C":"Den",
"Viscosity at 40Â°C or 50Â°C":"Vis",
"ROB_DIS_ULS":"ROB Dstlt ULS",
"ROB_DIS_VLS":"ROB Dstlt VLS",
"ROB_DIS":"ROB Tnktnr Dstlt VLS",
"ROB_RES_VLS":"ROB Rsdl VLS",
"ROB_RES_HS":"ROB Rsdl HS",
"ROB_RES_ULS":"ROB Rsdl ULS",
"ROB_LNG":"ROB Rsdl LNG",
"Eca miles":"ECA MILES",
"Eca time":"ECA TIME",
"Egcs dry waste removed":"EGCS DRY WASTE REMOVED",
"Egcs running time":"EGCS RUNNING TIME",
"Egcs wet waste removed":"EGCS WET SLURRY REMOVED",
"Egcs open loop running time":"EGCS OPEN LOOP RUNNING TIME",
"Egcs closed loop running time":"EGCS CLOSED LOOP RUNNING TIME"})

In [22]:
import pandas as pd


charter_data = pd.read_excel('charter_vessels_dec.xlsx')  # Adjust as needed
sorrento_data = pd.read_excel('sorrento_vessels_dec.xlsx')  # Adjust as needed

# Assuming the IMO number column in charter data is named 'imo' and in noon data is also named 'imo'
charter_imos = charter_data['IMO']
noon_imos = data['IMO No']
sorrento_imos = sorrento_data['IMO']

# Check which charter and Sorrento IMO numbers are in the noon data
charter_in_noon = charter_imos[charter_imos.isin(noon_imos)]
sorrento_in_noon = sorrento_imos[sorrento_imos.isin(noon_imos)]

# Display the results
print("IMO numbers from charter data that are also in noon data:")
print(charter_in_noon)

print("\nIMO numbers from Sorrento data that are also in noon data:")
print(sorrento_in_noon)

IMO numbers from charter data that are also in noon data:
14     9618305.0
16     9135638.0
17     9618317.0
101    9143879.0
110    9256365.0
Name: IMO, dtype: float64

IMO numbers from Sorrento data that are also in noon data:
0    9618264
5    9618290
Name: IMO, dtype: int64

data = data.drop(columns=['Unnamed: 0'])

In [26]:
data['REPORT DATE TIME Offset'] = 'UTC' + data['REPORT DATE TIME'].str[-6:]

In [28]:
data.columns.tolist()

['GID',
 'IMO No',
 'VSL',
 'Report Type',
 'REPORT DATE TIME',
 'Corrected Date',
 'LAT',
 'LONG',
 'CARGO TOTAL',
 'CARGO TOTAL TEU',
 'DRAFT AFT',
 'DRAFT FWD',
 'SPEED BY GPS',
 'SPEED BY LOG',
 'FUEL Aux Tnktnr Dstlt VLS',
 'FUEL Aux LNG',
 'FUEL Aux Rsdl HS',
 'FUEL Aux Rsdl ULS',
 'FUEL Aux Rsdl VLS',
 'FUEL Boiler Tnktnr Dstlt VLS',
 'FUEL Boiler LNG',
 'FUEL Boiler Rsdl HS',
 'FUEL Boiler Rsdl ULS',
 'FUEL Boiler Rsdl VLS',
 'FUEL M E Tnktnr Dstlt VLS',
 'FUEL M E LNG',
 'FUEL M E Rsdl HS',
 'FUEL M E Rsdl ULS',
 'FUEL M E Rsdl VLS',
 'STEAMING TIME AUX 1',
 'STEAMING TIME AUX 2',
 'STEAMING TIME AUX 3',
 'STEAMING TIME AUX 4',
 'STEAMING TIME AUX 5',
 'M_E_Fuel_Only_Steaming_Time',
 'STEAMING TIME SH GEN',
 'STEAMING TIME TG',
 'STEAMING LOAD KW AUX 1',
 'STEAMING LOAD KW AUX 2',
 'STEAMING LOAD KW AUX 3',
 'STEAMING LOAD KW AUX 4',
 'STEAMING LOAD KW AUX 5',
 'POWER KW',
 'STEAMING LOAD KW SH GEN',
 'STEAMING LOAD KW TG',
 'ROB Tnktnr Dstlt VLS',
 'ROB Rsdl LNG',
 'ROB Rsdl HS',
 'ROB Rsdl ULS',
 'ROB Rsdl VLS',
 'Max Residual HS capacity',
 'Max Lng capacity',
 'Min Lng request',
 'Tanktainer Number_1',
 'Tanktainer min request',
 'Template version',
 'Port Delivery',
 'TANKTAINER ROB',
 'Comments',
 'Fuel Type',
 'Supplier',
 'Vol Lt',
 'Quantity',
 'Den',
 'Vis',
 'Sulphur Content PC',
 'Bunker Order',
 'BDN Number',
 'PORT CODE',
 'PORT',
 'Pilot date/time',
 'PIER date/time',
 'TIME MANOEUVRING',
 'DISPLACEMENT',
 'ETD DATE TIME',
 'TANKTAINER NUMBER',
 'MANVRNG MILES BY GPS',
 'MANVRNG MILES BY SPEED LOG',
 'Kwhr total',
 'Hold ventilation off',
 'REEFERS POSITIVE PLUGGED',
 'REEFERS NEGATIVE PLUGGED',
 'ME TOTAL REVS COUNTER',
 'ROB FRESH WATER',
 'EGCS RUNNING TIME',
 'SO2 CO2 RATIO',
 'Rob tot Sludge',
 'BALLAST',
 'EGCS CLOSED LOOP RUNNING TIME',
 'EGCS OPEN LOOP RUNNING TIME',
 'Reefer power consumption',
 'Rob Ajustment HS',
 'Rob Adjustment VLS',
 'Rob Adjustment ULS',
 'Rob Adjustment Dist',
 'Rob Adjustment LNG',
 'Drydock2',
 'Rob Tanktainer adjustment',
 'WIND DIRECTION',
 'MILES BY GPS',
 'STEAMING TIME M/E RESIDUAL HS',
 'RPM',
 'SLIP',
 'ETA PORT CODE',
 'ETA PORT',
 'ETA DATE TIME',
 'WIND SPEED',
 'COURSE AT SEA',
 'WAVE HEIGHT',
 'SEA STATE',
 'AMBIENT TEMP',
 'SW TEMP',
 'MILES BY SPEED LOG',
 'REQUESTED SPEED',
 'TIME CHANGE',
 'TIME SEA',
 'kwhr total',
 'SCAVENGE PRESSURE',
 'SEA DIRECTION',
 'ECA MILES',
 'ECA TIME',
 'Steaming time m/e lng',
 'Drydock',
 'TEU FULL',
 'TEU EMPTY',
 'FW SUPPLY',
 'Tanktainer distillates transfd',
 'Hold Ventilation On/Off',
 'BILGE REMOVED',
 'Tot sludge removed',
 'Garbage cat a - plastic removed',
 'Garbage cat b - organic removed',
 'Garbage cat c - domestic removed',
 'Garbage cat e - ashes removed',
 'Rob garbage cat a - plastic',
 'Rob garbage cat b - organic',
 'Rob garbage cat c - domestic',
 'Rob garbage cat e - ashes',
 'EGCS WET SLURRY REMOVED',
 'EGCS DRY WASTE REMOVED',
 'Total Number of pax on board',
 'Total Number of vehicles on board',
 'TYPE OF DELAY',
 'REASON',
 'TIME HRS ANCHOR',
 'TIME HRS DRIFT',
 'Eta date/time',
 'Sludge rob',
 'Sludge min discharge request',
 'OIL CYL',
 'DryDock',
 'ETB DATE TIME',
 'STEAMING TIME M E Rsdl HS',
 'STEAMING TIME M E Rsdl ULS',
 'STEAMING TIME M E Rsdl VLS',
 'Rpm',
 'SHIFT BERTH HOURS',
 'ROB fresh water',
 'Rob actual sludge',
 'ROB BILGE',
 'Qty sludge disposed',
 'REPORT DATE TIME Offset']

In [30]:
data.shape

(8243, 162)

In [32]:
duplicate_gid = data[data.duplicated(subset='GID', keep=False)]

In [34]:
data.shape

(8243, 162)

In [36]:
data = data.drop_duplicates(subset=['GID'],keep='first')

In [38]:
data['Corrected Date'].dtypes

dtype('<M8[ns]')

In [40]:
data.shape

(8243, 162)

In [42]:
import pandas as pd
import re

# Replace "?" with NaN in the "IMO No" column using regular expressions
data['IMO No'] = data['IMO No'].replace(r'^\?$', pd.NA, regex=True)

# Remove rows with invalid values in the "IMO No" column
data['IMO No'] = pd.to_numeric(data['IMO No'], errors='coerce')

# Fill NaN values with 0
data['IMO No'] = data['IMO No'].fillna(0)

# Convert the column to integer
data['IMO No'] = data['IMO No'].astype(int)

In [44]:
noon=data

In [46]:
import pandas as pd

# List of IMO numbers to be removed
imo_to_remove = [9618305, 9143879, 9256365, 9618317, 9135638, 9618264, 9618290]

# Assuming the column name for IMO numbers is 'IMO'
noon = noon[~noon['IMO No'].isin(imo_to_remove)]

# Save the filtered dataframe to a new CSV file

In [48]:
noon.shape

(8089, 162)

In [50]:
noon['IMO No'].nunique()

532

In [52]:
#THese columns are not there in client file but there in our db so create a column and save it as nan file 
columns = ["VOY","Status","M E FOC","Has Cargo","Total M E Hours Fuel Only","ETA DATE TIME Offset","TEMP MIN","TEMP MAX","REM DIST TO PILOT","REM TIME TO PILOT","TOTAL UNPLND STPGE TECH","TOTAL UNPLND STPGE OPE WX","AUX BLOWERS ON","HOLD VENTILATION ON","ETB DATE TIME Offset","PILOT DATE TIME","PILOT DATE TIME Offset","TUG ARR","TUG SHIFT","ETD DATE TIME Offset","CARGO LOAD","CARGO DISCH","GARBAGE REMOVED","GARBAGE REMVL REQSTD","GARBAGE REMVL CMPLSRY","CY CREW SIGNED ON","CY CREW SIGNED OFF","CY DOCTORS VISIT","CY MAIL RECEIVED Ref NO","CY LUB OIL SAMPLE LANDED","CY CHECKD FOR STOWAWAYS","CY STOWAWAYS ON BOARD","CY DEP GM Mtr","CY REQUISITIONS RECEIVED","DISTANCE TO NEXT PILOT","TUG SAILING TRANSIT","STEAMING TIME M E Tnktnr Dstlt VLS","FUEL M E MDO","FUEL Aux MDO","FUEL Boiler MDO","DECK LAST CHANGE USER","ENGINE LAST CHANGE USER","DECK PART IS COMPLETE","ENGINE PART IS COMPLETE","SECA ENTRY TIME","SECA ENTRY LAT","SECA ENTRY LONG","SECA EXIT TIME","SECA EXIT LAT","SECA EXIT LONG","TANKTAINER TRANSFD QUANTITY","PILOT TAKEN","DATE TIME START TRANSIT","DATE TIME START TRANSIT Offset","DATE TIME END TRANSIT","DATE TIME END TRANSIT Offset","STEAMING KWHR TOTAL","CY OTHERS","ROB FO SLUDGE","ROB LO SLUDGE","SLUDGE REMOVED FO","SLUDGE REMOVED LO","CY LUB ADDED TO SYSTEM MECC","CY LUB ADDED TO SYSTEM AECC","CY LUB ADDED TO THRUSTERS","CY ME LO PURIFIER IN USE","CY BALLAST","CY BENDING MOMENT","CY SHEARING FORCE","CY TORTION MOMENT","CY SUPDT AUDITOR SIGNED ON","CY SUPDT AUDITOR SIGNED OFF","CY CASH RECEIVED","CY LUB OIL RECEIVED MECYL","CY LUB OIL RECEIVED MECC","CY LUB OIL RECEIVED AECC","CY M E UNDER PISTON TEMP","CY MAIL RECEIVED","WIND DIRECTION PORT STBD","SEA DIRECTION PORT STBD","TIME PILOT ONBOARD","GRADES ROB","Remarks","Carbon Factor","Product Quality","Delivery","ROB Rsdl MDO",'STEAMING TIME M E Dstlt ULS','STEAMING TIME M E Dstlt VLS','FUEL M E Dstlt VLS','FUEL M E Dstlt ULS','FUEL Aux Dstlt VLS','FUEL Aux Dstlt ULS','FUEL Boiler Dstlt VLS','FUEL Boiler Dstlt ULS','ROB Dstlt VLS','ROB Dstlt ULS']
noon[columns] = np.nan

In [54]:
#Replicating the columns
#noon['REPORT DATE TIME Offset'] = noon['REPORT DATE TIME']  
noon['STEAMING TIME M E HS'] = noon['STEAMING TIME M E Rsdl HS']  
noon['STEAMING TIME M E LS'] = noon[['STEAMING TIME M E Rsdl ULS','STEAMING TIME M E Rsdl VLS']].sum(axis=1)
noon['STEAMING TIME M E MGO'] = noon[['STEAMING TIME M E Dstlt VLS','STEAMING TIME M E Tnktnr Dstlt VLS']].sum(axis=1)
noon['STEAMING TIME M E MGO LS'] = noon['STEAMING TIME M E Dstlt ULS']
noon['FUEL M E HS'] = noon['FUEL M E Rsdl HS']
noon['FUEL M E LS'] = noon[['FUEL M E Rsdl VLS','FUEL M E Rsdl ULS']].sum(axis=1)
noon['FUEL M E MGO'] = noon[['FUEL M E Dstlt VLS','FUEL M E Tnktnr Dstlt VLS']].sum(axis=1)
noon['FUEL M E MGO LS'] = noon['FUEL M E Dstlt ULS']
noon['FUEL Aux HS'] = noon['FUEL Aux Rsdl HS']
noon['FUEL Aux LS'] = noon[['FUEL Aux Rsdl VLS','FUEL Aux Rsdl ULS']].sum(axis=1)
noon['FUEL Aux MGO'] = noon[['FUEL Aux Dstlt VLS','FUEL Aux Tnktnr Dstlt VLS']].sum(axis=1)
noon['FUEL Aux MGO LS'] = noon['FUEL Aux Dstlt ULS']
noon['FUEL Boiler HS'] = noon['FUEL Boiler Rsdl HS']
noon['FUEL Boiler LS'] = noon[['FUEL Boiler Rsdl VLS','FUEL Boiler Rsdl ULS']].sum(axis=1)
noon['FUEL Boiler MGO'] = noon[['FUEL Boiler Dstlt VLS','FUEL Boiler Tnktnr Dstlt VLS']].sum(axis=1)
noon['FUEL Boiler MGO LS'] = noon['FUEL Boiler Dstlt ULS']
noon['ROB FUEL HSFO'] = noon['ROB Rsdl HS']
noon['ROB FUEL LSFO'] = noon[['ROB Rsdl VLS','ROB Rsdl ULS']].sum(axis=1)
noon['ROB FUEL MDO'] = noon['ROB Rsdl MDO']
noon['ROB FUEL MGO'] = noon['ROB Dstlt VLS']
noon['ROB FUEL MGO LS'] = noon['ROB Dstlt ULS']
noon['ROB FUEL Tanktainer MGO'] = noon['ROB Tnktnr Dstlt VLS']

In [56]:
#add 'SINCE_DATE_TIME','SINCE_DATE_TIME_Offset' columns as null value
import numpy as np
noon['SINCE_DATE_TIME'] = np.nan
noon['SINCE_DATE_TIME_Offset'] = np.nan

In [58]:
# Dictionary mapping old vessel names to new vessel names
vessel_name_mapping= {
    'MSC SAO PAULO V': 'MSC SAO PAULO',
    'MSC ANISHA R.': 'MSC ANISHA R',
    'MSC ARUSHI R.': 'MSC ARUSHI R',
    'MSC JULIA R.': 'MSC JULIA R',
    'MSC LEANDRA V': 'MSC LEANDRA',
    'MSC VAISHNAVI R.': 'MSC VAISHNAVI R',
    'MSC VIDISHA R.': 'MSC VIDISHA R',
    'MSC ZLATA R.': 'MSC ZLATA R',
    'MSC ATLANTIC III': 'MSC ATLANTIC',
    'NORTHERN JUSTICE': 'MSC JUSTICE VIII',
    'MSC AMERICA': 'MSC AMERICA III',
    'MSC SARAH': 'MSC SARAH V',
    'MSC SINGAPORE': 'MSC SINGAPORE IV',
    'REN JIAN 9': 'MSC REN V',
    'MSC KATYA R.': 'MSC KATYA R',
    'MSC BREMERHAVEN': 'MSC BREMERHAVEN V',
    'MSC UBERTY': 'MSC UBERTY VIII',
    'MSC HOUSTON': 'MSC HOUSTON V',
    'MSC NASSAU': 'MSC NASSAU IV',
    'MSC DHANTIA': 'MSC DHANTIA F',
    'MSC JORDAN': 'MSC JORDAN III',
    'MSC SILVANA': 'MSC SILVANA VIII',
    'MSC ELEONORA': 'MSC ELEONORA III',
    'MSC LEA': 'MSC LEA II',
    'MSC MARYLENA': 'MSC MARYLENA II',
    'MSC MIRELLA': 'MSC MIRELLA R',
    'MSC VIDISHA R.': 'MSC VIDISHA R',
    'MSC MAGNITUDE VII': 'MSC MAGNITUDE',
    'MSC MANDY': 'MSC MANDY III',
    'MSC BHAVYA': 'MSC BHAVYA V',
    'MSC SAMANTHA': 'MSC SAMANTHA VI',
    'MSC PEGASUS': 'MSC PEGASUS VII',
    'MSC KOREA': 'MSC KOREA III',
    'MSC CANBERRA': 'MSC CANBERRA III',
}
 
 
# Replace the vessel names in the 'VSL' column using the dictionary
noon['VSL'] = noon['VSL'].replace(vessel_name_mapping)
 
# Verify the changes
print(noon['VSL'].unique())

In [60]:
#fleetclass = pd.read_excel(r"D:\Navalt\MSC\2023\Weekly Data\FLEETCLASS\AFTER UPDATION\Fleetclass_40.xlsx",sheet_name = "Sheet2")
#fleetclass
fleetclass = pd.read_excel(r"D:\Navalt\Files\ALL_VESSELS_IMO-IDVESSEL.xlsx")
fleetclass

    Vessel_Name (NEW) ID VESSEL      IMO  Fleet          CLASS
0           ANASTASIA      ANAS  9625970    9.0      ANASTASIA
1         MSC AURELIA      AURE  7602120    4.0        AURELIA
2           GNV ATLAS      GATL  8712520    4.0          ATLAS
3         GNV AZZURRA      GAZZ  7826790    2.0     GNV AZZURA
4          JOLLY BLUE      JBLU  9180205   11.0  JOLLY EXPRESS
..                ...       ...      ...    ...            ...
565     MSC VICTORINE      VICT  9946867   16.0      VICTORINE
566       MSC ABIDJAN      ABID  9618264    NaN            NaN
567      MSC ADELAIDE     ADELA  9618290    NaN            NaN
568        MSC ATHENS      ATHE  9618305    NaN            NaN
569         MSC ATHOS      ATHO  9618317    NaN            NaN

[570 rows x 5 columns]

In [61]:
#in this id classs is there in fleet class but in our noon soo we should do a dictiornary for tha prticular imo 
dictidvessel = pd.Series(fleetclass['ID VESSEL'].values,index=fleetclass['IMO']).to_dict()
dictidvessel

{9625970: 'ANAS',
 7602120: 'AURE',
 8712520: 'GATL',
 7826790: 'GAZZ',
 9180205: 'JBLU',
 9180190: 'JOLL',
 8512906: 'ADEL',
 9235581: 'ADIT',
 9169055: 'ADRI',
 9057173: 'AGAT',
 9618276: 'AGRI',
 9770751: 'AINO',
 9123166: 'ALAB',
 9618288: 'ALGH',
 9232632: 'ALIC',
 9166651: 'ALIX',
 9842097: 'ALIY',
 9465277: 'ALTA',
 9319600: 'AMAN',
 9008603: 'AMER',
 9242651: 'AMY',
 9227297: 'ANIS',
 8521402: 'ANMA',
 9169122: 'ANNI',
 9282261: 'ANS',
 9702273: 'ANTL',
 9398216: 'ANTO',
 9297864: 'ANYA',
 9710426: 'ANZU',
 9619452: 'ARIC',
 9857169: 'ARIE',
 9839284: 'ARIN',
 9244881: 'ARUS',
 9162631: 'ASLI',
 9263344: 'ASTR',
 8913447: 'ATLA',
 8512891: 'AUGU',
 9756729: 'AVNI',
 9263332: 'BANU',
 9203904: 'BELL',
 9297876: 'BHAV',
 9770749: 'BIAN',
 9720495: 'BRAN',
 9103685: 'BRIA',
 9138783: 'BRID',
 9702106: 'BRUN',
 9169043: 'CAIT',
 9102722: 'CANB',
 9154220: 'CAPR',
 9625944: 'CARI',
 9124512: 'CARL',
 9756731: 'CATA',
 9295397: 'CRLN',
 9705005: 'CATE',
 9316361: 'CELI',
 9710438: 'CHAN',
 9194866: 'CHER',
 8420892: 'CHIA',
 9720483: 'CHLO',
 9113446: 'CLAU',
 9720524: 'CLEA',
 9301550: 'CLEM',
 9307267: 'CORI',
 9453298: 'CRIS',
 9465241: 'CRIA',
 9250983: 'DAML',
 8509375: 'DENI',
 9720201: 'DOMI',
 9102746: 'DGIO',
 9237151: 'DONA',
 9110391: 'DYMP',
 9169029: 'EDTH',
 9282259: 'ELA',
 9236688: 'ELBE',
 9278143: 'ELNI',
 9064750: 'ELEO',
 9463059: 'ELIS',
 9735218: 'ELMA',
 9704972: 'ELOD',
 8917778: 'ELOI',
 9123221: 'ELSA',
 9463047: 'EMMA',
 9232890: 'ENGL',
 9043756: 'ERMI',
 9004231: 'ESHA',
 8201648: 'EYRA',
 9842085: 'FAIT',
 8715869: 'FEDE',
 9369758: 'FIMT',
 8413875: 'GABR',
 9770763: 'GAYA',
 9152856: 'GIAN',
 9720196: 'GISE',
 9770737: 'GIUL',
 8918057: 'GRAC',
 9316347: 'HANN',
 9127540: 'HIMA',
 9062984: 'HINA',
 9124366: 'IMMA',
 9463205: 'IMCL',
 9231248: 'IDID',
 9181651: 'INGR',
 8201624: 'IRIS',
 9839272: 'ISBL',
 9154206: 'ISHY',
 9134490: 'JANI',
 9110975: 'JAP',
 8420907: 'JASM',
 9135638: 'JEAN',
 9051478: 'JEMI',
 9000742: 'JENN',
 9720471: 'JEON',
 9842073: 'JEWE',
 8918980: 'JORD',
 9842061: 'JOSS',
 9039250: 'JOY',
 9227338: 'JULI',
 9704996: 'JLIE',
 9842102: 'KANO',
 9227302: 'KATA',
 9110389: 'KATY',
 9123154: 'KORE',
 9051507: 'KRIT',
 9193719: 'LANA',
 9064748: 'LARA',
 9162643: 'LEA',
 9347762: 'LENA',
 9702065: 'LETI',
 8608200: 'LEVI',
 9704960: 'LILY',
 8413887: 'LUCI',
 9251690: 'HPAF',
 9308625: 'LUNA',
 9778088: 'MADH',
 9625932: 'MAGA',
 8201636: 'MALI',
 8918966: 'MAND',
 9238789: 'MANU',
 9275397: 'MANY',
 9238741: 'MARG',
 9465318: 'MAGT',
 9067544: 'MARI',
 8616520: 'MARL',
 9155107: 'MARP',
 9169031: 'MARY',
 9188219: 'MASH',
 9181663: 'MATI',
 9720287: 'MAXI',
 9102710: 'MEDI',
 9702077: 'MELI',
 9074042: 'MESS',
 9169067: 'MIAS',
 9720512: 'MICH',
 9062996: 'MILA',
 9839260: 'MINA',
 9293179: 'MIRL',
 9060649: 'MONI',
 9149328: 'NDRL',
 9704984: 'NAOM',
 9463035: 'NASH',
 8918954: 'NEDE',
 9839296: 'NELA',
 9278155: 'NERI',
 8509387: 'NICO',
 9051492: 'NILG',
 9308584: 'NINA',
 9084607: 'NITA',
 9778117: 'NITY',
 9398228: 'NOA',
 9857157: 'ORIO',
 9281267: 'ORNE',
 9735206: 'PALA',
 9161297: 'PAOL',
 9267637: 'PEGA',
 9503732: 'PERL',
 9267649: 'PHOE',
 8715871: 'PILA',
 9154191: 'POSI',
 9309447: 'RANI',
 9139505: 'REBE',
 9465306: 'RENE',
 9224051: 'RHIA',
 9038907: 'ROBE',
 9141297: 'ROCH',
 9745653: 'ROMA',
 9293167: 'RONR',
 9502960: 'RUBY',
 8714205: 'SABR',
 9110377: 'SAMA',
 8913411: 'SANT',
 9147071: 'SPAO',
 9702261: 'SARE',
 9181675: 'SARA',
 8715857: 'SARI',
 9720500: 'SASH',
 9116369: 'SENA',
 8913423: 'SHAN',
 9036002: 'SHAU',
 9180968: 'SHEI',
 9224049: 'SHIR',
 9778105: 'SHRE',
 9778076: 'SHUB',
 9309459: 'SIVN',
 9720457: 'SILV',
 9839301: 'SIXI',
 9702091: 'SOCE',
 8918978: 'SUEZ',
 9308601: 'TALI',
 9351579: 'TAMA',
 9008574: 'TASM',
 9193680: 'TIA',
 9502908: 'TOPA',
 9163192: 'UMA',
 9227340: 'VAIS',
 9251688: 'VANE',
 9465265: 'VEGA',
 9238739: 'VIDH',
 9227326: 'VIDI',
 9857171: 'VIRG',
 9702089: 'VITA',
 9236690: 'WESE',
 9778090: 'YASH',
 9227314: 'ZLAT',
 9326940: 'WCOR',
 9354363: 'WECM',
 9246566: 'WVGO',
 9237371: 'WEVE',
 9226932: 'BARB',
 9857183: 'AURI',
 9289087: 'BUSA',
 9215672: 'JESS',
 9210098: 'SINE',
 9337444: 'UBER',
 9299537: 'CHAR',
 9189366: 'TAVV',
 9289099: 'BEIJ',
 9293442: 'SHRI',
 9203538: 'MALE',
 9217565: 'PANA',
 9299525: 'TORO',
 9350317: 'HERM',
 9295165: 'DAIS',
 9383223: 'LIDI',
 9318058: 'TEXA',
 9305477: 'TIAN',
 9318046: 'TOKY',
 9330238: 'CHRL',
 9334349: 'LILO',
 9793947: 'SIYA',
 9285691: 'VANC',
 9365984: 'WVEY',
 9285665: 'YOKO',
 9222302: 'PETR',
 9316373: 'TANI',
 9222106: 'SAMU',
 9305489: 'TIPG',
 9210086: 'CAPU',
 9334844: 'KYME',
 9896983: 'APOL',
 9435820: 'MANO',
 9242637: 'KAYL',
 9166778: 'ABY',
 9166780: 'ELLE',
 9408774: 'OLIA',
 9439735: 'LANG',
 9334832: 'EMIL',
 9376141: 'POLI',
 9724049: 'BRIT',
 9228576: 'NILA',
 9287792: 'VANR',
 9146479: 'VILD',
 9160982: 'DHAN',
 9232644: 'NIKO',
 9695028: 'SOPA',
 9695016: 'ALIN',
 9144134: 'RION',
 9270828: 'TIPH',
 9322011: 'YOSH',
 9235610: 'VERA',
 9344564: 'YURI',
 9261827: 'ANCM',
 9392561: 'SHNV',
 9369734: 'BREM',
 9215892: 'ELIZ',
 9330226: 'ABIG',
 9232656: 'KTLN',
 9224946: 'IDA',
 9235608: 'JUAN',
 9301328: 'DORI',
 9108398: 'TNAF',
 9434462: 'SMRA',
 9896995: 'AMEL',
 9471238: 'SHAR',
 9336359: 'OLGA',
 9287900: 'MACL',
 9240328: 'PATN',
 9230775: 'TRAD',
 9305506: 'KUMS',
 9426817: 'COLA',
 9307839: 'NAIS',
 9315006: 'WVRN',
 9393321: 'ELIN',
 9419644: 'RINI',
 9315836: 'VAIG',
 9330240: 'SIGM',
 9139086: 'POLO',
 9309411: 'HARM',
 9403437: 'AZRT',
 9302085: 'ANHT',
 9393022: 'SHAY',
 9471226: 'ALBM',
 9315018: 'WDHG',
 9259393: 'SOTI',
 9785445: 'CARO',
 9241463: 'CORC',
 9253014: 'CORD',
 9374571: 'EXPR',
 9315915: 'MATT',
 9366421: 'MOON',
 9239903: 'PAMI',
 9236224: 'REET',
 9231822: 'SHGI',
 9232462: 'WVEF',
 9227285: 'YANG',
 9403396: 'CANC',
 9231810: 'HOKO',
 9318773: 'ELKE',
 9440306: 'MELT',
 9222120: 'ANDR',
 9401776: 'ACAP',
 9190119: 'ADA',
 9785483: 'ALAN',
 9341122: 'ALDI',
 9241475: 'BALT',
 9360271: 'CAPE',
 9120853: 'FIE',
 9631876: 'GUER',
 9433157: 'JENR',
 9622007: 'JRSY',
 9330264: 'LVNT',
 9785457: 'RYMI',
 9449869: 'RCRD',
 9242625: 'VNQS',
 9162277: 'TRKY',
 9289960: 'MNZL',
 9317937: 'TAMP',
 9289972: 'TUXP',
 9287924: 'VRCZ',
 9327803: 'LBTR',
 9706310: 'ADON',
 9449687: 'AMIH',
 9262560: 'DIAM',
 9190092: 'EAGL',
 9326823: 'EMDE',
 9236444: 'EMLY',
 9232773: 'GIAD',
 9304459: 'LISB',
 9236212: 'MAKO',
 9231779: 'MEXI',
 9294991: 'MUMB',
 9294989: 'MUND',
 9456965: 'ODES',
 9280861: 'PRAT',
 9235402: 'RADI',
 9491616: 'SAGI',
 9239733: 'SAND',
 9210050: 'STAR',
 9259381: 'TARA',
 9147227: 'SUPA',
 9336165: 'HAPA',
 9327798: 'LOTR',
 9262546: 'CLDN',
 9286231: 'EVER',
 9357107: 'GRGA',
 9415296: 'GRTA',
 9127021: 'IZMI',
 9238882: 'MNSF',
 9477610: 'ROWN',
 9248928: 'TGRF',
 9243239: 'ALZE',
 9232395: 'FLOS',
 9231119: 'MADS',
 9240873: 'RESI',
 9908047: 'WASH',
 9436472: 'ZOND',
 9360283: 'AUBE',
 9785469: 'EUGE',
 9241451: 'SARY',
 9301990: 'ADBN',
 9243241: 'DAVA',
 9332729: 'FORT',
 9210062: 'GLOR',
 9275373: 'GREN',
 9347803: 'ANNE',
 9304746: 'ANTR',
 9785471: 'CASS',
 9232761: 'COLE',
 9225251: 'HAIT',
 9290426: 'SNMR',
 9317925: 'TMPA',
 9261815: 'CARD',
 9499010: 'ALBA',
 9289544: 'BADS',
 9301330: 'FRPT',
 9463281: 'HSTN',
 9313943: 'LNDR',
 9301483: 'PRIS',
 9393307: 'RIDA',
 9393319: 'RIKU',
 9401166: 'SGTA',
 9225249: 'SLVR',
 9224348: 'SGPR',
 9347970: 'TKTF',
 9150080: 'BMSR',
 9354416: 'JSTN',
 9306275: 'ANRA',
 9323041: 'ANUS',
 9315379: 'ARCH',
 9313967: 'BRHN',
 9243409: 'BRPT',
 9243394: 'DREN',
 9231250: 'DNMK',
 9306263: 'DIYA',
 9302633: 'FRFD',
 9289051: 'GNIA',
 9236585: 'KANU',
 9467445: 'KATR',
 9160920: 'MRTN',
 9293777: 'NWHN',
 9326768: 'NISH',
 9292175: 'SHNL',
 9231262: 'SWDN',
 9358905: 'TMSK',
 9908059: 'VRGN',
 9219393: 'HELE',
 9346017: 'AMEE',
 9315381: 'AGAM',
 9240952: 'DRAG',
 9141285: 'YUVI',
 9286267: 'GRWH',
 9220328: 'SMYA',
 9295177: 'TRAC',
 9305013: 'CHUL',
 9290402: 'FELI',
 9256315: 'NORD',
 9221059: 'QING',
 9305001: 'ULSN',
 9302619: 'UNIT',
 9302621: 'UTMO',
 9466960: 'JASP',
 9143879: 'LILF',
 9327683: 'MAKA',
 9196864: 'MICG',
 9315886: 'NIMI',
 9401685: 'ORTO',
 9374595: 'ARIA',
 9465253: 'BENE',
 9927251: 'FATM',
 9197545: 'ILLI',
 9200677: 'SYDN',
 9196838: 'YORK',
 9200689: 'DARW',
 9229300: 'CATR',
 9229312: 'MLEO',
 9256327: 'SUED',
 9318187: 'CAGL',
 9326964: 'HALS',
 9927263: 'AAYA',
 9253038: 'CARP',
 9275036: 'JULN',
 9344708: 'GENL',
 9299020: 'PORT',
 9244946: 'KALA',
 9932892: 'MARA',
 9223904: 'SUNF',
 9120841: 'DOMX',
 9316359: 'SPRG',
 9927275: 'SOFI',
 9196852: 'ALMA',
 9237498: 'LIPS',
 9290488: 'NIOV',
 9927287: 'DARI',
 9929429: 'IRIN',
 9930038: 'TESS',
 9146467: 'YUKT',
 9337676: 'ROSH',
 9293466: 'ADUV',
 9226360: 'MAYA',
 9444285: 'DUBA',
 9450296: 'PREC',
 9930052: 'RAYA',
 9934735: 'LORE',
 9288409: 'YAMU',
 9254848: 'ANSH',
 9294824: 'DURB',
 9380271: 'NAGO',
 9168843: 'UNIF',
 9930935: 'BIAS',
 9311737: 'CAPT',
 9927299: 'KAYY',
 9153850: 'GION',
 9330068: 'SURB',
 9450325: 'PREL',
 8521397: 'FLOR',
 8505836: 'GIOV',
 9141780: 'GNNN',
 9148025: 'ANAH',
 9163207: 'NORA',
 8618293: 'VERO',
 9309289: 'BEEX',
 9936616: 'GEMM',
 9450351: 'JUSC',
 9929431: 'MICA',
 9540065: 'AUDY',
 9932036: 'CALY',
 9947110: 'CHIO',
 9252541: 'MAGN',
 9934747: 'MALL',
 9930064: 'NIMA',
 9248148: 'PILV',
 9932048: 'TAYR',
 9932907: 'VICA',
 9930947: 'BERA',
 9256391: 'PAXI',
 9256365: 'TURN',
 9304708: 'VIGO',
 9259379: 'ANCO',
 9399765: 'PASS',
 9400148: 'LYSE',
 9936630: 'METT',
 9168831: 'FLON',
 9946843: 'MNAR',
 9275024: 'SHFF',
 9294408: 'MATN',
 9327671: 'MNOR',
 9930959: 'MDAR',
 9932050: 'MMON',
 9931288: 'MTUR',
 9947122: 'MVIV',
 9936628: 'MCLG',
 9252230: 'MREN',
 9947134: 'MGUS',
 9323493: 'IRAM',
 9540077: 'MMMA',
 9931290: 'MMCO',
 9605243: 'NAIR',
 9936642: 'CHIN',
 9946855: 'VALE',
 9158525: 'MDSL',
 9252553: 'MMTD',
 9326835: 'MHSM',
 9477309: 'MBRA',
 9946714: 'CADD',
 9219379: 'MPOL',
 9932062: 'FRYA',
 8905878: 'RONI',
 9947146: 'ANIT',
 9932919: 'AZRA',
 9360764: 'BASE',
 9362449: 'BERN',
 9930961: 'MONT',
 9962550: 'IVA',
 9946726: 'ORSO',
 9449821: 'ROMI',
 9957347: 'THAI',
 9946867: 'VICT',
 9618264: 'ABID',
 9618290: 'ADELA',
 9618305: 'ATHE',
 9618317: 'ATHO'}

In [64]:
#mapping the imo 
import numpy as np
noon['idvessel'] = np.nan
noon['idvessel'] = noon['idvessel'].fillna(noon['IMO No'].apply(lambda x:dictidvessel.get(x)))
noon

,GID,IMO No,VSL,Report Type,REPORT DATE TIME,Corrected Date,LAT,LONG,CARGO TOTAL,CARGO TOTAL TEU,...,FUEL Boiler MGO LS,ROB FUEL HSFO,ROB FUEL LSFO,ROB FUEL MDO,ROB FUEL MGO,ROB FUEL MGO LS,ROB FUEL Tanktainer MGO,SINCE_DATE_TIME,SINCE_DATE_TIME_Offset,idvessel
0,5843075,8913423,MSC SHANNON III,Powerpack,2024-12-01 00:00:00 +00:00,2024-12-01 00:00:00,NaN,NaN,27908.3,2167.0,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,SHAN
1,5844062,8913447,MSC ATLANTIC,Powerpack,2024-12-01 00:00:00 +00:00,2024-12-01 00:00:00,NaN,NaN,14426.9,1876.0,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,ATLA
2,5842589,8918954,MSC NEDERLAND III,Powerpack,2024-12-01 00:00:00 +00:00,2024-12-01 00:00:00,NaN,NaN,13968.0,1559.0,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NEDE
3,5842699,8918966,MSC MANDY,Powerpack,2024-12-01 00:00:00 +00:00,2024-12-01 00:00:00,NaN,NaN,1245.8,556.0,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,MAND
4,5843666,8918978,MSC SUEZ,Powerpack,2024-12-01 00:00:00 +00:00,2024-12-01 00:00:00,NaN,NaN,14471.8,990.0,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,SUEZ
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8238,5854136,9936642,MSC CHINA,Sludge,2024-12-25 12:00:00 +00:00,2024-12-25 12:00:00,NaN,NaN,141518.0,20053.0,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,CHIN
8239,5854134,9936642,MSC CHINA,Sludge,2024-12-25 12:00:00 +00:00,2024-12-25 12:00:00,NaN,NaN,141518.0,20053.0,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,CHIN
8240,5832965,9360271,MSC CAPE III,Sludge,2024-12-26 07:00:00 +00:00,2024-12-26 07:00:00,NaN,NaN,14042.0,1403.0,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,CAPE
8241,5852452,9243409,MSC BRIDGEPORT,Sludge,2024-12-28 12:00:00 +00:00,2024-12-28 12:00:00,NaN,NaN,60833.0,6650.0,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,BRPT
8242,5853166,9243409,MSC BRIDGEPORT,EGCS Waste,2024-12-29 12:00:00 +00:00,2024-12-29 12:00:00,NaN,NaN,60833.0,6650.0,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,BRPT

In [66]:
#checking if there is null , if there is null check the id class whether the id class is there or not and we should add it
noon['idvessel'].isna().sum()

54

In [68]:
#always should be null if any value comes up add it using code 
null = noon[noon['idvessel'].isnull()]
null

,GID,IMO No,VSL,Report Type,REPORT DATE TIME,Corrected Date,LAT,LONG,CARGO TOTAL,CARGO TOTAL TEU,...,FUEL Boiler MGO LS,ROB FUEL HSFO,ROB FUEL LSFO,ROB FUEL MDO,ROB FUEL MGO,ROB FUEL MGO LS,ROB FUEL Tanktainer MGO,SINCE_DATE_TIME,SINCE_DATE_TIME_Offset,idvessel
169,5843485,9286774,MSC LUCIA III,Port Noon,2024-12-01 12:00:00 +08:00,2024-12-01 04:00:00,NaN,NaN,0.0,0.0,...,NaN,510.52,0.00,NaN,NaN,NaN,229.90,NaN,NaN,None
245,5842233,9222273,MSC BRASILIA VII,Port Noon,2024-12-01 12:00:00 +07:00,2024-12-01 05:00:00,NaN,NaN,12579.9,4590.0,...,NaN,NaN,1115.47,NaN,NaN,NaN,400.54,NaN,NaN,None
353,5842421,9222273,MSC BRASILIA VII,Sailing,2024-12-01 14:42:00 +07:00,2024-12-01 07:42:00,NaN,NaN,38782.9,4590.0,...,NaN,NaN,1113.72,NaN,NaN,NaN,400.54,NaN,NaN,None
469,5843476,9222273,MSC BRASILIA VII,COSP,2024-12-01 17:00:00 +07:00,2024-12-01 10:00:00,1016N,10705E,38782.9,4590.0,...,NaN,NaN,1110.50,NaN,NaN,NaN,400.54,NaN,NaN,None
470,5842715,9222285,MSC SUAPE VII,Port Noon,2024-12-01 12:00:00 +02:00,2024-12-01 10:00:00,NaN,NaN,26622.0,3209.0,...,NaN,NaN,2089.49,NaN,NaN,NaN,440.22,NaN,NaN,None
808,5843495,9962548,MSC ILENIA,Delay,2024-12-01 12:00:00 -03:00,2024-12-01 15:00:00,0818S,03440W,43476.3,7749.0,...,NaN,3405.96,0.00,NaN,NaN,NaN,407.00,NaN,NaN,None
1057,5843868,9320398,MSC LAUSANNE VI,Noon,2024-12-01 12:00:00 -11:00,2024-12-01 23:00:00,2645N,16802W,10757.7,4882.0,...,NaN,NaN,1966.00,NaN,NaN,NaN,395.20,NaN,NaN,None
1278,5845644,9286774,MSC LUCIA III,Port Noon,2024-12-02 12:00:00 +08:00,2024-12-02 04:00:00,NaN,NaN,0.0,0.0,...,NaN,510.52,0.00,NaN,NaN,NaN,226.80,NaN,NaN,None
1355,5844125,9222273,MSC BRASILIA VII,Noon,2024-12-02 12:00:00 +07:00,2024-12-02 05:00:00,0518N,10637E,38782.9,2511.0,...,NaN,NaN,1043.23,NaN,NaN,NaN,400.54,NaN,NaN,None
1590,5844735,9222285,MSC SUAPE VII,Port Noon,2024-12-02 12:00:00 +02:00,2024-12-02 10:00:00,NaN,NaN,26622.0,3209.0,...,NaN,NaN,2080.48,NaN,NaN,NaN,440.22,NaN,NaN,None
1922,5847352,9962548,MSC ILENIA,Delay,2024-12-02 12:00:00 -03:00,2024-12-02 15:00:00,0822S,03439W,43476.3,7749.0,...,NaN,3386.45,0.00,NaN,NaN,NaN,407.00,NaN,NaN,None
2131,5846150,9222273,MSC BRASILIA VII,EOSP,2024-12-03 06:30:00 +08:00,2024-12-02 22:30:00,0201N,10453E,38782.9,2511.0,...,NaN,NaN,1015.33,NaN,NaN,NaN,400.54,NaN,NaN,None
2144,5845953,9320398,MSC LAUSANNE VI,Noon,2024-12-02 12:00:00 -11:00,2024-12-02 23:00:00,2359N,17240W,10757.7,4882.0,...,NaN,NaN,1913.40,NaN,NaN,NaN,395.20,NaN,NaN,None
2316,5846331,9222273,MSC BRASILIA VII,Delay,2024-12-03 12:00:00 +08:00,2024-12-03 04:00:00,0119N,10419E,38782.9,2511.0,...,NaN,NaN,1009.86,NaN,NaN,NaN,400.54,NaN,NaN,None
2337,5847815,9286774,MSC LUCIA III,Port Noon,2024-12-03 12:00:00 +08:00,2024-12-03 04:00:00,NaN,NaN,0.0,0.0,...,NaN,510.52,0.00,NaN,NaN,NaN,223.50,NaN,NaN,None
2645,5846872,9222285,MSC SUAPE VII,Port Noon,2024-12-03 12:00:00 +02:00,2024-12-03 10:00:00,NaN,NaN,26622.0,3209.0,...,NaN,NaN,2070.82,NaN,NaN,NaN,440.22,NaN,NaN,None
2869,5847549,9222273,MSC BRASILIA VII,Berthing,2024-12-03 20:30:00 +08:00,2024-12-03 12:30:00,0121N,10332E,38782.9,2511.0,...,NaN,NaN,997.44,NaN,NaN,NaN,400.54,NaN,NaN,None
2977,5847718,9962548,MSC ILENIA,Delay,2024-12-03 12:00:00 -03:00,2024-12-03 15:00:00,0817S,03438W,43476.3,7749.0,...,NaN,3366.39,0.00,NaN,NaN,NaN,407.00,NaN,NaN,None
3218,5848172,9222273,MSC BRASILIA VII,Sailing,2024-12-04 06:06:00 +08:00,2024-12-03 22:06:00,NaN,NaN,28898.4,2511.0,...,NaN,NaN,992.30,NaN,NaN,NaN,400.54,NaN,NaN,None
3294,5848075,9320398,MSC LAUSANNE VI,Noon,2024-12-04 12:00:00 +12:00,2024-12-04 00:00:00,2436N,17955W,10757.7,4882.0,...,NaN,NaN,1841.80,NaN,NaN,NaN,395.20,NaN,NaN,None
3318,5848207,9222273,MSC BRASILIA VII,COSP,2024-12-04 09:00:00 +08:00,2024-12-04 01:00:00,0118N,10320E,28898.4,2511.0,...,NaN,NaN,989.34,NaN,NaN,NaN,400.54,NaN,NaN,None
3408,5848308,9222273,MSC BRASILIA VII,Noon,2024-12-04 12:00:00 +08:00,2024-12-04 04:00:00,0132N,10305E,28898.4,1395.0,...,NaN,NaN,986.70,NaN,NaN,NaN,400.54,NaN,NaN,None
3428,5849657,9286774,MSC LUCIA III,Port Noon,2024-12-04 12:00:00 +08:00,2024-12-04 04:00:00,NaN,NaN,0.0,0.0,...,NaN,510.52,0.00,NaN,NaN,NaN,220.30,NaN,NaN,None
3758,5849143,9222285,MSC SUAPE VII,Port Noon,2024-12-04 12:00:00 +02:00,2024-12-04 10:00:00,NaN,NaN,26622.0,3209.0,...,NaN,NaN,2061.06,NaN,NaN,NaN,440.22,NaN,NaN,None
4083,5849597,9962548,MSC ILENIA,Delay,2024-12-04 12:00:00 -03:00,2024-12-04 15:00:00,0840S,03450W,43476.3,7749.0,...,NaN,3347.38,0.00,NaN,NaN,NaN,407.00,NaN,NaN,None
4397,5850194,9320398,MSC LAUSANNE VI,Bunker,2024-12-05 00:00:00 +00:00,2024-12-05 00:00:00,NaN,NaN,10757.7,4882.0,...,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,None
4398,5850027,9320398,MSC LAUSANNE VI,Noon,2024-12-05 12:00:00 +12:00,2024-12-05 00:00:00,2436N,17256E,10757.7,4882.0,...,NaN,NaN,1774.80,NaN,NaN,NaN,395.20,NaN,NaN,None
4480,5850292,9222273,MSC BRASILIA VII,EOSP,2024-12-05 11:00:00 +08:00,2024-12-05 03:00:00,0113N,10336E,28898.4,1395.0,...,NaN,NaN,959.46,NaN,NaN,NaN,400.54,NaN,NaN,None
4537,5851589,9286774,MSC LUCIA III,Port Noon,2024-12-05 12:00:00 +08:00,2024-12-05 04:00:00,NaN,NaN,0.0,0.0,...,NaN,510.52,0.00,NaN,NaN,NaN,216.90,NaN,NaN,None
4621,5850343,9222273,MSC BRASILIA VII,Berthing,2024-12-05 13:06:00 +08:00,2024-12-05 05:06:00,0113N,10334E,28898.4,1395.0,...,NaN,NaN,957.59,NaN,NaN,NaN,400.54,NaN,NaN,None
4842,5850775,9222285,MSC SUAPE VII,Port Noon,2024-12-05 12:00:00 +02:00,2024-12-05 10:00:00,NaN,NaN,26622.0,3209.0,...,NaN,NaN,2051.40,NaN,NaN,NaN,440.22,NaN,NaN,None
5157,5851664,9962548,MSC ILENIA,Delay,2024-12-05 12:00:00 -03:00,2024-12-05 15:00:00,0825S,03444W,43476.3,7749.0,...,NaN,3325.07,0.00,NaN,NaN,NaN,407.00,NaN,NaN,None
5429,5851943,9320398,MSC LAUSANNE VI,Bunker,2024-12-06 00:00:00 +00:00,2024-12-06 00:00:00,NaN,NaN,10757.7,4882.0,...,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,None
5462,5851998,9320398,MSC LAUSANNE VI,Noon,2024-12-06 12:00:00 +11:00,2024-12-06 01:00:00,2549N,16538E,10757.7,4882.0,...,NaN,NaN,1708.90,NaN,NaN,NaN,395.20,NaN,NaN,None
5540,5852184,9222273,MSC BRASILIA VII,Port Noon,2024-12-06 12:00:00 +08:00,2024-12-06 04:00:00,NaN,NaN,28898.4,1395.0,...,NaN,NaN,945.29,NaN,NaN,NaN,400.54,NaN,NaN,None
5558,5853300,9286774,MSC LUCIA III,Port Noon,2024-12-06 12:00:00 +08:00,2024-12-06 04:00:00,NaN,NaN,0.0,0.0,...,NaN,510.52,0.00,NaN,NaN,NaN,213.30,NaN,NaN,None
5813,5853016,9222285,MSC SUAPE VII,Sailing,2024-12-06 11:48:00 +02:00,2024-12-06 09:48:00,NaN,NaN,10076.0,3209.0,...,NaN,NaN,2042.02,NaN,NaN,NaN,440.22,NaN,NaN,None
6066,5853197,9962548,MSC ILENIA,Berthing,2024-12-06 10:42:00 -03:00,2024-12-06 13:42:00,0823S,03457W,43476.3,7749.0,...,NaN,3305.64,0.00,NaN,NaN,NaN,405.20,NaN,NaN,None
6131,5853458,9962548,MSC ILENIA,Port Noon,2024-12-06 12:00:00 -03:00,2024-12-06 15:00:00,NaN,NaN,43476.3,7749.0,...,NaN,3305.64,0.00,NaN,NaN,NaN,404.40,NaN,NaN,None
6166,5853617,9222273,MSC BRASILIA VII,Sailing,2024-12-07 00:30:00 +08:00,2024-12-06 16:30:00,NaN,NaN,37163.0,1395.0,...,NaN,NaN,938.39,NaN,NaN,NaN,400.54,NaN,NaN,None
6257,5854002,9222273,MSC BRASILIA VII,COSP,2024-12-07 02:42:00 +08:00,2024-12-06 18:42:00,0110N,10334E,37163.0,1395.0,...,NaN,NaN,935.85,NaN,NaN,NaN,400.54,NaN,NaN,None
6434,5853916,9320398,MSC LAUSANNE VI,Noon,2024-12-07 12:00:00 +11:00,2024-12-07 01:00:00,2624N,15840E,10757.7,4882.0,...,NaN,NaN,1643.90,NaN,NaN,NaN,395.20,NaN,NaN,None
6452,5854580,9222285,MSC SUAPE VII,COSP,2024-12-07 04:00:00 +02:00,2024-12-07 02:00:00,3325S,01736E,10076.0,3209.0,...,NaN,NaN,2025.64,NaN,NaN,NaN,440.22,NaN,NaN,None
6525,5854220,9222273,MSC BRASILIA VII,Noon,2024-12-07 12:00:00 +08:00,2024-12-07 04:00:00,0146N,10536E,37163.0,2035.0,...,NaN,NaN,905.26,NaN,NaN,NaN,400.54,NaN,NaN,None
6542,5856530,9286774,MSC LUCIA III,Port Noon,2024-12-07 12:00:00 +08:00,2024-12-07 04:00:00,NaN,NaN,0.0,0.0,...,NaN,510.52,0.00,NaN,NaN,NaN,209.10,NaN,NaN,None
6831,5854594,9222285,MSC SUAPE VII,Noon,2024-12-07 12:00:00 +02:00,2024-12-07 10:00:00,3429S,01825E,10076.0,4536.0,...,NaN,NaN,2015.62,NaN,NaN,NaN,440.22,NaN,NaN,None
7152,5856476,9962548,MSC ILENIA,Port Noon,2024-12-07 12:00:00 -03:00,2024-12-07 15:00:00,NaN,NaN,43476.3,7749.0,...,NaN,3305.64,0.00,NaN,NaN,NaN,390.10,NaN,NaN,None
7450,5856811,9320398,MSC LAUSANNE VI,Noon,2024-12-08 12:00:00 +10:00,2024-12-08 02:00:00,2700N,15135E,10757.7,4882.0,...,NaN,NaN,1584.40,NaN,NaN,NaN,395.20,NaN,NaN,None
7497,5856863,9222273,MSC BRASILIA VII,Noon,2024-12-08 12:00:00 +08:00,2024-12-08 04:00:00,0505N,11214E,37163.0,2035.0,...,NaN,NaN,798.46,NaN,NaN,NaN,400.54,NaN,NaN,None
7508,5857843,9286774,MSC LUCIA III,Port Noon,2024-12-08 12:00:00 +08:00,2024-12-08 04:00:00,NaN,NaN,0.0,0.0,...,NaN,510.52,0.00,NaN,NaN,NaN,201.50,NaN,NaN,None
7776,5857395,9222285,MSC SUAPE VII,Noon,2024-12-08 12:00:00 +02:00,2024-12-08 10:00:00,3328S,02721E,10076.0,4536.0,...,NaN,NaN,1910.28,NaN,NaN,NaN,440.22,NaN,NaN,None
8001,5857874,9962548,MSC ILENIA,Port Noon,2024-12-08 12:00:00 -03:00,2024-12-08 15:00:00,NaN,NaN,43476.3,7749.0,...,NaN,3305.64,0.00,NaN,NaN,NaN,376.00,NaN,NaN,None
8131,5852259,9222273,MSC BRASILIA VII,Sludge,2024-12-10 12:00:00 +00:00,2024-12-10 12:00:00,NaN,NaN,37163.0,2035.0,...,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,None
8173,5850173,9320398,MSC LAUSANNE VI,Sludge,2024-12-13 11:30:00 +00:00,2024-12-13 11:30:00,NaN,NaN,10757.7,4882.0,...,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,None

In [70]:
null['VSL'].unique()

array(['MSC LUCIA III ', 'MSC BRASILIA VII ', 'MSC SUAPE VII ',
       'MSC ILENIA ', 'MSC LAUSANNE VI '], dtype=object)

In [72]:
#you should update the new column (extra column which is not there in db ) in that server ref updated calculations in Db and we should upload
col = pd.read_excel(r"D:\Navalt\MSC\2023\Weekly Data\SERVER REF\Updated calculations in DB for updated fuel type 1.xlsx")

In [74]:
col_lst = col['Noondata'].tolist()

In [76]:
weekcol = noon.columns.tolist()

In [78]:
#correct column names as per noon Updated calculations in DB for updated fuel type file - noon data
#main difference is _,so replace all space as _
noon.columns = noon.columns.str.replace(' ','_')

In [80]:
noon.rename(columns = {'LONG':'LONG_','SPEED_BY_LOG':'SOW','SPEED_BY_GPS':'SOG','POWER_KW':'POWER_kW','FUEL_Aux_MDO':'FUEL_AUX_MDO','FUEL_Boiler_MDO':'FUEL_BOILER_MDO','FUEL_Aux_HS':'FUEL_AUX_HS','FUEL_Aux_LS':'FUEL_AUX_LS','FUEL_Aux_MGO':'FUEL_AUX_MGO','FUEL_Aux_MGO_LS':'FUEL_AUX_MGO_LS','FUEL_Boiler_HS':'FUEL_BOILER_HS','FUEL_Boiler_LS':'FUEL_BOILER_LS','FUEL_Boiler_MGO':'FUEL_BOILER_MGO','FUEL_Boiler_MGO_LS':'FUEL_BOILER_MGO_LS','ROB_FUEL_HSFO':'ROB_Fuel_HSFO','ROB_FUEL_LSFO':'ROB_Fuel_LSFO','ROB_FUEL_MDO':'ROB_Fuel_MDO','ROB_FUEL_MGO':'ROB_Fuel_MGO','ROB_FUEL_MGO_LS':'ROB_Fuel_MGO_LS','ROB_FUEL_Tanktainer_MGO':'ROB_Fuel_Tanktainer_MGO'}, inplace = True)

In [82]:
#noon.rename(columns = {'LONG':'LONG_','STEAMING_TIME':'TOTAL_STEAMING_TIME','Total_M_E_Hours_Fuel_Only':'M_E_Fuel_Only_Steaming_Time','SPEED_BY_LOG':'SOW','SPEED_BY_GPS':'SOG','POWER_KW':'POWER_kW','FUEL_Aux_MDO':'FUEL_AUX_MDO','FUEL_Boiler_MDO':'FUEL_BOILER_MDO','FUEL_Aux_HS':'FUEL_AUX_HS','FUEL_Aux_LS':'FUEL_AUX_LS','FUEL_Aux_MGO':'FUEL_AUX_MGO','FUEL_Aux_MGO_LS':'FUEL_AUX_MGO_LS','FUEL_Boiler_HS':'FUEL_BOILER_HS','FUEL_Boiler_LS':'FUEL_BOILER_LS','FUEL_Boiler_MGO':'FUEL_BOILER_MGO','FUEL_Boiler_MGO_LS':'FUEL_BOILER_MGO_LS','ROB_FUEL_HSFO':'ROB_Fuel_HSFO','ROB_FUEL_LSFO':'ROB_Fuel_LSFO','ROB_FUEL_MDO':'ROB_Fuel_MDO','ROB_FUEL_MGO':'ROB_Fuel_MGO','ROB_FUEL_MGO_LS':'ROB_Fuel_MGO_LS','ROB_FUEL_Tanktainer_MGO':'ROB_Fuel_Tanktainer_MGO'}, inplace = True)

In [84]:
weekcol = noon.columns.tolist()

In [86]:
#in the updated file has the db column name, so checking if there is any extra column is there
temp3 = []
for element in weekcol:
    if element not in col_lst:
        temp3.append(element)

temp3

['TANKTAINER_ROB',
 'BDN_Number',
 'Rob_Ajustment_HS',
 'Rob_Adjustment_VLS',
 'Rob_Adjustment_ULS',
 'Rob_Adjustment_Dist',
 'Rob_Adjustment_LNG',
 'Drydock2',
 'Rob_Tanktainer_adjustment',
 'STEAMING_TIME_M/E_RESIDUAL_HS',
 'kwhr_total',
 'Steaming_time_m/e_lng',
 'Drydock',
 'Total_Number_of_pax_on_board',
 'Total_Number_of_vehicles_on_board',
 'Eta_date/time',
 'DryDock',
 'Rpm',
 'ROB_fresh_water',
 'Total_M_E_Hours_Fuel_Only']

In [88]:
#same as above but vice versa
temp4 = []
for element in col_lst:
    if element not in weekcol:
        temp4.append(element)

temp4

['TOTAL_STEAMING_TIME', 'STEAMING_TIME_M_E_MDO']

In [90]:
#we already addd the new columns but there are two columns withnsame name with different value one row is there and one row isnot there 
#so we are doing mapping together to make it as one these value we will get from the above code 
#mapping the extra column which is already there so that the two rows values get merge 
noon['Kwhr_total'] = noon['Kwhr_total'].fillna(noon['kwhr_total'])

noon['ETA_DATE_TIME'] = noon['ETA_DATE_TIME'].fillna(noon['Eta_date/time'])

noon['STEAMING_TIME_M_E_Rsdl_HS'] = noon['STEAMING_TIME_M_E_Rsdl_HS'].fillna(noon['STEAMING_TIME_M/E_RESIDUAL_HS'])

noon['RPM'] = noon['RPM'].fillna(noon['Rpm'])
noon['ROB_FRESH_WATER'] = noon['ROB_FRESH_WATER'].fillna(noon['ROB_fresh_water'])

In [92]:
#since it will be two columns (extra) we are deleting one
drop = ['STEAMING_TIME_M/E_RESIDUAL_HS','kwhr_total','Eta_date/time','Rpm','ROB_fresh_water']
noon = noon.drop(columns=drop)

In [94]:
columns_to_fill_zero = ['FUEL_M_E_LNG', 'FUEL_Aux_LNG', 'FUEL_Boiler_LNG', 'ROB_Rsdl_LNG']

noon[columns_to_fill_zero].isna().sum()

FUEL_M_E_LNG       8028
FUEL_Aux_LNG       7948
FUEL_Boiler_LNG    8009
ROB_Rsdl_LNG       7921
dtype: int64

In [96]:
noon[columns_to_fill_zero] = noon[columns_to_fill_zero].fillna(0)

In [98]:
noondata_final = noon[['idvessel',
 'GID',
 'VSL',
 'IMO_No',
 'VOY',
 'Corrected_Date',
 'REPORT_DATE_TIME',
 'REPORT_DATE_TIME_Offset',
 'Report_Type',
 'Status',
 'LAT',
 'LONG_',
 'M_E_FOC',
 'CARGO_TOTAL',
 'Has_Cargo',
 'M_E_Fuel_Only_Steaming_Time',
 'MILES_BY_GPS',
 'OIL_CYL',
 'SOW',
 'SOG',
 'RPM',
 'SLIP',
 'WIND_DIRECTION',
 'WIND_SPEED',
 'DRAFT_AFT',
 'DRAFT_FWD',
 'DISPLACEMENT',
 'COURSE_AT_SEA',
 'WAVE_HEIGHT',
 'SEA_DIRECTION',
 'CARGO_TOTAL_TEU',
 'AMBIENT_TEMP',
 'SW_TEMP',
 'MILES_BY_SPEED_LOG',
 'ETA_PORT_CODE',
 'ETA_DATE_TIME',
 'ETA_DATE_TIME_Offset',
 'ETA_PORT',
 'TIME_CHANGE',
 'TIME_SEA',
 'TEMP_MIN',
 'TEMP_MAX',
 'REQUESTED_SPEED',
 'REM_DIST_TO_PILOT',
 'REM_TIME_TO_PILOT',
 'TOTAL_UNPLND_STPGE_TECH',
 'TOTAL_UNPLND_STPGE_OPE_WX',
 'REEFERS_POSITIVE_PLUGGED',
 'REEFERS_NEGATIVE_PLUGGED',
 'ME_TOTAL_REVS_COUNTER',
 'PORT_CODE',
 'PORT',
 'AUX_BLOWERS_ON',
 'HOLD_VENTILATION_ON',
 'SINCE_DATE_TIME',
 'SINCE_DATE_TIME_Offset',
 'TIME_HRS_ANCHOR',
 'TIME_HRS_DRIFT',
 'REASON',
 'TYPE_OF_DELAY',
 'ETB_DATE_TIME',
 'ETB_DATE_TIME_Offset',
 'PILOT_DATE_TIME',
 'PILOT_DATE_TIME_Offset',
 'TIME_MANOEUVRING',
 'TUG_ARR',
 'TUG_SHIFT',
 'ETD_DATE_TIME',
 'ETD_DATE_TIME_Offset',
 'SHIFT_BERTH_HOURS',
 'CARGO_LOAD',
 'CARGO_DISCH',
 'TEU_FULL',
 'TEU_EMPTY',
 'BILGE_REMOVED',
 'GARBAGE_REMOVED',
 'GARBAGE_REMVL_REQSTD',
 'GARBAGE_REMVL_CMPLSRY',
 'FW_SUPPLY',
 'CY_CREW_SIGNED_ON',
 'CY_CREW_SIGNED_OFF',
 'CY_DOCTORS_VISIT',
 'CY_MAIL_RECEIVED_Ref_NO',
 'CY_LUB_OIL_SAMPLE_LANDED',
 'CY_CHECKD_FOR_STOWAWAYS',
 'CY_STOWAWAYS_ON_BOARD',
 'CY_DEP_GM_Mtr',
 'CY_REQUISITIONS_RECEIVED',
 'DISTANCE_TO_NEXT_PILOT',
 'TUG_SAILING_TRANSIT',
 'STEAMING_TIME_M_E_Rsdl_VLS',
 'STEAMING_TIME_M_E_Rsdl_HS',
 'STEAMING_TIME_M_E_Rsdl_ULS',
 'STEAMING_TIME_M_E_Dstlt_VLS',
 'STEAMING_TIME_M_E_Dstlt_ULS',
 'STEAMING_TIME_M_E_Tnktnr_Dstlt_VLS',
 'STEAMING_TIME_M_E_HS',
 'STEAMING_TIME_M_E_LS',
 'Steaming_time_m/e_lng',
 'STEAMING_TIME_M_E_MGO',
 'STEAMING_TIME_M_E_MGO_LS',
 'STEAMING_TIME_AUX_1',
 'STEAMING_TIME_AUX_2',
 'STEAMING_TIME_AUX_3',
 'STEAMING_TIME_AUX_4',
 'STEAMING_TIME_AUX_5',
 'STEAMING_TIME_SH_GEN',
 'STEAMING_TIME_TG',
 'POWER_kW',
 'STEAMING_LOAD_KW_AUX_1',
 'STEAMING_LOAD_KW_AUX_2',
 'STEAMING_LOAD_KW_AUX_3',
 'STEAMING_LOAD_KW_AUX_4',
 'STEAMING_LOAD_KW_AUX_5',
 'STEAMING_LOAD_KW_SH_GEN',
 'STEAMING_LOAD_KW_TG',
 'FUEL_M_E_Rsdl_VLS',
 'FUEL_M_E_Rsdl_HS',
 'FUEL_M_E_Rsdl_ULS',
 'FUEL_M_E_Dstlt_VLS',
 'FUEL_M_E_Dstlt_ULS',
 'FUEL_M_E_Tnktnr_Dstlt_VLS',
 'FUEL_M_E_HS',
 'FUEL_M_E_LS',
 'FUEL_M_E_MDO',
 'FUEL_M_E_MGO',
 'FUEL_M_E_MGO_LS',
 'FUEL_Aux_Rsdl_VLS',
 'FUEL_Aux_Rsdl_HS',
 'FUEL_Aux_Rsdl_ULS',
 'FUEL_Aux_Dstlt_VLS',
 'FUEL_Aux_Dstlt_ULS',
 'FUEL_Aux_Tnktnr_Dstlt_VLS',
 'FUEL_AUX_HS',
 'FUEL_AUX_LS',
 'FUEL_AUX_MDO',
 'FUEL_AUX_MGO',
 'FUEL_AUX_MGO_LS',
 'FUEL_Boiler_Rsdl_VLS',
 'FUEL_Boiler_Rsdl_HS',
 'FUEL_Boiler_Rsdl_ULS',
 'FUEL_Boiler_Dstlt_VLS',
 'FUEL_Boiler_Dstlt_ULS',
 'FUEL_Boiler_Tnktnr_Dstlt_VLS',
 'FUEL_BOILER_HS',
 'FUEL_BOILER_LS',
 'FUEL_BOILER_MDO',
 'FUEL_BOILER_MGO',
 'FUEL_BOILER_MGO_LS',
 'DECK_LAST_CHANGE_USER',
 'ENGINE_LAST_CHANGE_USER',
 'DECK_PART_IS_COMPLETE',
 'ENGINE_PART_IS_COMPLETE',
 'SCAVENGE_PRESSURE',
 'SECA_ENTRY_TIME',
 'SECA_ENTRY_LAT',
 'SECA_ENTRY_LONG',
 'SECA_EXIT_TIME',
 'SECA_EXIT_LAT',
 'SECA_EXIT_LONG',
 'ROB_FRESH_WATER',
 'MANVRNG_MILES_BY_GPS',
 'MANVRNG_MILES_BY_SPEED_LOG',
 'TANKTAINER_TRANSFD_QUANTITY',
 'PILOT_TAKEN',
 'DATE_TIME_START_TRANSIT',
 'DATE_TIME_START_TRANSIT_Offset',
 'DATE_TIME_END_TRANSIT',
 'DATE_TIME_END_TRANSIT_Offset',
 'BALLAST',
 'TANKTAINER_NUMBER',
 'STEAMING_KWHR_TOTAL',
 'CY_OTHERS',
 'ROB_FO_SLUDGE',
 'ROB_LO_SLUDGE',
 'ROB_BILGE',
 'SLUDGE_REMOVED_FO',
 'SLUDGE_REMOVED_LO',
 'SEA_STATE',
 'CY_LUB_ADDED_TO_SYSTEM_MECC',
 'CY_LUB_ADDED_TO_SYSTEM_AECC',
 'CY_LUB_ADDED_TO_THRUSTERS',
 'CY_ME_LO_PURIFIER_IN_USE',
 'CY_BALLAST',
 'CY_BENDING_MOMENT',
 'CY_SHEARING_FORCE',
 'CY_TORTION_MOMENT',
 'CY_SUPDT_AUDITOR_SIGNED_ON',
 'CY_SUPDT_AUDITOR_SIGNED_OFF',
 'CY_CASH_RECEIVED',
 'CY_LUB_OIL_RECEIVED_MECYL',
 'CY_LUB_OIL_RECEIVED_MECC',
 'CY_LUB_OIL_RECEIVED_AECC',
 'CY_M_E_UNDER_PISTON_TEMP',
 'CY_MAIL_RECEIVED',
 'WIND_DIRECTION_PORT_STBD',
 'SEA_DIRECTION_PORT_STBD',
 'TIME_PILOT_ONBOARD',
 'GRADES_ROB',
 'SO2_CO2_RATIO',
 'Bunker_Order',
 'Remarks',
 'Fuel_Type',
 'Carbon_Factor',
 'Sulphur_Content_PC',
 'Quantity',
 'Port_Delivery',
 'Product_Quality',
 'Tanktainer_Number_1',
 'Supplier',
 'Delivery',
 'BDN_Number',
 'Vol_Lt',
 'Den',
 'Vis',
 'ROB_Dstlt_ULS',
 'ROB_Dstlt_VLS',
 'ROB_Rsdl_MDO',
 'ROB_Tnktnr_Dstlt_VLS',
 'ROB_Rsdl_VLS',
 'ROB_Rsdl_HS',
 'ROB_Rsdl_ULS',
 'ROB_Fuel_HSFO',
 'ROB_Fuel_LSFO',
 'ROB_Fuel_MDO',
 'ROB_Fuel_MGO',
 'ROB_Fuel_MGO_LS',
 'ROB_Fuel_Tanktainer_MGO',
 'ECA_MILES',
 'ECA_TIME',
 'EGCS_DRY_WASTE_REMOVED',
 'EGCS_RUNNING_TIME',
 'EGCS_WET_SLURRY_REMOVED',
 'EGCS_OPEN_LOOP_RUNNING_TIME',
 'EGCS_CLOSED_LOOP_RUNNING_TIME',
 'FUEL_M_E_LNG',
 'FUEL_Aux_LNG','FUEL_Boiler_LNG', 'ROB_Rsdl_LNG',
'Comments',
'Pilot_date/time',
'Hold_ventilation_off',
'Reefer_power_consumption',
'Tanktainer_distillates_transfd',
'Hold_Ventilation_On/Off',
'Tot_sludge_removed',
'Garbage_cat_a_-_plastic_removed',
'Garbage_cat_b_-_organic_removed',
'Garbage_cat_c_-_domestic_removed',
'Garbage_cat_e_-_ashes_removed',
'Rob_garbage_cat_a_-_plastic',
'Rob_garbage_cat_b_-_organic',
'Rob_garbage_cat_c_-_domestic',
'Rob_garbage_cat_e_-_ashes',
'Kwhr_total',
'Sludge_rob',
'Qty_sludge_disposed']]

In [100]:
import re
def replace_special_characters(value):
    if isinstance(value, str):
        # Replace all the special characters with underscores
        value = re.sub(r'[,\;\!\/\\\;\'\"\@\#\$\%\^\(\)]', '_', value)
    return value

 

noondata_final = noondata_final.applymap(replace_special_characters)

In [101]:
noondata_final[noondata_final.apply(lambda x: x.str.contains(',|;').any(), axis=1)]

Empty DataFrame
Columns: [idvessel, GID, VSL, IMO_No, VOY, Corrected_Date, REPORT_DATE_TIME, REPORT_DATE_TIME_Offset, Report_Type, Status, LAT, LONG_, M_E_FOC, CARGO_TOTAL, Has_Cargo, M_E_Fuel_Only_Steaming_Time, MILES_BY_GPS, OIL_CYL, SOW, SOG, RPM, SLIP, WIND_DIRECTION, WIND_SPEED, DRAFT_AFT, DRAFT_FWD, DISPLACEMENT, COURSE_AT_SEA, WAVE_HEIGHT, SEA_DIRECTION, CARGO_TOTAL_TEU, AMBIENT_TEMP, SW_TEMP, MILES_BY_SPEED_LOG, ETA_PORT_CODE, ETA_DATE_TIME, ETA_DATE_TIME_Offset, ETA_PORT, TIME_CHANGE, TIME_SEA, TEMP_MIN, TEMP_MAX, REQUESTED_SPEED, REM_DIST_TO_PILOT, REM_TIME_TO_PILOT, TOTAL_UNPLND_STPGE_TECH, TOTAL_UNPLND_STPGE_OPE_WX, REEFERS_POSITIVE_PLUGGED, REEFERS_NEGATIVE_PLUGGED, ME_TOTAL_REVS_COUNTER, PORT_CODE, PORT, AUX_BLOWERS_ON, HOLD_VENTILATION_ON, SINCE_DATE_TIME, SINCE_DATE_TIME_Offset, TIME_HRS_ANCHOR, TIME_HRS_DRIFT, REASON, TYPE_OF_DELAY, ETB_DATE_TIME, ETB_DATE_TIME_Offset, PILOT_DATE_TIME, PILOT_DATE_TIME_Offset, TIME_MANOEUVRING, TUG_ARR, TUG_SHIFT, ETD_DATE_TIME, ETD_DATE_TIME_Offset, SHIFT_BERTH_HOURS, CARGO_LOAD, CARGO_DISCH, TEU_FULL, TEU_EMPTY, BILGE_REMOVED, GARBAGE_REMOVED, GARBAGE_REMVL_REQSTD, GARBAGE_REMVL_CMPLSRY, FW_SUPPLY, CY_CREW_SIGNED_ON, CY_CREW_SIGNED_OFF, CY_DOCTORS_VISIT, CY_MAIL_RECEIVED_Ref_NO, CY_LUB_OIL_SAMPLE_LANDED, CY_CHECKD_FOR_STOWAWAYS, CY_STOWAWAYS_ON_BOARD, CY_DEP_GM_Mtr, CY_REQUISITIONS_RECEIVED, DISTANCE_TO_NEXT_PILOT, TUG_SAILING_TRANSIT, STEAMING_TIME_M_E_Rsdl_VLS, STEAMING_TIME_M_E_Rsdl_HS, STEAMING_TIME_M_E_Rsdl_ULS, STEAMING_TIME_M_E_Dstlt_VLS, STEAMING_TIME_M_E_Dstlt_ULS, STEAMING_TIME_M_E_Tnktnr_Dstlt_VLS, STEAMING_TIME_M_E_HS, STEAMING_TIME_M_E_LS, Steaming_time_m/e_lng, STEAMING_TIME_M_E_MGO, ...]
Index: []

[0 rows x 257 columns]

In [102]:
noondata_final['GID'].dtypes

dtype('int64')

In [103]:
noondata_final['GID'] = noondata_final['GID'].astype(str)
noondata_final['GID'].dtypes

dtype('O')

In [104]:
#corrected_date,report_date_time column format change to yyyy-mm-dd-hh:mm:ss
noondata_final[['Corrected_Date','REPORT_DATE_TIME']]

          Corrected_Date            REPORT_DATE_TIME
0    2024-12-01 00:00:00  2024-12-01 00:00:00 +00:00
1    2024-12-01 00:00:00  2024-12-01 00:00:00 +00:00
2    2024-12-01 00:00:00  2024-12-01 00:00:00 +00:00
3    2024-12-01 00:00:00  2024-12-01 00:00:00 +00:00
4    2024-12-01 00:00:00  2024-12-01 00:00:00 +00:00
...                  ...                         ...
8238 2024-12-25 12:00:00  2024-12-25 12:00:00 +00:00
8239 2024-12-25 12:00:00  2024-12-25 12:00:00 +00:00
8240 2024-12-26 07:00:00  2024-12-26 07:00:00 +00:00
8241 2024-12-28 12:00:00  2024-12-28 12:00:00 +00:00
8242 2024-12-29 12:00:00  2024-12-29 12:00:00 +00:00

[8089 rows x 2 columns]

In [105]:
import pandas as pd

# Define a function to convert datetime strings to the desired format
def convert_to_desired_format(datetime_string):
    formats_to_try = ['%Y-%m-%d %H:%M:%S', '%d.%m.%Y %H:%M', '%Y%m%d %H:%M:%S']
    for fmt in formats_to_try:
        try:
            return pd.to_datetime(datetime_string, format=fmt).strftime('%Y-%m-%d %H:%M:%S')
        except ValueError:
            continue
    return None  # Return None if none of the formats match

# Assuming noondata_final is your DataFrame and 'ETA_DATE_TIME', 'ETB_DATE_TIME', 'ETD_DATE_TIME' are columns containing datetime strings
noondata_final['ETA_DATE_TIME'] = noondata_final['ETA_DATE_TIME'].apply(convert_to_desired_format)
noondata_final['ETB_DATE_TIME'] = noondata_final['ETB_DATE_TIME'].apply(convert_to_desired_format)
noondata_final['ETD_DATE_TIME'] = noondata_final['ETD_DATE_TIME'].apply(convert_to_desired_format)

In [106]:
#noondata_final['Corrected_Date'] = pd.to_datetime(noondata_final['Corrected_Date'])
noondata_final['REPORT_DATE_TIME'] = pd.to_datetime(noondata_final['REPORT_DATE_TIME'])


# Assuming noondata_final is your DataFrame
noondata_final['ETA_DATE_TIME'] = pd.to_datetime(noondata_final['ETA_DATE_TIME'])
noondata_final['ETB_DATE_TIME'] = pd.to_datetime(noondata_final['ETB_DATE_TIME'])
noondata_final['ETD_DATE_TIME'] = pd.to_datetime(noondata_final['ETD_DATE_TIME'])

import pandas as pd

# Assuming noondata_final is your DataFrame and 'Corrected_Date' is the column containing datetime strings
# Convert the 'Corrected_Date' column to string
noondata_final['REPORT_DATE_TIME'] = noondata_final['REPORT_DATE_TIME'].astype(str)

# Split the strings to remove the timezone offset
noondata_final['REPORT_DATE_TIME'] = noondata_final['REPORT_DATE_TIME'].str.split().str[0] + ' ' + noondata_final['REPORT_DATE_TIME'].str.split().str[1]

# Convert the strings back to datetime objects
noondata_final['REPORT_DATE_TIME'] = pd.to_datetime(noondata_final['REPORT_DATE_TIME'])

In [108]:
import re

# Convert 'REPORT_DATE_TIME' to string if not already
noondata_final['REPORT_DATE_TIME'] = noondata_final['REPORT_DATE_TIME'].astype(str)

# Use regex to extract the date and time parts
# This will handle cases with or without spaces around the time part and timezone offset
pattern = r'(\d{4}-\d{2}-\d{2})[T ](\d{2}:\d{2}:\d{2})[\+\-]?.*'
noondata_final['REPORT_DATE_TIME'] = noondata_final['REPORT_DATE_TIME'].apply(lambda x: ' '.join(re.match(pattern, x).groups()))

# Display the result to check if it's correct
#print(noondata_final[['REPORT_DATE_TIME']])

In [109]:
# Convert LAT to string (object data type)
noondata_final['LAT'] = noondata_final['LAT'].astype(str)

# Validate LAT format: valid formats are like '25N', '35W', etc.
valid_latitudes = noondata_final['LAT'].str.match(r'^[0-9]+(E|W|N|S)?$')

# Set LAT to NaN where it doesn't match the valid format
noondata_final.loc[~valid_latitudes, 'LAT'] = np.nan

In [110]:
# Fill missing values in LAT for berthing reports directly using fillna with ffill
noondata_final.loc[noondata_final['Report_Type'] == 'Berthing', 'LAT'] = noondata_final.groupby('IMO_No')['LAT'].transform(lambda x: x.ffill())

In [111]:
catherine_data = noondata_final[noondata_final['IMO_No'] == 9229300]

# Print the relevant data for the "Catherine" vessel
print("Data for the Catherine vessel:")
catherine_data[['LAT', 'Report_Type']].head(30)

Data for the Catherine vessel:

        LAT Report_Type
246   0512N        Noon
1356  0935N        Noon
1524  1008N        EOSP
1842  1008N    Berthing
2410    NaN   Port Noon
2678    NaN     Sailing
2860  1016N        COSP
3499  1224N        Noon
4376    NaN      Bunker
4521  1803N        Noon
5377  2223N        EOSP
5521  2223N    Berthing
5543    NaN   Port Noon
6355    NaN     Sailing
6411  2229N        COSP
6528  2212N        Noon
7500  2536N        Noon
8149    NaN      Sludge
8150    NaN      Sludge

pd.set_option('display.max_rows', None)  # None means unlimited

# To see the data types of all columns
column_types = noondata_final.dtypes

In [112]:
nan_columns = noondata_final.columns[noondata_final.isna().all()].tolist()

# # Display the list of columns with all NaN values
# print("Columns with all NaN values:")
# print(nan_columns)

In [113]:
# Count the number of columns with all NaN values
nan_count = len(nan_columns)

# Print the count
print(f"Number of columns with all NaN values: {nan_count}")

Number of columns with all NaN values: 106

In [114]:
#corrected_date,report_date_time column format change to yyyy-mm-dd-hh:mm:ss
noondata_final[['Corrected_Date','REPORT_DATE_TIME']]

          Corrected_Date     REPORT_DATE_TIME
0    2024-12-01 00:00:00  2024-12-01 00:00:00
1    2024-12-01 00:00:00  2024-12-01 00:00:00
2    2024-12-01 00:00:00  2024-12-01 00:00:00
3    2024-12-01 00:00:00  2024-12-01 00:00:00
4    2024-12-01 00:00:00  2024-12-01 00:00:00
...                  ...                  ...
8238 2024-12-25 12:00:00  2024-12-25 12:00:00
8239 2024-12-25 12:00:00  2024-12-25 12:00:00
8240 2024-12-26 07:00:00  2024-12-26 07:00:00
8241 2024-12-28 12:00:00  2024-12-28 12:00:00
8242 2024-12-29 12:00:00  2024-12-29 12:00:00

[8089 rows x 2 columns]

In [115]:
noondata_final['BDN_Number'].unique()

array([nan, 'A012788', 10012, 100081, 'A018200', 'HIJ1_173',
       'BRBTB202400001329', 'BRBTB202400001331', 'I *3411',
       'BRBTB2024580796A888', 'L * 3410', 'D-7520_24', 'B-30321_24',
       'A 1073', 7154, 2408330, 'HP-0063', 1562, 688, 'BRBTB202400001328',
       5803, 'VA01122024.4', 'VA01122024.3', '41-2412D1', 20240035, 19693,
       46684, 'PRI_ETT_HIJ9_140', 'RSV 10130', 2238, 'RSV 10132',
       '_BRBTB202400001333', 327328, 'BRBTB202400001334', 2540, 5689,
       2539, 'D-7530-24', 'A012790', 'BRBTB202400001336', 'HIJ11_79',
       2416981, 'A017618', 'BE1A000049599', 15453, 'B 15075', 2543,
       'B 15076', 'HIJ1_174', 12324, 104808, 'HIJ7257', 6775,
       '21212024X0393', '2024-01-214042902', '12_3-4_24', '24BK.007359',
       '1083_2003', 284789, 896, 897, 169701, 100085, 'BRTB202400001338',
       687, '15504_2024', 19231, 'RSV 10136', 'TWPLM_03122024_00014',
       183042, 2102203, 6746, 'HL0000019', 'D-7541_24', 15500,
       'AE197605A', 124, 'A124', 284942, 'AE197605',
       '24BK.007473_24BK.007464', 'HI J7 _ 260',
       '24BK.007473_24BK.007464 _6_', 10532510, 'BRBTB202400001342',
       'HIJ1_175', 1320, 30743, 'BDN 04.12.2024', 'HL0000435',
       'BRBTB202400001343', 2050747, 270945, ':13558', 'HIJ7_258',
       'SAG-29NOV_11198', 'SH20242601',
       147051147057146991288146157138608128, 'OCA20240314', ':13557',
       234135, 'HIJ7_259', 2239, 7825, 2241, 271427152716271007563776,
       56137, 'BRBTB202400001344', 283755, 284340, 6776, 'BE 1A006626000',
       'BRBTB202400009147', 'BRBTB202400001345', 0, 'HIJ1_177', '1024-GB',
       1201, 4944, 4945, 22352103, 'VA 05122024-3', 284938, 'HBC-24-0953',
       'BR 00935 CHN', 'TFG-MU-2407562', 406024000469, 406524000534,
       'LMTS1676', 508050945081, 19696, 480338939, 'OCA20240318', 2277,
       183332, 2279, 'HP-0067', 'BRBTB202400001350', 'HIJ7_269', 13302,
       403692, '01380-VB', 4129, 23916, 'MCT1468', 202935, 8953, 3425,
       3424, 27232725272424898560, 8024029124, 'HIJ1_180',
       '008024101375-0', 'RSV 10131'], dtype=object)

In [116]:
noondata_final.shape

(8089, 257)

In [ ]:
noondata_final.to_csv(r"D:\Navalt\MSC\2024\Weekly Data\MSCSMCY\CSV\noondata_Dec_2024.csv",index=False)

In [ ]:
noondata_final.to_csv(r"D:\Navalt\MSC\2024\Weekly Data\MSCSMCY\EXCEL\noondata_Dec_2024.csv",index=False)