In [3]:
import pandas as pd

In [5]:
df1= pd.read_csv(r'C:\Users\akshaya\Downloads\noon_2024_.csv')

C:\Users\akshaya\AppData\Local\Temp\ipykernel_36424\870331990.py:1: DtypeWarning: Columns (197,204,330,332,333,336,337) have mixed types. Specify dtype option on import or set low_memory=False.
  df1= pd.read_csv(r'C:\Users\akshaya\Downloads\noon_2024_.csv')

In [7]:
df2= pd.read_excel(r'D:\Navalt\MSC\2024\Weekly Data\CLIENT\Actual data by client\LimassolExport - 2024 Week 51.xlsx')

In [11]:
df1.shape

(340407, 356)

In [13]:
df2.shape8

(375069, 161)

In [15]:
df1.columns.to_list()

['id',
 'pi_sog',
 'pi_stw',
 'true_wind_dir',
 'true_wind_speed',
 'relative_wind_speed',
 'relative_wind_direction',
 'caa',
 'corrected_power',
 'rw',
 'ref_speed',
 'imo',
 'vessel',
 'id_vessel',
 'gid',
 'voyage',
 'corrected_date',
 'report_date_time',
 'report_date_time_offset',
 'report_type',
 'status',
 'lat',
 'long',
 'latitude',
 'longitude',
 'me_foc',
 'cargo_total',
 'total_steaming_time',
 'me_fuel_only_steaming_time',
 'miles_by_gps',
 'oil_cyl',
 'speed_by_log',
 'speed_by_gps',
 'rpm',
 'slip',
 'wind_direction',
 'wind_speed',
 'draft_aft',
 'draft_fwd',
 'displacement',
 'course_at_sea',
 'wave_height',
 'sea_direction',
 'cargo_total_teu',
 'ambient_temp',
 'sw_temp',
 'miles_by_speed_log',
 'eta_port_code',
 'eta_date_time',
 'eta_date_time_offset',
 'eta_port',
 'time_change',
 'time_sea',
 'temp_min',
 'temp_max',
 'requested_speed',
 'rem_dist_to_pilot',
 'rem_time_to_pilot',
 'total_unplnd_stpge_tech',
 'total_unplnd_stpge_ope_wx',
 'reefers_positive_plugged',
 'reefers_negative_plugged',
 'me_total_revs_counter',
 'port_code',
 'port',
 'aux_blowers_on',
 'hold_ventilation_on',
 'since_date_time',
 'since_date_time_offset',
 'time_hrs_anchor',
 'time_hrs_drift',
 'reason',
 'type_of_delay',
 'etb_date_time',
 'etb_date_time_offset',
 'pilot_date_time',
 'pilot_date_time_offset',
 'time_manoeuvring',
 'tug_arr',
 'tug_shift',
 'etd_date_time',
 'etd_date_time_offset',
 'shift_berth_hours',
 'cargo_load',
 'cargo_disch',
 'teu_full',
 'teu_empty',
 'bilge_removed',
 'garbage_removed',
 'garbage_remvl_reqstd',
 'garbage_remvl_cmplsry',
 'fw_supply',
 'cy_crew_signed_on',
 'cy_crew_signed_off',
 'cy_doctors_visit',
 'cy_mail_received_ref_no',
 'cy_lub_oil_sample_landed',
 'cy_checkd_for_stowaways',
 'cy_stowaways_on_board',
 'cy_dep_gm_mtr',
 'cy_requisitions_received',
 'distance_to_next_pilot',
 'tug_sailing_transit',
 'steaming_time_me_rsdl_vls',
 'steaming_time_me_rsdl_hs',
 'steaming_time_me_rsdl_uls',
 'steaming_time_me_dstlt_vls',
 'steaming_time_me_dstlt_uls',
 'steaming_time_me_tnktnr_dstlt_vls',
 'steaming_time_me_mdo',
 'steaming_time_aux_1',
 'steaming_time_aux_2',
 'steaming_time_aux_3',
 'steaming_time_aux_4',
 'steaming_time_aux_5',
 'steaming_time_sh_gen',
 'steaming_time_tg',
 'fuel_me_rsdl_vls',
 'fuel_me_rsdl_hs',
 'fuel_me_rsdl_uls',
 'fuel_me_dstlt_vls',
 'fuel_me_dstlt_uls',
 'fuel_me_mdo',
 'fuel_me_tnktnr_dstlt_vls',
 'fuel_aux_rsdl_vls',
 'fuel_aux_rsdl_hs',
 'fuel_aux_rsdl_uls',
 'fuel_aux_dstlt_vls',
 'fuel_aux_dstlt_uls',
 'fuel_aux_tnktnr_dstlt_vls',
 'fuel_aux_mdo',
 'fuel_boiler_rsdl_vls',
 'fuel_boiler_rsdl_hs',
 'fuel_boiler_rsdl_uls',
 'fuel_boiler_dstlt_vls',
 'fuel_boiler_dstlt_uls',
 'fuel_boiler_tnktnr_dstlt_vls',
 'fuel_boiler_mdo',
 'power_kw',
 'steaming_load_kw_aux_1',
 'steaming_load_kw_aux_2',
 'steaming_load_kw_aux_3',
 'steaming_load_kw_aux_4',
 'steaming_load_kw_aux_5',
 'steaming_load_kw_sh_gen',
 'steaming_load_kw_tg',
 'deck_last_change_user',
 'engine_last_change_user',
 'deck_part_is_complete',
 'engine_part_is_complete',
 'scavenge_pressure',
 'seca_entry_time',
 'seca_entry_lat',
 'seca_entry_long',
 'seca_exit_time',
 'seca_exit_lat',
 'seca_exit_long',
 'rob_fresh_water',
 'manvrng_miles_by_gps',
 'manvrng_miles_by_speed_log',
 'tanktainer_transfd_quantity',
 'pilot_taken',
 'date_time_start_transit',
 'date_time_start_transit_offset',
 'date_time_end_transit',
 'date_time_end_transit_offset',
 'ballast',
 'tanktainer_number',
 'steaming_kwhr_total',
 'cy_others',
 'rob_fo_sludge',
 'rob_lo_sludge',
 'rob_bilge',
 'sludge_removed_fo',
 'sludge_removed_lo',
 'sea_state',
 'cy_lub_added_to_system_me_cc',
 'cy_lub_added_to_system_ae_cc',
 'cy_lub_added_to_thrusters',
 'cy_me_lo_purifier_in_use',
 'cy_ballast',
 'cy_bending_moment',
 'cy_shearing_force',
 'cy_tortion_moment',
 'cy_supdt_auditor_signed_on',
 'cy_supdt_auditor_signed_off',
 'cy_cash_received',
 'cy_lub_oil_received_me_cyl',
 'cy_lub_oil_received_me_cc',
 'cy_lub_oil_received_ae_cc',
 'cy_me_under_piston_temp',
 'cy_mail_received',
 'wind_direction_port_stbd',
 'sea_direction_port_stbd',
 'time_pilot_onboard',
 'grades_rob',
 'so_2_co_2_ratio',
 'bunker_order',
 'remarks',
 'bdn_number',
 'fuel_type',
 'carbon_factor',
 'sulphur_content_pc',
 'quantity',
 'port_delivery',
 'product_quality',
 'tanktainer_number_1',
 'supplier',
 'delivery',
 'volume_lt',
 'density',
 'viscosity',
 'rob_dstlt_uls',
 'rob_dstlt_vls',
 'rob_rsdl_mdo',
 'rob_tnktnr_dstlt_vls',
 'rob_rsdl_vls',
 'rob_rsdl_hs',
 'rob_rsdl_uls',
 'has_cargo',
 'steaming_time_me_hs',
 'steaming_time_me_ls',
 'steaming_time_me_mgo',
 'steaming_time_me_mgo_ls',
 'fuel_me_hs',
 'fuel_me_ls',
 'fuel_me_mgo',
 'fuel_me_mgo_ls',
 'fuel_aux_hs',
 'fuel_aux_ls',
 'fuel_aux_mgo',
 'fuel_aux_mgo_ls',
 'fuel_boiler_hs',
 'fuel_boiler_ls',
 'fuel_boiler_mgo',
 'fuel_boiler_mgo_ls',
 'rob_fuel_hs_fo',
 'rob_fuel_ls_fo',
 'rob_fuel_mdo',
 'rob_fuel_mgo',
 'rob_fuel_mgo_ls',
 'rob_fuel_tanktainer_mgo',
 'eca_miles',
 'eca_time',
 'egcs_dry_waste_removed',
 'egcs_running_time',
 'egcs_wet_slurry_removed',
 'egcs_open_loop_running_time',
 'egcs_closed_loop_running_time',
 'voyage_order',
 'voyage_code',
 'eca',
 'eu',
 'sea_time',
 'eta_country_code',
 'port_country_code',
 'check_eta_code',
 'check_port_code',
 'status_temp_eu',
 'fuel_hs',
 'fuel_ls',
 'fuel_mdo',
 'fuel_mgo',
 'fuel_mgo_ls',
 'cargo_transport_work',
 'teu_transport_work',
 'eeoi_voyage_no',
 'cargo_total_old',
 'draft',
 'fo_per_24_hrs',
 'sfoc',
 'cy_oil_gm_hr',
 'scoc',
 'voyage_name',
 'total_fo',
 'total_co_2',
 'eeoi',
 'voy_condition',
 'same_date',
 'time_since_last_report',
 'wind_direction_360',
 'ref_power',
 'ref_fuel',
 'fuel_loss',
 'draft_pow',
 'draft_sp_pow',
 'fo_nor',
 'fo_model',
 'sfoc_model',
 'sfoc_deviation',
 'ref_power_corrected',
 'ref_fo_corrected',
 'propulsive_eff',
 'speed_performance',
 'pi',
 'me_con',
 'ae_con',
 'bl_con',
 't_con',
 'hs',
 'ls',
 'mdo',
 'mgo',
 'mgo_ls',
 't_co_2',
 'ae_t_steaming',
 'ae_power',
 'trim',
 'distance_covered',
 'updated_date',
 'hyd_slip_sog',
 'hyd_slip_stw',
 'fuel_rsdl_hs',
 'fuel_rsdl_vls',
 'fuel_rsdl_uls',
 'fuel_dstlt_vls',
 'fuel_dstlt_uls',
 'fuel_tnktnr_dstlt_vls',
 'rsdl_hs',
 'rsdl_vls',
 'rsdl_uls',
 'dstlt_vls',
 'dstlt_uls',
 'tnktnr_dstlt_vls',
 'fuel_m_e_lng',
 'fuel_aux_lng',
 'fuel_boiler_lng',
 'rob_rsdl_lng',
 'sulphur_content_pc_main',
 'quantity_main',
 'port_delivery_main',
 'product_quality_main',
 'delivery_main',
 'bdn_number_main',
 'fo_nor_sog',
 'fo_nor_stw',
 'created_at',
 'updated_at',
 'created_by_id',
 'updated_by_id',
 'rob_lng',
 'sludge_rob',
 'garbage_cat_a_plastic_removed',
 'garbage_cat_b_organic_removed',
 'garbage_cat_c_domestic_removed',
 'garbage_cat_e_ashes_removed',
 'rob_garbage_cat_a_plastic',
 'rob_garbage_cat_b_organic',
 'rob_garbage_cat_c_domestic',
 'rob_garbage_cat_e_ashes',
 'qty_sludge_disposed',
 'steaming_time_m_e_lng',
 'reefer_power_consumption',
 'wind_direction_side',
 'sea_direction_side',
 'tot_sludge_removed']

In [17]:
df2.columns.to_list()

['MessagesId',
 'ImoNumber',
 'vName',
 'MessageType',
 'DateTimeLt',
 'DateTimeUtc',
 'Latitude',
 'Longitude',
 'CargoMT',
 'CargoTEU',
 'DraftAft',
 'DraftFwd',
 'Speed by gps',
 'Speed by log',
 'FOC_AE_DIS',
 'FOC_AE_LNG',
 'FOC_AE_RES_HS',
 'FOC_AE_RES_ULS',
 'FOC_AE_RES_VLS',
 'FOC_BLR_DIS',
 'FOC_BLR_LNG',
 'FOC_BLR_RES_HS',
 'FOC_BLR_RES_ULS',
 'FOC_BLR_RES_VLS',
 'FOC_ME_DIS',
 'FOC_ME_LNG',
 'FOC_ME_RES_HS',
 'FOC_ME_RES_ULS',
 'FOC_ME_RES_VLS',
 'Hours_AE_1',
 'Hours_AE_2',
 'Hours_AE_3',
 'Hours_AE_4',
 'Hours_AE_5',
 'Hours_ME',
 'Hours_SG',
 'Hours_TG',
 'Power_AE_1',
 'Power_AE_2',
 'Power_AE_3',
 'Power_AE_4',
 'Power_AE_5',
 'Power_ME',
 'Power_SG',
 'Power_TG',
 'ROB_DIS',
 'ROB_LNG',
 'ROB_RES_HS',
 'ROB_RES_ULS',
 'ROB_RES_VLS',
 'Max Residual HS capacity',
 'Max Lng capacity',
 'Min Lng request',
 'Tanktainer number',
 'Tanktainer min request',
 'Template version',
 'Port bunkering',
 'TANKTAINER ROB',
 'Comments',
 'Product Name',
 'Physical supplier name',
 'Volume',
 'Quantity',
 'Density at 15Â°C',
 'Viscosity at 40Â°C or 50Â°C',
 'Sulfur content',
 'Bunker Order',
 'Bdn number',
 'Port Code',
 'Port Name',
 'Pilot date/time',
 'PIER date/time',
 'Time manoeuvring',
 'Displacement',
 'Estimated departure date/time',
 'Number of Tanktainer',
 'Manoeuvring miles by gps',
 'Manoeuvring miles by speed log',
 'Kwhr total',
 'Hold ventilation off',
 'Reefers positive plugged',
 'Reefers negative plugged',
 'Me total revs counter',
 'Rob fresh water',
 'Egcs running time',
 'So2/co2 ratio',
 'Rob tot Sludge',
 'Ballast',
 'Egcs closed loop running time',
 'Egcs open loop running time',
 'Reefer power consumption',
 'Rob Ajustment HS',
 'Rob Adjustment VLS',
 'Rob Adjustment ULS',
 'Rob Adjustment Dist',
 'Rob Adjustment LNG',
 'Drydock2',
 'Rob Tanktainer adjustment',
 'Wind direction',
 'Miles by gps',
 'STEAMING TIME M/E RESIDUAL HS',
 'RPM',
 'Slip',
 'ETA Port Code',
 'ETA Port Name',
 'ETA Date/Time',
 'Wind speed',
 'Course at Sea',
 'Wave height',
 'Sea state',
 'Ambient temp',
 'Sw temp',
 'Miles speed log',
 'Requested speed',
 'Time change',
 'Time sea',
 'kwhr total',
 'Scavenge pressure',
 'SEA DIRECTION',
 'Eca miles',
 'Eca time',
 'Steaming time m/e lng',
 'Drydock',
 'TEU Full',
 'TEU Empty',
 'Fresh water supply',
 'Tanktainer distillates transfd',
 'Hold Ventilation On/Off',
 'Bilge removed',
 'Tot sludge removed',
 'Garbage cat a - plastic removed',
 'Garbage cat b - organic removed',
 'Garbage cat c - domestic removed',
 'Garbage cat e - ashes removed',
 'Rob garbage cat a - plastic',
 'Rob garbage cat b - organic',
 'Rob garbage cat c - domestic',
 'Rob garbage cat e - ashes',
 'Egcs wet waste removed',
 'Egcs dry waste removed',
 'Total Number of pax on board',
 'Total Number of vehicles on board',
 'Type of delay',
 'Reason',
 'Time hrs. anchor',
 'Time hrs. drift',
 'Eta date/time',
 'Sludge rob',
 'Sludge min discharge request',
 'Oil Cylinder',
 'DryDock',
 'ETB Date/Time',
 'Steaming time m/e residual hs',
 'Steaming time m/e residual uls',
 'Steaming time m/e residual vls',
 'Rpm',
 'Shift berth hours',
 'ROB fresh water',
 'Rob actual sludge',
 'Rob actual bilge',
 'Qty sludge disposed']

In [19]:
df2['ImoNumber'].dtype

dtype('int64')

In [21]:

imos_to_remove = [9618305, 9143879, 9256365, 9618317, 9135638, 9618264, 9618290]

# Filter df2 to exclude the specified IMOs
df2_filtered = df2[~df2['ImoNumber'].isin(imos_to_remove)]

In [22]:
df2_filtered.shape

(369599, 161)

In [25]:
new_rows = df2_filtered[~df2_filtered['MessagesId'].isin(df1['gid'])]

# Step 3: Display the results
if not new_rows.empty:
    print("New rows added this month:")
    print(new_rows)
else:
    print("No new rows added this month.")

New rows added this month:
        MessagesId  ImoNumber              vName MessageType  \
0          5189146    9222273  MSC BRASILIA VII      Sailing
15         5189147    9222273  MSC BRASILIA VII         COSP
504        5830206    9399765    MSC PASSION III       Delay
3421       5832436    9467445        MSC KATRINA       Delay
4549       5832435    9467445        MSC KATRINA       Delay
...            ...        ...                ...         ...
375064     5854136    9936642          MSC CHINA      Sludge
375065     5854134    9936642          MSC CHINA      Sludge
375066     5832965    9360271       MSC CAPE III      Sludge
375067     5852452    9243409     MSC BRIDGEPORT      Sludge
375068     5853166    9243409     MSC BRIDGEPORT  EGCS Waste

                        DateTimeLt         DateTimeUtc Latitude Longitude  \
0       2023-12-31 19:06:00 -05:00 2024-01-01 00:06:00      NaN       NaN
15      2023-12-31 20:18:00 -05:00 2024-01-01 01:18:00    4222N    07052W
504     2024-01-01 12:00:00 +01:00 2024-01-01 11:00:00    5355N    00749E
3421    2024-01-04 12:00:00 +08:00 2024-01-04 04:00:00    3034N    12319E
4549    2024-01-05 12:00:00 +08:00 2024-01-05 04:00:00    3028N    12232E
...                            ...                 ...      ...       ...
375064  2024-12-25 12:00:00 +00:00 2024-12-25 12:00:00      NaN       NaN
375065  2024-12-25 12:00:00 +00:00 2024-12-25 12:00:00      NaN       NaN
375066  2024-12-26 07:00:00 +00:00 2024-12-26 07:00:00      NaN       NaN
375067  2024-12-28 12:00:00 +00:00 2024-12-28 12:00:00      NaN       NaN
375068  2024-12-29 12:00:00 +00:00 2024-12-29 12:00:00      NaN       NaN

         CargoMT  CargoTEU  ...  ETB Date/Time  Steaming time m/e residual hs  \
0        21933.7    2217.0  ...            NaN                            NaN
15       21933.7    2217.0  ...            NaN                            NaN
504          0.0       0.0  ...            NaN                            NaN
3421     89027.0    8780.0  ...            NaN                            NaN
4549     89027.0    8780.0  ...            NaN                            NaN
...          ...       ...  ...            ...                            ...
375064  141518.0   20053.0  ...            NaN                            NaN
375065  141518.0   20053.0  ...            NaN                            NaN
375066   14042.0    1403.0  ...            NaN                            NaN
375067   60833.0    6650.0  ...            NaN                            NaN
375068   60833.0    6650.0  ...            NaN                            NaN

        Steaming time m/e residual uls  Steaming time m/e residual vls  Rpm  \
0                                  NaN                             NaN  NaN
15                                 NaN                             NaN  NaN
504                                NaN                             NaN  NaN
3421                               NaN                             NaN  NaN
4549                               NaN                             NaN  NaN
...                                ...                             ...  ...
375064                             NaN                             NaN  NaN
375065                             NaN                             NaN  NaN
375066                             NaN                             NaN  NaN
375067                             NaN                             NaN  NaN
375068                             NaN                             NaN  NaN

        Shift berth hours  ROB fresh water  Rob actual sludge  \
0                     NaN              NaN                NaN
15                    NaN              NaN                NaN
504                   NaN              NaN                NaN
3421                  NaN              NaN                NaN
4549                  NaN              NaN                NaN
...                   ...              ...                ...
375064                NaN              NaN                NaN
375065                NaN              NaN                NaN
375066                NaN              NaN                NaN
375067                NaN              NaN                NaN
375068                NaN              NaN                NaN

        Rob actual bilge  Qty sludge disposed
0                    NaN                  NaN
15                   NaN                  NaN
504                  NaN                  NaN
3421                 NaN                  NaN
4549                 NaN                  NaN
...                  ...                  ...
375064               NaN                  NaN
375065               NaN                  NaN
375066               NaN                  NaN
375067               NaN                  NaN
375068               NaN                  NaN

[30062 rows x 161 columns]

In [27]:
new_rows.to_csv("new_rows_dec.csv",index=False)

In [28]:
new_rows

,MessagesId,ImoNumber,vName,MessageType,DateTimeLt,DateTimeUtc,Latitude,Longitude,CargoMT,CargoTEU,...,ETB Date/Time,Steaming time m/e residual hs,Steaming time m/e residual uls,Steaming time m/e residual vls,Rpm,Shift berth hours,ROB fresh water,Rob actual sludge,Rob actual bilge,Qty sludge disposed
0,5189146,9222273,MSC BRASILIA VII,Sailing,2023-12-31 19:06:00 -05:00,2024-01-01 00:06:00,NaN,NaN,21933.7,2217.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,5189147,9222273,MSC BRASILIA VII,COSP,2023-12-31 20:18:00 -05:00,2024-01-01 01:18:00,4222N,07052W,21933.7,2217.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
504,5830206,9399765,MSC PASSION III,Delay,2024-01-01 12:00:00 +01:00,2024-01-01 11:00:00,5355N,00749E,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3421,5832436,9467445,MSC KATRINA,Delay,2024-01-04 12:00:00 +08:00,2024-01-04 04:00:00,3034N,12319E,89027.0,8780.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4549,5832435,9467445,MSC KATRINA,Delay,2024-01-05 12:00:00 +08:00,2024-01-05 04:00:00,3028N,12232E,89027.0,8780.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375064,5854136,9936642,MSC CHINA,Sludge,2024-12-25 12:00:00 +00:00,2024-12-25 12:00:00,NaN,NaN,141518.0,20053.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
375065,5854134,9936642,MSC CHINA,Sludge,2024-12-25 12:00:00 +00:00,2024-12-25 12:00:00,NaN,NaN,141518.0,20053.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
375066,5832965,9360271,MSC CAPE III,Sludge,2024-12-26 07:00:00 +00:00,2024-12-26 07:00:00,NaN,NaN,14042.0,1403.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
375067,5852452,9243409,MSC BRIDGEPORT,Sludge,2024-12-28 12:00:00 +00:00,2024-12-28 12:00:00,NaN,NaN,60833.0,6650.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
375068,5853166,9243409,MSC BRIDGEPORT,EGCS Waste,2024-12-29 12:00:00 +00:00,2024-12-29 12:00:00,NaN,NaN,60833.0,6650.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:

imo_to_remove = [9618305, 9143879, 9256365, 9618317, 9135638, 9618264, 9618290]

# Step 1: Extract rows with the specified IMOs to a separate DataFrame
imos_to_remove_df = df2[df2['ImoNumber'].isin(imos_to_remove)]

# Step 2: Save the rows with specified IMOs to a CSV file
imos_to_remove_df.to_csv('charter_imos_dec.csv', index=False)

In [35]:
imos_to_remove_df

,MessagesId,ImoNumber,vName,MessageType,DateTimeLt,DateTimeUtc,Latitude,Longitude,CargoMT,CargoTEU,...,ETB Date/Time,Steaming time m/e residual hs,Steaming time m/e residual uls,Steaming time m/e residual vls,Rpm,Shift berth hours,ROB fresh water,Rob actual sludge,Rob actual bilge,Qty sludge disposed
298,5191837,9143879,MSC LILO F,Port Noon,2024-01-01 12:00:00 +03:00,2024-01-01 09:00:00,NaN,NaN,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,50.0,NaN,NaN,NaN
392,5189396,9618264,MSC ABIDJAN,Delay,2024-01-01 12:00:00 +02:00,2024-01-01 10:00:00,3317S,01721E,36869.0,2291.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
393,5190792,9618290,MSC ADELAIDE,Delay,2024-01-01 12:00:00 +02:00,2024-01-01 10:00:00,2920S,03216E,35148.1,2532.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
429,5189878,9135638,MSC JEANNE,Noon,2024-01-01 12:00:00 +01:00,2024-01-01 11:00:00,5538N,01528E,14950.4,1576.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
513,5189849,9618305,MSC ATHENS,Delay,2024-01-01 12:00:00 +01:00,2024-01-01 11:00:00,5132N,00248E,28484.0,2581.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
374711,5858084,9618317,MSC ATHOS,Port Noon,2024-12-08 12:00:00 +01:00,2024-12-08 11:00:00,NaN,NaN,34983.0,3208.0,...,NaN,NaN,NaN,NaN,NaN,0.0,291.0,NaN,NaN,NaN
374860,5857994,9256365,MSC TURIN II,Sailing,2024-12-08 19:54:00 +03:00,2024-12-08 16:54:00,NaN,NaN,7763.0,1000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
374890,5857995,9256365,MSC TURIN II,COSP,2024-12-08 20:12:00 +03:00,2024-12-08 17:12:00,4053N,02731E,7763.0,1000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
374930,5858281,9135638,MSC JEANNE,Sailing,2024-12-09 00:30:00 +03:00,2024-12-08 21:30:00,NaN,NaN,16385.0,356.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
374931,5858289,9135638,MSC JEANNE,COSP,2024-12-09 00:48:00 +03:00,2024-12-08 21:48:00,4026N,02905E,16385.0,356.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN