In [1]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('NOONDATA.csv')

df.head()

,UID,mail_date,GID,Fleet,Class,Vessel_Name,IMO_No,Voyage_Name,VOY,VoyCondition,...,ais_Relative_wind_direction,ais_Corrected_power,ais_draft_pow,ais_fo_nor,ais_speed_performance,ais_Propulsive_eff,ais_Ref_speed,Power_ME_Model,NPP_Nor_pow,ais_PI
0,594025,02-01-23 10:26,NaN,NaN,NaN,MKW,NaN,LIANYUNGANG-BALBOA,NaN,Laden,...,14.536297,4663.101269,4356.280814,10.594729,88.549777,82.026021,14.206754,5306.92,2701.609108,-0.579533
1,594062,02-01-23 10:41,NaN,NaN,NaN,BEL,NaN,MINA SAQR-PARADIP,NaN,Laden,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,594064,02-01-23 10:41,NaN,NaN,NaN,MAM,NaN,POINT LISAS-HOUSTON,NaN,Laden,...,40.348460,2189.872196,2465.061386,9.941512,98.882872,95.055637,12.199336,2267.79,2424.855099,-0.448953
3,594065,02-01-23 10:41,NaN,NaN,NaN,MAW,NaN,ONSAN-Ras Al Khair,NaN,Laden,...,126.132355,1979.969753,1945.179642,13.703970,24.786628,28.909717,11.131817,3200.36,3833.560559,-5.762237
4,594066,02-01-23 10:41,NaN,NaN,NaN,MAZ,NaN,Krishnapatnam-KAKINADA,NaN,Laden,...,3.011646,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
df.head()

,UID,mail_date,GID,Fleet,Class,Vessel_Name,IMO_No,Voyage_Name,VOY,VoyCondition,VoyageNo,Voyage_Code,Stoppages,StoppagesHH,StoppagesMM,Report_Type,Status,Lattitude,Longitude,Corrected_Date,ReportMonth,REPORT_DATE_TIME,REPORT_DATE_TIME_Offset,TimeZone,PORT_CODE,PORT,Depart_Arrival,Departure_Date,DepPort,Arrival_Date,ArrivalPort,ArrivalPortAgent,Date_Berthed,COSP_Date,SBEDate,FWEDate,COSP_Time,EOSP_Date,Date_Anchored,CharterPartyCons,CharterPartySpeed,CHARTERER_NAME,CARGO_TOTAL,CARGO_TOTAL_TEU,TEU_FULL,TEU_EMPTY,Laden20Ft,Laden40Ft,Laden45Ft,Empty20Ft,Empty40Ft,Empty45Ft,REFRLaden20Ft,REFRLaden40Ft,TOTAL_Cargo_Loaded,TOTAL_Cargo_Discharged,BallastWeight,MILES_BY_GPS,Distance_to_Go,STW,SOG,RPM,SLIP,DRAFT_AFT,DRAFT_FWD,DRAFT,DISPLACEMENT,COURSE_AT_SEA,WindDirection,WindSpeed_kn,SEA_STATE,WindForce,WAVE_HEIGHT,SEA_DIRECTION,CurrentDirection,CurrentStrength,AMBIENT_TEMP,SW_TEMP,TIME_at_SEA,TEMP_MIN,TEMP_MAX,ExhTempMin,ExhTempMax,EngRoomTemp,AuxTempMin1,AuxTempMin2,AuxTempMin3,AuxTempMin4,AuxTempMax1,AuxTempMax2,AuxTempMax3,AuxTempMax4,AEFOInletTemp,ME_TOTAL_REVS_COUNTER,METhermalLoad,MELoadIndicator,METCNo1RPM,METCNo2RPM,STEAMING_TIME_M_E_HS,STEAMING_TIME_M_E_LS,STEAMING_TIME_M_E_MDO,STEAMING_TIME_M_E_MGO,STEAMING_TIME_M_E_MGO_LS,TOTAL_STEAMING_TIME,M_E_FUEL_ONLY_STEAMING_TIME,STEAMING_TIME_AUX_1,STEAMING_TIME_AUX_2,STEAMING_TIME_AUX_3,STEAMING_TIME_AUX_4,STEAMING_TIME_AUX_5,STEAMING_TIME_SH_GEN,STEAMING_TIME_TG,Tank_cleaning_time,Cargo_Heating_Time,Inert_Gas_Time,POWER_kW,STEAMING_KWHR_TOTAL,TotalAUXLoad,STEAMING_LOAD_KW_AUX_1,STEAMING_LOAD_KW_AUX_2,STEAMING_LOAD_KW_AUX_3,STEAMING_LOAD_KW_AUX_4,STEAMING_LOAD_KW_AUX_5,STEAMING_LOAD_KW_SH_GEN,STEAMING_LOAD_KW_TG,BligPump,Weather_True_Wind_Direction,Weather_True_Wind_Speed,Weather_Wave_Height,Weather_Wave_Direction,FUEL_HS,FUEL_LS,FUEL_MDO,FUEL_MGO_HS,FUEL_MGO_LS,M_E_FOC,FUEL_M_E_HS,FUEL_M_E_LS,FUEL_M_E_MDO,FUEL_M_E_MGO_HS,FUEL_M_E_MGO_LS,FUEL_ME_VLSFOH,FUEL_ME_VLSFOL,FUEL_AUX_HS,FUEL_AUX_LS,FUEL_AUX_MDO,FUEL_AUX_MGO_HS,FUEL_AUX_MGO_LS,FUEL_AUX_VLSFOH,FUEL_AUX_VLSFOL,FUEL_BOILER_HS,FUEL_BOILER_LS,FUEL_BOILER_MDO,FUEL_BOILER_MGO_HS,FUEL_BOILER_MGO_LS,FUEL_BOILER_VLSFOH,FUEL_BOILER_VLSFOL,ROB_Fuel_HSFO,ROB_Fuel_LSFO,ROB_Fuel_MDO,ROB_Fuel_MGO_HS,ROB_Fuel_MGO_LS,ROB_Fuel_Tanktainer_MGO,ROB_MECC,ROB_MECYL_LOWBN,ROB_CYL_HighBN,ROB_AECC,ROB_HYD,ROB_FO_SLUDGE,ROB_LO_SLUDGE,ROB_BILGE,ROB_OILI_BILGE_TANK,ROB_GARBAGE,ROB_FRESH_WATER,ROB_VLSFOL,ROB_VLSFOH,GeneratedFreshWater,ConsumedFreshWater,CY_OIL_gm_hr,CONS_MECC,CONS_MECYL_LOWBN,MECYLLube_HighBN,CONS_AECC,CONS_HYD,FW_RECEIVED,HS_RECEIVED,MGO_RECEIVED,MDO_RECEIVED,LUB_OIL_RECEIVED_MECYL,LUB_OIL_RECEIVED_MECC,LUB_OIL_RECEIVED_AECC,HYD_RECEIVED,VLSFOHeavy_Recieved,VLSFOLight_Recieved,RECMECYL_HighBN,LUB_ADDED_TO_SYSTEM_MECC,LUB_ADDED_TO_SYSTEM_AECC,LUB_ADDED_TO_THRUSTERS,FO_per_24Hrs,SFOC,SCOC,Cargo_Transport_Work,TEU_Transport_Work,TOTAL_FO,TOTAL_CO2,EEOI,ECA_Y_N,EU_Y_N,Sea_Time,EngineDistance,LubeOilPressure_BAR,MESCAVPressure_BAR,SCAVTEMP,SECA_ENTRY_TIME,SECA_ENTRY_LAT,SECA_ENTRY_LONG,SECA_EXIT_TIME,SECA_EXIT_LAT,SECA_EXIT_LONG,MANVRNG_MILES_BY_GPS,MANVRNG_MILES_BY_SPEED_LOG,TANKTAINER_TRANSFD_QUANTITY,BALLAST,TANKTAINER_NUMBER,SLUDGE_REMOVED_FO,SLUDGE_REMOVED_LO,CY_M_E_UNDER_PISTON_TEMP,QTYBallasted,QTYDeBallasted,BWTS,BWTSHrs,ETA_PORT,ETA_PORT_CODE,ETA_DATE_TIME,ETA_DATE_TIME_Offset,ETB_port,ETB_DATE_TIME,ETB_DATE_TIME_Offset,ETD_port,ETD_DATE_TIME,ETD_DATE_TIME_Offset,REQUESTED_SPEED,GRADES_ROB,Bunker_Order,Remarks,Fuel_Type,Carbon_Factor,Sulphur_Content_PC,Quantity,Port_Delivery,Product_Quality,Tanktainer_Number_1,Supplier,Delivery,Vol_Lt,Den,Vis,SinceLastReport,AllFastDate,BilgeWaterLanded,OilyBilgWaterLanded,SeasonalLoadLines,Sludgelanded,SootLanded,GarbageLanded,Calorific_Value_of_Fuel,FO_Temperature_at_ME_Inlet,Fuel_Oil_Specific_Gravity,Alert_FW_Generated_24_hrs,Alert_FW_ROB,Alert_ME_o,Alert_AE_Exh_Temp,Alert_ME_Cyl_Oil,Alert_ME_Sys_Oil,Alert_AE_Sys_Oil,Alert_Bilge_water_Tank_ROB,Alert_Oil_Bilge_Tank,Alert_Waste_Oil_Sludge_Tank,Alert_AE_FO_Inlet_temp,Alert_Blr_FO_Consumption_at_sea,Alert_exhtemp,Alert_good_weather,Alert_windforce,Alert_slip,Alert_scavtemp,Alert_fuel,Alert_SOG,Alert_RPM,Alert_POWER,Alert_chrterpartycons_speed,Alert_voycond_cargo,Alert_duplicate,Alert_power_mcr,heversine_distance,haversine_status,FO_per_hr,SFOC_corrected,Power_corrected,True_wind_speed,True_wind_dir,condn,numeratorcase,ref_power,ref_fuel,fuel_loss,Relative_wind_speed,Relative_wind_direction,CAA,RW,Corrected_Power,draft_pow,draft_sp_pow,fo_nor,fo_model,sfoc_model,sfoc_deviation,ref_power_corrected,ref_FO_corrected,Propulsive_eff,speed_performance,Ref_speed,P_I,updated_date,P_I_SOG,fo_nor_sog,ais_R_Wind,ais_R_Wave,ais_R_Swell,ais_STW,ais_R_Total,swell_wave_height,wind_wave_height,ais_speed,ais_wind_speed,ais_Relative_wind_speed,ais_Relative_wind_direction,ais_Corrected_power,ais_draft_pow,ais_fo_nor,ais_speed_performance,ais_Propulsive_eff,ais_Ref_speed,Power_ME_Model,NPP_Nor_pow,ais_PI
0,594025,02-01-23 10:26,NaN,NaN,NaN,MKW,NaN,LIANYUNGANG-BALBOA,NaN,Laden,15,NaN,NaN,0.0,0.0,Noon at Sea,At Sea,21.716667,-114.600000,NaN,Jan,01-01-23 12:00,01-01-23 12:00,UTC - 07:00,NaN,NaN,NaN,NaN,LIANYUNGANG,NaN,BALBOA,0.0,NaN,11-12-22 14:30,11-12-22 12:00,NaN,NaN,NaN,NaN,23.5,13.5,NaN,33104.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,608.0,315.0,2358.0,14.91,13.70,92.0,12.18,11.70,11.1,11.400,43938.0,111.0,0.0,13.0,4.0,4.0,NaN,0.0,113.0,0.4,NaN,21.0,NaN,NaN,NaN,304.0,320.0,36.0,0,0.0,362.0,0,0,0.0,370.0,0,98.0,NaN,72.0,8.35,14800.0,0.0,NaN,NaN,NaN,NaN,NaN,23.00000,23.00000,0.0,0.0,23.0,0.0,NaN,0,NaN,0.0,23.0,0.0,4900.0,NaN,390.0,0,0.0,390.0,0,NaN,NaN,NaN,0.0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,20.05,0,0,0,0.0,0,20.05,0.0,NaN,NaN,NaN,NaN,0.00,1.80,0.00,NaN,NaN,NaN,NaN,0.0,1.8,0.0,NaN,NaN,NaN,47.96,NaN,NaN,11000.0,21563.0,0.0,4550,2500.0,0.62,NaN,1.67,1.07,0.90,465.0,0.00,433.78,19.0,12.0,NaN,0.0,119.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,20.92170,164.265,NaN,10427800.0,NaN,23.65,74.52110,7.14642,N,NO,NaN,358.7,2.4,1.70,44.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,0.0,41850,98.0,0.93,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,315.161161,Ok,0.871738,164.264384,5306.92,0.360080,69.006110,0.1290,-0.336164,5537.324977,21.821923,-4.125135,7.280396,1.630847,0.727377,843.060576,5297.68,5078.025060,2385.819991,4.531907,20.898637,164.083227,0.110542,5528.087798,21.784658,104.124509,104.167536,14.730603,1.217850,02-01-23 10:41,-7.00008,13.1915,1251.321468,4.632648,21567.908850,14.124421,22823.863010,1.739182,0.050674,14.050000,1.929494,7.348332,14.536297,4663.101269,4356.280814,10.594729,88.549777,82.026021,14.206754,5306.92,2701.609108,-0.579533
1,594062,02-01-23 10:41,NaN,NaN,NaN,BEL,NaN,MINA SAQR-PARADIP,NaN,Laden,40,NaN,No,0.0,0.0,Noon At Anchor,Manoeuvring,20.183333,86.733333,NaN,Jan,01-01-23 12:00,01-01-23 12:00,UTC + 05:30,NaN,NaN,NaN,NaN,MINA SAQR,NaN,PARADIP,0.0,NaN,21-12-22 9:00,21-12-22 7:42,NaN,NaN,31-12-22 9:00,NaN,31.5,13.5,NaN,79570.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,530.0,14.0,8.0,10.50,10.53,0.0,0.00,14.50,14.5,14.500,94426.0,0.0,45.0,9.0,2.0,3.0,NaN,200.0,200.0,0.5,NaN,25.0,NaN,NaN,NaN,0.0,0.0,40.0,0,240.0,0.0,0,0,260.0,0.0,0,88.0,NaN,0.0,0.00,0.0,0.0,NaN,NaN,NaN,NaN,NaN,1.33333,1.33333,0.0,12.0,0.0,0.0,NaN,0,NaN,0.0,0.0,0.0,0.0,NaN,280.0,0,280.0,0.0,0,NaN,NaN,NaN,0.0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,0.00,0,0,0,0.0,0,0.00,0.0,NaN,NaN,NaN,NaN,0.00,0.00,0.00,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,120.60,NaN,NaN,14000.0,11685.8,6000.0,2800,4209.0,2.30,NaN,3.60,14.70,0.04,290.0,0.00,1412.22,0.0,7.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.00000,0.000,NaN,1113980.0,NaN,0.00,0.00000,0.00000,N,NO,NaN,0.0,0.0,0.00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,0.0,41480,50.0,945.90,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.791362,Ok,NaN,NaN,0.00,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,-8.174910,0.000000,0.000000,0.000000,0.000000,NaN,NaN,0.000000,0.000000,0.000000,02-01-23 10:57,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,594064,02-01-23 10:41,NaN,NaN,NaN,MAM,NaN,POINT LISAS-HOUSTON,NaN,Laden,40,NaN,No,0.0,0.0,Noon at Sea,At Sea,25.316667,-93.116667,NaN,Jan,01-01-23 12:00,01-01-23 12:00,UTC - 06:00,NaN,NaN,NaN,NaN,POINT LISAS,NaN,HOUSTON,0.0,NaN,25-12-22 18:00,25-12-22 16:50,NaN,NaN,NaN,NaN,15.7,12.5,NaN,12503.4,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,205.0,305.0,284.0,13.92,12.20,98.0,-1.63,8.20,6.7,7.450,20147.0,300.0,135.0,13.0,3.0,4.0,NaN,315.0,120.0,1.5,NaN,26.0,NaN,NaN,NaN,335.0,345.0,39.0,0,0.0,350.0,0,0,0.0,362.0,0,85.0,NaN,45.0,5.20,12400.0,0.0,NaN,NaN,NaN,NaN,NaN,25.00000,25.00000,0.0,2.8,25.0,0.0,NaN,0,NaN,0.0,0.0,0.0,2200.0,NaN,280.0,0,0.0,280.0,0,NaN,NaN,NaN,0.0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,10.10,0,0,0,0.0,0,0.00,10.1,NaN,NaN,NaN,NaN,0.00,0.00,1.26,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,60.50,NaN,NaN,13900.0,5510.0,0.0,5820,3100.0,7.47,NaN,6.41,0.00,1.83,135.0,178.44,0.00,10.0,27.0,NaN,0.0,185.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,9.69600,178.147,NaN,3813530.0,NaN,11.36,35.79540,9.38642,N,NO,NaN,300.1,2.0,0.90,45.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,0.0,42030,85.0,0.91,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,303.479526,Ok,0.404000,178.147020,2267.79,11.977175,96.746790,-1.4071,11.894237,3590.768143,14.926452,-35.041495,5.072793,127.510579,-0.383679,-12272.893740,2393.33,2725.335022,1588.102377,0.597396,9.578716,175.992124,1.224420,3716.310168,15.449556,159.339484,163.873647,12.500851,11.352423,02-01-23 10:57,-2.23209,10.2285,-5145.438773,2848.970058,3431.297642,12.144567,1134.828809,0.790193,0.486102,12.214286,4.191084,4.142528,40.348460,2189.872196,2465.061386,9.941512,98.882872,95.055637,12.199336,2267.79,2424.855099,-0.448953
3,594065,02-01-23 10:41,NaN,NaN,NaN,MAW,NaN,ONSAN-Ras Al Khair,NaN,Laden,74,NaN,No,0.0,0.0,Noon at Sea,At Sea,19.883333,120.016667,NaN,Jan,01-01-23 12:00,01-01-23 12:00,UTC + 09:00,NaN,NaN,NaN,NaN,ONSAN,NaN,Ras Al Khair,0.0,NaN,28-12-22 16:00,28-12-22 9:24,NaN,NaN,NaN,NaN,25.0,12.0,NaN,19950.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,20.0,260.0,1482.0,11.13,10.83,108.9,13.82,9.95,9.9,9.925,25977.0,222.0,45.0,13.0,4.0,4.0,NaN,45.0,45.0,2.0,NaN,30.0,NaN,NaN,NaN,340.0,360.0,46.0,0,270.0,250.0,0,0,290.0,270.0,0,130.0,NaN,42.0,6.60,11000.0,0.0,NaN,NaN,NaN,NaN,NaN,24.00000,24.00000,0.0,24.0,4.0,0.0,NaN,0,NaN,0.0,0.0,0.0,2854.0,NaN,360.0,0,190.0,170.0,0,NaN,NaN,NaN,0.0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,13.60,0,0,0,0.0,0,13.60,0.0,NaN,NaN,NaN,NaN,0.15,1.35,0.00,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,65.75,NaN,NaN,9900.0,10279.0,2010.0,3091,1000.0,0.95,NaN,4.35,6.33,0.86,121.0,-0.01,264.86,10.0,9.0,NaN,0.0,220.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,13.60000,177.063,NaN,5187000.0,NaN,15.10,47.58830,9.17455,N,NO,NaN,301.7,2.6,1.05,42.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,0.0,41510,130.0,0.94,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,254.119108,Ok,0.566667,177.063505,3200.36,4.803013,37.899119,3.7900,-2.950341,1983.489908,8.756456,55.313982,1.493294,11.372393,0.913598,-4788.957632,3239.53,3197.572418,4264.996984,8.094497,13.491713,175.653583,0.802620,2022.658601,8.906831,65.491404,63.200971,12.660016,-12.085416,02-01-23 10:57,-14.44780,19.6701,-7876.083147,112438.477700,8816.579799,10.490375,113378.974500,2.014417,3.370665,10.285714,13.516299,9.717696,126.132355,1979.969753,1945.179642,13.703970,24.786628,28.909717,11.131817,3200.36,3833.560559,-5.762237
4,594066,02-01-23 10:41,NaN,NaN,NaN,MAZ,NaN,Krishnapatnam-KAKINADA,NaN,Laden,14,NaN,No,0.0,0.0,COSP,At Sea,14.250000,80.183333,NaN,Jan,01-01-23 14:18,01-01-23 14:18,UTC + 05:30,NaN,NaN,NaN,NaN,Krishnapatnam,NaN,KAKINADA,0.0,NaN,01-01-23 14:18,01-01-23 13:00,NaN,NaN,NaN,NaN,25.0,13.0,NaN,18274.8,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,148.0,6.0,272.0,6.15,4.62,44.1,25.93,8.60,7.4,8.000,27145.0,84.0,90.0,9.0,3.0,3.0,NaN,90.0,230.0,0.1,NaN,30.0,NaN,NaN,NaN,340.0,350.0,38.0,340,340.0,0.0,0,350,350.0,0.0,0,0.0,NaN,0.0,7.00,8200.0,0.0,NaN,NaN,NaN,NaN,NaN,1.30000,1.30000,1.3,1.3,0.0,0.0,NaN,0,NaN,0.0,0.0,0.0,0.0,NaN,760.0,380,380.0,0.0,0,NaN,NaN,NaN,0.0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,0.40,0,0,0,0.0,0,0.00,0.4,NaN,NaN,NaN,NaN,0.00,0.00,0.15,NaN,NaN,NaN,NaN,0.0,0.0,0.2,NaN,NaN,NaN,68.82,NaN,NaN,14718.0,14387.0,11665.0,1700,2200.0,2.70,NaN,0.50,0.00,0.02,145.0,161.68,0.00,0.0,0.0,NaN,0.0,0.0,25.0,0.0,0.0,0.0,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,7.38462,190.768,NaN,109649.0,NaN,0.75,2.36325,21.55290,N,YES,NaN,8.1,1.6,0.75,45.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,150.0,0.0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,2.7,41760,90.0,0.94,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.849424,Ok,0.307692,190.768947,1612.91,5.203949,158.827244,-4.8527,-1.879584,144.738946,3.228194,128.753732,5.642239,50.840813,0.482142,3581.732726,1596.72,1647.760190,24368.439070,6.810002,7.897009,204.005214,-6.488454,128.551766,3.178845,43.046864,7.970176,11.160773,-44.896290,02-01-23 10:57,-58.63060,739.2500,6070.604980,0.000000,0.000000,6.100000,6070.604980,NaN,NaN,6.100000,3.250902,6.323306,3.011646,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# SFOC Calculation

In [ ]:
#SFOC (g/kwh) = Mass of fuel consumed per hour / Power developed in KW

In [4]:
fuel_columns = ['FUEL_M_E_HS', 'FUEL_M_E_LS', 'FUEL_M_E_MDO', 'FUEL_M_E_MGO_HS', 'FUEL_M_E_MGO_LS', 'FUEL_ME_VLSFOH', 'FUEL_ME_VLSFOL']
df[fuel_columns] = df[fuel_columns] * 1000000 

df['SFOC_Calc'] = (df[fuel_columns].sum(axis=1) / (df['TOTAL_STEAMING_TIME'] * df['POWER_kW'])).round(2)
df.head(10)

,UID,mail_date,GID,Fleet,Class,Vessel_Name,IMO_No,Voyage_Name,VOY,VoyCondition,VoyageNo,Voyage_Code,Stoppages,StoppagesHH,StoppagesMM,Report_Type,Status,Lattitude,Longitude,Corrected_Date,ReportMonth,REPORT_DATE_TIME,REPORT_DATE_TIME_Offset,TimeZone,PORT_CODE,PORT,Depart_Arrival,Departure_Date,DepPort,Arrival_Date,ArrivalPort,ArrivalPortAgent,Date_Berthed,COSP_Date,SBEDate,FWEDate,COSP_Time,EOSP_Date,Date_Anchored,CharterPartyCons,CharterPartySpeed,CHARTERER_NAME,CARGO_TOTAL,CARGO_TOTAL_TEU,TEU_FULL,TEU_EMPTY,Laden20Ft,Laden40Ft,Laden45Ft,Empty20Ft,Empty40Ft,Empty45Ft,REFRLaden20Ft,REFRLaden40Ft,TOTAL_Cargo_Loaded,TOTAL_Cargo_Discharged,BallastWeight,MILES_BY_GPS,Distance_to_Go,STW,SOG,RPM,SLIP,DRAFT_AFT,DRAFT_FWD,DRAFT,DISPLACEMENT,COURSE_AT_SEA,WindDirection,WindSpeed_kn,SEA_STATE,WindForce,WAVE_HEIGHT,SEA_DIRECTION,CurrentDirection,CurrentStrength,AMBIENT_TEMP,SW_TEMP,TIME_at_SEA,TEMP_MIN,TEMP_MAX,ExhTempMin,ExhTempMax,EngRoomTemp,AuxTempMin1,AuxTempMin2,AuxTempMin3,AuxTempMin4,AuxTempMax1,AuxTempMax2,AuxTempMax3,AuxTempMax4,AEFOInletTemp,ME_TOTAL_REVS_COUNTER,METhermalLoad,MELoadIndicator,METCNo1RPM,METCNo2RPM,STEAMING_TIME_M_E_HS,STEAMING_TIME_M_E_LS,STEAMING_TIME_M_E_MDO,STEAMING_TIME_M_E_MGO,STEAMING_TIME_M_E_MGO_LS,TOTAL_STEAMING_TIME,M_E_FUEL_ONLY_STEAMING_TIME,STEAMING_TIME_AUX_1,STEAMING_TIME_AUX_2,STEAMING_TIME_AUX_3,STEAMING_TIME_AUX_4,STEAMING_TIME_AUX_5,STEAMING_TIME_SH_GEN,STEAMING_TIME_TG,Tank_cleaning_time,Cargo_Heating_Time,Inert_Gas_Time,POWER_kW,STEAMING_KWHR_TOTAL,TotalAUXLoad,STEAMING_LOAD_KW_AUX_1,STEAMING_LOAD_KW_AUX_2,STEAMING_LOAD_KW_AUX_3,STEAMING_LOAD_KW_AUX_4,STEAMING_LOAD_KW_AUX_5,STEAMING_LOAD_KW_SH_GEN,STEAMING_LOAD_KW_TG,BligPump,Weather_True_Wind_Direction,Weather_True_Wind_Speed,Weather_Wave_Height,Weather_Wave_Direction,FUEL_HS,FUEL_LS,FUEL_MDO,FUEL_MGO_HS,FUEL_MGO_LS,M_E_FOC,FUEL_M_E_HS,FUEL_M_E_LS,FUEL_M_E_MDO,FUEL_M_E_MGO_HS,FUEL_M_E_MGO_LS,FUEL_ME_VLSFOH,FUEL_ME_VLSFOL,FUEL_AUX_HS,FUEL_AUX_LS,FUEL_AUX_MDO,FUEL_AUX_MGO_HS,FUEL_AUX_MGO_LS,FUEL_AUX_VLSFOH,FUEL_AUX_VLSFOL,FUEL_BOILER_HS,FUEL_BOILER_LS,FUEL_BOILER_MDO,FUEL_BOILER_MGO_HS,FUEL_BOILER_MGO_LS,FUEL_BOILER_VLSFOH,FUEL_BOILER_VLSFOL,ROB_Fuel_HSFO,ROB_Fuel_LSFO,ROB_Fuel_MDO,ROB_Fuel_MGO_HS,ROB_Fuel_MGO_LS,ROB_Fuel_Tanktainer_MGO,ROB_MECC,ROB_MECYL_LOWBN,ROB_CYL_HighBN,ROB_AECC,ROB_HYD,ROB_FO_SLUDGE,ROB_LO_SLUDGE,ROB_BILGE,ROB_OILI_BILGE_TANK,ROB_GARBAGE,ROB_FRESH_WATER,ROB_VLSFOL,ROB_VLSFOH,GeneratedFreshWater,ConsumedFreshWater,CY_OIL_gm_hr,CONS_MECC,CONS_MECYL_LOWBN,MECYLLube_HighBN,CONS_AECC,CONS_HYD,FW_RECEIVED,HS_RECEIVED,MGO_RECEIVED,MDO_RECEIVED,LUB_OIL_RECEIVED_MECYL,LUB_OIL_RECEIVED_MECC,LUB_OIL_RECEIVED_AECC,HYD_RECEIVED,VLSFOHeavy_Recieved,VLSFOLight_Recieved,RECMECYL_HighBN,LUB_ADDED_TO_SYSTEM_MECC,LUB_ADDED_TO_SYSTEM_AECC,LUB_ADDED_TO_THRUSTERS,FO_per_24Hrs,SFOC,SCOC,Cargo_Transport_Work,TEU_Transport_Work,TOTAL_FO,TOTAL_CO2,EEOI,ECA_Y_N,EU_Y_N,Sea_Time,EngineDistance,LubeOilPressure_BAR,MESCAVPressure_BAR,SCAVTEMP,SECA_ENTRY_TIME,SECA_ENTRY_LAT,SECA_ENTRY_LONG,SECA_EXIT_TIME,SECA_EXIT_LAT,SECA_EXIT_LONG,MANVRNG_MILES_BY_GPS,MANVRNG_MILES_BY_SPEED_LOG,TANKTAINER_TRANSFD_QUANTITY,BALLAST,TANKTAINER_NUMBER,SLUDGE_REMOVED_FO,SLUDGE_REMOVED_LO,CY_M_E_UNDER_PISTON_TEMP,QTYBallasted,QTYDeBallasted,BWTS,BWTSHrs,ETA_PORT,ETA_PORT_CODE,ETA_DATE_TIME,ETA_DATE_TIME_Offset,ETB_port,ETB_DATE_TIME,ETB_DATE_TIME_Offset,ETD_port,ETD_DATE_TIME,ETD_DATE_TIME_Offset,REQUESTED_SPEED,GRADES_ROB,Bunker_Order,Remarks,Fuel_Type,Carbon_Factor,Sulphur_Content_PC,Quantity,Port_Delivery,Product_Quality,Tanktainer_Number_1,Supplier,Delivery,Vol_Lt,Den,Vis,SinceLastReport,AllFastDate,BilgeWaterLanded,OilyBilgWaterLanded,SeasonalLoadLines,Sludgelanded,SootLanded,GarbageLanded,Calorific_Value_of_Fuel,FO_Temperature_at_ME_Inlet,Fuel_Oil_Specific_Gravity,Alert_FW_Generated_24_hrs,Alert_FW_ROB,Alert_ME_o,Alert_AE_Exh_Temp,Alert_ME_Cyl_Oil,Alert_ME_Sys_Oil,Alert_AE_Sys_Oil,Alert_Bilge_water_Tank_ROB,Alert_Oil_Bilge_Tank,Alert_Waste_Oil_Sludge_Tank,Alert_AE_FO_Inlet_temp,Alert_Blr_FO_Consumption_at_sea,Alert_exhtemp,Alert_good_weather,Alert_windforce,Alert_slip,Alert_scavtemp,Alert_fuel,Alert_SOG,Alert_RPM,Alert_POWER,Alert_chrterpartycons_speed,Alert_voycond_cargo,Alert_duplicate,Alert_power_mcr,heversine_distance,haversine_status,FO_per_hr,SFOC_corrected,Power_corrected,True_wind_speed,True_wind_dir,condn,numeratorcase,ref_power,ref_fuel,fuel_loss,Relative_wind_speed,Relative_wind_direction,CAA,RW,Corrected_Power,draft_pow,draft_sp_pow,fo_nor,fo_model,sfoc_model,sfoc_deviation,ref_power_corrected,ref_FO_corrected,Propulsive_eff,speed_performance,Ref_speed,P_I,updated_date,P_I_SOG,fo_nor_sog,ais_R_Wind,ais_R_Wave,ais_R_Swell,ais_STW,ais_R_Total,swell_wave_height,wind_wave_height,ais_speed,ais_wind_speed,ais_Relative_wind_speed,ais_Relative_wind_direction,ais_Corrected_power,ais_draft_pow,ais_fo_nor,ais_speed_performance,ais_Propulsive_eff,ais_Ref_speed,Power_ME_Model,NPP_Nor_pow,ais_PI,SFOC_Calc
0,594025,02-01-23 10:26,NaN,NaN,NaN,MKW,NaN,LIANYUNGANG-BALBOA,NaN,Laden,15,NaN,NaN,0.0,0.0,Noon at Sea,At Sea,21.716667,-114.600000,NaN,Jan,01-01-23 12:00,01-01-23 12:00,UTC - 07:00,NaN,NaN,NaN,NaN,LIANYUNGANG,NaN,BALBOA,0.0,NaN,11-12-22 14:30,11-12-22 12:00,NaN,NaN,NaN,NaN,23.5,13.5,NaN,33104.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,608.0,315.0,2358.0,14.91,13.70,92.0,12.18,11.70,11.1,11.400,43938.0,111.0,0.0,13.0,4.0,4.0,NaN,0.0,113.0,0.4,NaN,21.0,NaN,NaN,NaN,304.0,320.0,36.0,0,0.0,362.0,0,0,0.0,370.0,0,98.0,NaN,72.0,8.35,14800.0,0.0,NaN,NaN,NaN,NaN,NaN,23.00000,23.00000,0.0,0.0,23.0,0.0,NaN,0,NaN,0.0,23.0,0.0,4900.0,NaN,390.0,0,0.0,390.0,0,NaN,NaN,NaN,0.0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,20.05,0,0,0,0.0,0,20050000.0,0.0,NaN,NaN,NaN,NaN,0.00,1.80,0.00,NaN,NaN,NaN,NaN,0.0,1.80,0.00,NaN,NaN,NaN,47.96,NaN,NaN,11000.0,21563.0,0.0,4550,2500.0,0.62,NaN,1.67,1.07,0.90,465.0,0.00,433.78,19.0,12.0,NaN,0.0,119.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,20.92170,164.265,NaN,10427800.0,NaN,23.65,74.52110,7.14642,N,NO,NaN,358.7,2.4,1.70,44.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,0.0,41850,98.0,0.93,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,315.161161,Ok,0.871738,164.264384,5306.920,0.360080,69.006110,0.1290,-0.336164,5537.324977,21.821923,-4.125135,7.280396,1.630847,0.727377,843.060576,5297.680,5078.025060,2385.819991,4.531907,20.898637,164.083227,0.110542,5528.087798,21.784658,104.124509,104.167536,14.730603,1.217850,02-01-23 10:41,-7.00008,13.1915,1251.321468,4.632648,21567.908850,14.124421,22823.863010,1.739182,0.050674,14.050000,1.929494,7.348332,14.536297,4663.101269,4356.280814,10.594729,88.549777,82.026021,14.206754,5306.92,2701.609108,-0.579533,177.91
1,594062,02-01-23 10:41,NaN,NaN,NaN,BEL,NaN,MINA SAQR-PARADIP,NaN,Laden,40,NaN,No,0.0,0.0,Noon At Anchor,Manoeuvring,20.183333,86.733333,NaN,Jan,01-01-23 12:00,01-01-23 12:00,UTC + 05:30,NaN,NaN,NaN,NaN,MINA SAQR,NaN,PARADIP,0.0,NaN,21-12-22 9:00,21-12-22 7:42,NaN,NaN,31-12-22 9:00,NaN,31.5,13.5,NaN,79570.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,530.0,14.0,8.0,10.50,10.53,0.0,0.00,14.50,14.5,14.500,94426.0,0.0,45.0,9.0,2.0,3.0,NaN,200.0,200.0,0.5,NaN,25.0,NaN,NaN,NaN,0.0,0.0,40.0,0,240.0,0.0,0,0,260.0,0.0,0,88.0,NaN,0.0,0.00,0.0,0.0,NaN,NaN,NaN,NaN,NaN,1.33333,1.33333,0.0,12.0,0.0,0.0,NaN,0,NaN,0.0,0.0,0.0,0.0,NaN,280.0,0,280.0,0.0,0,NaN,NaN,NaN,0.0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,0.00,0,0,0,0.0,0,0.0,0.0,NaN,NaN,NaN,NaN,0.00,0.00,0.00,NaN,NaN,NaN,NaN,0.0,0.00,0.00,NaN,NaN,NaN,120.60,NaN,NaN,14000.0,11685.8,6000.0,2800,4209.0,2.30,NaN,3.60,14.70,0.04,290.0,0.00,1412.22,0.0,7.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.00000,0.000,NaN,1113980.0,NaN,0.00,0.00000,0.00000,N,NO,NaN,0.0,0.0,0.00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,0.0,41480,50.0,945.90,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.791362,Ok,NaN,NaN,0.000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000000,-8.174910,0.000000,0.000000,0.000000,0.000000,NaN,NaN,0.000000,0.000000,0.000000,02-01-23 10:57,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,594064,02-01-23 10:41,NaN,NaN,NaN,MAM,NaN,POINT LISAS-HOUSTON,NaN,Laden,40,NaN,No,0.0,0.0,Noon at Sea,At Sea,25.316667,-93.116667,NaN,Jan,01-01-23 12:00,01-01-23 12:00,UTC - 06:00,NaN,NaN,NaN,NaN,POINT LISAS,NaN,HOUSTON,0.0,NaN,25-12-22 18:00,25-12-22 16:50,NaN,NaN,NaN,NaN,15.7,12.5,NaN,12503.4,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,205.0,305.0,284.0,13.92,12.20,98.0,-1.63,8.20,6.7,7.450,20147.0,300.0,135.0,13.0,3.0,4.0,NaN,315.0,120.0,1.5,NaN,26.0,NaN,NaN,NaN,335.0,345.0,39.0,0,0.0,350.0,0,0,0.0,362.0,0,85.0,NaN,45.0,5.20,12400.0,0.0,NaN,NaN,NaN,NaN,NaN,25.00000,25.00000,0.0,2.8,25.0,0.0,NaN,0,NaN,0.0,0.0,0.0,2200.0,NaN,280.0,0,0.0,280.0,0,NaN,NaN,NaN,0.0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,10.10,0,0,0,0.0,0,0.0,10100000.0,NaN,NaN,NaN,NaN,0.00,0.00,1.26,NaN,NaN,NaN,NaN,0.0,0.00,0.00,NaN,NaN,NaN,60.50,NaN,NaN,13900.0,5510.0,0.0,5820,3100.0,7.47,NaN,6.41,0.00,1.83,135.0,178.44,0.00,10.0,27.0,NaN,0.0,185.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,9.69600,178.147,NaN,3813530.0,NaN,11.36,35.79540,9.38642,N,NO,NaN,300.1,2.0,0.90,45.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,0.0,42030,85.0,0.91,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,303.479526,Ok,0.404000,178.147020,2267.790,11.977175,96.746790,-1.4071,11.894237,3590.768143,14.926452,-35.041495,5.072793,127.510579,-0.383679,-12272.893740,2393.330,2725.335022,1588.102377,0.597396,9.578716,175.992124,1.224420,3716.310168,15.449556,159.339484,163.873647,12.500851,11.352423,02-01-23 10:57,-2.23209,10.2285,-5145.438773,2848.970058,3431.297642,12.144567,1134.828809,0.790193,0.486102,12.214286,4.191084,4.142528,40.348460,2189.872196,2465.061386,9.941512,98.882872,95.055637,12.199336,2267.79,2424.855099,-0.448953,183.64
3,594065,02-01-23 10:41,NaN,NaN,NaN,MAW,NaN,ONSAN-Ras Al Khair,NaN,Laden,74,NaN,No,0.0,0.0,Noon at Sea,At Sea,19.883333,120.016667,NaN,Jan,01-01-23 12:00,01-01-23 12:00,UTC + 09:00,NaN,NaN,NaN,NaN,ONSAN,NaN,Ras Al Khair,0.0,NaN,28-12-22 16:00,28-12-22 9:24,NaN,NaN,NaN,NaN,25.0,12.0,NaN,19950.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,20.0,260.0,1482.0,11.13,10.83,108.9,13.82,9.95,9.9,9.925,25977.0,222.0,45.0,13.0,4.0,4.0,NaN,45.0,45.0,2.0,NaN,30.0,NaN,NaN,NaN,340.0,360.0,46.0,0,270.0,250.0,0,0,290.0,270.0,0,130.0,NaN,42.0,6.60,11000.0,0.0,NaN,NaN,NaN,NaN,NaN,24.00000,24.00000,0.0,24.0,4.0,0.0,NaN,0,NaN,0.0,0.0,0.0,2854.0,NaN,360.0,0,190.0,170.0,0,NaN,NaN,NaN,0.0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,13.60,0,0,0,0.0,0,13600000.0,0.0,NaN,NaN,NaN,NaN,0.15,1.35,0.00,NaN,NaN,NaN,NaN,0.0,0.00,0.00,NaN,NaN,NaN,65.75,NaN,NaN,9900.0,10279.0,2010.0,3091,1000.0,0.95,NaN,4.35,6.33,0.86,121.0,-0.01,264.86,10.0,9.0,NaN,0.0,220.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,13.60000,177.063,NaN,5187000.0,NaN,15.10,47.58830,9.17455,N,NO,NaN,301.7,2.6,1.05,42.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,0.0,41510,130.0,0.94,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,254.119108,Ok,0.566667,177.063505,3200.360,4.803013,37.899119,3.7900,-2.950341,1983.489908,8.756456,55.313982,1.493294,11.372393,0.913598,-4788.957632,3239.530,3197.572418,4264.996984,8.094497,13.491713,175.653583,0.802620,2022.658601,8.906831,65.491404,63.200971,12.660016,-12.085416,02-01-23 10:57,-14.44780,19.6701,-7876.083147,112438.477700,8816.579799,10.490375,113378.974500,2.014417,3.370665,10.285714,13.516299,9.717696,126.132355,1979.969753,1945.179642,13.703970,24.786628,28.909717,11.131817,3200.36,3833.560559,-5.762237,198.55
4,594066,02-01-23 10:41,NaN,NaN,NaN,MAZ,NaN,Krishnapatnam-KAKINADA,NaN,Laden,14,NaN,No,0.0,0.0,COSP,At Sea,14.250000,80.183333,NaN,Jan,01-01-23 14:18,01-01-23 14:18,UTC + 05:30,NaN,NaN,NaN,NaN,Krishnapatnam,NaN,KAKINADA,0.0,NaN,01-01-23 14:18,01-01-23 13:00,NaN,NaN,NaN,NaN,25.0,13.0,NaN,18274.8,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,148.0,6.0,272.0,6.15,4.62,44.1,25.93,8.60,7.4,8.000,27145.0,84.0,90.0,9.0,3.0,3.0,NaN,90.0,230.0,0.1,NaN,30.0,NaN,NaN,NaN,340.0,350.0,38.0,340,340.0,0.0,0,350,350.0,0.0,0,0.0,NaN,0.0,7.00,8200.0,0.0,NaN,NaN,NaN,NaN,NaN,1.30000,1.30000,1.3,1.3,0.0,0.0,NaN,0,NaN,0.0,0.0,0.0,0.0,NaN,760.0,380,380.0,0.0,0,NaN,NaN,NaN,0.0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,0.40,0,0,0,0.0,0,0.0,400000.0,NaN,NaN,NaN,NaN,0.00,0.00,0.15,NaN,NaN,NaN,NaN,0.0,0.00,0.20,NaN,NaN,NaN,68.82,NaN,NaN,14718.0,14387.0,11665.0,1700,2200.0,2.70,NaN,0.50,0.00,0.02,145.0,161.68,0.00,0.0,0.0,NaN,0.0,0.0,25.0,0.0,0.0,0.0,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,7.38462,190.768,NaN,109649.0,NaN,0.75,2.36325,21.55290,N,YES,NaN,8.1,1.6,0.75,45.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,150.0,0.0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,2.7,41760,90.0,0.94,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.849424,Ok,0.307692,190.768947,1612.910,5.203949,158.827244,-4.8527,-1.879584,144.738946,3.228194,128.753732,5.642239,50.840813,0.482142,3581.732726,1596.720,1647.760190,24368.439070,6.810002,7.897009,204.005214,-6.488454,128.551766,3.178845,43.046864,7.970176,11.160773,-44.896290,02-01-23 10:57,-58.63060,739.2500,6070.604980,0.000000,0.000000,6.100000,6070.604980,NaN,NaN,6.100000,3.250902,6.323306,3.011646,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
5,594067,02-01-23 10:41,NaN,NaN,NaN,MAZ,NaN,Krishnapatnam-KAKINADA,NaN,Laden,14,NaN,NaN,0.0,0.0,SBE,Manoeuvring,14.250000,80.100000,NaN,Jan,01-01-23 13:00,01-01-23 13:00,UTC + 05:30,NaN,NaN,NaN,NaN,Krishnapatnam,NaN,KAKINADA,0.0,NaN,NaN,01-01-23 13:00,NaN,NaN,NaN,NaN,25.0,13.0,NaN,18274.8,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,148.0,0.0,6.0,0.00,0.00,0.0,0.00,8.60,7.4,8.000,27145.0,191.0,60.0,9.0,3.0,3.0,NaN,60.0,283.0,0.1,NaN,0.0,NaN,NaN,NaN,0.0,0.0,0.0,340,340.0,0.0,0,350,350.0,0.0,0,0.0,NaN,0.0,0.00,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.00000,0.00000,1.0,1.0,0.0,0.0,NaN,0,NaN,0.0,0.0,0.0,0.0,NaN,760.0,380,380.0,0.0,0,NaN,NaN,NaN,0.0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,0.00,0,0,0,0.0,0,0.0,0.0,NaN,NaN,NaN,NaN,0.00,0.00,0.12,NaN,NaN,NaN,NaN,0.0,0.00,0.18,NaN,NaN,NaN,68.82,NaN,NaN,14718.0,14387.0,11690.0,1700,2200.0,2.70,NaN,0.50,0.00,0.02,145.0,162.43,0.00,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.00000,NaN,NaN,0.0,NaN,0.30,0.94530,0.00000,N,YES,NaN,0.0,0.0,0.00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,0.0,41760,90.0,0.94,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,Ok,NaN,NaN,0.000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000000,0.707322,0.000000,0.000000,0.000000,0.000000,NaN,NaN,0.000000,0.000000,0.000000,02-01-23 10:57,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,594068,02-01-23 10:41,NaN,NaN,NaN,MAZ,NaN,SUEZ-Krishnapatnam,NaN,Laden,14,NaN,NaN,0.0,0.0,Noon At Berth,In Port,14.250000,80.100000,NaN,Jan,01-01-23 12:00,01-01-23 12:00,UTC + 05:30,NaN,NaN,NaN,NaN,SUEZ,NaN,Krishnapatnam,0.0,NaN,10-12-22 21:18,10-12-22 15:36,30-12-22 0:48,NaN,25-12-22 21:24,NaN,25.0,13.0,NaN,30204.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,389.0,0.0,0.0,0.00,0.00,0.0,0.00,8.60,7.4,8.000,39729.0,191.0,60.0,5.0,2.0,2.0,NaN,60.0,283.0,0.1,NaN,0.0,NaN,NaN,NaN,0.0,0.0,0.0,340,340.0,0.0,0,350,350.0,0.0,0,0.0,NaN,0.0,0.00,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.00000,0.00000,24.0,24.0,0.0,0.0,NaN,0,NaN,0.0,0.0,0.0,0.0,NaN,600.0,300,300.0,0.0,0,NaN,NaN,NaN,0.0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,0.00,0,0,0,0.0,0,0.0,0.0,NaN,NaN,NaN,NaN,0.00,0.00,1.50,NaN,NaN,NaN,NaN,0.0,0.00,2.50,NaN,NaN,NaN,68.82,NaN,NaN,14718.0,14387.0,11690.0,1700,2200.0,2.70,NaN,0.50,0.00,0.02,145.0,162.73,0.00,0.0,6.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.00000,NaN,NaN,0.0,NaN,4.00,12.60400,0.00000,N,YES,NaN,0.0,0.0,0.00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,0.0,41760,90.0,0.94,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,Ok,NaN,NaN,0.000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000000,0.707322,0.000000,0.000000,0.000000,0.000000,NaN,NaN,0.000000,0.000000,0.000000,02-01-23 10:57,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,594069,02-01-23 10:41,NaN,NaN,NaN,MBA,NaN,ULSAN-Mejillones,NaN,Laden,30,NaN,NaN,0.0,0.0,Noon At Berth,In Port,-23.066667,-70.400000,NaN,Jan,01-01-23 12:00,01-01-23 12:00,UTC - 03:00,NaN,NaN,NaN,NaN,ULSAN,NaN,Mejillones,0.0,NaN,17-11-22 16:54,10-11-22 11:12,31-12-22 2:36,NaN,27-12-22 16:12,NaN,18.5,12.0,NaN,18077.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,4563.0,0.0,1.0,0.00,0.00,0.0,0.00,9.18,8.3,8.740,32757.0,26.0,60.0,5.0,2.0,2.0,NaN,60.0,240.0,0.1,NaN,16.0,NaN,NaN,NaN,0.0,0.0,32.0,0,340.0,339.0,0,0,351.0,356.0,0,106.0,NaN,0.0,0.00,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.00000,0.00000,0.0,24.0,24.0,0.0,NaN,0,NaN,0.0,0.0,0.0,0.0,NaN,490.0,0,245.0,245.0,0,NaN,NaN,NaN,0.0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,0.00,0,0,0,0.0,0,0.0,0.0,NaN,NaN,NaN,NaN,0.00,0.00,3.95,NaN,NaN,NaN,NaN,0.0,0.00,1.80,NaN,NaN,NaN,71.44,NaN,NaN,11650.0,8200.0,0.0,4650,1340.0,1.02,NaN,5.31,15.85,2.92,211.0,419.51,0.00,0.0,7.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.00000,NaN,NaN,0.0,NaN,5.75,18.11820,0.00000,N,NO,NaN,0.0,0.0,0.00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,0.0,41040,108.0,0.98,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,Ok,NaN,NaN,0.000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000000,0.349000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,0.000000,0.000000,0.000000,02-01-23 10:57,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df[['SFOC','SFOC_Calc']]

               SFOC  SFOC_Calc
0        164.265000     177.91
1          0.000000        NaN
2        178.147000     183.64
3        177.063000     198.55
4        190.768000        inf
5               NaN        NaN
6               NaN        NaN
7               NaN        NaN
8               NaN        NaN
9        201.147000        inf
10       164.310000     174.32
11              NaN        NaN
12       174.199000     175.15
13       192.716000        inf
14              NaN        NaN
15       178.972000     167.41
16              NaN        NaN
17       171.292000     141.81
18              NaN        NaN
19       175.174000     133.73
20       190.058000        inf
21              NaN        NaN
22       177.913000     187.45
23       180.820000     196.29
24       181.563000     185.87
25       171.578000     172.97
26              NaN        NaN
27              NaN        inf
28              NaN        NaN
29       182.244000        inf
30       173.558000     198.14
31       179.566000     188.41
32       172.793000        inf
33       161.544000     168.78
34              NaN        NaN
35              NaN        NaN
36              NaN        inf
37       172.656000     163.22
38       186.769000     173.56
39       154.045000     154.04
40       178.426000        inf
41       172.252000     262.23
42       194.383000        inf
43       161.605000     177.88
44              NaN        NaN
45       193.662000        inf
46       179.608000     220.05
47       178.714000     188.37
48       185.158000     193.03
49       171.579000     225.62
50              NaN        inf
51              NaN        NaN
52              NaN        NaN
53              NaN        NaN
54       203.697000        inf
55       170.887000     174.35
56       165.565000     170.21
57       172.802000     186.42
58       180.230000     173.89
59       180.906000     167.53
60       184.758000     114.92
61       178.972000     168.91
62       183.222000     120.40
63       220.280000        inf
64       173.482000     130.12
65       191.301000        inf
66       175.330000     133.12
67       201.282000     156.25
68       175.376000     174.73
69       180.593000     177.99
70              NaN        NaN
71       178.068000     186.78
72       176.176000     196.46
73       177.013000        inf
74         0.000000        NaN
75              NaN        inf
76       180.645000     194.68
77       178.283000     197.04
78       170.973000     172.69
79       201.504000        inf
80       169.535000     166.80
81       181.794000     150.47
82       194.792000        inf
83              NaN        NaN
84              NaN        inf
85              NaN        NaN
86       173.197000        inf
87              NaN        NaN
88       173.607000     198.14
89       188.294000     188.29
90       179.634000     187.09
91       172.876000        inf
92              NaN        NaN
93              NaN        NaN
94       161.559000     170.31
95              NaN        NaN
96              NaN        NaN
97              NaN        NaN
98       213.606000        inf
99       174.375000     145.49
100      207.667000        inf
101      188.957000     188.17
102      161.445000     183.18
103             NaN        NaN
104      171.773000        inf
105             NaN        NaN
106      168.191000        inf
107      161.611000     177.63
108             NaN        NaN
109      175.298000     185.29
110      175.315000     179.37
111      175.260000     198.58
112             NaN        NaN
113      179.216000     185.81
114             NaN        NaN
115      205.533000        inf
116             NaN        NaN
117      181.047000        inf
118             NaN        NaN
119      171.937000     159.07
120      200.941000        inf
121             NaN        NaN
122      199.926000        inf
123      164.258000     178.57
124      164.246000     180.12
125      181.642000     211.42
126      177.253000     191.80
127      178.404000     177.14
128      202.297000        inf
129             NaN        NaN
130      165.565000     170.21
131      172.795000     186.51
132             NaN        NaN
133      213.139000        inf
134      183.848000     118.51
135      182.137000     148.12
136      196.025000        inf
137      173.950000     148.88
138             NaN        NaN
139      175.392000     181.02
140      181.152000     210.44
141      179.020000     209.17
142      171.018000     174.31
143      183.146000     146.81
144      186.302000        inf
145      199.173000        inf
146             NaN        NaN
147             NaN        NaN
148      173.668000     198.18
149      173.205000     178.04
150      179.566000     188.41
151      172.793000        inf
152             NaN        NaN
153      161.579000     227.88
154             NaN        inf
155             NaN        NaN
156             NaN        NaN
157             NaN        NaN
158             NaN        NaN
159             NaN        NaN
160      172.830000     157.43
161        0.000000        inf
162             NaN        NaN
163      161.441000     187.53
164             NaN        NaN
165             NaN        NaN
166             NaN        NaN
167      185.687000        inf
168             NaN        NaN
169             NaN        NaN
170      175.376000     183.89
171             NaN        NaN
172      178.242000     188.79
173             NaN        inf
174             NaN        NaN
175      200.292000        inf
176      171.098000     188.17
177      173.657000     165.05
178      175.785000     148.96
179      182.129000        inf
180      170.778000     191.15
181      172.795000     165.57
182      203.510000        inf
183             NaN        NaN
184      210.752000        inf
185      172.366000     191.15
186             NaN        NaN
187      164.240000     177.50
188      205.514000        inf
189      165.507000     187.02
190      172.318000     180.30
191      182.352000     126.34
192      179.690000     165.51
193      200.529000        inf
194      192.535000      96.17
195      176.074000     119.34
196      202.007000        inf
197             NaN        NaN
198             NaN        NaN
199      217.829000        inf
200             NaN        NaN
201      199.192000        inf
202      174.065000     148.38
203             NaN        NaN
204      180.646000     190.50
205      203.423000        inf
206      180.048000     205.20
207             NaN        NaN
208      195.462000        inf
209      170.835000     172.84
210      202.879000        inf
211             NaN        NaN
212             NaN        NaN
213      178.303000     164.10
214      181.745000        inf
215             NaN        NaN
216      175.015000        inf
217      173.196000     197.57
218      179.518000     188.63
219      172.793000        inf
220      163.267000     182.14
221      162.125000     163.85
222             NaN        inf
223             NaN        NaN
224             NaN        NaN
225      162.014000     165.08
226      168.086000        inf
227             NaN        NaN
228             NaN        NaN
229             NaN        NaN
230      168.366000        inf
231             NaN        NaN
232             NaN        NaN
233             NaN        NaN
234      161.439000     182.33
235             NaN        NaN
236             NaN        NaN
237             NaN        NaN
238             NaN        NaN
239      175.447000     182.38
240             NaN        NaN
241      180.088000     178.01
242             NaN        NaN
243             NaN        NaN
244      177.888000        inf
245      172.191000     171.08
246             NaN        NaN
247      213.978000        inf
248      201.356000        inf
249             NaN        NaN
250             NaN        NaN
251             NaN        NaN
252             NaN        NaN
253             NaN        NaN
254             NaN        NaN
255      200.184000        inf
256      172.911000     184.90
257      202.917000        inf
258             NaN        NaN
259        0.000000        NaN
260        0.000000        inf
261      218.958000        inf
262      179.585000     165.79
263      190.370000        inf
264      176.194000     118.88
265      174.276000     143.54
266             NaN        NaN
267      178.542000     181.52
268      186.004000        inf
269             NaN        NaN
270             NaN        NaN
271      175.392000     180.60
272      175.453000     180.52
273             NaN        NaN
274      171.251000     172.77
275      196.118000        inf
276      179.640000     203.33
277      179.975000     194.90
278             NaN        NaN
279      176.423000     186.97
280      178.274000     198.14
281      173.236000     188.62
282        0.000000        NaN
283      179.774000     185.69
284      172.834000     181.20
285      165.626000     149.34
286             NaN        NaN
287             NaN        NaN
288      162.589000        inf
289      172.644000     163.85
290      172.545000     164.84
291             NaN        NaN
292      161.434000     179.09
293             NaN        NaN
294      161.509000     182.86
295      168.132000        inf
296             NaN        NaN
297             NaN        NaN
298      186.726000        inf
299             NaN        NaN
300             NaN        NaN
301             NaN        NaN
302      172.198000     180.04
303      175.657000        inf
304      172.405000     168.76
305      172.009000     152.80
306      202.200000        inf
307             NaN        NaN
308             NaN        NaN
309      164.258000     178.57
310      164.239000     177.83
311      165.394000     184.66
312      165.739000     183.26
313             NaN        NaN
314      180.330000     170.93
315      182.856000     123.64
316      191.016000      88.36
317      180.452000     163.03
318             NaN        NaN
319      172.292000     154.66
320      180.153000        inf
321             NaN        NaN
322      174.308000     142.11
323      177.470000     193.95
324      177.030000     192.67
325      178.845000     167.85
326             NaN        NaN
327      208.155000        inf
328             NaN        NaN
329      191.157000        inf
330      171.106000     158.63
331      170.937000     174.73
332      208.506000        inf
333             NaN        NaN
334      188.442000        inf
335      176.446000     186.67
336      173.524000     198.14
337      173.479000     184.48
338      172.917000     181.20
339      161.770000     167.02
340      163.555000        inf
341             NaN        NaN
342      176.073000        inf
343      181.090000        inf
344             NaN        inf
345             NaN        inf
346      161.548000     182.14
347             NaN        NaN
348      161.559000     180.05
349      162.456000     155.84
350             NaN        NaN
351      172.849000     161.90
352             NaN        NaN
353      226.319000        inf
354             NaN        NaN
355             NaN        NaN
356             NaN        NaN
357             NaN        NaN
358      164.063000        inf
359      161.462000     186.46
360             NaN        NaN
361      175.355000     184.33
362      174.825000     232.23
363      191.052000        inf
364      172.849000     199.15
365      186.726000        inf
366             NaN        NaN
367             NaN        NaN
368      171.721000     178.65
369      172.895000     163.80
370      172.500000     153.32
371             NaN        NaN
372      164.957000     192.89
373             NaN        NaN
374             NaN        NaN
375      165.450000     183.71
376             NaN        NaN
377      180.230000     162.91
378      182.862000     123.09
379      181.138000     155.41
380      185.798000     103.01
381      187.814000        inf
382             NaN        NaN
383             NaN        NaN
384      181.783000     102.61
385      194.924000        inf
386      179.140000     120.02
387             NaN        NaN
388             NaN        NaN
389      177.913000     187.91
390      193.887000        inf
391      185.680000        inf
392      182.773000        inf
393      190.195000        inf
394             NaN        NaN
395      171.150000     177.58
396      210.515000        inf
397      178.781000     208.92
398      179.291000     202.38
399      175.562000     109.48
400             NaN        NaN
401      176.098000     191.24
402      173.658000     198.14
403      181.767000     181.77
404             NaN        NaN
405      177.641000        inf
406      161.472000     180.45
407             NaN        NaN
408             NaN        NaN
409      161.600000     175.55
410             NaN        NaN
411      161.700000        inf
412      161.770000        inf
413      173.996000     161.61
414             NaN        NaN
415      161.428000     182.55
416      201.452000        inf
417             NaN        NaN
418             NaN        NaN
419      176.343000        inf
420             NaN        NaN
421             NaN        NaN
422      175.659000     179.46
423      179.537000     182.88
424      172.836000     132.30
425             NaN        NaN
426      171.298000     185.34
427      172.952000     221.97
428      171.726000     159.81
429             NaN        NaN
430      166.681000     178.57
431             NaN        NaN
432      165.680000     180.00
433      184.207000        inf
434      195.319000        inf
435      179.173000     168.46
436      183.654000     119.62
437      180.617000     161.86
438      180.873000     127.50
439             NaN        NaN
440      208.420000        inf
441             NaN        NaN
442      186.357000        inf
443      167.907000        inf
444      170.090000     166.32
445             NaN        NaN
446      194.479000        inf
447      176.488000     193.18
448      177.624000     211.52
449             NaN        NaN
450             NaN        NaN
451      186.830000        inf
452             NaN        NaN
453             NaN        NaN
454      207.415000        inf
455      170.835000     175.01
456      180.012000        inf
457      182.542000        inf
458      196.616000        inf
459      177.226000     240.10
460      175.627000     192.71
461      173.251000     198.14
462      172.659000     177.16
463      179.704000        inf
464      179.518000     188.63
465      173.759000     181.20
466      171.485000        inf
467             NaN        NaN
468             NaN        NaN
469             NaN        NaN
470             NaN        NaN
471      161.600000     175.55
472      161.808000     192.64
473      174.103000     159.18
474             NaN        NaN
475      277.288000     277.29
476      161.433000     170.76
477      169.696000        inf
478             NaN        NaN
479             NaN        NaN
480             NaN        NaN
481             NaN        NaN
482      201.452000        inf
483             NaN        NaN
484      204.936000     188.79
485      205.021000        inf
486      207.094000        inf
487             NaN        NaN
488      196.658000        inf
489      181.958000        inf
490      155.450000     155.45
491      174.042000     185.94
492             NaN        NaN
493      170.458000     182.22
494      172.661000     225.79
495      200.915000        inf
496      174.469000        inf
497      166.004000     180.18
498             NaN        NaN
499      165.450000     179.63
500      172.454000     174.71
501      180.906000     165.03
502      185.043000     123.27
503      182.352000     157.64
504      181.248000     125.42
505             NaN        NaN
506      184.792000     183.07
507      196.234000        inf
508      200.846000        inf
509             NaN        NaN
510      170.598000     176.51
511      189.420000        inf
512      175.510000        inf
513             NaN        inf
514             NaN        NaN
515      174.285000     135.54
516      175.782000     190.62
517      173.412000     198.14
518      184.382000     184.38
519      179.518000     189.04
520      180.570000        inf
521      176.242000     177.12
522      161.437000   18455.27
523      166.450000     100.16
524             NaN        inf
525             NaN        NaN
526             NaN        NaN
527             NaN        NaN
528             NaN        NaN
529             NaN        inf
530      161.749000     177.54
531      161.651000     171.05
532             NaN        inf
533             NaN        NaN
534      165.547000        inf
535        4.051210     243.07
536      161.426000     198.51
537             NaN        inf
538        0.000000        inf
539             NaN        NaN
540      182.033000        inf
541      169.758000      84.98
542             NaN        NaN
543             NaN        NaN
544             NaN        NaN
545      178.398000     175.98
546      173.787000     189.65
547             NaN        NaN
548      171.805000     174.31
549        0.000000        NaN
550      172.654000     142.37
551      171.873000     157.11
552      191.798000        inf
553             NaN        NaN
554      196.482000        inf
555      164.313000     174.15
556      175.665000        inf
557             NaN        NaN
558      165.450000     179.63
559      171.535000     187.03
560      181.138000     160.07
561      182.352000     127.44
562      181.176000     126.61
563      181.192000        inf
564      168.429000     191.85
565      186.357000        inf
566             NaN        NaN
567             NaN        NaN
568      194.164000     176.21
569             NaN        NaN
570      155.041000     155.04
571      203.553000        inf
572             NaN        NaN
573             NaN        NaN
574             NaN        NaN
575      170.835000     175.21
576             NaN        NaN
577      204.296000        inf
578      175.860000     191.98
579      173.412000     198.14
580      173.370000     194.43
581      197.000000        inf
582      179.518000     189.04
583             NaN        NaN
584      161.443000     187.81
585      161.711000     184.28
586      161.442000     186.05
587             NaN        NaN
588             NaN        NaN
589      161.632000     176.73
590             NaN        inf
591      161.577000     190.01
592      161.740000     198.26
593      177.825000     143.12
594             NaN        NaN
595             NaN        NaN
596      176.893000        inf
597      162.803000     138.10
598             NaN        NaN
599      161.440000     186.41
600      175.373000      77.99
601             NaN        NaN
602             NaN        NaN
603      207.353000        inf
604      206.464000        inf
605      175.740000     181.87
606      171.571000     181.44
607      165.739000     171.30
608      187.142000     193.97
609             NaN        inf
610             NaN        NaN
611             NaN        NaN
612      177.497000     145.54
613      204.923000     185.97
614      205.057000        inf
615      206.857000        inf
616             NaN        inf
617             NaN        NaN
618      193.003000        inf
619      178.292000     172.39
620      179.537000     162.02
621      178.442000     181.07
622      185.965000        inf
623             NaN        NaN
624             NaN        inf
625      199.207000        inf
626      182.849000        inf
627      168.302000     110.74
628      168.194000     111.47
629      173.074000     175.75
630             NaN        NaN
631             NaN        inf
632      171.878000     180.31
633      171.917000     177.03
634      171.890000     179.06
635      179.121000     179.12
636      179.201000     179.20
637             NaN        NaN
638      182.534000        inf
639      177.791000   15522.98
640      170.534000     166.23
641             NaN        NaN
642             NaN        NaN
643      201.485000        inf

# TASK

In [7]:
import pandas as pd

data = {
    'TFC': [20,20,20,20],  
    'TOTAL_STEAMING_TIME': [24, 24, 14, 10],  
    'POWER_kW': [900, 850, 650, 690],  
}

sf = pd.DataFrame(data)

sf['TFC'] = sf['TFC'] * 1000000  

sf['SFOC_Calc'] = (sf['TFC']/ (sf['TOTAL_STEAMING_TIME'] * sf['POWER_kW'])).round(2)

print(sf)

        TFC  TOTAL_STEAMING_TIME  POWER_kW  SFOC_Calc
0  20000000                   24       900     925.93
1  20000000                   24       850     980.39
2  20000000                   14       650    2197.80
3  20000000                   10       690    2898.55

In [4]:

data = {
    'AE': ['AE 1', 'AE 2', 'AE 3', 'AE 4'],
    'TFC': [20,20,20,20],  
    'TOTAL_STEAMING_TIME': [24, 24, 14, 10], 
    'POWER_kW': [900, 850, 650, 690]
}

sf = pd.DataFrame(data)


sf['TFC'] = sf['TFC'] * 1000000  

sf['Fuel_Consumption'] = (sf['TFC'] / sf['TOTAL_STEAMING_TIME']).round(2)  

sf['SFOC'] = (sf['Fuel_Consumption'] / (sf['POWER_kW'] * 24)).round(2)

print(sf)

     AE       TFC  TOTAL_STEAMING_TIME  POWER_kW  Fuel_Consumption    SFOC
0  AE 1  20000000                   24       900         833333.33   38.58
1  AE 2  20000000                   24       850         833333.33   40.85
2  AE 3  20000000                   14       650        1428571.43   91.58
3  AE 4  20000000                   10       690        2000000.00  120.77